### DISCUSSION TITLE
The secrets are not being applied in the gitaction docker/build-push-action

### DISCUSSION THREAD

**Discussion by aitrics-ray** [docker/build-push-action#1018] [Q&A]
https://docs.docker.com/build/ci/github-actions/secrets/  
I attempted to verify if the secrets were correctly applied based on the above link, but contrary to my expectations, it did not work.

Here is a question similar to mine. [Pass secrets from git action to docker image as env variable](https://stackoverflow.com/questions/69917498/pass-secrets-from-git-action-to-docker-image-as-env-variable)

- Git action
```
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: apps/vc-screening-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          secrets: |
             VC_MYSQL_USER=${{ secrets.VC_MYSQL_USER }}
```
- Dockerfile
```
# syntax=docker/dockerfile:1
FROM alpine
RUN --mount=type=secret,id=VC_MYSQL_USER \
  VC_MYSQL_USER=$(cat /run/secrets/VC_MYSQL_USER)
```

Git Action Output enter image description here

![image](https://github.com/docker/build-push-action/assets/147586739/d44b56d4-eb03-45bf-8259-62047aad9702)
![image](https://github.com/docker/build-push-action/assets/147586739/89e4570d-d396-404d-b0d8-a372e97de1fc)
![image](https://github.com/docker/build-push-action/assets/147586739/46135f44-6e98-455e-91bb-004e37019a25)

Docker run output
```
docker run -it 997245385850.dkr.ecr.ap-northeast-2.amazonaws.com/dev/vc-screening-service:latest sh
/ # env
HOSTNAME=6a893ca9c566
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
/ #
```
The environment variable VC_MYSQL_USER is missing. What did I do wrong here?

**Comment by mabasic** [comment]
Try wrapping `VC_MYSQL_USER=${{ secrets.VC_MYSQL_USER }}` in quotes like so:

```
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: apps/vc-screening-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          secrets: |
             "VC_MYSQL_USER=${{ secrets.VC_MYSQL_USER }}"
```

in the docker file you must call the build command in the same `RUN` command as you export the variable.
