### DISCUSSION TITLE
How to set multi arch annotations if different platforms are built on different runners?

### DISCUSSION THREAD

**Discussion by TKrisee** [docker/build-push-action#1022] [Q&A]
I'm trying to add annotations to our docker images while building for multiple platforms. The relevant part of the dockerfile is as follows:
```docker
FROM ubuntu:22.04 as app

LABEL maintainer="Inline Studio"
LABEL org.opencontainers.image.description "Base Docker image for Laravel development"
```

and the workflows looks like this:
```yaml
name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        image:
          - app
          - database
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-latest' || fromJSON('["self-hosted", "ARM64"]') }}
    name: Build Docker image ${{ matrix.image }} ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.image }}
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders
          platforms: ${{ matrix.platform }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: .
          target: ${{ matrix.image }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          outputs: |
            type=image,name=${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.image }},push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha,scope=${{ github.repository }}-${{ github.ref_name }}-${{ matrix.platform }}-${{ matrix.image }}
          cache-to: type=gha,scope=${{ github.repository }}-${{ github.ref_name }}-${{ matrix.platform }}-${{ matrix.image }}
          secrets: |
            "COMPOSER_AUTH=${{ secrets.COMPOSER_AUTH }}"
      - name: Export digest
        run: |
          mkdir -p /tmp/digests/${{ matrix.image }}
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${{ matrix.image }}/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.image }}-digests
          path: /tmp/digests/${{ matrix.image }}/*
          if-no-files-found: error
          retention-days: 1
      - name: Clear digest
        run: |
          rm -rf /tmp/digests/${{ matrix.image }}

  merge:
    strategy:
      fail-fast: false
      matrix:
        image:
          - app
          - database
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - build
    name: Merge Docker manifests
    steps:
      - name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.image }}-digests
          path: /tmp/digests/${{ matrix.image }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.image }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create manifest list and push
        working-directory: /tmp/digests/${{ matrix.image }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< '${{ steps.meta.outputs.json }}') \
            $(printf '${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.image }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect '${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.image }}:${{ steps.meta.outputs.version }}'
```

the ARM images are built on raspberry pi-s using github ARC, while the x86 ones are built on the default github runners. My problem is that once I check the images on GHCR they have no description available:

<img width="732" alt="Screenshot 2023-12-06 at 22 54 59" src="https://github.com/docker/build-push-action/assets/107202954/6b26c69f-5cec-46fd-a46e-4eb9a4cd860e">

**Comment by oklopfer** [comment]
Finally figured it out. Buildx version is currently outdated (`v0.11.2` vs `v0.12.0`). Issue is solved by adding:

```yaml
      - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
         with:
++         version: v0.12.0
      [...]
      - name: Create manifest list and push
         working-directory: /tmp/digests
         run: |
           docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
++           --annotation "index:org.opencontainers.image.description=Your description goes here" \
             $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
```

~~However I say "solved" because it adds significant time to the build in doing the update to `v0.12.0`.~~
EDIT: seems to have only stalled the first time. Works just fine now with the pin :D
