### DISCUSSION TITLE
buildx failed with: ERROR: failed to solve: process "/bin/sh -c apk add --no-cache libc6-compat" did not complete successfully: exit code: 1

### DISCUSSION THREAD

**Discussion by Tockra** [docker/build-push-action#1044] [Q&A]
Hey,

I'm trying to build an image for my server platform linux/aarch64 .
For this I have following git action:
```
name: Build and Publish Docker image

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: link to my registry
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: link-to-my-registry/web-application

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/aarch64
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

```

```Dockerfile
FROM node:21-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi


# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn build
# ... I cut the remaing lines here ...
```

But the pipeline failes with following log:
```bash
Buildx version
/usr/bin/docker buildx build --file ./Dockerfile --iidfile /home/runner/work/_temp/docker-actions-toolkit-IsgDFC/iidfile --label org.opencontainers.image.created=2024-01-31T12:02:43.809Z --label org.opencontainers.image.description= --label org.opencontainers.image.licenses= --label org.opencontainers.image.revision=0bf49bbaef0eb7fc655926c86da7f3ff42f72d11 --label org.opencontainers.image.source=https://***hub.com/User/Repo --label org.opencontainers.image.title=webapp --label org.opencontainers.image.url=https://***hub.com/User/Repo --label org.opencontainers.image.version=0.0.1 --platform linux/aarch64 --tag link-to-my-registry/web-application:0.0.1 --tag link-to-my-registry/web-application:latest --metadata-file /home/runner/work/_temp/docker-actions-toolkit-IsgDFC/metadata-file --push .
#0 building with "default" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context: 2B 0.0s done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 2.39kB done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/node:21-alpine
#3 ...

#4 [auth] library/node:pull token for registry-1.docker.io
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/library/node:21-alpine
#3 DONE 1.9s

#5 [base 1/1] FROM docker.io/library/node:21-alpine@sha256:4cc2d9f365691fc6f8fe227321d32d9a2691216a71f51c21c7f02224515dea48
#5 resolve docker.io/library/node:21-alpine@sha256:4cc2d9f365691fc6f8fe227321d32d9a2691216a71f51c21c7f02224515dea48 done
#5 sha256:20d4320a57895f808c3e4ece1cb0439ec6f1fcac2bf4c8e02e4a7f[150](https://github.com/User/Repo/actions/runs/XX/job/XX#step:5:155)3a0c405 0B / 2.37MB 0.1s
#5 sha256:4cc2d9f365691fc6f8fe227321d32d9a2691216a71f51c21c7f02224515dea48 1.43kB / 1.43kB done
#5 sha256:dddddb4633e05f8632b192ae0a260d44d97fcdfd0d78b8ce04d1d466e6a44ff7 1.16kB / 1.16kB done
#5 sha256:9f6e9ed23f8bf88b7e6d436b454c9023576fdd8363d24f39de39c2e649a711af 7.15kB / 7.15kB done
#5 sha256:bca4290a96390d7a6fc6f2f9929370d06f8dfcacba591c76e3d5c5044e7f420c 0B / 3.35MB 0.1s
#5 sha256:2685ca0674b359ea438457efa61ea6523b943fba95a2b1bb05b439409f2d9534 0B / 43.23MB 0.1s
#5 ...

#6 [internal] load build context
#6 transferring context: 5.75MB 0.1s done
#6 DONE 0.1s

#5 [base 1/1] FROM docker.io/library/node:21-alpine@sha256:4cc2d9f365691fc6f8fe227321d32d9a2691216a71f51c21c7f02224515dea48
#5 sha256:20d4320a57895f808c3e4ece1cb0439ec6f1fcac2bf4c8e02e4a7f1503a0c405 2.37MB / 2.37MB 0.2s done
#5 sha256:e42c4e9efb859f9be0c[180](https://github.com/User/Repo/actions/runs/7725699358/job/21060491437#step:5:185)a84037193dc21e218dda7e51d97dfbe25890bce31d 0B / 446B 0.2s
#5 sha256:bca4290a96390d7a6fc6f2f9929370d06f8dfcacba591c76e3d5c5044e7f420c 2.10MB / 3.35MB 0.3s
#5 sha256:2685ca0674b359ea438457efa61ea6523b943fba95a2b1bb05b439409f2d9534 7.34MB / 43.23MB 0.3s
#5 sha256:e42c4e9efb859f9be0c180a84037193dc21e218dda7e51d97dfbe25890bce31d 446B / 446B 0.3s done
#5 sha256:bca4290a96390d7a6fc6f2f9929370d06f8dfcacba591c76e3d5c5044e7f420c 3.35MB / 3.35MB 0.3s done
#5 sha256:2685ca0674b359ea438457efa61ea6523b943fba95a2b1bb05b439409f2d9534 22.02MB / 43.23MB 0.4s
#5 extracting sha256:bca4290a96390d7a6fc6f2f9929370d06f8dfcacba591c76e3d5c5044e7f420c
#5 sha256:2685ca0674b359ea438457efa61ea6523b943fba95a2b1bb05b439409f2d9534 34.52MB / 43.23MB 0.5s
#5 extracting sha256:bca4290a96390d7a6fc6f2f9929370d06f8dfcacba591c76e3d5c5044e7f420c 0.2s done
#5 sha256:2685ca0674b359ea438457efa61ea6523b943fba95a2b1bb05b439409f2d9534 43.23MB / 43.23MB 0.6s
#5 extracting sha256:2685ca0674b359ea438457efa61ea6523b943fba95a2b1bb05b439409f2d9534
#5 sha256:2685ca0674b359ea438457efa61ea6523b943fba95a2b1bb05b439409f2d9534 43.23MB / 43.23MB 0.6s done
#5 extracting sha256:2685ca0674b359ea438457efa61ea6523b943fba95a2b1bb05b439409f2d9534 1.5s done
#5 extracting sha256:20d4320a57895f808c3e4ece1cb0439ec6f1fcac2bf4c8e02e4a7f1503a0c405
#5 extracting sha256:20d4320a57895f808c3e4ece1cb0439ec6f1fcac2bf4c8e02e4a7f1503a0c405 0.1s done
#5 extracting sha256:e42c4e9efb859f9be0c180a84037[193](https://github.com/User/Repo/actions/runs/7725699358/job/21060491437#step:5:198)dc21e218dda7e51d97dfbe25890bce31d done
#5 DONE 2.8s

#7 [deps 1/4] RUN apk add --no-cache libc6-compat
#7 ...

#8 [builder 1/4] WORKDIR /app
#8 DONE 0.0s

#9 [runner  2/11] RUN apk add --no-cache chromium
#9 0.330 exec /bin/sh: exec format error
#9 ERROR: process "/bin/sh -c apk add --no-cache chromium" did not complete successfully: exit code: 1

#7 [deps 1/4] RUN apk add --no-cache libc6-compat
#7 0.344 exec /bin/sh: exec format error
#7 ERROR: process "/bin/sh -c apk add --no-cache libc6-compat" did not complete successfully: exit code: 1
------
 > [deps 1/4] RUN apk add --no-cache libc6-compat:
0.344 exec /bin/sh: exec format error
------
------
 > [runner  2/11] RUN apk add --no-cache chromium:
0.330 exec /bin/sh: exec format error
------
Dockerfile:6
--------------------
   4 |     FROM base AS deps
   5 |     # Check https://***hub.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
   6 | >>> RUN apk add --no-cache libc6-compat
   7 |     WORKDIR /app
   8 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache libc6-compat" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c apk add --no-cache libc6-compat" did not complete successfully: exit code: 1

```

I tried it on my local system:
`docker build --platform linux/aarch64 . --no-cache` 
There is no such problem.

Has somebody an idea ?

**Comment by Tockra** [comment]
Okay I found the solution. I don't know the reason, but there is a problem because the runner has not the aarch64 architecture. So there is a problem when it tries to run stuff inside the aarch64 container. 
I don't understand why, because I thought the buildx command is specially for cross compile and I have no similar issue when I choose platform linux/amd64 on my local arm (macos) system.

But after adding following step the problem was soluted:
```
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
              with:
                  platforms: linux/aarch64
```
