### DISCUSSION TITLE
How to push multi platform matrix build to multiple registries

### DISCUSSION THREAD

**Discussion by alessfg** [docker/build-push-action#1067] [Q&A]
I am trying to use a matrix build to speed up the build process of the NGINX Unprivileged images here https://github.com/nginxinc/docker-nginx-unprivileged/pull/195 but I am running into an issue with pushing the build results to multiple registries (I can get things working if I push to a single registry).

I have tried two approaches, they both fail for different reasons:
1. The first approach is to specify multiple names when using the type=image output and thus push the build results to multiple registries. This is supported according to the docs. However, I can't seem to get this working no matter what I try. If I use double quotes to wrap the names, only the second name gets recognized. If I try to escape the double quotes (as per the docs), GH actions fails to parse the workflow:

```yaml
- name: Build and push image to Docker Hub and GitHub Container Registry
  id: build
  uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
  with:
    platforms: ${{ matrix.platform }}
    context: "."
    labels: ${{ steps.meta.outputs.labels }}
    outputs: type=image,name=\"ghcr.io/nginxinc/nginx-unprivileged,docker.io/nginxinc/nginx-unprivileged\",push-by-digest=true,name-canonical=true,push=true
```

2. The second approach has been to copy the image from one registry to another per https://docs.docker.com/build/ci/github-actions/copy-image-registries/, but the process slows down to a crawl and eventually freezes at around 40-50 mins.

Is anyone doing this in their workflows or has any suggestions on how to do this? Thanks!
