### DISCUSSION TITLE
Manifest not found

### DISCUSSION THREAD

**Discussion by manast** [docker/build-push-action#1069] [Q&A]
I wonder if there is some kind soul that could take a look at this github workflow to see if some error can be spotted, because from what I can see, everything is correct, the image is built correctly but then when trying to pull it I get this error:
```
Error response from daemon: manifest for ghcr.io/taskforcesh/bullmq-proxy:main not found
```
And indeed the manifest is actually missing from what I can see in github, but what is it the case?  did I hit a bug? I think this started to happen after upgrading to v5.

https://github.com/taskforcesh/bullmq-proxy/blob/main/.github/workflows/build-docker.yml:
```
name: Build Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  run:
    name: Build and publish
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ghcr.io/taskforcesh/bullmq-proxy
    steps:
      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=true
       
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true # push to registry
          pull: true # always fetch the latest base images

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```
