### DISCUSSION TITLE
Dockerhub platform of my image is reported as linux/amd64 and unknown/unknown

### DISCUSSION THREAD

**Discussion by aghozlane** [docker/build-push-action#1078] [Q&A] [answered]
Hello,

I have an issue with the platform that is reported for my image, I get 
![image](https://github.com/docker/build-push-action/assets/1582715/351f9dd2-6768-4bba-bc0b-7810186712d8)

I tried with and without platforms option:
```
jobs:
  docker:
    needs: conda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USER }}/meteor:${{  github.ref_name }} , ${{ secrets.DOCKER_USER }}/meteor:latest
```
but I couldn't solve this issue.
 
This is annoying because macos arm refuse to directly to download this image
```
docker pull aghozlane/meteor:latest
latest: Pulling from aghozlane/meteor
no matching manifest for linux/arm64/v8 in the manifest list entries
```
I'm forced to specify the platform:
`docker pull --platform linux/amd64  aghozlane/meteor`

I am working from continuumio/miniconda3 which is debian. Other similar software doesn't have this issue (but they don't use github actions). I don't want to build the app for linux/arm64.

Any idea ?
