### DISCUSSION TITLE
How do I pass this action a commit hash to build the docker images from ?

### DISCUSSION THREAD

**Discussion by ishaan-jaff** [docker/build-push-action#1091] [Q&A]
Hi I'm trying to pass this action a specific commit hash to build the docker image from, how do i do this?

**Comment by ishaan-jaff** [comment]
would something like this work
```
- name: Build and push Docker image
        uses: docker/build-push-action@4976231911ebf5f32aad765192d35f942aa48cb8
        with:
          context: https://github.com/BerriAI/litellm/tree/26f5823c4ec4806aba82d8c48dc9816713ffc214
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ github.event.inputs.tag || 'latest' }}, ${{ steps.meta.outputs.tags }}-${{ env.type_release }} # if a tag is provided, use that, otherwise use the release tag, and if neither is available, use 'latest'
          labels: ${{ steps.meta.outputs.labels }}
          platforms: local,linux/amd64,linux/arm64,linux/arm64/v8
          
```
