### DISCUSSION TITLE
Use of Environment Variables in docker/build-push-action?

### DISCUSSION THREAD

**Discussion by colinbjohnson** [docker/build-push-action#1097] [Q&A]
I am curious if Environment Variables are not supported as inputs by the [docker/build-push-action](https://github.com/docker/build-push-action). An example file is below:

```yaml
name: build-and-push-image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: aws-actions/amazon-ecr-login@v2
      - uses: docker/build-push-action@v5
        env:
          REGISTRY: 123456789012.dkr.ecr.us-west-2.amazonaws.com
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: $REGISTRY/github-actions-lab:test
```

Which results in an error:

```shell
ERROR: invalid tag "$REGISTRY/github-actions-lab:test": invalid reference format`
Error: buildx failed with: ERROR: invalid tag "$REGISTRY/github-actions-lab:test": invalid reference format
```

If Environment Variables are not supported as inputs I feel like this might be worth mentioning in the documentation (or I missed it). I'd be happy to submit a PR if desired.

**Comment by crazy-max** [comment]
Inputs are not evaluated, this is a limitation on GitHub side, not this action. But you can use contexts to access variable values but it must be first applied to your job, not the step: https://docs.github.com/en/actions/learn-github-actions/variables#using-contexts-to-access-variable-values

```yaml
name: build-and-push-image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: 123456789012.dkr.ecr.us-west-2.amazonaws.com
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: aws-actions/amazon-ecr-login@v2
      - uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/github-actions-lab:test
```
