### DISCUSSION TITLE
Is it possible to build without pushing?

### DISCUSSION THREAD

**Discussion by GersonTrj** [docker/build-push-action#1163] [Q&A] [answered]
I am using this action in a reusable workflow and I would like to give the other devs the option to build the image without pushing it to check for build errors using some sort of push boolean variable, how could I do this?

**Comment by crazy-max** [comment, marked as answer]
You can use the `cacheonly` exporter: https://docs.docker.com/build/exporters/#cache-only-export

```yaml
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          outputs: type=cacheonly
          tags: user/app:latest
```
