### DISCUSSION TITLE
How to update build image to `docker.io/library/golang:1.23-alpine` from `docker.io/library/golang:1.18-alpine`?

### DISCUSSION THREAD

**Discussion by grokify** [docker/build-push-action#1224] [General]
I'm using docker/build-push-action@v6, however it is is using the Go 1.18 image for builds and test, which is failing because 1.21 or higher is needed.

This is my pipeline config:

```yaml
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

Ref: https://github.com/grokify/ringcentral-permahooks/blob/41a94cdd949173dd9f86ca7bea60d4071218479a/.github/workflows/release.yaml

This pulls the `golang:1.18-alpine` image.

```
#9 [1/7] FROM docker.io/library/golang:1.18-alpine@sha256:77f25981bd57e60a510165f3be89c901aec90453fd0f1c5a45691f6cb1528807
#9 resolve docker.io/library/golang:1.18-alpine@sha256:77f25981bd57e60a510165f3be89c901aec90453fd0f1c5a45691f6cb1528807 done
```

More here: https://github.com/grokify/ringcentral-permahooks/issues/196

How can I configure this to use ` `golang:1.23-alpine`?
