### DISCUSSION TITLE
Pass different build-args based on architecture, only the last image gets pushed

### DISCUSSION THREAD

**Discussion by nemanjam** [docker/build-push-action#1233] [Q&A]
I am using matrix with platforms to set different `build-args` for each platform. I want to keep that in Github Action and keep Dockerfile agnostic of this. The problem is that the second image gets pushed with `"architecture": "unknown"` manifest data even though it's built and pushed successfully.

Here is my code, the relevant part:

```yaml
name: Build and push Docker

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  SITE_URL_ARM64: 'https://nmc-docker.arm1.nemanjamitic.com'
  SITE_URL_AMD64: 'https://nmc-docker.local.nemanjamitic.com'
  PLAUSIBLE_SCRIPT_URL: 'https://plausible.arm1.nemanjamitic.com/js/script.js'
  PLAUSIBLE_DOMAIN: 'nemanjamitic.com'

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set environment variables for each architecture
        run: |
          if [[ "${{ matrix.platform }}" == "linux/amd64" ]]; then
            echo "SITE_URL=${{ env.SITE_URL_AMD64 }}" >> $GITHUB_ENV
          elif [[ "${{ matrix.platform }}" == "linux/arm64" ]]; then
            echo "SITE_URL=${{ env.SITE_URL_ARM64 }}" >> $GITHUB_ENV
          fi

      # Must be in separate step to reflect
      - name: Debug assigned environment variable
        run: |
          echo "Debug: PLATFORM: ${{ matrix.platform }}, SITE_URL: ${{ env.SITE_URL }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            "ARG_SITE_URL=${{ env.SITE_URL }}"
            "ARG_PLAUSIBLE_SCRIPT_URL=${{ env.PLAUSIBLE_SCRIPT_URL }}"
            "ARG_PLAUSIBLE_DOMAIN=${{ env.PLAUSIBLE_DOMAIN }}"
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
```
Here is the complete code:

https://github.com/nemanjam/nemanjam.github.io/blob/main/.github/workflows/default__build-push-docker.yml

And this is the manifest for the pushed images:

```bash
$ docker manifest inspect nemanjamitic/nemanjam.github.io:latest
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1808,
         "digest": "sha256:aa9477dfb8fd2b41b06c2673fed1a02ced0848d3552350e0338275ef9b5bda7d",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 567,
         "digest": "sha256:952d5d382e6c50aa2fc3757d3d1fbbbacd64e83dac404bf34d2f84c248290485",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

Here is the Github Actions log for the missing `x86` image, architecture is set in metadata:

https://github.com/nemanjam/nemanjam.github.io/actions/runs/11094437089/job/30821924988

```bash
      "invocation": {
        "configSource": {},
        "parameters": {
          "frontend": "dockerfile.v0",
          "args": {
            "build-arg:ARG_PLAUSIBLE_DOMAIN": "***.com",
            "build-arg:ARG_PLAUSIBLE_SCRIPT_URL": "https://plausible.arm1.***.com/js/script.js",
            "build-arg:ARG_SITE_URL": "https://nmc-docker.local.***.com"
          },
          "locals": [
            {
              "name": "context"
            },
            {
              "name": "dockerfile"
            }
          ]
        },
        "environment": {
          "platform": "linux/amd64"
        }
      }
    },
```

On Docker hub only the second image is visible:

![image](https://github.com/user-attachments/assets/14c4a5bd-8234-4227-80f6-4f8c140a832c)
