### DISCUSSION TITLE
Problems building for multiple plattforms

### DISCUSSION THREAD

**Discussion by gltched-usr** [docker/build-push-action#1250] [Q&A]
My workflow:

```
name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
        default: "latest"
      release_description:
        description: "Description for the release"
        required: true
        default: "Automated release"

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - linux/amd64
          - linux/arm64

    steps:
      - name: 🔡 Prepare env
        id: prepareEnv
        run: |
          echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          platform=${{ matrix.architecture }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: 🐳 Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REPO_NAME }}

      - name: 📥 Check out the repository
        uses: actions/checkout@v4

      - name: 🔑 Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔍 Verify Dockerfile exists
        run: test -f Dockerfile

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 📦 Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.architecture }}
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=ghcr.io/${{ env.REPO_NAME }},push-by-digest=true,name-canonical=true,push=true

      - name: 📜 Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: 📤 Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:
      - name: 🔡 Prepare env
        id: prepareEnv
        run: |
          echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          platform=${{ matrix.architecture }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: 📥 Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            -t ghcr.io/${{ env.REPO_NAME }}:${{ github.event.inputs.tag }} \
            -t ghcr.io/${{ env.REPO_NAME }}:latest \
            $(printf 'ghcr.io/${{ env.REPO_NAME }}@sha256:%s ' *)

      - name: 🔍 Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/${{ env.REPO_NAME }}:${{ github.event.inputs.tag }}
          docker buildx imagetools inspect ghcr.io/${{ env.REPO_NAME }}:latest

```

But on ghcr I find arch `linux/amd64` and `unknown/unkonw`
