### DISCUSSION TITLE
How to show debug build log?

### DISCUSSION THREAD

**Discussion by seepine** [docker/build-push-action#1304] [Q&A] [answered]
eg `docker build -t xxx --debug -f Dockerfile .`
I didn't find similar parameters in `docker/build-push-action`. 
<img width="858" alt="image" src="https://github.com/user-attachments/assets/98467680-31e5-4128-9abf-db42c3c52d15" />

**Comment by crazy-max** [comment, marked as answer]
You can set the `DEBUG: 1` env var in your workflow that would act the same as the `--debug` flag:

```yaml
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
        env:
          DEBUG: 1
```

If you want the BuildKit logs with debug enabled, see https://docs.docker.com/build/ci/github-actions/configure-builder/#buildkit-container-logs
