### DISCUSSION TITLE
How to access platform as a build-arg?

### DISCUSSION THREAD

**Discussion by educlos** [docker/build-push-action#1305] [Q&A] [answered]
Hello,
I'm checking this action to build one of our docker image, but I'm wondering how I could get the `platform` as a `build-arg`
It looks like this:
```
      - name: Build and push
        id: build-docker
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-base
          platforms: linux/amd64,linux/arm64
          no-cache: true
          build-args: |
            PHP_VERSION=${{ matrix.version }}
            TARGET_PLATFORM=${{ not sure what to put here }}
          push: true
```

I know I could get it by using a matrix. build each platform on its own and then build the manifest (which is what I'm currently doing, just without this action), but from what I understand this action does all that, so if I could use it it would make the action shorter.
