### DISCUSSION TITLE
Pushing a README with Build

### DISCUSSION THREAD

**Discussion by y0utubeperson1** [docker/build-push-action#1310] [Q&A]
I am attempting to push my README.md file as the overview on my DockerHub. This is my GitHub action steps:

```
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Retrieve Docker Credentials
        run: |
          <Removed>

      - name: Log in to Docker Hub
        run: |
          echo "Logging in to Docker Hub..."
          docker_username=${{ env.DOCKERHUB_USERNAME }}
          docker_password==${{ env.DOCKERHUB_PASSWORD }}
          echo "$docker_password" | docker login -u "$docker_username" --password-stdin

      - name: Read README content for metadata
        id: readme
        run: |
          content=$(cat README.md)
          escaped_content=$(echo "$content" | jq -Rsa .)
          echo "content=$escaped_content" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.OFFICIAL_TAG }}
          labels: |
            org.opencontainers.image.description=${{ steps.readme.outputs.content }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
```

Yet for some reason, it does not. The image itself gets pushed successfully but not the README. What is the issue?
