### DISCUSSION TITLE
Best practices for effectively utilizing build cache

### DISCUSSION THREAD

**Discussion by mohammed-rahib** [docker/build-push-action#1331] [Q&A]
I am using a GitHub workflow to build and push Docker images for amd64 and arm64. The workflow is triggered in two ways: one by pushing to a branch and the other by creating a release version

```
on:
  push:
    branches:
      - develop
  release:
    types:
      - created
```
    
 I am utilizing the cache action as shown below. 

```
   - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
```

The issue is that when the workflow is triggered by a push event, the cache is used effectively, but when triggered by a release, it is not. How can I resolve this?"
