### DISCUSSION TITLE
Support for compression with zstd

### DISCUSSION THREAD

**Discussion by chainhead** [docker/build-push-action#1357] [Q&A]
Can you please show an example of compressing the container image with `zstd`? If not supported, is this on roadmap? Also, what's an alternative to add a compression step in the workflow?

**Comment by crazy-max** [comment]
Yes this is supported, see https://docs.docker.com/build/exporters/image-registry/

```yaml
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
          outputs: |
            type=image,compression=zstd,force-compression=true
```
