### DISCUSSION TITLE
Is `docker build --check` used to validate Dockerfiles and check for warnings?

### DISCUSSION THREAD

**Discussion by johnthagen** [docker/build-push-action#1359] [Q&A] [answered]
I'd like to ensure that my Dockerfile does not have any warnings and that it's validated in CI. If I use a simple job such as:

```yaml
  container:
    runs-on: ubuntu-24.04
    steps:
      - name: Build Container Image
        uses: docker/build-push-action@v6
        with:
          push: false
```

Will this fail if `docker build --check` fails? I don't see any documentation in the README about if lint warnings are checked. I think the documentation could be improved here.

If they _aren't_ checked, I'd propose a new

```yaml
        with:
          checked: true
```

flag so that users can lint their Dockerfiles using this action in CI.

### References

- https://docs.docker.com/reference/build-checks/
- https://docs.docker.com/build/checks/

**Comment by mschoettle** [comment]
You can use the input `call` and pass `check` to it. 

https://github.com/docker/build-push-action?tab=readme-ov-file#inputs

**Reply by johnthagen** [reply]
@mschoettle So would this look like:

```yaml
  container:
    runs-on: ubuntu-24.04
    steps:
      - name: Lint Dockerfile
        uses: docker/build-push-action@v6
        with:
          call: check
```

If I want to check and then actually build the container, would the most concise way of expressing this be the following? (i.e., I need to duplicate and have two separate `docker/build-push-action@v6` steps?

```yaml
  container:
    runs-on: ubuntu-24.04
    steps:
      - name: Lint Dockerfile
        uses: docker/build-push-action@v6
        with:
          call: check
    steps:
      - name: Build Container Image
        uses: docker/build-push-action@v6
        with:
          push: false
```
