### DISCUSSION TITLE
Cant use github secret as docker secret?

### DISCUSSION THREAD

**Discussion by Sahar23391** [docker/build-push-action#1362] [Q&A]
# Issue: Docker secret with GitHub secret not being passed to build process

## Description
I'm trying to use a GitHub secret as a Docker secret to pass my token to the Docker build process. However, I'm getting an error that the secret is invalid, and it appears the `--secret` flag isn't being sent to the Docker build command.

## Current Configuration
I'm using the docker/build-push-action to build my Docker image and attempting to pass a secret from GitHub secrets to the Docker build process.

My workflow configuration looks something like:

```yaml
- name: Build and push
  uses: docker/build-push-action@v6
  with:
    context: .
    push: true
    tags: ${{ env.IMAGE_NAME }}
    secrets: |
      MYSECRET=${{ secrets.DEVOPS_PAT}}
```

## Error
When the build runs, I receive an error indicating that the secret is invalid. Additionally, when examining the build logs, I don't see the `--secret` flag being passed to the Docker build command.

![image](https://github.com/user-attachments/assets/4732e93d-490a-42c6-935d-87d7d8e1b34f)

## Expected Behavior
The GitHub secret should be properly passed as a Docker secret to the build process, and the `--secret` flag should be included in the Docker build command.

## Additional Information
- I've verified that the GitHub secret is correctly stored and accessible to the workflow, also has expiration date.
- The Dockerfile does attempt to use the secret with the expected syntax.

## Questions
1. Is there a specific format or configuration needed to ensure the `--secret` flag is passed to the Docker build command?
2. Are there known limitations when passing GitHub secrets to Docker builds?

Any help troubleshooting this issue would be greatly appreciated!
