### DISCUSSION TITLE
Exporting build cache takes too long

### DISCUSSION THREAD

**Discussion by hotrush** [docker/build-push-action#1372] [General]
It happened that actions burnt all available minutes in one day for me. I check actions outputs and found that it might be related to `docker/build-push-action` action.

I found several jobs with similar output like:

```
#44 exporting to GitHub Actions Cache
#44 preparing build cache for export
#44 writing layer sha256:071bce5745e0d1e301d9b7e7b25dcbf2545d7354a30c42cf86491b3143869c5c
#44 writing layer sha256:071bce5745e0d1e301d9b7e7b25dcbf2545d7354a30c42cf86491b3143869c5c 0.8s done
#44 writing layer sha256:5a0afb461c3017dbcf68eaf0f9f6501a196a1f83b3e2a29807f1399dca694e98
#44 writing layer sha256:5a0afb461c3017dbcf68eaf0f9f6501a196a1f83b3e2a29807f1399dca694e98 2.7s done
#44 writing layer sha256:89cf9f0cecba95b416d820e3f02d6a1075b96bef1fb0cdd4d98a774ce0fb59a0
#44 writing layer sha256:89cf9f0cecba95b416d820e3f02d6a1075b96bef1fb0cdd4d98a774ce0fb59a0 0.7s done
#44 preparing build cache for export 12703.9s done
#44 DONE 12703.9s
```

or 

```
#44 exporting to GitHub Actions Cache
#44 preparing build cache for export
#44 writing layer sha256:0220997a715f430985558c1ca8619b3a3f2b35bbd8d37f912de3a52f894e918a
#44 writing layer sha256:0220997a715f430985558c1ca8619b3a3f2b35bbd8d37f912de3a52f894e918a 2.5s done
#44 writing layer sha256:0892c784d2a865d0e397bd9cb776d4417be1c76db1dfa6f866648d6ed57300b4
#44 writing layer sha256:0892c784d2a865d0e397bd9cb776d4417be1c76db1dfa6f866648d6ed57300b4 0.7s done
#44 writing layer sha256:100bb0fc8257ed617286349de9ef29c74a26a99d01d016302de6f2f428c3a7bb
#44 writing layer sha256:100bb0fc8257ed617286349de9ef29c74a26a99d01d016302de6f2f428c3a7bb 0.6s done
#44 writing layer sha256:1d339251fc2c770db281953a85c3d64414d45d830ff2186828753c7245eb9d00
#44 writing layer sha256:1d339251fc2c770db281953a85c3d64414d45d830ff2186828753c7245eb9d00 0.7s done
#44 writing layer sha256:292100fd585fa3233788884d35726d51dc24f1f5bcac34b9c84b0d30393cade4
#44 writing layer sha256:292100fd585fa3233788884d35726d51dc24f1f5bcac34b9c84b0d30393cade4 2.7s done
#44 writing layer sha256:4732126784059c83f96fe88aac31af829db77eb1c3aa2494fa97c776971f9999
#44 writing layer sha256:4732126784059c83f96fe88aac31af829db77eb1c3aa2494fa97c776971f9999 0.4s done
#44 writing layer sha256:486abd77d5c06cb13e883f095f4cca2779d4e11d1e4eeca7b2627b268cb66bef
#44 writing layer sha256:486abd77d5c06cb13e883f095f4cca2779d4e11d1e4eeca7b2627b268cb66bef 11.1s done
#44 writing layer sha256:50780a3ed69d845a5fab52f68b5bda9fed29e9f12ca507bbd7561fc2de250001
#44 writing layer sha256:50780a3ed69d845a5fab52f68b5bda9fed29e9f12ca507bbd7561fc2de250001 2.7s done
#44 writing layer sha256:5f99c5725e2e53e8c8a789517836e935d6d177e86b8bcc91d02c93421c1d6521
#44 writing layer sha256:5f99c5725e2e53e8c8a789517836e935d6d177e86b8bcc91d02c93421c1d6521 0.5s done
#44 writing layer sha256:94aa18bd83ce32e36515443a449e5818d5a6a770b3b59049e72861a81777f04c
#44 writing layer sha256:94aa18bd83ce32e36515443a449e5818d5a6a770b3b59049e72861a81777f04c 0.3s done
#44 writing layer sha256:a8660b03a0a6f6f88e4408f870ddb3a3c27ab3c20d461454c87b717e88c26862
#44 writing layer sha256:a8660b03a0a6f6f88e4408f870ddb3a3c27ab3c20d461454c87b717e88c26862 4.0s done
#44 writing layer sha256:c0b1642318b4aa05e72c85385572f060504892ce04a3fa4cc37f67fcd6ae8ff1
#44 writing layer sha256:c0b1642318b4aa05e72c85385572f060504892ce04a3fa4cc37f67fcd6ae8ff1 0.4s done
#44 preparing build cache for export 2374.7s done
#44 DONE 2374.7s
```

Step is pretty simple:
```
    - name: Build and push
      uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
      with:
        push: ${{ inputs.push }}
        tags: ${{ inputs.image_tags }}
        cache-from: type=gha,scope=build-${{ inputs.target }}
        cache-to: type=gha,mode=max,scope=build-${{ inputs.target }}
        provenance: false
        target: ${{ inputs.target }}
      env:
        DOCKER_BUILDKIT: 1
```

I think it might started happening after this upgrade
```
-   uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
+  uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
```

Any ideas about that?
