### DISCUSSION TITLE
Building with additional contexts

### DISCUSSION THREAD

**Discussion by PaulRudin** [docker/build-push-action#1384] [General]
In my workflow file I have:
```
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:pingchange"
          build-contexts: |
            rtcommon="{{defaultContext}}:/realtime/rtcommon"
          push: true
          tags: |
           ...
```
but the additional context fails: `Error: buildx failed with: ERROR: failed to build: failed to get build context rtcommon:`. -Does this sort of thing require an explicit checkout ? Or is there a way to achieve this ?
