### DISCUSSION TITLE
Multiple unwanted tags within the same push

### DISCUSSION THREAD

**Discussion by saadbahir** [docker/build-push-action#936] [Q&A]
Hello everyone

On each build and push, I have 3 separate tags for the same push

- 1 normal tagged version (for example: 1.0.0) that I specified
- 2 untagged versions with commit digest

The 2 untagged versions can be traced in the logs of the `build-and-push` workflow step but they come out of nowhere

I am pushing images to two separate registries, including Github registry

```
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ needs.prepare.outputs.image_fly }}${{ env.IMAGE_SUFFIX }}
            ${{ needs.prepare.outputs.image_github }}${{ env.IMAGE_SUFFIX }}
```

```
#12 exporting to image
#12 exporting layers
#12 exporting layers 17.8s done
#12 exporting manifest sha256:b1ee819a2e3d5896b86d8d87e242cee35566f20afbb527441c46f7b0d1480a06 0.0s done
#12 exporting config sha256:9d265a628e53ff77b40026a825fb59758f08eb9935ad42ab9bb95170fbdbf3a3
#12 exporting config sha256:9d265a628e53ff77b40026a825fb59758f08eb9935ad42ab9bb95170fbdbf3a3 done
#12 exporting attestation manifest sha256:8f6eb2770bfada4f266d37985611558f866d281d366cc659486975817d602296 done
#12 exporting manifest list sha256:7264527bd66a26218825ead8b63be68931267f02b45d2bc76a7a2c2943b0d4a1 done
#12 pushing layers
#12 ...
```
In this case for example, I get two other images with tags
```
b1ee819a2e3d5896b86d8d87e242cee35566f20afbb527441c46f7b0d1480a06
```
and
```
8f6eb2770bfada4f266d37985611558f866d281d366cc659486975817d602296
```
Does anyone know what triggers this behavior?
