### DISCUSSION TITLE
buildx image tags are "none"

### DISCUSSION THREAD

**Discussion by arsalanyavari** [docker/build-push-action#969] [Q&A]
I use the below snip code in my workflow. After that, when I pull image from **Packages > OS / Arch**, the image tags are **none**. What should I do to fix it? 
```
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: arsalanyavari
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/arsalanyavari/guard-service-test:${{ matrix.versions }}
```
![image](https://github.com/docker/build-push-action/assets/67124852/2d0c18f0-b557-424b-bc3a-2a57c1bb1c5e)
![image](https://github.com/docker/build-push-action/assets/67124852/8c014cfd-ae65-4558-8ff7-95c7ec65b8bf)

my Workflow address: https://github.com/arsalanyavari/watcher-test/blob/dev/.github/workflows/docker-release.yml
