### ISSUE TITLE
Please consider adding input safelisting

### ISSUE THREAD

**Issue by franky47** [docker/build-push-action#10]
GitHub Actions can be vulnerable to environment injection for optional inputs, see my article here:
https://francoisbest.com/posts/2020/the-security-of-github-actions

One form of defence against that for now is to add another input that lists input names that are safe to load (because explicitly defined by the user in their workflow).

Example:
```yml
uses: docker/build-push-action@v1
with:
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}
  repository: myorg/myrepository
  tags: latest
  inputsSafeList: username,password,repository,tags
```

In this example, if a malicious action defines and exports `INPUT_REGISTRY`, it would be ignored as `registry` is not part of the safelist. Without it, the image could be pushed to a registry controlled by the attacker.
