### ISSUE TITLE
v2: docker driver doesn't support auto-push

### ISSUE THREAD

**Issue by ngraef** [docker/build-push-action#100]
I'm experimenting with the v2 branch and ran into an issue with the basic use case below. Notice it's using the default builder (no setup-buildx-action step) with the docker driver.

```yaml
jobs:
  build:
    - uses: actions/checkout@v2

    - uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USER }}
        password: ${{ secrets.PASSWORD }}

    - uses: docker/build-push-action@v2-build-push
      with:
        context: .
        tags: ${{ env.REGISTRY }}/myapp:latest
        push: true
```

The output for the build step is:

```
Run docker/build-push-action@v2-build-push
📣 Buildx version: 0.4.2
🏃 Starting build...
/usr/bin/docker buildx build --tag myregistry.io/myapp:latest --iidfile /tmp/docker-build-push-Ghos6S/iidfile --file ./Dockerfile --push .
auto-push is currently not implemented for docker driver
##[error]The process '/usr/bin/docker' failed with exit code 1
```

I realize the error is coming from buildx upstream, but considering this action is called "build-push", I think users would expect this functionality to be implemented by the action if the underlying tool doesn't support it — or at least have a large warning in the README. My use case is more complex than this example, and part of the appeal of this action is that it seamlessly handles pushing a dynamic number of tags.

**Comment by crazy-max** [comment]
@ngraef 

> `auto-push is currently not implemented for docker driver`

The error message will be more explicit in a further release. See docker/buildx#360.

> I think users would expect this functionality to be implemented by the action if the underlying tool doesn't support it — or at least have a large warning in the README.

Thanks for your input, will consider that.

**Comment by ngraef** [comment]
> I think it's better to separate the build part from the setup part.

I agree. I really like the decision to extract login and setup from v2. 👍 

In this case, the environment is already set up to use the docker driver. I don't expect this action to change that setup. I _do_ expect an action called `docker/build-push-action` to be able to push images built with docker.

Thanks for considering, and great work with v2 so far!

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

And it should fix this current issue. Don't hesitate if you have any questions.

**Comment by ngraef** [comment]
> And it should fix this current issue.

@crazy-max It doesn't look like this issue has been fixed yet.

**Comment by crazy-max** [comment]
@ngraef Now the [README with its examples](https://github.com/docker/build-push-action#usage) clearly shows the use of `setup-buildx` within this action.

**Comment by ngraef** [comment]
The result is the same with the `setup-buildx` step.

```yaml
jobs:
  build:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1
      with:
        driver: docker

    - uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USER }}
        password: ${{ secrets.PASSWORD }}

    - uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ env.REGISTRY }}/myapp:latest
        push: true
```

Again, I know this is an upstream limitation, but I believe it makes sense for `docker/build-push-action` to support this basic use case despite buildx's lack of support for it.

**Comment by crazy-max** [comment]
@ngraef 

> I believe it makes sense for docker/build-push-action to support this basic use case despite buildx's lack of support for it.

Our goal is to avoid hacks around this action and be as closed as possible of the `buildx build` command. @tonistiigi can tell us more about it.

**Comment by tonistiigi** [comment]
I'm ok with a hack in `buildx` that just runs `docker push` after build until docker driver doesn't support full buildkit features(pending on containerd storage) if anyone has cycles to implement it.

**Comment by wbobeirne** [comment]
Surprised to find this closed, I also ran into this and was somewhat confused. Unfortunately I have to use the docker driver since multiple images in my build rely on "base" images being built on that same machine. Would definitely like to see this supported.

**Comment by Locustv2** [comment]
@wbobeirne - same here. How are you using the docker driver?

**Comment by crazy-max** [comment]
You have three possibilities (the first one being the more straightforward).

### With docker-container driver (via `setup-buildx`)

```yaml
jobs:
  build:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USER }}
        password: ${{ secrets.PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ env.REGISTRY }}/myapp:latest
        push: true
```

### With docker driver (without `setup-buildx`)

```yaml
jobs:
  build:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USER }}
        password: ${{ secrets.PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ env.REGISTRY }}/myapp:latest
        load: true
    - run: docker push ${{ env.REGISTRY }}/myapp:latest
```

### With docker driver (with `setup-buildx`)

```yaml
jobs:
  build:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      with:
        driver: docker
    - uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USER }}
        password: ${{ secrets.PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ env.REGISTRY }}/myapp:latest
        load: true
    - run: docker push ${{ env.REGISTRY }}/myapp:latest
```

**Comment by veerendra2** [comment]
wow, seems `v1` is easy to use, I can login, build and push in single step. 

I started trying to use v2 to get rid of warning, did I miss anything? 
```
name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: my-org/my-repo/my-image
          tag_with_ref: true

```
