### ISSUE TITLE
Keep last n images option

### ISSUE THREAD

**Issue by paololazzari** [docker/build-push-action#1000]
### Description

Imagine I had a repository which had 3 images in it. 

When I push the fourth one, it would be useful to be able to delete the oldest one so that my repository only ever has 3 images in it.

Something like:

```
- name: Build and push
  uses: docker/build-push-action@v5
  with:
    context: .
    platforms: linux/amd64,linux/arm64
    push: true
    tags: |
      ...
    keep_releases = 3
```

Perhaps considering this is to an extent a destructive operation it could live in a separate action.
