### ISSUE TITLE
`build` is interpreted as file instead of argument

### ISSUE THREAD

**Issue by norman-zon** [docker/build-push-action#1012]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

The `build` part of the `/usr/bin/docker buildx build ...` command is interpreted as a file path, instead of a command argument.

### Expected behaviour

`build` is interpreted as argument to the `docker buildx` command

### Actual behaviour

```
/usr/bin/docker buildx build --file ./build/Dockerfile [...] .
ERROR: could not find build: stat build: no such file or directory
```

### YAML workflow

```yaml
name: Build Migrator Image

on:
  workflow_dispatch:
    inputs:
      MigratorTag:
        description: 'The tag of the image to build'
        required: true
        type: string
env:
  ENVIRONMENT: devel
  PROJECT: xxx
  IMAGE: xxx

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: zon-ubuntu-general-dind

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Baseproject
        id: baseproject
        uses: ZeitOnline/gh-action-baseproject@v0
        with:
          project_name: ${{ env.PROJECT }}
          environment: ${{ env.ENVIRONMENT }}
          gar_docker_auth: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          driver: docker

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          target: migrator
          tags: |
            ${{ env.IMAGE }}:${{ inputs.MigratorTag }}
            ${{ env.IMAGE }}:latest
      - name: Show Image Tag
        run: |
          echo "### Image Tag: ${{ inputs.MigratorTag }}:rocket:" >> $GITHUB_STEP_SUMMARY
```

### Additional info

Running on self-hosted runners, using `ghcr.io/actions/actions-runner v2.311.0`

**Comment by crazy-max** [comment]
> `could not find build`

It means `./build` folder doesn't exist. You can add an additional step before "Build and push Docker Image" to make sure of it:

```yaml
      - run: ls -al

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          target: migrator
          tags: |
            ${{ env.IMAGE }}:${{ inputs.MigratorTag }}
            ${{ env.IMAGE }}:latest
```
