### ISSUE TITLE
is there a push only action?

### ISSUE THREAD

**Issue by nektro** [docker/build-push-action#1016]
### Description

didn't see a bool in the config to disable building. i'm doing the building myself in a different step but need an action to push `local_tag` to `user/repo:latest`.

**Comment by crazy-max** [comment]
No but you can just use the push command as shown in https://github.com/docker/build-push-action/issues/538#issuecomment-1692111198

```yaml
      - name: Tag and push
        run: |
          docker tag local_tag user/repo:latest
          docker push user/repo:latest
```
