### ISSUE TITLE
secrets are visibible in the debug messages 

### ISSUE THREAD

**Issue by dsl400** [docker/build-push-action#1025]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

I can see the whole private key in the debug log when I run the workflow locally using act
```yml
 - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: eu.gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
          build-args: |
            GCP_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }}
```

```[Deploy to Cloud/deploy]   💬  ::debug::Exec.getExecOutput: docker buildx build --build-arg GCP_CREDENTIALS={"type":"service_account","project_id":```

### Expected behaviour

secrets should not be shown in the logs

### Actual behaviour

secrets are shown in the debug output

### YAML workflow

```yaml
- name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: eu.gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
          build-args: |
            GCP_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }}
```
