### ISSUE TITLE
Provenance ignored when set to false If Buildx version is not provided

### ISSUE THREAD

**Issue by warrenbrown** [docker/build-push-action#1035]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

When using build push action when trying to set provenance to false to prevent multi images being built and pushed.  Setting `provenance: false` is not working and provenance is ignored resulting in multi image builds.  What I have discovered is that the buildx version is not being provided hence why setting `provenance: false` is ignored

![buildx-error](https://github.com/docker/build-push-action/assets/209406/0946a8a9-df9f-417b-8efa-608823af8e9b)

![build-push-issue-report](https://github.com/docker/build-push-action/assets/209406/75e475dd-41bb-45bc-ba1b-4284f0daca61)

![CleanShot 2024-01-04 at 07 45 11](https://github.com/docker/build-push-action/assets/209406/08541943-b4a8-411a-b03c-7db8c4e5b084)

Here is a link to the if statement that is supposed to set the buildx version 
https://github.com/docker/build-push-action/blob/master/src/context.ts#L159-L180

Had to create a workaround where I set the buildx version before calling the build push action.

### Expected behaviour

Expect a buildx version to be set so  `provenance: false` is recognized and multiple format image is not pushed to ecr

### Actual behaviour

After setting `provenance: false` a default buildx version is not provided resulting in the provenance value not being recognized, and muilti image builds are being pushed to ecr.

GHA run with provenance: false:
![build-push-issue-report](https://github.com/docker/build-push-action/assets/209406/478f5a67-425b-4f36-ac83-52f2da5eb580)

Buildx version is not recognized or set:
![buildx-error](https://github.com/docker/build-push-action/assets/209406/ab0ef235-b3a9-4e0a-bd5e-d8492ef826a0)

Multiple images pushed:
![multi-images](https://github.com/docker/build-push-action/assets/209406/67190c57-80c6-4bb0-b6d1-1a42a08cec0c)

### YAML workflow

```yaml
jobs:
  build:
    name: docker // build
    steps:
...
      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@1.14.0
        with:
          organization: ${{ inputs.organization }}
          provenance: ${{ inputs.provenance }}
          repository: ${{ inputs.repository }}
          registry: ${{ secrets.registry }}
          workdir: ${{ inputs.context-path }}
          file: ${{ inputs.dockerfile }}
          image_name: ${{ steps.context.outputs.image }}
          build-args: |
            ${{ inputs.build-args }}

      - uses: cloudposse/github-action-secret-outputs@0.1.0
        id: image
        with:
          secret: ${{ secrets.secret-outputs-passphrase }}
          op: encode
          in: ${{ steps.build.outputs.image }}
```

### Workflow logs

[github action logs.txt](https://github.com/docker/build-push-action/files/13831466/github.action.logs.txt)
