### ISSUE TITLE
Build/Push fails if the tag name matches an existing tag in the registry

### ISSUE THREAD

**Issue by jstuessy** [docker/build-push-action#1042]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

The build/push step fails if the tag name matches a tag currently in ECR.

### Expected behaviour

Docker Build/Push shouldn't fail if the tags match since the image is pulled before it is pushed.

### Actual behaviour

The push fails any time the tag is matching a tag currently in ECR

### YAML workflow

```yaml
- uses: docker/build-push-action@v5
        with:
          context: "xxxxx/"
          push: true
          pull: true
          tags: ${{ steps.login-ecr.outputs.registry }}/XXXXXXX:${{ hashFiles('xxxx/**') }}
          file: "xxxxx/docker/Dockerfile"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
```

### Workflow logs

pushing manifest for XXXXXX.dkr.ecr.us-west-2.amazonaws.com/XXXXXXXXXXX@sha256:XXXXXXXXXX
pushing manifest for XXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/XXXXXX:XXXXXXXXXXXXX@sha256:XXXXXXX 0.7s done
ERROR: failed to push XXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/XXXXX:XXXXXXXXXXXX: failed commit on ref "manifest-sha256:XXXXXXXXXXXX": unexpected status from PUT request to https://XXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/v2/XXXXXX/manifests/XXXXXXXXXXXXXXX: 400 Bad Request
