### ISSUE TITLE
net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by tgajdo** [docker/build-push-action#1065]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

This action time to time fails with "net/http: TLS handshake timeout" without any reason. On subsequent re-runs without any change it passes. I'm using ARC on local hosted Kubernetes. 

### Expected behaviour

Always be able to push images.

### Actual behaviour

For almost every first run the push action fails with timeout. 

### YAML workflow

```yaml
- name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.NEXT_VERSION }}
          context: .
          file: ./Dockerfile
          target: production
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ env.NEXT_VERSION }}
            org.opencontainers.image.created=${{ steps.semvers.outputs.date }}
```

### Workflow logs

```
ERROR: failed to solve: failed to push ghcr.io/***/***:0.3.7: failed to do request: Head "https://ghcr.io/v2/***/***/blobs/sha256:***": net/http: TLS handshake timeout
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/***/***:0.3.7: failed to do request: Head "https://ghcr.io/v2/***/***/blobs/sha256:***": net/http: TLS handshake timeout
```
