### ISSUE TITLE
Docker build hangs for `linux/arm/v7`

### ISSUE THREAD

**Issue by Lissy93** [docker/build-push-action#1071]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Feel free to close this ticket if you don't think it's an issue with this action. But any pointers would also be much appreciated, I've been going round in circles for hours trying to get it to work.

I have the following [workflow file](https://github.com/Lissy93/dashy/blob/HEAD/.github/workflows/docker-build-publish.yml) which builds this [Dockerfile](https://github.com/Lissy93/dashy/blob/master/Dockerfile), and it always used to work great.

But now it only works for `linux/amd64` and `linux/arm64` architectures, as soon as I add  `linux/arm/v7` back in under `platforms`, the workflow just hangs forever midway through the ARM v7 step (specifically during `yarn install`) - [here's an example run](https://github.com/Lissy93/dashy/actions/runs/8133127098/job/22224327445#step:10:882)

### Expected behaviour

I expect  `linux/arm/v7` to complete successfully, like it does for `linux/amd64` and `linux/arm64`

### Actual behaviour

The workflow just hangs indefinabley once it starts the `yarn install` on the `linux/arm/v7` step.

### Repository URL

https://github.com/Lissy93/dashy

### Workflow run URL

https://github.com/Lissy93/dashy/actions/workflows/docker-build-publish.yml

### YAML workflow

```yaml
Full workflow file here:
https://github.com/Lissy93/dashy/blob/HEAD/.github/workflows/docker-build-publish.yml

The relevant step is:

- name: ⚒️ Build and push
  uses: docker/build-push-action@v2
  with:
    context: .
    file: ./Dockerfile
    platforms: linux/amd64,linux/arm64,linux/arm/v7
    tags: ${{ steps.meta.outputs.tags }}
    labels: ${{ steps.meta.outputs.labels }}
    push: true
```

### Workflow logs

[logs_21336268151.zip](https://github.com/docker/build-push-action/files/14479222/logs_21336268151.zip) or on GitHub at: https://github.com/Lissy93/dashy/actions/runs/8133127098/job/22224327445 

Another example: [here](https://github.com/Lissy93/dashy/actions/runs/8137851103/job/22237230833)

### Additional info

Thank you for building and maintaining this action, it's been super useful 💙
