### ISSUE TITLE
Cache from different multi platform builds doesn't get used

### ISSUE THREAD

**Issue by ferferga** [docker/build-push-action#1087]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

First of all, please excuse me in case the buildx repo is a better fit for this issue.

I'm building a multi-platform image in different runners (the job has a matrix execution schema). Given my requirements, I can't upload images to any registry and later on create a manifest and push it to have those images for different architectures under a single tag.

Given that it's a must to upload images to a registry to fiddle with manifests, I decided that a good workaround would be to use the cache and rebuild the image in a single job (this time for all platforms) and push it (if the requirements are met).

Using cache in ``max`` or ``min`` mode doesn't change a thing.

### Expected behaviour

When the action is given caches for the same Dockerfile and multiple architectures, the action should use both, and not just one of the architectures.

### Actual behaviour

<details>

1. Every architecture is built in a different runner as part of an matrix strategy. Those builders cache to local:
    *amd64*
    ![amd64](https://github.com/docker/build-push-action/assets/10274099/89719289-684d-4e6c-b757-a879d6edc879)
    *arm64*
    ![arm64](https://github.com/docker/build-push-action/assets/10274099/6c099275-8412-452b-b9e2-964780aa2b3c)
2. That cache is uploaded as an artifact later on:
    *amd64*
    ![image](https://github.com/docker/build-push-action/assets/10274099/e2eb00bc-4dcf-45fa-ad13-6a4e2d2dfe9a)
    *arm64*
    ![image](https://github.com/docker/build-push-action/assets/10274099/f895dc69-b85a-401f-86c3-a75b47612a4a)
3. The artifacts are downloaded in the "Merge Docker images" job, which also targets multiple platforms
    ![image](https://github.com/docker/build-push-action/assets/10274099/5f2fc307-4b6e-4370-9415-2920f206242a)
4. Correct directories, same build arguments and tags are passed to builder (except provenance and sbom, which are not done individually, but they're incompatible with Docker runner)
    ![image](https://github.com/docker/build-push-action/assets/10274099/ec09ee6a-5774-484a-92ba-f4902781721c)
5. ``linux/arm64`` hits cache:
    ![image](https://github.com/docker/build-push-action/assets/10274099/6fa490aa-514d-405b-a985-7776286bbf30)
6. But ``linux/amd64`` doesn't and rebuilds:
    ![image](https://github.com/docker/build-push-action/assets/10274099/d5a83f2d-3bc2-4872-8a48-12c3b681c6b9)

</details>

### Repository URL

https://github.com/ferferga/vue

### Workflow run URL

https://github.com/ferferga/vue/actions/runs/8492650441

### YAML workflow
Irrelevant jobs have been removed:

<details>

```yaml
name: Packaging 📦

on:
  workflow_call:
    inputs:
      commit:
        required: true
        type: string
      tag_name:
        required: false
        type: string
      is_prerelease:
        required: false
        type: boolean
      push:
        required: false
        type: boolean
      architectures:
        description: As GitHub Actions doesn't support globals and/or arrays, you must pass this as an string, like '["amd64", "arm64"]'
        required: false
        type: string
        default: '["amd64", "arm64"]'

env:
  REGISTRY_IMAGE: jellyfin/jellyfin-vue
  RELEASE_TAG: stable
  PRERELEASE_TAG: stable-rc
  COMMIT_TAG: unstable

defaults:
  run:
    shell: bash

jobs:
  docker_tags:
    name: Generate Docker tags 🏷️🐳
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tags.outputs.tags }}

    steps:
      - name: Get current date ⌛
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Parse commit hash ⚙️
        if: ${{ inputs.commit != '' }}
        id: sha
        run: |
          PARSEABLE_SHA='${{ inputs.commit }}'
          echo "sha=${PARSEABLE_SHA::7}" >> $GITHUB_OUTPUT

      ## How tags are assigned:
      ## - 1º block: Handle 'stable' release: No commit, is_prerelease=false
      ## - 2º block: Handle 'stable-rc' release: No commit, is_prerelease=true
      ## - 3º block: Handle 'unstable' release: Has commit hash
      - name: Generate tags 🏷️
        id: tags
        run: |
          TG='${{ inputs.commit == '' && !inputs.is_prerelease && format('{0}:{1},', env.REGISTRY_IMAGE, 'latest') || '' }}'
          TG+='${{ inputs.commit == '' && !inputs.is_prerelease && format('{0}:{1},', env.REGISTRY_IMAGE, env.RELEASE_TAG) || '' }}'
          TG+='${{ inputs.commit == '' && !inputs.is_prerelease && inputs.tag_name && format('{0}:{1}.{2},', env.REGISTRY_IMAGE, env.RELEASE_TAG, inputs.tag_name) || '' }}'
          TG+='${{ inputs.commit == '' && !inputs.is_prerelease && format('ghcr.io/{0}:{1},', env.REGISTRY_IMAGE, 'latest') || '' }}'
          TG+='${{ inputs.commit == '' && !inputs.is_prerelease && format('ghcr.io/{0}:{1},', env.REGISTRY_IMAGE, env.RELEASE_TAG) || '' }}'
          TG+='${{ inputs.commit == '' && !inputs.is_prerelease && inputs.tag_name && format('ghcr.io/{0}:{1}.{2},', env.REGISTRY_IMAGE, env.RELEASE_TAG, inputs.tag_name) || '' }}'

          TG+='${{ inputs.commit == '' && inputs.is_prerelease && format('{0}:{1},', env.REGISTRY_IMAGE, env.PRERELEASE_TAG) || '' }}'
          TG+='${{ inputs.commit == '' && inputs.is_prerelease && inputs.tag_name && format('{0}:{1}.{2},', env.REGISTRY_IMAGE, env.PRERELEASE_TAG, inputs.tag_name) || '' }}'
          TG+='${{ inputs.commit == '' && inputs.is_prerelease && format('ghcr.io/{0}:{1},', env.REGISTRY_IMAGE, env.PRERELEASE_TAG) || '' }}'
          TG+='${{ inputs.commit == '' && inputs.is_prerelease && inputs.tag_name && format('ghcr.io/{0}:{1}.{2},', env.REGISTRY_IMAGE, env.PRERELEASE_TAG, inputs.tag_name) || '' }}'

          TG+='${{ inputs.commit != '' && format('{0}:{1},', env.REGISTRY_IMAGE, env.COMMIT_TAG) || '' }}'
          TG+='${{ inputs.commit != '' && format('{0}:{1}.{2}.{3},', env.REGISTRY_IMAGE, env.COMMIT_TAG, steps.date.outputs.date, steps.sha.outputs.sha) || '' }}'
          TG+='${{ inputs.commit != '' && format('ghcr.io/{0}:{1},', env.REGISTRY_IMAGE, env.COMMIT_TAG) || '' }}'
          TG+='${{ inputs.commit != '' && format('ghcr.io/{0}:{1}.{2}.{3}', env.REGISTRY_IMAGE, env.COMMIT_TAG, steps.date.outputs.date, steps.sha.outputs.sha) || '' }}'
          echo "tags=$TG" >> $GITHUB_OUTPUT

  docker:
    name: Docker image for ${{ matrix.platform }} 💿🐳
    runs-on: ubuntu-latest
    needs: docker_tags
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(inputs.architectures) }}

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.1
        with:
          show-progress: false

      - name: Configure QEMU ⚙️
        uses: docker/setup-qemu-action@v3.0.0

      - name: Configure Docker Buildx ⚙️
        uses: docker/setup-buildx-action@v3.2.0

      - name: Build images 🛠️
        uses: docker/build-push-action@v5.3.0
        id: image
        with:
          context: .
          file: packaging/docker/Dockerfile
          platforms: ${{ format('linux/{0}', matrix.platform) }}
          no-cache: true
          cache-to: type=local,mode=max,dest=/tmp/${{ env.REGISTRY_IMAGE }}/cache/${{ matrix.platform }}
          outputs: type=docker,dest=docker_image.tar
          build-args: |
            ${{ inputs.commit == '' && 'IS_STABLE=1' || '' }}
            ${{ inputs.commit != '' && format('COMMIT_HASH={0}', inputs.commit) || '' }}
          tags: ${{ needs.docker_tags.outputs.tags }}

      - name: Upload Docker image as artifact ⬆️📦
        uses: actions/upload-artifact@v4.3.1
        with:
          compression-level: 0
          name: docker_image-linux_${{ matrix.platform }}
          path: |
            docker_image.tar

      - name: Upload cache artifact ⬆️⚙️
        uses: actions/upload-artifact@v4.3.1
        if: ${{ inputs.push }}
        with:
          compression-level: 0
          name: buildx-${{ matrix.platform }}
          path: |
            /tmp/${{ env.REGISTRY_IMAGE }}/cache/${{ matrix.platform }}

  docker_merge:
    name: Merge Docker images 💿🐳
    runs-on: ubuntu-latest
    if: ${{ inputs.push }}
    needs:
      - docker
      - docker_tags

    steps:
      - name: Download cache artifacts 📦⬇️
        uses: actions/download-artifact@v4.1.4
        with:
          pattern: buildx-*
          path: /tmp/${{ env.REGISTRY_IMAGE }}/cache/

      - name: Remove cache artifacts 🗑️
        uses: geekyeggo/delete-artifact@v5.0.0
        with:
          name: |
            buildx-*
  
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.1
        with:
          show-progress: false

      - name: Configure QEMU ⚙️
        uses: docker/setup-qemu-action@v3.0.0

      - name: Configure Docker Buildx ⚙️
        uses: docker/setup-buildx-action@v3.2.0

      - name: Merge images from cache for multiplatform ${{ inputs.push && 'and push 🛠️⬆️' || '🛠️' }} 
        uses: docker/build-push-action@v5.3.0
        id: image
        with:
          context: .
          file: packaging/docker/Dockerfile
          push: true
          provenance: true
          sbom: true
          cache-from: type=local,mode=max,src=/tmp/${{ env.REGISTRY_IMAGE }}/cache/buildx-${{ join(fromJson(inputs.architectures), format(',type=local,mode=max,src=/tmp/{0}/cache/buildx-', env.REGISTRY_IMAGE)) }}
          platforms: linux/${{ join(fromJson(inputs.architectures), ',linux/') }}
          build-args: |
            ${{ inputs.commit == '' && 'IS_STABLE=1' || '' }}
            ${{ inputs.commit != '' && format('COMMIT_HASH={0}', inputs.commit) || '' }}
          tags: ${{ needs.docker_tags.outputs.tags }}
```

</details>

### Additional info

- This is different from all the issues I found online about this (the most prominent one being https://github.com/docker/buildx/issues/1044). In those cases, users are building for multiple platforms in a single builder and the cache is just being exported for a single architecture. However, I'm using the cache, not exporting it.

- The sample actions failed because no credentials are given. I'm aware that the login actions musty appear first, but it's this way just for testing, you can ignore this as this is completely unrelated
