### ISSUE TITLE
Issue with git clone when the repo include submodules from other repositories

### ISSUE THREAD

**Issue by or-he-MA** [docker/build-push-action#1089]
### Description

We have some submodules in our repo, that points to some other repositories.
Since the first stage of the `build-push-action` is to checkout the current repo, it keeps failing with the error: 
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

When using the the `checkout` action (https://github.com/actions/checkout) we can overcome it using the `submodules` option, for example:
```
      - name: "Checkout current repo"
        uses: actions/checkout@v4
        with:
          submodules: recursive
```

So if i could control wether to checkout the repo and disable it, or the other hand have the option to overcome the submodules, it would be great. Since right now our workflow is failing due to that issue.
