### ISSUE TITLE
Add support for --progress CLI option

### ISSUE THREAD

**Issue by TheFriendlyCoder** [docker/build-push-action#1092]
### Description

The Docker CLI provides an option --progress for customizing the verbosity level produced by the tool. This is particularly helpful when building from a CI because some of the default status messages produced by the tool. For example, when pulling or pushing containers Docker will, by default, show a percentage status update / progress bar to the user. This is great when running within an interactive shell but it just produces unnecessary noise in a build log when running on CI.

It'd be nice if you exposed this property to your GH action plugin so we could easily control the verbosity in a similar way. Perhaps this could be as simple as adding a customization parameter to your plugin config with the same name. It could be optional to preserve backwards compatibility.

**Comment by crazy-max** [comment]
There is no tty on GitHub runners afaik so doesn't make sense imo. That's why the current progress in GitHub actions defaults to `plain` otherwise would be `tty` if detected.

But you can still use the [`BUILDKIT_PROGRESS`](https://docs.docker.com/build/building/variables/#buildkit_progress) env var if you want:

```yaml
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest
        env:
          BUILDKIT_PROGRESS: tty
```
