### ISSUE TITLE
docs: Change use of "Name" to "Path" in dockerfile option information

### ISSUE THREAD

**Issue by matthewfeickert** [docker/build-push-action#11]
Hi. Thanks very much for making this GitHub Action!

I'd like to suggest that in the `dockerfile` option the text

> Name of the Dockerfile

be changed to

> Path to the Dockerfile relative to `path`.

When I first read the docs I got confused by the use of "path" and "name" (instead of "context" and "path") and for a directory that structure that is structured with
```
$ tree
.
├── other_files_needed_for_build
├── docker
│   └── Dockerfile
```
attempted to use

```yaml
    - name: Build and Publish to Registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: org/repo-name
        path: docker
        dockerfile: Dockerfile
```

instead of the following (correct)

```yaml
    - name: Build and Publish to Registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: org/repo-name
        dockerfile: docker/Dockerfile
```

I think the use of "path" would be more clear than "name". If you agree with me I have a branch with this change on my fork that I can open a PR here on (though telling me to do so might involve more typing).
