### ISSUE TITLE
 x509: certificate signed by unknown authority when importing and exporting cache to self hosted GHE

### ISSUE THREAD

**Issue by cbvbs** [docker/build-push-action#1101]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

When importing or exporting a cache to GHE I get an error `tls: failed to verify certificate: x509: certificate signed by unknown authority`. I'm behind a corporate firewall and I need the import/export to make use of my company CA.

I think this might be down to my configuration but I couldn't find documentation in either action I'm using to change ssl configuration for the cache or change the image of the buildx container to one where I could mount the cert at `/etc/ssl/certs`

### Expected behaviour

I expect the import and export to use the company CA that I have provided to the container via the inline buildkit configuration.

### Actual behaviour

The request out to the GHE caching endpoint is ignoring the CA and I receive a failed to verify certificate error.

### YAML workflow

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
          buildkitd-config-inline: |
            [registry."github.company.net"]
              ca=["/etc/docker/certs.d/github.company.net/ca.crt"] # I have verified this works by going into the buildx container and seeing the certificate mounted.

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            111111111111.dkr.ecr.some-region.amazonaws.com/otel-collector:${{ github.sha }}
```

### Workflow logs
[5_Set up Docker Buildx.txt](https://github.com/docker/build-push-action/files/15074302/5_Set.up.Docker.Buildx.txt)
[6_Build and push Docker image.txt](https://github.com/docker/build-push-action/files/15074303/6_Build.and.push.Docker.image.txt)
