### ISSUE TITLE
buildx failed with: ERROR: attestations are not supported by the current buildkitd

### ISSUE THREAD

**Issue by AdarshSavalagi** [docker/build-push-action#1102]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

  /usr/bin/docker buildx version
  github.com/docker/buildx v0.12.1-desktop.4 6996841df2f61988c2794d84d33205368f96c317
/usr/bin/docker buildx build --iidfile /home/runner/work/_temp/docker-actions-toolkit-eOcMoW/iidfile --output type=registry,push=true --provenance mode=min,inline-only=true,builder-id=https://github.com/Envision24/EnvisionMainJS/actions/runs/8803652055 --tag ***/envisionbackend:latest --metadata-file /home/runner/work/_temp/docker-actions-toolkit-eOcMoW/metadata-file .
2024/04/23 16:08:47 http2: server connection error from localhost: connection error: PROTOCOL_ERROR
ERROR: attestations are not supported by the current buildkitd
Error: buildx failed with: ERROR: attestations are not supported by the current buildkitd

and this is my workflow file
name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "adarshsavaligi/aldebrans"
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: adarshsavaligi/envisionbackend:latest
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
          
      - name: SSH into VPS and update container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            docker pull adarshsavaligi/envisionbackend:latest
            docker stop envisionbackend || true
            docker rm envisionbackend || true
            docker image prune -f
            docker run --restart always -d --name envisionbackend -p 3000:3000  adarshsavaligi/envisionbackend:latest

### Expected behaviour

it must build correctly

### Actual behaviour

dont why its fai;ing

### YAML workflow

```yaml
name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "adarshsavaligi/aldebrans"
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: adarshsavaligi/envisionbackend:latest
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
          
      - name: SSH into VPS and update container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            docker pull adarshsavaligi/envisionbackend:latest
            docker stop envisionbackend || true
            docker rm envisionbackend || true
            docker image prune -f
            docker run --restart always -d --name envisionbackend -p 3000:3000  adarshsavaligi/envisionbackend:latest
```
