### ISSUE TITLE
Path context error when copying file from nested Dockerfile

### ISSUE THREAD

**Issue by moy2010** [docker/build-push-action#1113]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Copying a file from a Dockerfile fails despite providing a path context.

### Expected behaviour

The behaviour observed when building the docker image locally.

### Actual behaviour

The file can't be located, resulting in an error

### YAML workflow

```yaml
name: Publish Docker Image

on:
  pull_request:
    paths:
      - web-apps/apps/ssr/**
      - web-apps/packages/**
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: demo-app
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: web-apps
          file: web-apps/apps/demo-app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### Workflow logs

#11 [builder 5/7] COPY /apps/demo-app/tsconfig.production.json ./tsconfig.production.json
#11 ERROR: failed to calculate checksum of ref 584d62f5-11d9-4074-87e4-acacf60905a6::lk5e1y6f6z47pufppid6zsnff: "/apps/demo-app/tsconfig.production.json": not found

### Additional info

Building the docker image locally from the aforementioned build context works (`docker build -f ./apps/demo-app/Dockerfile .`). My gut feeling is that somehow `build-push-action` is reading the path provided to the `COPY` command as absolute rather than relative to the path context.
