### ISSUE TITLE
using `outputs: type=local,dest=$GITHUB_WORKSPACE` with multiarch has unexpected behavior

### ISSUE THREAD

**Issue by jdrouet** [docker/build-push-action#1126]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I want to use an actual Dockerfile to build a binary, using the `platforms` parameter and `outputs: type=local...`.
In my dockerfile, I use the multiarch feature to build the binary and copy it in a target `FROM scratch`.
When I run it locally using `docker buildx build --platform linux/arm64,linux/amd64 --target binary --output type=local,dest=$(pwd)`, it creates 2 directories, `linux_amd64` and `linux_arm64` in which I find the binaries. With this gh action, I only get a single binary.

### Expected behaviour

With this configuration
```yaml
 - name: build binaries using buildx
   uses: docker/build-push-action@v5
   with:
     cache-from: type=gha
     cache-to: type=gha,mode=max
     outputs: type=local,dest=$GITHUB_WORKSPACE
     platform: linux/amd64,linux/arm64
     push: false
     target: binary
```
I'd expect to find `$GITHUB_WORKSPACE/linux_amd64/my-binary` and `$GITHUB_WORKSPACE/linux_arm64/my-binary` but I only get `$GITHUB_WORKSPACE/my-binary`.

### Actual behaviour

With this configuration
```yaml
 - name: build binaries using buildx
   uses: docker/build-push-action@v5
   with:
     cache-from: type=gha
     cache-to: type=gha,mode=max
     outputs: type=local,dest=$GITHUB_WORKSPACE
     platform: linux/amd64,linux/arm64
     push: false
     target: binary
```
I only get `$GITHUB_WORKSPACE/my-binary`.

### Repository URL

https://github.com/jdrouet/git-metrics

### Workflow run URL

https://github.com/jdrouet/git-metrics/actions/runs/9250622026/job/25444518546

### YAML workflow

```yaml
name: release

on:
  pull_request:

jobs:
  build-binaries:
    name: build binaries
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up qemu
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: build binaries using buildx
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=$GITHUB_WORKSPACE
          platform: linux/amd64,linux/arm64
          push: false
          target: binary
      - name: show files
        run: ls -lha $GITHUB_WORKSPACE/*
```

### Workflow logs

See https://github.com/jdrouet/git-metrics/actions/runs/9250622026/job/25444518546
