### ISSUE TITLE
Unexpected error with v5.4.0 release

### ISSUE THREAD

**Issue by javierjulio** [docker/build-push-action#1135]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I started encountering errors with `docker/build-push-action@v5` today since v5.4.0 was released. Since it was on a minor version the error was unexpected. This is the message I see for the action step failure:

> ERROR: docker exporter does not currently support exporting manifest lists
> Error: buildx failed with: ERROR: docker exporter does not currently support exporting manifest lists

Downgrading and locking the action to `docker/build-push-action@v5.3.0` helps avoid any errors in the short term.

It's likely that I'm doing something wrong with the action setup. I don't understand what the error means with how I'm using the action. I believe the error may be related to [this change](https://github.com/docker/build-push-action/pull/1086). Could the error have to do with using a self-hosted runner?

Example action setup:

```
- uses: actions/checkout@v4
- uses: docker/login-action@v3
  with:
    # ...
- uses: docker/setup-buildx-action@v3
  id: buildx
- uses: docker/build-push-action@v5
  with:
    context: .
    builder: ${{ steps.buildx.outputs.name }}
    build-args: |
      # ...
    provenance: false
    load: true
    tags: example-name:${{ github.sha }}
    cache-from: type=gha,scope=${{ github.workflow }}
    cache-to: type=gha,scope=${{ github.workflow }},mode=max
```

### Expected behaviour

No errors on a minor version (v5.4.0) update.

### Actual behaviour

The v5.4.0 action fails to run with an error message as noted in the description. It's likely user error though.

### YAML workflow

```yaml
- uses: actions/checkout@v4
- uses: docker/login-action@v3
  with:
    # ...
- uses: docker/setup-buildx-action@v3
  id: buildx
- uses: docker/build-push-action@v5
  with:
    context: .
    builder: ${{ steps.buildx.outputs.name }}
    build-args: |
      # ...
    provenance: false
    load: true
    tags: example-name:${{ github.sha }}
    cache-from: type=gha,scope=${{ github.workflow }}
    cache-to: type=gha,scope=${{ github.workflow }},mode=max
```

**Comment by crazy-max** [comment]
Thanks for this report! Do you have a link to your repository or full logs?

**Comment by spar-eag** [comment]
I can confirm we ran into the same issue. Possibly related to multi-arch? Our workflow looks something like:
```
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest-l
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install updated Skopeo
        # This can be omitted once runner images have a version of Skopeo > 1.4.1
        # See https://github.com/containers/skopeo/issues/1874
        run: |
          sudo apt purge buildah golang-github-containers-common podman skopeo
          sudo apt autoremove --purge
          REPO_URL="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable"
          source /etc/os-release
          sudo sh -c "echo 'deb ${REPO_URL}/x${NAME}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
          sudo wget -qnv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${NAME}_${VERSION_ID}/Release.key -O Release.key
          sudo apt-key add Release.key
          sudo apt-get update
          sudo apt-get install skopeo

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and export Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Build for all platforms on main, otherwise if triggered manually the selected platforms, otherwise x86
          platforms: ${{ ( github.ref == 'refs/heads/main' && 'linux/amd64,linux/arm/v7' ) || ( github.event.inputs.platforms || 'linux/amd64' ) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
```
