### ISSUE TITLE
v2 doesn't seem to work with GitHub docker package registry

### ISSUE THREAD

**Issue by devpow112** [docker/build-push-action#114]
### Behaviour

Using `v2` to build and push an image to github packages gives error `insufficient_scope: authorization failed` when previous version `v1` did not. Any help would be appreciated.

#### Steps to reproduce this issue

1. Use docker/build-push-action@v2
2. Log into GitHub registry
3. Attempt to build and push to logged in registry
4. Watch error message appear

#### Expected behaviour

Upload of built docker image to succeed

#### Actual behaviour

Fails with `failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed`. This did not happen with `v1`

### Configuration

```yml
name: build
on:
  pull_request:
  push:
    branches:
      - main
env:
  TAG: ${{ github.repository }}/test
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login into registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build & push docker image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.TAG }}
          push: true
```

### Logs

[logs_39.zip](https://github.com/docker/build-push-action/files/5196386/logs_39.zip)
