### ISSUE TITLE
Build-push action requires actions/checkout 

### ISSUE THREAD

**Issue by Ethycs** [docker/build-push-action#1146]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Despite the documentation claiming the opposite, you do need to check out the repository

### Expected behaviour

By default, this action uses the [Git context](https://docs.docker.com/engine/reference/commandline/build/#git-repositories), so you don't need to use the [actions/checkout](https://github.com/actions/checkout/) action to check out the repository as this will be done directly by [BuildKit](https://github.com/moby/buildkit).

(This is a quote of the documentation from the repo)

### Actual behaviour

Build fails because the repository is not checked out. action is fixed by adding a actions/checkout
This was also tried with the following added:
name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

### YAML workflow

```yaml
name: <REDACTED>
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Check working directory
      run: pwd
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: <REDACTED>
        # tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
```

### BuildKit logs

Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: open dockerfile: no such file or directory
