### ISSUE TITLE
Allow configuration of artifacts retention time

### ISSUE THREAD

**Issue by millotp** [docker/build-push-action#1152]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Hello,

With the new feature in [6.0.0](https://github.com/docker/build-push-action/pull/1120) to upload build artifacts, the retention time is set to `90 days` ([source](https://github.com/docker/build-push-action/blob/31159d49c0d4756269a0940a750801a1ea5d7003/src/main.ts#L162)) and is not configurable, which gives warning when the repository already has a default retention.

I like the new feature and would like to keep it, would it be possible to make this configurable, or use the repo default value directly ?

### Expected behaviour

No warnings displayed

### Actual behaviour

![Screenshot 2024-06-24 at 08 46 02](https://github.com/docker/build-push-action/assets/20277482/22fc7269-2c99-45f6-9d6d-59c46ee9b2e0)

### YAML workflow

```yaml
uses: docker/build-push-action@v6.1.0
with:
  file: build/docker/Dockerfile
  context: .
  push: false
```

**Comment by crazy-max** [comment]
> ### Actual behaviour
> 
> ![Screenshot 2024-06-24 at 08 46 02](https://private-user-images.githubusercontent.com/20277482/342231532-22fc7269-2c99-45f6-9d6d-59c46ee9b2e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTMyMzYsIm5iZiI6MTcxOTIxMjkzNiwicGF0aCI6Ii8yMDI3NzQ4Mi8zNDIyMzE1MzItMjJmYzcyNjktMmM5OS00NWY2LTlkNmQtNTljNDZlZTliMmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA3MDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNzJlOGVkYWRkYmY0NDc4MzI5NmRkYTU3MGIwZjZhNDMzNDA5N2JkNzdkN2FjMGQxYzc4ZmYzY2JhMTA0MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BWLmmXXMtADuovRrB3C8WxFcx6Rn3tZHQe_8OyesKuQ)

Yes we should keep default retention days set in repository settings. I think I will just remove the override in actions-toolkit and allow customization with a new env var. Pretty much like https://github.com/actions/upload-artifact/ does.

**Comment by crazy-max** [comment]
@millotp Should be fixed with https://github.com/docker/build-push-action/pull/1153

You can try with:

Default from repo settings:

```yaml
uses: crazy-max/docker-build-push-action@export-retention
with:
  file: build/docker/Dockerfile
  context: .
  push: false
```

Or custom value:

```yaml
uses: crazy-max/docker-build-push-action@export-retention
with:
  file: build/docker/Dockerfile
  context: .
  push: false
env:
  DOCKER_BUILD_EXPORT_RETENTION_DAYS: 2
```
