### ISSUE TITLE
Missing high-level features from v1 in v2 like `tag_with_ref` and `add_git_labels`

### ISSUE THREAD

**Issue by garethr** [docker/build-push-action#116]
The utility in using the action to me, over just running the `docker` commands manually, was in the high-level interface offered by helpers in `v1` like:

* `add_git_labels`
* `tag_with_sha`
* `tag_with_ref`

These all appear to have disappeared in `v2`. Are these planned to be brought back?

Doing:

```yaml
-  name: Build and push
   uses: docker/build-push-action@v2
   with:
     push: true
     tags: user/app:latest
```

Doesn't provide a huge benefit over:

```yaml
- name: Build and push
  run: |
     docker buildx build --push user/app:latest .
```

Compared to implementing any of the following which requires lots of logic and loops.

* `add_git_labels`
* `tag_with_sha`
* `tag_with_ref`
