### ISSUE TITLE
Setting path context does not work when using workflow_dispatch

### ISSUE THREAD

**Issue by mmllc-jsilverman** [docker/build-push-action#1165]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I'm trying to manually trigger a workflow that builds off of a specific branch or tag

For example, tag `v24.6.28.1` exists; I want to use that tag to run this action against. However, I want to trigger it manually, via workflow_dispatch.

No matter what combination of checkout action, moving the codebase into a different dir, specifying that dir with this action's PATH context -- it **always** uses the master branch to build images.

fwiw, the checkout action seems to suffer from this problem as well. To fix that, I had to check out to a subdir, and manually run `git checkout -b branchname tagname` to switch to the branch or tag i want here.

For example, I check out the codebase with the checkout action, then switch branch as stated.

The final path is `${GITHUB_WORKSPACE}/fix-refs/`

When I run the action in this example, I get the error `ERROR: unable to prepare context: path "$***GITHUB_WORKSPACE***/fix-refs/" not found`

If I try to use a relative path, it just uses the `master` branch and not the tag I want to use.

Is there no way to do this with workflow_dispatch?

### Expected behaviour

context should use any arbitrary directory; and/or should not use the github push event context

### Actual behaviour

this action always uses the branch (master) in the push context

### YAML workflow

```yaml
This is just the step causing the issue; in this case, the build-push action builds master:

      - name: Build and push docker
        uses: docker/build-push-action@v6
        with:
          context:  fix-refs/
          push: true
          tags: |
            us-docker.pkg.dev/${{ matrix.project }}/my-proj/my-proj:${{ env.RELEASE_TAG }}
          file: fix-refs/Dockerfile
          target: prod


Or this; in this case, I get the error `ERROR: unable to prepare context: path "$***GITHUB_WORKSPACE***/fix-refs/" not found`

      - name: Build and push docker
        uses: docker/build-push-action@v6
        with:
          context: ${GITHUB_WORKSPACE}/fix-refs/
          push: true
          tags: |
            us-docker.pkg.dev/${{ matrix.project }}/my-proj/my-proj:${{ env.RELEASE_TAG }}
          file: fix-refs/Dockerfile
          target: prod
```
