### ISSUE TITLE
v6 cannot be used with actions/download-artifact@v4

### ISSUE THREAD

**Issue by kateinoigakukun** [docker/build-push-action#1167]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

After updating `docker/build-push-action` to v6, we started observing the following error at `actions/download-artifact` step.

```
Unable to download artifact(s): Unable to download and extract artifact: Artifact download failed after 5 retries.
```

I guess something in the build summary uploading feature is incompatible with `actions/download-artifact`.

You can reproduce the problem with this  https://github.com/kateinoigakukun/gh-actions-sandbox/actions/runs/9737812232/workflow

### Expected behaviour

`actions/download-artifact` can download all artifacts even with this action.

### Actual behaviour

`actions/download-artifact` fails while trying to download all artifacts

### YAML workflow

```yaml
name: Docker Build

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v6
  post-job:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - uses: actions/download-artifact@v4
```

**Comment by crazy-max** [comment]
Thanks for your feedback, looking at the workflow:

```yaml
name: Docker Build

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v6
  post-job:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - uses: actions/download-artifact@v4
```

It seems `actions/download-artifact@v4` downloads all available artifacts within the workflow if `name` or `pattern` is not set: https://github.com/actions/download-artifact?tab=readme-ov-file#download-all-artifacts

> If the `name` input parameter is not provided, all artifacts will be downloaded. To differentiate between downloaded artifacts, by default a directory denoted by the artifacts name will be created for each individual artifact. This behavior can be changed with the `merge-multiple` input parameter.

And will therefore try to download the `.dockerbuild` file uploaded by our action.

```
Starting download of artifact to: /home/runner/work/gh-actions-sandbox/gh-actions-sandbox/kateinoigakukun~gh-actions-sandbox~8P1DEG.dockerbuild
```

I wonder if this is because we are setting the content disposition header when uploading the file to the store: https://github.com/docker/actions-toolkit/blob/fe9937dd36b64d2090fbfec40e144944ae390a12/src/github.ts#L159

I will taker a closer look.
