### ISSUE TITLE
How to always checkout latest commit/tag when using workflow_call

### ISSUE THREAD

**Issue by zigang93** [docker/build-push-action#1175]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I can't force the docker to checkout latest tag / changes / commit when run workflow_call..
my workflow will commit then run docker build.. it cause some issue to take old commit to build

something like this in `actions/checkout@v4`

```yml
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
```

### Expected behaviour

should be able checkout the latest changes

### Actual behaviour

not able checkout the latest changes

### YAML workflow

```yaml
sorry can't provide
```
