### ISSUE TITLE
Default `docker-container`driver does not support referencing local images

### ISSUE THREAD

**Issue by khalil-omer** [docker/build-push-action#1176]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

The `docker-container`driver is needed for caching a base image, however it does not support references to local images, requiring falling back to the `docker` driver, which does not support caching.

### Expected behaviour

As long as an image tag is loaded in a prior action step, a subsequent action step should succeed at referencing that image.  (This is the actual behavior when using the `docker`driver.)

### Actual behaviour

This works fine when using the `docker` driver, but using the `docker-container` default driver, as described in [this stackoverflow post](https://stackoverflow.com/questions/78303777/docker-buildx-with-github-actions), even if you build an image locally prior to building a dependent image, the `FROM local/base-builder` line will lead to this error:

```
#2 [internal] load metadata for docker.io/local/base-builder:latest
#2 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
#3 CANCELED
```

This occurs regardless of the format of the image name. This occurs despite verifying that the image was successfully built in a prior step and was successfully loaded.

### YAML workflow

The below version works, but if I remove `driver: docker` the second image will fail to build despite the first image being visible in the the output of `docker images`.

```yaml
- name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build Base Builder Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Base.Dockerfile
          push: false
          load: true
          tags: local/base-builder
          platforms: linux/arm64
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: List Docker Images
        run: docker images

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/${{ matrix.service }}/Dockerfile
          push: true
          pull: false
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.service }}:${{ github.sha }}
          platforms: linux/arm64
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
```

**Comment by crazy-max** [comment]
Same as https://github.com/docker/build-push-action/issues/1116#issuecomment-2132899905

You can use a local registry for such case: https://docs.docker.com/build/ci/github-actions/local-registry/

```yaml
name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      - name: Build Base Builder Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Base.Dockerfile
          push: true
          tags: localhost:5000/local/base-builder:latest
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/local/base-builder:latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.service }}:${{ github.sha }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

You would need to set `localhost:5000/local/base-builder:latest` in `./apps/${{ matrix.service }}/Dockerfile` or better use a build arg like:

```dockerfile
ARG BASE_IMAGE=local/base-builder
FROM $BASE_IMAGE
```

**Comment by nwalters512** [comment]
It seems like `localhost:5000` doesn't work, I get a "connection refused" error when I try to push with that:

```
Run docker push localhost:5000/prairielearn/workspace-vscode-base:e93040296b50909b9ccc85c05edeb31cf02f5a5f
The push refers to repository [localhost:5000/prairielearn/workspace-vscode-base]
0b99571e357d: Waiting
bc705[8](https://github.com/PrairieLearn/PrairieLearn/actions/runs/12680950876/job/35343715549?pr=11096#step:26:9)8fea44: Waiting
4f4fb700ef54: Waiting
67c94c3c4113: Waiting
8ca1b070baff: Waiting
[9](https://github.com/PrairieLearn/PrairieLearn/actions/runs/12680950876/job/35343715549?pr=11096#step:26:10)7ddd1460abc: Waiting
9015bd43ebf9: Waiting
e2224a467a4e: Waiting
de44b265507a: Waiting
[10](https://github.com/PrairieLearn/PrairieLearn/actions/runs/12680950876/job/35343715549?pr=11096#step:26:11)77948bfe21: Waiting
0e05c971a9d7: Waiting
54189f4b2d04: Waiting
95429cf60879: Waiting
eaa4db556ba8: Waiting
ed6a[12](https://github.com/PrairieLearn/PrairieLearn/actions/runs/12680950876/job/35343715549?pr=11096#step:26:13)ac6415: Waiting
df3cef0bcb[13](https://github.com/PrairieLearn/PrairieLearn/actions/runs/12680950876/job/35343715549?pr=11096#step:26:14): Waiting
failed to do request: Head "https://localhost:5000/v2/prairielearn/workspace-vscode-base/blobs/sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1": dial tcp [::1]:5000: connect: connection refused
```

Here's how the service is set up:

```yaml
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
```

Here's where buildx is set up:

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
```

And here's how I try to push it (after building + loading/exporting the image back to Docker):

```yaml
      - run: docker tag prairielearn/workspace-vscode-base:${{ env.COMMIT_SHA }} registry:5000/prairielearn/workspace-vscode-base:${{ env.COMMIT_SHA }}
      - run: docker push registry:5000/prairielearn/workspace-vscode-base:${{ env.COMMIT_SHA }}
```

Any tips? Let me know if I should open a new issue about this.
