### ISSUE TITLE
v6.4.0 breaks GitHub Actions cache

### ISSUE THREAD

**Issue by TastyPi** [docker/build-push-action#1181]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

We've been seeing errors whenever our workflow tries to export layers to the GitHub cache, e.g.:

```
#37 exporting to GitHub Actions Cache
#37 preparing build cache for export
#37 writing layer sha256:02e1e64c0260323cc3d99a8927d5ecf7bff2f32154352f1822ff9990ee9c0b98
#37 writing layer sha256:02e1e64c0260323cc3d99a8927d5ecf7bff2f32154352f1822ff9990ee9c0b98 0.2s done
#37 writing layer sha256:046ed2589a65eca532f9472df4530273d6b0abd0c9b5985659d6e90b28e28ee5
ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
```

```
------
 > exporting to GitHub Actions Cache:
------
ERROR: failed to solve: error writing layer blob: Patch "https://acghubeus1.actions.githubusercontent.com/Odv8msvJgMS5iWxgU43K2EnWLcwj1p7E8K5nLVIfXGs2O9tj1t/_apis/artifactcache/caches/205053": read tcp 172.17.0.2:57224->20.60.63.33:443: use of closed network connection
```

Fixing the action to `v6.3` instead of `v6` fixed the issue.

### Expected behaviour

Exporting to GitHub action cache should work

### Actual behaviour

Exporting to GitHub action cache always fails

### YAML workflow

We actually use a composite action

```yaml
runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v3
    - name: Docker build
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ inputs.tag }}
        push: ${{ inputs.push }}
        provenance: false
        build-args: REDACTED
        cache-from: type=gha
        cache-to: type=gha,mode=max
```

### Workflow logs

This is just the logs for this action with bits redacted.

[3_Run _._.github_actions_docker_build.txt](https://github.com/user-attachments/files/16253600/3_Run._._.github_actions_docker_build.txt)
