### ISSUE TITLE
Cannot use yaml generic file patterns for Dockerfile

### ISSUE THREAD

**Issue by thunermay** [docker/build-push-action#1182]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

The Dockerfile is not always in the same place (not everytime root). When using generic yaml file specifier, in my case `**/Dockerfile`, the file specifier is ignored. Normally this specifier should match any Dockerfile anywhere in the repo.

### Expected behaviour

When using the generic file specifier, it should match any Dockerfile in the repository.

### Actual behaviour

It takes the file specifier literal as '**/Dockerfile' which is obviously not a file, and fails trying to find it:
```
Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: open **/Dockerfile: no such file or directory
```

### YAML workflow

```yaml
name: build and push to ACR

env:
  tag: "${{ github.run_id }}"
  dockerfile: "**/Dockerfile"

on:
  workflow_call:
   inputs: 
     # name of the image stored in ACR
     IMAGE_REPOSITORY:
       required: true
       type: string
       description: "Name of the image in ACR"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # no need to checkout -> build and push checks out automatically
    
      - name: Login to Docker Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: "${{ secrets.DOCKER_REGISTRY }}"
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build and push image to container Registry (ACR)
        uses: docker/build-push-action@v6.4.0
        with:
          file: "${{ env.dockerfile }}"
          push: true
          tags: |
            "${{secrets.DOCKER_REGISTRY}}/${{ inputs.IMAGE_REPOSITORY }}:${{ env.tag }}"
            "${{secrets.DOCKER_REGISTRY}}/${{ inputs.IMAGE_REPOSITORY }}:latest"
```

### Additional info

This is where my information for the file specifier comes from: [source](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths)
