### ISSUE TITLE
can this be used with GitHub package registry?

### ISSUE THREAD

**Issue by leoschweizer** [docker/build-push-action#12]
Hi,

I'm currently trying to figure out if this action can be used with GitHub package registry. So this was my attempt:
```
      with:
        username: ${{ env.GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        ...
```

However, this nonetheless fails with
> Error: both username and password must be set to login

I suspect the username is the problem, however this is how this docker action is authenticating: https://github.com/matootie/github-docker/blob/master/index.js#L39

I do not want to add a personal access token so I could publish this with my username and my personal access token, although that would probably work.

Does anyone know how to make this work with the injected GITHUB_TOKEN?
