### ISSUE TITLE
Error: Invalid character at v6.6.0.

### ISSUE THREAD

**Issue by tsukaby** [docker/build-push-action#1204]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

Version 6.6.0 is probably broken.
Since this version was released I have observed an error in GitHub Action.

It seems to be pushed to my docker repository(AWS ECR), so the build and push are successful, but it is an error for my workflow.

**Run docker/setup-buildx-action@v3**
```
Booting builder
  /usr/bin/docker buildx inspect --bootstrap --builder builder-8b7d88ad-78c7-4a77-a3ed-8aa5b647861a
  #1 [internal] booting buildkit
  #1 pulling image moby/buildkit:buildx-stable-1
  #1 pulling image moby/buildkit:buildx-stable-1 0.7s done
  #1 creating container buildx_buildkit_builder-8b7d88ad-78c7-4a77-a3ed-8aa5b647861a0
  #1 creating container buildx_buildkit_builder-8b7d88ad-78c7-4a77-a3ed-8aa5b647861a0 30.9s done
  #1 DONE 31.6s
  Name:          builder-8b7d88ad-78c7-4a77-a3ed-8aa5b647861a
  Driver:        docker-container
  Last Activity: 2024-08-07 12:13:30 +0000 UTC
  
  Nodes:
  Name:     builder-8b7d88ad-78c7-4a77-a3ed-8aa5b647861a0
  Endpoint: unix:///var/run/docker.sock
  Error:    Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.46/containers/buildx_buildkit_builder-8b7d88ad-78c7-4a77-a3ed-8aa5b647861a0/json": context deadline exceeded
```

**Run docker/build-push-action@v6**
```

Error: Invalid character
```

### Expected behaviour

Successful build and push without an error.

### Actual behaviour

Build and push failed.

### YAML workflow

```yaml
- name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set Docker tags
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: |
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_WEB }}
        tags: |
          type=sha,prefix=

    - uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/rails/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_WEB }}:cache,scope=${{ github.ref }}-web
        cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_WEB }}:cache,mode=max,image-manifest=true,oci-mediatypes=true,scope=${{ github.ref }}-web
```
