### ISSUE TITLE
Permission denied when accessing secrets

### ISSUE THREAD

**Issue by dluo-sig** [docker/build-push-action#1210]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I'm trying to pass secrets to use in the Dockerfile, but when setting it up based on some of the other examples that I've seen here, I'm getting a permission error.

### Expected behaviour

I would expect that I can read my secret and export it into an env variable to use in the build session.

### Actual behaviour

Permission denied error

### YAML workflow

```yaml
uses: docker/build-push-action@v4
        with:
          context: .
          build-args: ENVIRONMENT_NAME=prod
          secrets: |
            "OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}"
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}:${{ env.IMAGE_TAG }}-orchestration
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

### Dockerfile

```
FROM 1password/op:2

WORKDIR /opt/app
COPY . /opt/app

ARG ENVIRONMENT_NAME

RUN --mount=type=secret,id=OP_SERVICE_ACCOUNT_TOKEN \
  export OP_SERVICE_ACCOUNT_TOKEN=$(cat /run/secrets/OP_SERVICE_ACCOUNT_TOKEN) && \
  op inject -i src/elt_projects/dbt/profiles.${ENVIRONMENT_NAME}.yml -o src/elt_projects/dbt/profiles.yml --force
```

### Workflow logs

```
#11 [stage-0 2/4] WORKDIR /opt/dagster/app
#11 DONE 0.9s
#12 [stage-1 2/7] WORKDIR /opt/dagster/app
#12 DONE 0.3s
#13 [stage-0 3/4] COPY . /opt/dagster/app
#13 DONE 0.0s
#14 [stage-0 4/4] RUN --mount=type=secret,id=OP_SERVICE_ACCOUNT_TOKEN   export OP_SERVICE_ACCOUNT_TOKEN=$(cat /run/secrets/OP_SERVICE_ACCOUNT_TOKEN) &&   op inject -i src/elt_projects/dbt/profiles.prod.yml -o src/elt_projects/dbt/profiles.yml --force
#14 1.072 cat: /run/secrets/OP_SERVICE_ACCOUNT_TOKEN: Permission denied

### BuildKit logs

_No response_

### Additional info
