### ISSUE TITLE
Automations Issues

### ISSUE THREAD

**Issue by andyblac** [docker/build-push-action#1218]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

When using automations to control the lights, the light do perform the action, but Home Assistant UI does not show the updated state.

<img width="1026" alt="Screenshot 2024-08-24 at 21 18 36" src="https://github.com/user-attachments/assets/f4074219-e291-463c-8786-4093d45216da">

### Expected behaviour

when sun evelevation reales -3 and lounge tv is on and lounge patio shade is still open turn on `light.back_garden_neon_rope` and set to 15% and change to green.

the device does turn on and brightness is set and colour is set as well. but HA UI does not see the change.

### Actual behaviour

I expect the UI to update and show the current on state.

### YAML workflow

```yaml
alias: Evening
description: Activate Evening Scene
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.sun_solar_elevation
    below: -3
    id: Elevation
  - platform: time
    at: "21:00:00"
    id: Time
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Elevation
        sequence:
          - data: {}
            target:
              entity_id: scene.evening
            action: scene.turn_on
          - choose:
              - conditions:
                  - condition: device
                    device_id: d2f20607d5ee0e26a00154fa88cec75d
                    domain: media_player
                    entity_id: media_player.lounge_tv
                    type: is_on
                  - condition: state
                    entity_id: cover.lounge_patio_window_shade
                    state: open
                sequence:
                  - data:
                      rgb_color:
                        - 0
                        - 255
                        - 0
                      brightness_pct: 10
                    target:
                      entity_id: light.back_garden_neon_rope
                    action: light.turn_on
            enabled: true
          - choose:
              - conditions:
                  - condition: state
                    entity_id: media_player.media_room_tv
                    state: "on"
                sequence:
                  - data:
                      brightness_pct: 50
                    target:
                      entity_id: light.media_room_sideboard_lamps
                    action: light.turn_on
                  - data: {}
                    target:
                      entity_id: switch.office_sockets_1_left
                    action: switch.turn_off
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.andrews_imac_active
                    state: "on"
                sequence:
                  - data: {}
                    target:
                      entity_id: light.office_dimmer
                    action: light.turn_on
            enabled: true
      - conditions:
          - condition: trigger
            id:
              - Time
        sequence:
          - device_id: 544648ee280e620220c713004dd26b38
            domain: cover
            entity_id: 52152b8c44e661769d399054db667131
            type: close
mode: single
```

### Workflow logs

```yaml
{
  "trace": {
    "last_step": "action/0/choose/0/sequence/3/choose/0/conditions/0/entity_id/0",
    "run_id": "4c1ada3f30bd4916fb89221a6c5cb345",
    "state": "stopped",
    "script_execution": "finished",
    "timestamp": {
      "start": "2024-08-24T19:36:28.453343+00:00",
      "finish": "2024-08-24T19:36:29.771557+00:00"
    },
    "domain": "automation",
    "item_id": "1680805974926",
    "trigger": "numeric state of sensor.sun_solar_elevation",
    "trace": {
      "trigger/1": [
        {
          "path": "trigger/1",
          "timestamp": "2024-08-24T19:36:28.453495+00:00",
          "changed_variables": {
            "this": {
              "entity_id": "automation.evening_sunset",
              "state": "on",
              "attributes": {
                "id": "1680805974926",
                "last_triggered": "2024-08-23T20:00:00.417120+00:00",
                "mode": "single",
                "current": 0,
                "icon": "mdi:weather-sunset-down",
                "friendly_name": "Evening"
              },
              "last_changed": "2024-08-23T19:55:20.345914+00:00",
              "last_reported": "2024-08-23T20:00:00.422250+00:00",
              "last_updated": "2024-08-23T20:00:00.422250+00:00",
              "context": {
                "id": "01J60D62X138W15D5VYV70VH30",
                "parent_id": null,
                "user_id": null
              }
            },
            "trigger": {
              "id": "Elevation",
              "idx": "1",
              "alias": null,
              "platform": "numeric_state",
              "entity_id": "sensor.sun_solar_elevation",
              "below": -3,
              "above": null,
              "from_state": {
                "entity_id": "sensor.sun_solar_elevation",
                "state": "-2.83",
                "attributes": {
                  "state_class": "measurement",
                  "unit_of_measurement": "°",
                  "friendly_name": "Sun Solar elevation"
                },
                "last_changed": "2024-08-24T19:32:28.452143+00:00",
                "last_reported": "2024-08-24T19:32:28.452143+00:00",
                "last_updated": "2024-08-24T19:32:28.452143+00:00",
                "context": {
                  "id": "01J62Y0CN4JAZPH8D1Q2BMDKNH",
                  "parent_id": null,
                  "user_id": null
                }
              },
              "to_state": {
                "entity_id": "sensor.sun_solar_elevation",
                "state": "-3.38",
                "attributes": {
                  "state_class": "measurement",
                  "unit_of_measurement": "°",
                  "friendly_name": "Sun Solar elevation"
                },
                "last_changed": "2024-08-24T19:36:28.452366+00:00",
                "last_reported": "2024-08-24T19:36:28.452366+00:00",
                "last_updated": "2024-08-24T19:36:28.452366+00:00",
                "context": {
                  "id": "01J62Y7Q14JEPT484TZMEC3DXP",
                  "parent_id": null,
                  "user_id": null
                }
              },
              "for": null,
              "description": "numeric state of sensor.sun_solar_elevation"
            }
          }
        }
      ],
      "action/0": [
        {
          "path": "action/0",
          "timestamp": "2024-08-24T19:36:28.453981+00:00",
          "changed_variables": {
            "context": {
              "id": "01J62Y7Q15D7CEN773NH8Z1ADA",
              "parent_id": "01J62Y7Q14JEPT484TZMEC3DXP",
              "user_id": null
            }
          },
          "result": {
            "choice": 0
          }
        }
      ],
      "action/0/choose/0": [
        {
          "path": "action/0/choose/0",
          "timestamp": "2024-08-24T19:36:28.454119+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "action/0/choose/0/conditions/0": [
        {
          "path": "action/0/choose/0/conditions/0",
          "timestamp": "2024-08-24T19:36:28.454175+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "action/0/choose/0/sequence/0": [
        {
          "path": "action/0/choose/0/sequence/0",
          "timestamp": "2024-08-24T19:36:28.454532+00:00",
          "result": {
            "params": {
              "domain": "scene",
              "service": "turn_on",
              "service_data": {},
              "target": {
                "entity_id": [
                  "scene.evening"
                ]
              }
            },
            "running_script": false
          }
        }
      ],
      "action/0/choose/0/sequence/1": [
        {
          "path": "action/0/choose/0/sequence/1",
          "timestamp": "2024-08-24T19:36:29.761379+00:00",
          "result": {
            "choice": 0
          }
        }
      ],
      "action/0/choose/0/sequence/1/choose/0": [
        {
          "path": "action/0/choose/0/sequence/1/choose/0",
          "timestamp": "2024-08-24T19:36:29.761910+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "action/0/choose/0/sequence/1/choose/0/conditions/0": [
        {
          "path": "action/0/choose/0/sequence/1/choose/0/conditions/0",
          "timestamp": "2024-08-24T19:36:29.761976+00:00",
          "result": {
            "result": true,
            "state": "on",
            "wanted_state": "on"
          }
        }
      ],
      "action/0/choose/0/sequence/1/choose/0/conditions/1": [
        {
          "path": "action/0/choose/0/sequence/1/choose/0/conditions/1",
          "timestamp": "2024-08-24T19:36:29.762071+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "action/0/choose/0/sequence/1/choose/0/conditions/1/entity_id/0": [
        {
          "path": "action/0/choose/0/sequence/1/choose/0/conditions/1/entity_id/0",
          "timestamp": "2024-08-24T19:36:29.762118+00:00",
          "result": {
            "result": true,
            "state": "open",
            "wanted_state": "open"
          }
        }
      ],
      "action/0/choose/0/sequence/1/choose/0/sequence/0": [
        {
          "path": "action/0/choose/0/sequence/1/choose/0/sequence/0",
          "timestamp": "2024-08-24T19:36:29.762544+00:00",
          "result": {
            "params": {
              "domain": "light",
              "service": "turn_on",
              "service_data": {
                "rgb_color": [
                  0,
                  255,
                  0
                ],
                "brightness_pct": 15,
                "entity_id": [
                  "light.back_garden_neon_rope"
                ]
              },
              "target": {
                "entity_id": [
                  "light.back_garden_neon_rope"
                ]
              }
            },
            "running_script": false
          }
        }
      ],
      "action/0/choose/0/sequence/2": [
        {
          "path": "action/0/choose/0/sequence/2",
          "timestamp": "2024-08-24T19:36:29.766597+00:00"
        }
      ],
      "action/0/choose/0/sequence/2/choose/0": [
        {
          "path": "action/0/choose/0/sequence/2/choose/0",
          "timestamp": "2024-08-24T19:36:29.767110+00:00",
          "result": {
            "result": false
          }
        }
      ],
      "action/0/choose/0/sequence/2/choose/0/conditions/0": [
        {
          "path": "action/0/choose/0/sequence/2/choose/0/conditions/0",
          "timestamp": "2024-08-24T19:36:29.767195+00:00",
          "result": {
            "result": false
          }
        }
      ],
      "action/0/choose/0/sequence/2/choose/0/conditions/0/entity_id/0": [
        {
          "path": "action/0/choose/0/sequence/2/choose/0/conditions/0/entity_id/0",
          "timestamp": "2024-08-24T19:36:29.767263+00:00",
          "result": {
            "result": false,
            "state": "off",
            "wanted_state": "on"
          }
        }
      ],
      "action/0/choose/0/sequence/3": [
        {
          "path": "action/0/choose/0/sequence/3",
          "timestamp": "2024-08-24T19:36:29.767539+00:00"
        }
      ],
      "action/0/choose/0/sequence/3/choose/0": [
        {
          "path": "action/0/choose/0/sequence/3/choose/0",
          "timestamp": "2024-08-24T19:36:29.767919+00:00",
          "result": {
            "result": false
          }
        }
      ],
      "action/0/choose/0/sequence/3/choose/0/conditions/0": [
        {
          "path": "action/0/choose/0/sequence/3/choose/0/conditions/0",
          "timestamp": "2024-08-24T19:36:29.767995+00:00",
          "result": {
            "result": false
          }
        }
      ],
      "action/0/choose/0/sequence/3/choose/0/conditions/0/entity_id/0": [
        {
          "path": "action/0/choose/0/sequence/3/choose/0/conditions/0/entity_id/0",
          "timestamp": "2024-08-24T19:36:29.768062+00:00",
          "result": {
            "result": false,
            "state": "off",
            "wanted_state": "on"
          }
        }
      ]
    },
    "config": {
      "id": "1680805974926",
      "alias": "Evening",
      "description": "Activate Evening Scene",
      "trigger": [
        {
          "platform": "sun",
          "event": "sunset",
          "enabled": false
        },
        {
          "platform": "numeric_state",
          "entity_id": [
            "sensor.sun_solar_elevation"
          ],
          "below": -3,
          "id": "Elevation"
        },
        {
          "platform": "time",
          "at": "21:00:00",
          "id": "Time"
        }
      ],
      "condition": [],
      "action": [
        {
          "choose": [
            {
              "conditions": [
                {
                  "condition": "trigger",
                  "id": [
                    "Elevation"
                  ]
                }
              ],
              "sequence": [
                {
                  "data": {},
                  "target": {
                    "entity_id": "scene.evening"
                  },
                  "action": "scene.turn_on"
                },
                {
                  "choose": [
                    {
                      "conditions": [
                        {
                          "condition": "device",
                          "device_id": "d2f20607d5ee0e26a00154fa88cec75d",
                          "domain": "media_player",
                          "entity_id": "media_player.lounge_tv",
                          "type": "is_on"
                        },
                        {
                          "condition": "state",
                          "entity_id": "cover.lounge_patio_window_shade",
                          "state": "open"
                        }
                      ],
                      "sequence": [
                        {
                          "data": {
                            "rgb_color": [
                              0,
                              255,
                              0
                            ],
                            "brightness_pct": 15
                          },
                          "target": {
                            "entity_id": "light.back_garden_neon_rope"
                          },
                          "action": "light.turn_on"
                        }
                      ]
                    }
                  ],
                  "enabled": true
                },
                {
                  "choose": [
                    {
                      "conditions": [
                        {
                          "condition": "state",
                          "entity_id": "media_player.media_room_tv",
                          "state": "on"
                        }
                      ],
                      "sequence": [
                        {
                          "data": {
                            "brightness_pct": 50
                          },
                          "target": {
                            "entity_id": "light.media_room_sideboard_lamps"
                          },
                          "action": "light.turn_on"
                        },
                        {
                          "data": {},
                          "target": {
                            "entity_id": "switch.office_sockets_1_left"
                          },
                          "action": "switch.turn_off"
                        }
                      ]
                    }
                  ]
                },
                {
                  "choose": [
                    {
                      "conditions": [
                        {
                          "condition": "state",
                          "entity_id": "binary_sensor.andrews_imac_active",
                          "state": "on"
                        }
                      ],
                      "sequence": [
                        {
                          "data": {},
                          "target": {
                            "entity_id": "light.office_dimmer"
                          },
                          "action": "light.turn_on"
                        }
                      ]
                    }
                  ],
                  "enabled": true
                }
              ]
            },
            {
              "conditions": [
                {
                  "condition": "trigger",
                  "id": [
                    "Time"
                  ]
                }
              ],
              "sequence": [
                {
                  "device_id": "544648ee280e620220c713004dd26b38",
                  "domain": "cover",
                  "entity_id": "52152b8c44e661769d399054db667131",
                  "type": "close"
                }
              ]
            }
          ]
        }
      ],
      "mode": "single"
    },
    "blueprint_inputs": null,
    "context": {
      "id": "01J62Y7Q15D7CEN773NH8Z1ADA",
      "parent_id": "01J62Y7Q14JEPT484TZMEC3DXP",
      "user_id": null
    }
  },
  "logbookEntries": [
    {
      "name": "Evening",
      "message": "triggered by numeric state of sensor.sun_solar_elevation",
      "source": "numeric state of sensor.sun_solar_elevation",
      "entity_id": "automation.evening_sunset",
      "context_id": "01J62Y7Q15D7CEN773NH8Z1ADA",
      "when": 1724528188.4536078,
      "domain": "automation"
    },
    {
      "when": 1724528188.4553838,
      "state": "2024-08-24T19:36:28.455296+00:00",
      "entity_id": "scene.evening",
      "icon": "mdi:sofa",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528188.5976796,
      "state": "on",
      "entity_id": "switch.lounge_sockets_4_right",
      "icon": "mdi:power-socket-uk",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528188.5996838,
      "state": "on",
      "entity_id": "light.lounge_lamp_2",
      "icon": "mdi:lamp",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528188.6377175,
      "state": "on",
      "entity_id": "light.lounge_lamps",
      "icon": "mdi:lamp",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528188.647578,
      "state": "on",
      "entity_id": "switch.lounge_sockets_3_right",
      "icon": "mdi:power-socket-uk",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528188.647969,
      "state": "on",
      "entity_id": "light.lounge_lamp_1",
      "icon": "mdi:lamp",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528188.6493552,
      "state": "on",
      "entity_id": "light.garage_wall_light",
      "icon": "phu:wall-lucca",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528188.6551707,
      "state": "on",
      "entity_id": "switch.lounge_sockets_5_left",
      "icon": "mdi:power-socket-uk",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528188.6553228,
      "state": "on",
      "entity_id": "light.lounge_lamp_3",
      "icon": "mdi:lamp",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.291067,
      "state": "closing",
      "entity_id": "cover.mums_bedroom_somfy_window_shade",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.2914977,
      "state": "closing",
      "entity_id": "sensor.mums_shade_helper",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.2918024,
      "state": "closing",
      "entity_id": "cover.mums_bedroom_window_shade",
      "icon": "phu:shutter-20",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.4008875,
      "state": "closing",
      "entity_id": "cover.office_somfy_window_shade",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.4024096,
      "state": "closing",
      "entity_id": "sensor.office_shade_helper",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.4033022,
      "state": "closing",
      "entity_id": "cover.office_window_shade",
      "icon": "phu:shutter-20",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.4994164,
      "state": "closing",
      "entity_id": "cover.media_room_somfy_window_shade",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.5000308,
      "state": "closing",
      "entity_id": "sensor.media_room_shade_helper",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.5006716,
      "state": "closing",
      "entity_id": "cover.media_room_window_shade",
      "icon": "phu:shutter-20",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.7354746,
      "state": "closing",
      "entity_id": "cover.andys_bedroom_somfy_window_shade",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.7360332,
      "state": "closing",
      "entity_id": "cover.kitchen_somfy_window_shade",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.736609,
      "state": "closing",
      "entity_id": "sensor.andys_shade_helper",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.7370636,
      "state": "closing",
      "entity_id": "sensor.kitchen_shade_helper",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.7380455,
      "state": "closing",
      "entity_id": "cover.andys_bedroom_window_shade",
      "icon": "phu:shutter-20",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.7389438,
      "state": "closing",
      "entity_id": "cover.kitchen_window_shade",
      "icon": "phu:shutter-20",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528189.8932602,
      "state": "closing",
      "entity_id": "cover.lounge_window_shade",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528190.8496518,
      "state": "unknown",
      "entity_id": "cover.mums_bedroom_somfy_window_shade",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528190.8508403,
      "state": "closed",
      "entity_id": "sensor.mums_shade_helper",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528190.8516626,
      "state": "closed",
      "entity_id": "cover.mums_bedroom_window_shade",
      "icon": "mdi:arrow-down-box",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528191.859362,
      "state": "unknown",
      "entity_id": "cover.office_somfy_window_shade",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528191.860855,
      "state": "closed",
      "entity_id": "sensor.office_shade_helper",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528191.8616738,
      "state": "closed",
      "entity_id": "cover.office_window_shade",
      "icon": "mdi:arrow-down-box",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528192.8505075,
      "state": "unknown",
      "entity_id": "cover.media_room_somfy_window_shade",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528192.8514824,
      "state": "closed",
      "entity_id": "sensor.media_room_shade_helper",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    },
    {
      "when": 1724528192.852297,
      "state": "closed",
      "entity_id": "cover.media_room_window_shade",
      "icon": "mdi:arrow-down-box",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Evening",
      "context_message": "triggered by numeric state of sensor.sun_solar_elevation",
      "context_source": "numeric state of sensor.sun_solar_elevation",
      "context_entity_id": "automation.evening_sunset"
    }
  ]
}
```

```
[2024-08-24T20:36:29 INFO  govee::service::hass] Command for Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8): {"state":"ON","color":{"r":0,"g":255,"b":0},"brightness":15}
[2024-08-24T20:36:29 INFO  govee::service::state] Using LAN API to set Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8) brightness
[2024-08-24T20:36:29 INFO  govee::service::state] Using LAN API to set Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8) color
```
