### ISSUE TITLE
COPY will be invalid due to `#!/bin/bash`

### ISSUE THREAD

**Issue by Mon-ius** [docker/build-push-action#1225]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I have an action file for build `v3` from the sub-sub-directory Dockerfile,

The structure of project is:

```sh
├── dev
│   ├── Meta
│   ├── click.sh
│   ├── v1
│   │   ├── Dockerfile
│   │   └── entrypoint.sh
│   ├── v2
│   │   ├── Dockerfile
│   │   └── entrypoint.sh
│   ├── v3
│   │   ├── Dockerfile
│   │   └── entrypoint.sh
```

The action file is:
```yml
name: build-v3

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 */6 * *'
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-v3.yml"
      - "dev/v3/Dockerfile"
      - "dev/v3/entrypoint.sh"

jobs:
  build-v3:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push v3 file
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dev/v3/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64, linux/s390x, linux/arm, linux/ppc64le, linux/riscv64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-warp-socks:v3
```

Inside the `dev/v3/Dockerfile`, see [Dockerfile](https://github.com/Mon-ius/Docker-Warp-Socks/blob/947deee8b7e222f43250fffdb0986c7fa1ce9b61/dev/v3/Dockerfile)

```sh
COPY dev/v3/entrypoint.sh /opt/entrypoint.sh
ENTRYPOINT ["/opt/entrypoint.sh"]
```

### Expected behaviour

It should copy the `dev/v3/entrypoint.sh` from `git` to `/opt/entrypoint.sh` inside the container.

### Actual behaviour

exec /opt/entrypoint.sh: no such file or directory
exec /opt/entrypoint.sh: no such file or directory
exec /opt/entrypoint.sh: no such file or directory
exec /opt/entrypoint.sh: no such file or directory

### Repository URL

https://github.com/Mon-ius/Docker-Warp-Socks/blob/947deee8b7e222f43250fffdb0986c7fa1ce9b61

### Workflow run URL

https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/10761703139

### YAML workflow

```yaml
https://github.com/Mon-ius/Docker-Warp-Socks/blob/947deee8b7e222f43250fffdb0986c7fa1ce9b61/.github/workflows/build-v3.yml
```
