### ISSUE TITLE
No builder found

### ISSUE THREAD

**Issue by jfkrdev** [docker/build-push-action#1239]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

In the build summary I receive an error message, that no builder was found, yet the build succeeds.

### Expected behaviour

I expected that the summary would not show any errors

### Actual behaviour

The post build job contains this error on every run:
```
ERROR: no builder "builder-27f86516-8b69-444b-b6c4-28e945d1c29e" found
  Process "buildx dial-stdio" exited with code 1
  2024/09/09 16:[18](https://github.com/mia-gmbh/coder-web/actions/runs/10776953395/job/29885311241#step:25:21):06 error: Unavailable: connection error: desc = "error reading server preface: EOF"
  github.com/moby/buildkit/util/stack.Enable
```

The error is reproduced when running the same workflow. 

### YAML workflow

```
name: Build Vue.js application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docker-image:
    name: Build Vue.js application and BFF as docker image
    runs-on: [self-hosted, Linux, node, deno, playwright]

    permissions:
      contents: read
      packages: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout reusable actions
      uses: actions/checkout@v4
      with:
        repository: mia-gmbh/github-workflows
        ref: main
        token: ${{ secrets.MIA_CHECKOUT_SHARED_ACTIONS }}
        path: ./.github/actions/shared

    - name: Initialize git lfs
      run: |
        git lfs install
        git lfs fetch
        git lfs checkout
    - name: Install dependencies
      uses: ./.github/actions/shared/install-npm-dependencies
      with:
        fontawesome-npm-registry-token: ${{ secrets.FONTAWESOME_NPM_REGISTRY_TOKEN }}

    - name: Lint frontend code
      run: "npm run ci:lint"

    - name: Check frontend types
      run: "npm run typecheck"

    - name: Run frontend unit test
      run: "npm run test"

    - name: Lint bff code
      run: "deno lint"

    - name: Run bff unit tests
      run: "deno task test"

    - name: Run storybook tests
      run: "npm run storybook:test"
      env:
        NODE_OPTIONS: --max-old-space-size=4096

    - name: Build vue app
      if: success() && github.ref == 'refs/heads/main'
      run: "npm run build"

    - name: Calculate version
      id: get-version
      if: success() && github.ref == 'refs/heads/main'
      uses: ./.github/actions/shared/npm-project-version

    - name: Build docker image
      id: docker
      if: success() && github.ref == 'refs/heads/main'
      uses: ./.github/actions/shared/build-docker-image
      with:
        version: ${{ steps.get-version.outputs.version }}
        push: true

    outputs:
      docker-tag: ${{ steps.docker.outputs.docker-tag }}

  deploy-to-dev:
    needs: build-docker-image
    if: github.ref == 'refs/heads/main'
    uses: mia-gmbh/github-workflows/.github/workflows/deploy-service.yml@main
    secrets: inherit
    with:
      docker-tag: ${{ needs.build-docker-image.outputs.docker-tag }}
```

### Workflow logs

```
Post job cleanup.
Post job cleanup.
Removing builder
Cleaning up certificates
Post cache
Post job cleanup.
Generating build summary
  exporting build record to /_work/github-runner-OPmlDSV95c4un/_temp/docker-actions-toolkit-n5deYQ/export
  /usr/bin/mkfifo /_work/github-runner-OPmlDSV95c4un/_temp/docker-actions-toolkit-n5deYQ/buildx-in-GT69qU.fifo
  /usr/bin/mkfifo /_work/github-runner-OPmlDSV95c4un/_temp/docker-actions-toolkit-n5deYQ/buildx-out-SVoaT0.fifo
  docker buildx --builder builder-[2](https://github.com/mia-gmbh/coder-web/actions/runs/10776953395/job/29885311241#step:25:2)7f86516-8b69-444b-b6c4-28e945d1c29e dial-stdio
  docker run --rm -i -v /root/.docker/buildx/refs:/buildx-refs -v /_work/github-runner-OPmlDSV95c4un/_temp/docker-actions-toolkit-n5deYQ/export:/out docker.io/dockereng/export-build:latest --ref-state-dir=/buildx-refs --node=builder-27f86516-8b69-444b-b6c4-28e945d1c29e/builder-27f86516-8b69-444b-b6c4-28e945d1c29e0 --ref=971vi0a7jcujv1f5bv4k95va4 --uid=0 --gid=0
  ERROR: no builder "builder-27f86516-8b69-444b-b6c4-28e945d1c29e" found
  Process "buildx dial-stdio" exited with code 1
  2024/09/09 16:18:06 error: Unavailable: connection error: desc = "error reading server preface: EOF"
  github.com/moby/buildkit/util/stack.Enable
  	/go/pkg/mod/github.com/moby/buildkit@v0.15.0/util/stack/stack.go:78
  github.com/moby/buildkit/util/grpcerrors.FromGRPC
  	/go/pkg/mod/github.com/moby/buildkit@v0.15.0/util/grpcerrors/grpcerrors.go:198
  github.com/moby/buildkit/util/grpcerrors.UnaryClientInterceptor
  	/go/pkg/mod/github.com/moby/buildkit@v0.15.0/util/grpcerrors/intercept.go:41
  google.golang.org/grpc.(*ClientConn).Invoke
  	/go/pkg/mod/google.golang.org/grpc@v1.59.0/call.go:[3](https://github.com/mia-gmbh/coder-web/actions/runs/10776953395/job/29885311241#step:25:3)5
  github.com/moby/buildkit/api/services/control.(*controlClient).ListWorkers
  	/go/pkg/mod/github.com/moby/buildkit@v0.15.0/api/services/control/control.pb.go:2324
  github.com/moby/buildkit/client.(*Client).ListWorkers
  	/go/pkg/mod/github.com/moby/buildkit@v0.15.0/client/workers.go:31
  main.run
  	/src/main.go:104
  main.main
  	/src/main.go:81
  runtime.main
  	/usr/local/go/src/runtime/proc.go:271
  runtime.goexit
  	/usr/local/go/src/runtime/asm_amd[6](https://github.com/mia-gmbh/coder-web/actions/runs/10776953395/job/29885311241#step:25:7)4.s:1695
  failed to list workers
  github.com/moby/buildkit/client.(*Client).ListWorkers
  	/go/pkg/mod/github.com/moby/buildkit@v0.15.0/client/workers.go:33
  main.run
  	/src/main.go:104
  main.main
  	/src/main.go:81
  runtime.main
  	/usr/local/go/src/runtime/proc.go:2[7](https://github.com/mia-gmbh/coder-web/actions/runs/10776953395/job/29885311241#step:25:9)1
  runtime.goexit
  	/usr/local/go/src/runtime/asm_amd64.s:16[9](https://github.com/mia-gmbh/coder-web/actions/runs/10776953395/job/29885311241#step:25:12)5
  failed to list workers
  main.run
  	/src/main.go:[10](https://github.com/mia-gmbh/coder-web/actions/runs/10776953395/job/29885311241#step:25:13)6
  main.main
  	/src/main.go:81
  runtime.main
  	/usr/local/go/src/runtime/proc.go:271
  runtime.goexit
  	/usr/local/go/src/runtime/asm_amd64.s:1695
  Process "docker run" exited with code 1
  Warning: Process "docker run" closed with code 1
Removing temp folder /_work/github-runner-OPmlDSV95c4un/_temp/docker-actions-toolkit-Xd7eaZ
Post cache
```
