### ISSUE TITLE
Docker build fails with gh cache

### ISSUE THREAD

**Issue by navpreet-securitas** [docker/build-push-action#1253]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

I'm setting up docker cache with Github Cache.
we have reusable  workflow which contains:

```
- name: Docker Setup Buildx
   id: buildx
   if: ${{ inputs.enable_docker_cache }}
   uses:  docker/setup-buildx-action@v3
    with: 
       driver: docker-container
       driver-opts: image=moby/buildkit:master,network=host

- name: Build and push Docker images
   if: ${{ !inputs.enable_docker_cache }}
   uses: docker/build-push-action@v6
   with:
      context: .
      file: ${{ inputs.dockerFilePath }}
      push: true
      tags: "${{ inputs.image }}:${{ inputs.buildId }}"
      cache-from: type=gha
      cache-to: type=gha,mode=max
```

with this setup  Docker build fails giving following error:

> ERROR: Cache export is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again. 

even though in buildx  step we have `driver: docker-container` defined. When i check Builder Info in build-push-action , it show still using docker driver. Means it might not be using builder created by buildx.

_Builder info
{
    "nodes": [
      {
        "name": "default",
        "endpoint": "default",
        "status": "running",
        "buildkit": "v0.13.2",
        "platforms": "linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/386",
        "features": {
          "Automatically load images to the Docker Engine image store": true,
          "Cache export": true,
          "Docker exporter": true,
          "Multi-platform build": true,
          "OCI exporter": true
        },
        "labels": {
          "org.mobyproject.buildkit.worker.moby.host-gateway-ip": "172.17.0.1"
        }
      }
    ],
    "name": "default",
    "driver": "docker"
  }_

then i tried to explicitly specify builder like:

```
- name: Build and push Docker images with cache
   if: ${{ inputs.enable_docker_cache }}
   uses: docker/build-push-action@v6
   with:
       context: .
       file: ${{ inputs.dockerFilePath }}
       build-args: PAT=${{ secrets.GH_PACKAGES_PAT }}
       push: true
       **builder: ${{ steps.buildx.outputs.name }}**
       tags: "${{ inputs.image }}:${{ inputs.buildId }}"
       cache-from: type=gha
       cache-to: type=gha,mode=max
```

it can't find builder with that ID:

_Builder info
Error: ERROR: no builder "builder-73c5e432-9c93-4ad2-8927-cade4c092a42" found
2375 v0.18.0 /usr/libexec/docker/cli-plugins/docker-buildx buildx inspect builder-73c5e432-9c93-4ad2-8927-cade4c092a42
github.com/docker/buildx/store/storeutil.GetNodeGroup
	github.com/docker/buildx/store/storeutil/storeutil.go:108_

### Expected behaviour

docker cache to work with GH cache

### Actual behaviour

ERROR: Cache export is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.  
on switching to driver: docker-container , it again fails. check description above

### YAML workflow

```
name: build-scan-publish-container

on:
  workflow_call:
    inputs:
      testProject:
        required: false
        type: string
      acrLoginServer:
        required: true
        type: string
      dockerFilePath:
        required: true
        type: string
      image:
        required: true
        type: string
      buildId:
        required: true
        type: string
      dotNetVersion:
        required: false
        type: string
        default: "6.0.x"
      enable_docker_cache:
        required: false
        type: boolean
        default: false
    secrets:
      GH_PACKAGES_PAT:
        required: true
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true

jobs:
  build-scan-publish-container:
    name: Build, scan and push container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotNetVersion }}
          source-url: https://nuget.pkg.github.com/secuis/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GH_PACKAGES_PAT}}
      - name: Dotnet Test
        if: inputs.testProject
        run: dotnet test ${{ inputs.testProject }} --configuration Release --collect "XPlat Code Coverage"
      - name: Docker Setup Buildx
        id: buildx
        if: ${{ inputs.enable_docker_cache }}
        uses:  docker/setup-buildx-action@v3
        with: 
          driver: docker-container
          driver-opts: image=moby/buildkit:master,network=host

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v2
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          login-server: ${{ inputs.acrLoginServer }}

      - name: Build and push Docker images
        if: ${{ !inputs.enable_docker_cache }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerFilePath }}
          build-args: PAT=${{ secrets.GH_PACKAGES_PAT }}
          push: true
          tags: "${{ inputs.image }}:${{ inputs.buildId }}"

      - name: Build and push Docker images with cache
        if: ${{ inputs.enable_docker_cache }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerFilePath }}
          build-args: PAT=${{ secrets.GH_PACKAGES_PAT }}
          push: true
          tags: "${{ inputs.image }}:${{ inputs.buildId }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy Container image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ inputs.image }}:${{ inputs.buildId }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          scanners: "vuln,secret,config"
```
