### ISSUE TITLE
Artifact Name for Dockerbuild causes issues when download all artifacts for a workflow run

### ISSUE THREAD

**Issue by rplankenhorn** [docker/build-push-action#1255]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

See https://github.com/docker/actions-toolkit/issues/490

### Expected behaviour

Artifacts uploaded as part of the workflow run should use a name that doesn't cause issues when trying to download all artifacts.

### Actual behaviour

Artifacts fail to download and the workflow fails.

### YAML workflow

```yaml
test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true
```

### Workflow logs

```
(node:14488) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Artifact download completed successfully.
Artifact download completed successfully.
Artifact download completed successfully.
Artifact download completed successfully.
Artifact download completed successfully.
Artifact download completed successfully.
Artifact download completed successfully.
/Users/runner/work/_actions/actions/download-artifact/v4/dist/index.js:2[47](https://github.com/cvent-internal/falcon/actions/runs/11786964965/job/32832426738#step:9:48)8
            throw new Error(`Unable to download and extract artifact: ${error.message}`);
                  ^

Error: Unable to download and extract artifact: Artifact download failed after 5 retries.
    at /Users/runner/work/_actions/actions/download-artifact/v4/dist/index.js:2478:19
    at Generator.throw (<anonymous>)
    at rejected (/Users/runner/work/_actions/actions/download-artifact/v4/dist/index.js:2320:65)

Node.js v20.13.1
```

### BuildKit logs

```text

```
