### ISSUE TITLE
Data exceeding the limit of 491994 byte

### ISSUE THREAD

**Issue by erez-levi** [docker/build-push-action#1256]
Hi,

Starting to encounter this issue when running the action:

`Error: buildx failed with: ERROR: failed to solve: Internal: rpc error: code = Internal desc = received 4294967293-bytes data exceeding the limit 491994 bytes
`

It started after I added the **load: true** parameter to my action but I didn't manage to reproduce it to know if that is indeed what triggered it, when it fails a rerun is always successful afterwards which isn't expected.

The configuration:
```
- name: Build image
    uses: docker/build-push-action@v6
    with:
      push: ${{ inputs.push_image }} # true by default
      context: ./${{ inputs.image_path }}
      load: ${{ inputs.load }} # true by default
      provenance: false
      tags: |
        ${{ inputs.docker_repo }}/${{ env.NAME }}:rc-${{ env.TAG }}
      build-args: |
        GIT_BRANCH=${{ inputs.branch }}
        GIT_REPO=${{ github.repository }}
        GIT_TAG=${{ env.TAG }}
        ${{ inputs.args }}
      target: ${{ inputs.target }}
      file: ./${{ inputs.image_path }}/${{ inputs.dockerfile_name }}
      cache-from: ${{ env.CACHE_FROM }}
      cache-to: ${{ env.CACHE_TO }}
```
