### ISSUE TITLE
Working with Github package registry

### ISSUE THREAD

**Issue by kyler-hyuna** [docker/build-push-action#127]
Hey so i'm currently stuck between v1 no longer working and v2 not working either.

I use the Github container registry in a private repo.

In v1 i used:

```yaml
- uses: docker/build-push-action@v1
  with:
    username: ${{ github.actor }}
    password: ${{ github.token }}
    registry: docker.pkg.github.com
    repository: <org-name>/<repo-name>/<app-name>
    tag_with_ref: true
```

This worked great. However this is failing recently. I suspect a major update to docker happened cause I cannot even pull these images locally since it fails with the error:

```md
Error response from daemon: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''
```

In v2:
I'm using the setup from the readme:

```yml
- run: echo ::set-env name=IMAGE_TAG::${GITHUB_REF:10}

- name: Set up QEMU
  uses: docker/setup-qemu-action@v1
  with:
    platforms: all

- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v1

- name: Cache Docker layers
  uses: actions/cache@v2
  with:
    path: /tmp/.buildx-cache
    key: ${{ runner.os }}-buildx-${{ github.sha }}
    restore-keys: |
      ${{ runner.os }}-buildx-

- name: Login to Registry
  uses: docker/login-action@v1
  with:
    registry: docker.pkg.github.com
    username: ${{ github.actor }}
    password: ${{ github.token }}

- uses: docker/build-push-action@v2
  with:
    push: true
    tags: <org-name>/<repo-name>/<app-name>:${{ env.IMAGE_TAG }}
    secrets: |
      GIT_AUTH_TOKEN=${{ github.token }}
```

This fails with:

```
failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed
```

Is there anything i am missing here?

**Comment by crazy-max** [comment]
@kyler-hyuna Do you have a link to your repo? Also `docker.pkg.github.com` is deprecated and will sunset early next year. I suggest to [migrate to GitHub Container Registry](https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images) instead.

**Comment by kyler-hyuna** [comment]
@crazy-max I tried github container registry as well but it failed. Build-x returns

```
failed to solve: rpc error: code = Unknown desc = unexpected response: 401 Unauthorized
```

But v2 worked perfectly with aws ecr, so i suspect it's some mismatch between github's repositories and buildx

**Comment by crazy-max** [comment]
@hiddeco Someone from GitHub told me they had an issue with the new cross repo mounting and should have been fixed about an hour ago.

**Comment by crazy-max** [comment]
@kyler-hyuna Do you have a link to your repo? Thanks.

**Comment by nathane** [comment]
@kyler-hyuna your issue looks like an authentication `401 Unauthorized` and maybe `tags`.

If you're planning on migrating to GitHub Container Registry,

1. **Create a new personal access token** (PAT) with the appropriate scopes for the tasks you want to accomplish. If your organization requires SSO, you must enable SSO for your new token.

- Select the `read:packages` scope to download container images and read their metadata.
- Select the `write:packages` scope to download and upload container images and read and write their metadata.
- Select the `delete:packages` scope to delete container images.

2. In your GitHub Actions workflow files, update the package URL from `https://docker.pkg.github.com` to `ghcr.io`.

3. Add your new container registry authentication personal access token (PAT) as a GitHub Actions secret. **GitHub Container Registry does not support using `GITHUB_TOKEN` for your PAT so you must use a different custom variable, such as `CR_PAT`**. For more information, see "[Creating and storing encrypted secrets.](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)"

---

**`Updated build.yml`**
```yaml
- run: echo ::set-env name=IMAGE_TAG::${GITHUB_REF:10}

- name: Set up QEMU
  uses: docker/setup-qemu-action@v1
  with:
    platforms: all

- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v1

- name: Login to Registry
  uses: docker/login-action@v1
  with:
    # registry: docker.pkg.github.com
    registry: ghcr.io
    username: ${{ github.repository_owner }}
    password: ${{ secrets.CR_PAT }}

- name: Cache Docker layers
  uses: actions/cache@v2
  with:
    path: /tmp/.buildx-cache
    key: ${{ runner.os }}-buildx-${{ github.sha }}
    restore-keys: ${{ runner.os }}-buildx-

- uses: docker/build-push-action@v2
  with:
    push: true
    # tags: <org-name>/<repo-name>/<app-name>:${{ env.IMAGE_TAG }}
    tags: ghcr.io/${{ github.repository_owner }}/<image-name>:${{ env.IMAGE_TAG }}
```

I hope you find this helpful. ✌🏽 @crazy-max @hiddeco @kyler-hyuna
