### ISSUE TITLE
Action with Matrix Strategy Behavior Bug

### ISSUE THREAD

**Issue by Mon-ius** [docker/build-push-action#1271]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

We would like to accelerate the build process when leverage github matrix strategy to build in parallel. For example,

```sh
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/s390x, linux/ppc64le, linux/riscv64, linux/arm]
        include:
          - platform: linux/amd64
            tag_suffix: amd64
          - platform: linux/arm64
            tag_suffix: arm64
          - platform: linux/s390x
            tag_suffix: s390x
          - platform: linux/riscv64
            tag_suffix: riscv64
          - platform: linux/ppc64le
            tag_suffix: ppc64le
          - platform: linux/arm
            tag_suffix: arm
      -
        name: Build and push file
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
```

### Expected behaviour

It should act the same as,

```sh
      -
        name: Build and push file
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64, linux/s390x, linux/riscv64, linux/ppc64le, linux/arm
```

### Actual behaviour

However, the final build result will keep only the last push, instead of keep them all if they are different architectures. In practice, the `linux/arm` is slowest, so when the workflow finished, only  `linux/arm` left in the `https://hub.docker.com/r/xxx/xxx/tags`.

### YAML workflow

```yaml
name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 */6 * *'
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build.yml"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/s390x, linux/riscv64, linux/arm]
        include:
          - platform: linux/amd64
            tag_suffix: amd64
          - platform: linux/arm64
            tag_suffix: arm64
          - platform: linux/s390x
            tag_suffix: s390x
          - platform: linux/riscv64
            tag_suffix: riscv64
          - platform: linux/arm
            tag_suffix: arm
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push file for ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          tags: xxxx/xx
```

### BuildKit logs

```text

```
