### ISSUE TITLE
It should be possible to skip docker build

### ISSUE THREAD

**Issue by sbp-bvanb** [docker/build-push-action#1278]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

In one of my flows I use this plugin twice. In the first call it should build a docker image and not push, then some test will be applied. Once succeeded, the second call should be done, but then the docker build should be skipped to prevent that it is built for the second time and it should be pushed.

### Expected behaviour

That the docker build can be skipped.

### Actual behaviour

build cannot be skipped

### YAML workflow

```yaml
- name: Build an image from a dockerfile
      uses: docker/build-push-action@v6.9.0
      with:
        build-args: APPLICATION=${{ inputs.build-args }}
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}


    - name: Build an image from a dockerfile
      uses: docker/build-push-action@v6.9.0
      with:
        build: false
        build-args: APPLICATION=${{ inputs.build-args }}
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
```

### BuildKit logs

```text

```
