### ISSUE TITLE
Merge Docker manifests from different runners

### ISSUE THREAD

**Issue by diehard2** [docker/build-push-action#1287]
### Description

I've followed the steps here - https://docs.docker.com/build/ci/github-actions/multi-platform/ 
but I've been unable to get it to work for a custom registry. Its also extremely difficult to both understand and debug

adding an option in this action such as 

'merge-manifests' that replaces all of that code would make this far simpler. With more runners allowing for ARM builds, this would let people avoid QEMU emulation and parallelize their build configurations far more easily

**Comment by crazy-max** [comment]
> I've followed the steps here - https://docs.docker.com/build/ci/github-actions/multi-platform/
but I've been unable to get it to work for a custom registry.

Can you create a bug report with workflow and logs so we can take a look?

> Its also extremely difficult to both understand and debug

Yes this has been raised in https://github.com/docker/build-push-action/issues/671 as well. We also want to ease distributed builds by using subactions for both build-push-action and bake-action.

> 'merge-manifests' that replaces all of that code would make this far simpler.

Can you explain how this `merge-manifests` input would work?

> this would let people avoid QEMU emulation

This will not avoid QEMU on GitHub hosted runners, it will just build on a dedicated runner.

**Comment by junghans** [comment]
I ran into a similar issue now that the amd64 linux runners (` ubuntu-24.04-arm`) are online. Previously arm64 image were out of the question as qemu was too slow and MacOS M1 runner cannot build docker containers.

Using `Noelware/docker-manifest-action` seems to work.
<details>
<summary>workflow.yml</summary>

```yml
jobs:
  build:
    strategy:
      matrix:
        config:
          - {arch: 'arm64'}
          - {arch: 'amd64'}
    runs-on: ${{ matrix.config.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code    
        uses: actions/checkout@v4
      - name: Build and Push Docker images for all Container Registries
        uses: docker/build-push-action@v6
        with:
          tags: |
            ghcr.io/${{ github.repository }}/build:latest-${{matrix.config.arch}}
          file: Dockerfile 
          push: true
  merge-docker-manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
        with:
          inputs: ghcr.io/${{ github.repository }}/build:latest
          images: ghcr.io/${{ github.repository }}/build:latest-amd64,ghcr.io/${{ github.repository }}/build:latest-arm64           
        push: true
```
</details>
