### ISSUE TITLE
build-and-push sometimes failing with 403 Forbidden when pushing to docker hub

### ISSUE THREAD

**Issue by cdrini** [docker/build-push-action#1291]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem
    - I saw some related issues, but none seemed to have this issue sporadically.

### Description

The build and push step sometimes fails, reporting a "403 Forbidden" error when trying to do the push.

### Expected behaviour

It pushes normally.

### Actual behaviour

It fails.

### Repository URL

https://github.com/internetarchive/openlibrary

### Workflow run URL

https://github.com/internetarchive/openlibrary/actions/workflows/olbase.yaml

### YAML workflow

```yaml
name: olbase

on:
  schedule:
    - cron: '00 16 * * 2'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # If on master, use the latest tag, otherwise use the branch name
      - name: Master Build and push
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/master'
        with:
          context: "."
          file: "./docker/Dockerfile.olbase"
          tags: openlibrary/olbase:latest
          push: true

      # If on another branch, use the branch name -- just the branch name, not the full ref
      - name: Test Branch Build and push
        uses: docker/build-push-action@v6
        if: github.ref != 'refs/heads/master'
        with:
          context: "."
          file: "./docker/Dockerfile.olbase"
          tags: openlibrary/olbase:${{ github.ref_name }}
          push: true
```

### Workflow logs

```
...
#28 [auth] openlibrary/olbase:pull,push token for registry-1.docker.io
#28 DONE 0.0s

#27 exporting to image
#27 exporting manifest sha256:f2b91bbbee710e784de0b4d96b2165d9c97b1c77737599d211d4f3605a5524a2 done
#27 exporting config sha256:626bc6d34ed3db6a194cc6614d807014d6c90ee69c18456b895755741028ec32 done
#27 exporting attestation manifest sha256:4b364e385077bd1069ffe5f73880d82fa469bbfef2e8a911b6e790b320295144 done
#27 exporting manifest list sha256:1268929ca3b79418126a4ea585ee32b5ee0c6d14bb1517b723e19eff0ff58383 done
#27 pushing layers
#27 pushing layers 1.4s done
```

`#27 ERROR: failed to push openlibrary/olbase:fix-docker-hub: unexpected status from HEAD request to https://docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com/registry-v2/docker/registry/v2/blobs/sha256/11/1103112ebfc46e01c0f35f3586e5a39c6a9ffa32c1a362d4d5f20e3783c6fdd7/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=***&X-Amz-Date=20250102T225820Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=***: 403 Forbidden`

### BuildKit logs

```text

```

### Additional info

Not sure what's happening. The key is working ; it worked twice in the past few days, and failed like 10 times with this 403 Forbidden error. I'm wondering if maybe there's some caching issue, perhaps caching of some sort of temporary auth key? Or something with trying to fetch info about a tag? Or maybe the push needs to be done with a retry? The fact that `cloudflare` is mentioned also makes me wonder if it's a caching issue somewhere.

I checked the permissions of the secret and everything looks correct.

I found it seems to work more reliably if pushing to a new branch/docker tag ? Which also suggests potentially some issue with cached tag access?
