### ISSUE TITLE
6.11: build breaks

### ISSUE THREAD

**Issue by ro0NL** [docker/build-push-action#1297]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

patching v6.10.0 -> v6.11.0 breaks our docker build

### Expected behaviour

succesfull docker build

### Actual behaviour

```
Dockerfile:6
--------------------
   4 |     FROM php:8.3.15-fpm
   5 |     
   6 | >>> RUN ln -sr /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
   7 |     
   8 |     COPY --from=php_ext_installer /usr/bin/install-php-extensions /usr/bin/
--------------------
ERROR: failed to solve: failed to compute cache key: failed to copy: httpReadSeeker: failed open: unexpected status code 
```

### Workflow run URL

https://github.com/etrias-nl/php/actions/runs/12674967058/job/35324893850?pr=185

### YAML workflow

```yaml
steps:
            -
                uses: actions/checkout@v4.2.2
            -
                uses: docker/setup-buildx-action@v3.8.0
            -
                id: build
                uses: docker/build-push-action@v6.11.0
                with:
                    context: .
                    load: true
                    # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
```

### BuildKit logs

```text

```
