### ISSUE TITLE
arm64 multiarch BuildKit compilation randomly segfaults

### ISSUE THREAD

**Issue by FacuM** [docker/build-push-action#1309]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Compilling my multiarch project started to randomly segfault on the action's QEMU binary while processing the Dockerfile steps.

As this is a public project, you can actually just [take a look at the job output](https://github.com/wprint3d/wprint3d/actions/runs/12978569098/job/36193269962), but may also check the build log attached below. If you were to retry that job, it would fail on another random spot.

I don't know for how long this has been a thing since I haven't touched the image for about a month.

### Expected behaviour

Getting the resulting image and publishing it to Docker Hub.

### Actual behaviour

Random crashes and segfaults during image compilation for the target system, **amd64** looks to be alright, but **arm64** (which runs on top of QEMU) fails. I've already tried upgrading my dependencies, including both **docker/setup-buildx-action** and **docker/build-push-action**.

### Repository URL

https://github.com/wprint3d/wprint3d

### Workflow run URL

https://github.com/wprint3d/wprint3d/blob/alpha/.github/workflows/docker-image.yml

### YAML workflow

```yaml
name: Docker Image CI

on:
  push:
    branches: [ "alpha" ]
  pull_request:
    branches: [ "alpha" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wprint3d:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

### Workflow logs

[logs_33538460101.zip](https://github.com/user-attachments/files/18551974/logs_33538460101.zip)

### BuildKit logs

```text
BuildKit logs are contained as part of the attached ZIP file and the link to the job.
```
