### ISSUE TITLE
Multi arch build / GHA cache

### ISSUE THREAD

**Issue by ro0NL** [docker/build-push-action#1311]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

We're building multi arch Dockerfile (AMD/ARM)

Using a matrix of runners we noticed the default runner (`ubuntu-latest`) leverages GHA cache, but our custom runner doesnt.

```
cache-from: type=gha
cache-to: type=gha,mode=max
```

Are we missing something?

![Image](https://github.com/user-attachments/assets/62dcc87d-fa09-46b5-b219-febc67fab297)

### Expected behaviour

Fast build

### Actual behaviour

Slow build

### YAML workflow

```yaml
runs-on: ${{ matrix.runner }}
        steps:
            -
                uses: actions/checkout@v4.2.2
            -
                uses: docker/setup-buildx-action@v3.8.0
            -
                id: build
                uses: docker/build-push-action@v6.13.0
                with:
                    context: .
                    load: true
                    # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
```

### BuildKit logs

```text

```
