### ISSUE TITLE
Issue with signing keys

### ISSUE THREAD

**Issue by roger-mdisrupt** [docker/build-push-action#1313]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Seeing this issue in the last couple of days, is there a recommended fix please ? :

#9 [builder 2/7] RUN corepack enable
#9 DONE 1.5s
#10 [builder 3/7] WORKDIR /usr/src/app
#10 DONE 0.0s
#11 [builder 4/7] COPY package.json pnpm-lock.yaml ./
#11 DONE 0.0s
#12 [builder 5/7] RUN pnpm install
#12 0.258 /usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21535
#12 0.258   if (key == null || signature == null) throw new Error(`Cannot find matching keyid: ${JSON.stringify({ signatures, keys })}`);
#12 0.258                                               ^
#12 0.258 
#12 0.258 Error: Cannot find matching keyid: {"signatures":[{"sig":"MEQCIBfxS9RKPsi46jxBHnsGYQ03mg8um110415vE6KRCzY8AiBvik66sYxJ/NyCovwJSbDuuoaYCxc7EVdFhaaciIXjTw==","keyid":"SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U"}],"keys":[{"expires":null,"keyid":"SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="}]}
#12 0.258     at verifySignature (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21535:47)
#12 0.258     at fetchLatestStableVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21553:5)

### Expected behaviour

Docker should execute sucessfuly

### Actual behaviour

Fails to install corepack

### YAML workflow

```yaml
- uses: docker/build-push-action@v6
        with:
          push: true
          context: my-services
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
```

### BuildKit logs

```text

```
