### ISSUE TITLE
segfault on alpine/arm64

### ISSUE THREAD

**Issue by chipitsine** [docker/build-push-action#1319]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

I see a lot of "build on alpine crashed inside qemu", for example https://gitlab.com/qemu-project/qemu/-/issues/1953 looks very similar to what I see. 

the idea "make sure both qemu and alpine use PIE" is not clear for me, I setup qemu using GHA.

do you know maybe some best practices of using alpine/arm64  together `docker/build-push-action` ?

### Expected behaviour

no segfault

### Actual behaviour

segfault

### Repository URL

https://github.com/chipitsine/SoftEtherVPN

### Workflow run URL

https://github.com/chipitsine/SoftEtherVPN/actions/runs/13229185394/job/36923962614

### YAML workflow

```yaml
name: docker-vpnserver

on:
  push:
    branches: 
      - 'master'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        variant: [
          { name: amd64, platform: "linux/amd64", repo: "chipitsine/vpnserver" },
          { name: arm64, platform: "linux/arm64", repo: "chipitsine/vpnserver-arm64" }
        ]
    name: vpnserver/${{ matrix.variant.name }}
    runs-on: ubuntu-latest
    #if: ${{ github.repository_owner == 'SoftEtherVPN' }}
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.variant.repo }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          target: vpnserver
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ matrix.variant.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### Workflow logs

#10 65.49 [  2%] Building C object src/Mayaqua/3rdparty/liboqs/src/common/sha3/xkcp_low/CMakeFiles/xkcp_low_keccakp_1600times4_serial.dir/KeccakP-1600times4/serial/KeccakP-1600-times4-on1.c.o
#10 65.80 [  2%] Building C object src/Mayaqua/3rdparty/liboqs/src/sig/cross/CMakeFiles/cross_rsdpg_256_small_clean.dir/upcross_cross-rsdpg-256-small_clean/merkle.c.o
#10 66.03 cc: internal compiler error: Segmentation fault signal terminated program cc1
#10 66.04 Please submit a full bug report, with preprocessed source (by using -freport-bug).
#10 66.04 See <https://gitlab.alpinelinux.org/alpine/aports/-/issues> for instructions.
#10 66.04 make[2]: *** [src/Mayaqua/3rdparty/liboqs/src/sig/cross/CMakeFiles/cross_rsdpg_256_small_clean.dir/build.make:121: src/Mayaqua/3rdparty/liboqs/src/sig/cross/CMakeFiles/cross_rsdpg_256_small_clean.dir/upcross_cross-rsdpg-256-small_clean/merkle.c.o] Error 4
#10 66.04 make[1]: *** [CMakeFiles/Makefile2:3805: src/Mayaqua/3rdparty/liboqs/src/sig/cross/CMakeFiles/cross_rsdpg_256_small_clean.dir/all] Error 2
#10 66.04 make[1]: *** Waiting for unfinished jobs....

### BuildKit logs

```text

```
