### ISSUE TITLE
Complicated Action Structure - Request Advice

### ISSUE THREAD

**Issue by tomeichlersmith** [docker/build-push-action#132]
I am a developer for physics simulation software and we are using docker containers to package all of our dependencies together into a container. The obvious postivie of this is that it is much easier for our users and developers to use/develop our software, but the downside is that the image itself is rather large (~1.5GB compressed) and takes a long time to build (~4hrs). The main reason I am asking for some help is because of the long build time: I can't effectively develop an action that does what I want when I have to wait 4 hours to see if it works.

## Basic Outline
- Download image from DockerHub with the same tag to see if we can skip some of the earlier layers that take the longest time to build
- Re-build the image with the changes and push to a local registry (*not* DockerHub because we want to test it first)
- Run some tests using the software we develop inside of this container to make sure we don't break anything
- Assuming all the tests passed, push the image to DockerHub (without having to rebuild because that would take another 4 hours)

## Current Workflow
This is a piece of the file that I use for to build the image using a GitHub action. The entire docker build context (including the action file below) is https://github.com/LDMX-Software/docker. 

#### Flaws
- When I re-run the workflow twice in a row, it restarts the build entirely. *Desired Behavior*: It would be "smart" enough to recognize that the build context hasn't changed so no new layers need to be built. Even better would be if I only change the last few lines of the Dockerfile, it would know that it can skip the first few big layers because they haven't changed.
- It builds twice. Once to the local registry and once at the end. *Desired Behavior*: The second call to the build-push action is really only to push from the local registry to DockerHub.
```
name: Build

# only build if push changes to files involved in the build
on:
  push:
    branches: [ main ]
    paths: [ 'ldmx.sh' , 'Dockerfile' , 'install-scripts/**' , '**base.yml' ]
  pull_request:
    branches: [ main ]

# the jobs are the different container tags that we want built
jobs:
  # basic, defaults development container
  #     this is the container that pretty much everyone in ldmx-sw should use
  basic:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - 
      name: Get Build Context
      uses: actions/checkout@v2
    -
      name: Determine Image Tag
      id: generate_tag
      run: |
          _tag=latest
          if [ "${{ github.event_name }}" == "pull_request" ]
          then
              _tag=pr-${{ github.event.number }}
          fi
          _full=ldmx/dev:${_tag}
          echo ::set-output name=tag::${_full}
    -
      name: Build the Image to Local Cache
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        cache-from: ${{ steps.generate_tag.outputs.tag }}
        tags: localhost:5000/${{ steps.generate_tag.outputs.tag }}
    -
      name: Pull down ldmx-sw for testing
      uses: actions/checkout@v2
      with:
        repository: LDMX-Software/ldmx-sw
        submodules: recursive
    - 
      name: Test the Build Image
      run: |
          export LDMX_BASE=$(pwd)
          _image=localhost:5000/${{ steps.generate_tag.outputs.tag }}
          mkdir ldmx-sw/build
          docker run -i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE $_image ldmx-sw/build cmake -DBUILD_TESTS=ON ..
          docker run -i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE $_image ldmx-sw/build make install
          docker run -i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE $_image . run_test
          for c in `ls ldmx-sw/*/test/*.py`; do if ! docker run -i -e LDMX_BASE -v $(pwd):$(pwd) $_image . fire $c; then exit 1; fi; done
          docker run -i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE $_image . python test.py
          docker run -i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE $_image . python3 test.py
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Push Build to DockerHub
      uses: docker/build-push-action@v2
      with:
        push: true
        cache-from: localhost:5000/${{ steps.generate_tag.outputs.tag }}
        tags: ${{ steps.generate_tag.outputs.tag }}
```

**Comment by shrink** [comment]
> I can't effectively develop an action that does what I want when I have to wait 4 hours to see if it works.

A good way to reduce this time-to-test is to create an image that you're just using for testing. You can create an image that has the required characteristics, e.g: cachable layers, uncacheable layers. For example:

```
FROM alpine

RUN touch example.txt
RUN echo "Hello, World!" > example.txt
ADD https://worldtimeapi.org/api/ip.txt datetime.txt
```

The first two layers of this image can be cached, the final line will never be cached. After the image is built you can inspect for the presence of the files (`example.txt` and `datetime.txt`) to verify the expected behaviour.

Specific to the workflow you're trying to create, you can use `actions/cache` to cache the layers instead of a local registry. Something like this (untested):

```yaml
name: Build

on:
  push:
    branches: [ main ]
    paths: [ 'ldmx.sh' , 'Dockerfile' , 'install-scripts/**' , '**base.yml' ]
  pull_request:
    branches: [ main ]

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Build Context
      uses: actions/checkout@v2
    - name: Pull down ldmx-sw for testing
      uses: actions/checkout@v2
      with:
        repository: LDMX-Software/ldmx-sw
        submodules: recursive

    - name: Determine Image Tag
      id: generate_tag
      run: |
          _tag=latest
          if [ "${{ github.event_name }}" == "pull_request" ]
          then
              _tag=pr-${{ github.event.number }}
          fi
          _full=ldmx/dev:${_tag}
          echo ::set-output name=tag::${_full}

    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        push: false
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: ${{ steps.generate_tag.outputs.tag }}

    - name: Test the Build Image
      run: |
          export LDMX_BASE=$(pwd)
          _image=${{ steps.generate_tag.outputs.tag }}
          mkdir ldmx-sw/build
          docker run -i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE $_image ldmx-sw/build cmake -DBUILD_TESTS=ON ..
          docker run -i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE $_image ldmx-sw/build make install
          docker run -i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE $_image . run_test
          for c in `ls ldmx-sw/*/test/*.py`; do if ! docker run -i -e LDMX_BASE -v $(pwd):$(pwd) $_image . fire $c; then exit 1; fi; done
          docker run -i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE $_image . python test.py
          docker run -i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE $_image . python3 test.py

    - name: Push image to Docker Hub
      run: docker push ${{ steps.generate_tag.outputs.tag }}
```

Specific notes:

- `load: true` means the newly built image will be available to the `docker` instance so we do not need a local registry and we can then do a `docker push ...`
