### ISSUE TITLE
Action produces large number of untagged images

### ISSUE THREAD

**Issue by Time0o** [docker/build-push-action#1323]
I have tried all measures I can think of to prevent this but in some cases (it is not clear to me which those are) this action produces a number of untagged images that from their history seem to be more or less identical to existing ones. I have this setup:

```yaml
    - name: Extract image metadata                                                  
      id: metadata                                                                  
      # 369eb59 = v5.6.1                                                            
      uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96         
      with:                                                                         
        images: ghcr.io/my_org_my_image                               
        tags: |                                                                     
          type=raw,pattern={{version}},value=${{ steps.version.outputs.version }}

    - name: Build and push image
      # 4f58ea7 = v6.9.0
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75       
      with:
        context: image
        file: image/Dockerfile    
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        push: true
        outputs: type=image,name=ghcr.io/my_org/my_image,push=true 
        platforms: linux/amd64
        provenance: false
```

Here is the result for one of my packages:

![Image](https://github.com/user-attachments/assets/78fd63f7-4167-4e28-b6dc-d8a84b17f7f4)

I'm hesitant to file this as a bug because maybe there's a sensible explanation? But without multi arch build or provenance this just can't be right, can it?
