### ISSUE TITLE
GitHub Actions Cache - Docker Build

### ISSUE THREAD

**Issue by ajithshah** [docker/build-push-action#1345]
# This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP

ERROR: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset

ERROR: failed to solve: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset
Reference
Check build summary support

```
      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ inputs.docker_image_platforms }}
          build-args: |
            IMAGE_TAG=${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.TOKEN_GITHUB }}
```

**Comment by andrewhharmon** [comment]
is [this](https://github.com/docker/build-push-action/blob/ca052bb54ab0790a636c9b5f226502c73d547a25/yarn.lock#L39C16-L39C30) indicating version `3.2.4` of `actions/cache` is being used and [this](https://github.com/actions/cache/discussions/1510) indicates that it's deprecated?

**Comment by newman-dani** [comment]
@patbernard I do use ```471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0``` and still getting it.

**Comment by bradley-yoo-anrok** [comment]
I don't think 4.0.2 is fine. if you look at the original deprecation [notice](https://github.com/actions/cache/discussions/1510), 4.1.2 is deprecated.

**Comment by andrewhharmon** [comment]
yes we tried v6 and still got it as well

**Comment by mmckane** [comment]
I also tried V6 and am seeing this happen

**Comment by andrewhharmon** [comment]
I think [this](https://github.com/actions/toolkit/tree/main/packages/cache) is the package being used here. it says v4.0.0 should be good.

**Comment by mmckane** [comment]
if it helps I am using docker/setup-buildx-action@v3 as well

**Comment by trautonen** [comment]
I'm using the latest docker/setup-buildx-action@v3 which `yarn.lock` currently points to 
```
"@actions/cache@npm:^4.0.2":
  version: 4.0.2
  resolution: "@actions/cache@npm:4.0.2"
```
and the builds are failing

**Comment by jpugliesi** [comment]
Buildkit v0.20+ fixes this: https://github.com/moby/buildkit/issues/5683

You can upgrade by updating the `docker/setup-buildx-action` that's commonly run before this `build-push-action`:

```
- uses: docker/setup-buildx-action@v3
  with:
    version: v0.20.0
```

**Comment by johnfountainsomos** [comment]
> Buildkit v0.20+ fixes this: [moby/buildkit#5683](https://github.com/moby/buildkit/issues/5683)
> 
> You can upgrade by updating the `docker/setup-buildx-action` that's commonly run before this `build-push-action`:
> 
> ```
> - uses: docker/setup-buildx-action@v3
>   with:
>     version: v0.20.0
> ```

this did not work for us. still the same failure

**Comment by jpugliesi** [comment]
> > Buildkit v0.20+ fixes this: [moby/buildkit#5683](https://github.com/moby/buildkit/issues/5683)
> > You can upgrade by updating the `docker/setup-buildx-action` that's commonly run before this `build-push-action`:
> > ```
> > - uses: docker/setup-buildx-action@v3
> >   with:
> >     version: v0.20.0
> > ```
> 
> this did not work for us. still the same failure

Indeed - v0.20 _upgrades to cache API v2, while cache <v4.0 is being deprecated - updated my comment

**Comment by patbernard** [comment]
This actions has a dependency on docker/actions-toolkit, and that latest release is locked to an outdated version here: https://github.com/docker/actions-toolkit/blob/main/package.json#L49

So to resolve this we need docker/actions-toolkit to be updated, then update docker/build-push-action to point to that latest version of docker/actions-toolkit.

**Comment by patbernard** [comment]
It looks like what we need is docker/actions-toolkit to cut a new release (the latest release is using 4.0.2). See: https://github.com/docker/actions-toolkit/issues/643

Then `docker/build-push-action` can be updated to use the latest version of `docker/actions-toolkit` and we'll be on a supported version of `actions/cache`.

**Comment by andrewhharmon** [comment]
perhaps not as `4.0.0` and higher  of the node library should support this.

**Comment by patbernard** [comment]
I think that did the trick. I ran the changes on a fork, and it worked for me: https://github.com/patbernard/build-push-action/tree/patbernard/update-cache-action-version

E.g.

```
    - name: Build and push image
      uses: patbernard/build-push-action@patbernard/update-cache-action-version
```

**Comment by bradley-yoo-anrok** [comment]
Are you sure it didn't work because the brownout just ended?

**Comment by patbernard** [comment]
> Are you sure it worked because the brownout just ended?

I'm not sure now. 😢  I'll have to test again on April 8th if there's no other traction between now any then.

**Comment by crazy-max** [comment]
I'm creating a release with latest v0.58.0 of actions-toolkit: https://github.com/docker/actions-toolkit/releases/tag/v0.58.0

**Comment by crazy-max** [comment]
> Edit: Looking at this https://npmdiff.dev/%40actions%2Fcache/4.0.2/4.0.3/, I really doubt the 4.0.3 version fixes this. Feeling more confident it only worked because the brownout concluded.

> I don't think 4.0.2 is fine. if you look at the original deprecation [notice](https://github.com/actions/cache/discussions/1510), 4.1.2 is deprecated.

[`actions/cache` action](https://github.com/actions/cache) should not be confused with the [`@actions/cache` module](https://www.npmjs.com/package/@actions/cache). We are not using this library for `type=gha` cache backend but https://github.com/tonistiigi/go-actions-cache which supports the new cache service v2.

If you have this issue you're likely using BuildKit < 0.20.0 or Buildx < v0.21.0 that doesn't support cache service v2. This can happen on self-hosted runners so to make sure you're using the latest version of Buildx, either update your self-hosted runner or set `version: latest` in `setup-buildx-action`:

```yaml
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
```

Also it would good if someone can give a link to the workflow run so we can take a look or logs of the workflow.

**Comment by aleksey-perplexity** [comment]
I am using v0.20.2 of the buildkit, cached in our ECR:

```
    - name: Set up Docker Buildx # required for build cache
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: image=[redacted].dkr.ecr.us-east-1.amazonaws.com/buildkit:v0.20.2
        install: true
```

This last step in my workflow is failing:

```
    - name: Build locally
      uses: docker/build-push-action@v6
      ...
```

Am I using the wrong version of something?

**Comment by OldCrowEW** [comment]
hello, im not sure this is fixed yet. we just experienced a brownout from GitHub. 

> Error: buildx failed with: ERROR: failed to solve: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset

```
name: "Docker deployment"
description: "Docker Build, Tag and Push to AWS"

runs:
  using: "composite"
  steps: 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::REDACTED:role/REDACTED
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/arm64
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/REDACTED:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/REDACTED:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        target: REDACTED
        build-args: |
          GIT_COMMIT=${{ github.sha }}
        labels: |
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/REDACTED/REDACTED
```
