### ISSUE TITLE
Why does the Linux/arm64 build take so long?

### ISSUE THREAD

**Issue by eryajf** [docker/build-push-action#1348]
I use this plugin to build the linux/arm64 and linux/amd64 images for my Go language project. With the same configuration, why does the linux/amd64 build only take a few seconds, while the linux/arm64 build takes nearly twenty minutes?

see: https://github.com/eryajf/k8m/actions/runs/14278285139/job/40024634589

<img width="1046" alt="Image" src="https://github.com/user-attachments/assets/7044b6b1-f997-4c62-9bac-f16aae9ee44e" />

**Comment by AlexsJones** [comment]
Plus one to this

**Comment by crazy-max** [comment]
> https://github.com/eryajf/k8m/actions/runs/14278285139/job/40024634589

From what I see in your workflow: https://github.com/eryajf/k8m/actions/runs/14278285139/workflow#L131

```yaml
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPONAME }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPONAME }}:buildcache,mode=max
        platforms: linux/amd64,linux/arm64
        # 给清单打上多个标签
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPONAME }}:latest
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPONAME }}:${{ steps.date.outputs.today }}
          ${{ env.ALIHUB_URL }}/${{ env.ALIHUB_USERNAME }}/${{ env.IMAGE_REPONAME }}:${{ env.GITHUB_REF_NAME }}
          ${{ env.ALIHUB_URL }}/${{ env.ALIHUB_USERNAME }}/${{ env.IMAGE_REPONAME }}:latest
```

You're building a multi-plaform image. In this case `linux/amd64` builds natively on `ubuntu-latest` but not `linux/arm64` that will build using emulation with QEMU which has performance penalty. (docs related to multi-platform build: https://docs.docker.com/build/building/multi-platform/)

As you're building a Go project it's trivial to do cross-compilation and avoid using emulation: https://docs.docker.com/build/building/multi-platform/#cross-compilation

Here is a complete example to achieve that: https://docs.docker.com/build/building/multi-platform/#cross-compiling-a-go-application
