### ISSUE TITLE
Cannot import .dockerbuild.zip in Docker Desktop v4.42.0

### ISSUE THREAD

**Issue by lukpueh** [docker/build-push-action#1383]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Trying to import build summary (.dockerbuild or .dockerbuild.zip) in Docker Desktop v4.42.0 (for mac) created with build-push-action fails with message:
```
Failed to import build record: {"error":"unrecognized image
format", message": "Internal Server Error"}
```

### Expected behaviour

Import works as described in https://docs.docker.com/build/ci/github-actions/build-summary/ and https://docs.docker.com/desktop/use-desktop/builds/#import-builds

### Actual behaviour

Import fails

### Repository URL

https://github.com/lukpueh/lind-wasm/

### Workflow run URL

https://github.com/lukpueh/lind-wasm/actions/runs/15614173396

### YAML workflow

```yaml
name: End-to-end testing

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build e2e
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          platforms: linux/amd64
```

### Workflow logs

[0_docker.txt](https://github.com/user-attachments/files/20722733/0_docker.txt)

### BuildKit logs

```text

```

### Additional info

Import also fails with a randomly picked build summary from build-push-action CI:

https://github.com/docker/build-push-action/actions/runs/15607595663#summary-43960681791
https://github.com/docker/build-push-action/actions/runs/15607595663/artifacts/3313124564
