### ISSUE TITLE
Feature request: load to artafact

### ISSUE THREAD

**Issue by gianarb** [docker/build-push-action#147]
Hello!

Thank you for your work! I would like to load images I built in a GitHub Action and/or files/binaries inside the image as [GitHub artifact](https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts#about-workflow-artifacts)

Why?

* We build images as part of the CI for every commit, to validate that nothing broke along the way. We also like the idea to have that image pushed somewhere in a way that makes it easy to be used by teammates or contributors. Artifacts sound the best place for that.
* Now that Docker Action has multi-arch support with buildx having the ability to copy a binary from inside the container and publish it as an artifact sounds very appealing. An easy way to do it even more!

Thanks

**Comment by shrink** [comment]
@gianarb I published a GitHub Action to support this workflow recently that you might find suitable for your use-case, [shrink/actions-docker-extract@v1](https://github.com/shrink/actions-docker-extract).

**Comment by crazy-max** [comment]
@gianarb 

> We build images as part of the CI for every commit, to validate that nothing broke along the way. We also like the idea to have that image pushed somewhere in a way that makes it easy to be used by teammates or contributors. Artifacts sound the best place for that.

You can export the image as tarball and upload through [actions/upload-artifact](https://github.com/actions/upload-artifact/) action:

```yaml
name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          tags: docker.io/name/app:latest
          outputs: type=oci,dest=/tmp/image.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: /tmp/image.tar
```
