### ISSUE TITLE
Unable to push image to docker.pkg.github.com

### ISSUE THREAD

**Issue by avgur** [docker/build-push-action#148]
Error occurred while trying to push built image into docker.pkg.github.com

### Behaviour

When using 'push' option with docker.pkg.github.com error occured, in the same time it is still possible to build with 'load' option and then manually push each tag into docker.pkg.github.com

#### Steps to reproduce this issue

1. prepeare any dockerfile
2. use docker/build-push-action@v2 with 'push: true' option and tags prefixed with 'docker.pkg.github.com' f.e. 'tags: docker.pkg.github.com/repo/imagename:latest'
3. run action

#### Expected behaviour
image pushed into repository

#### Actual behaviour

action fails with an error:

failed to solve: rpc error: code = Unknown desc = failed commit on ref "layer-sha256:4766...": invalid content digest in response: invalid checksum digest format

### Configuration

```yml
name: ci

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prep
        run: |
          DOCKER_REGISTRY=docker.pkg.github.com
          DOCKER_IMAGE="${DOCKER_REGISTRY}/${GITHUB_REPOSITORY}/sample"
          DOCKER_TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:1.0.0"
          echo ::set-output name=docker_registry::${DOCKER_REGISTRY}
          echo ::set-output name=docker_tags::${DOCKER_TAGS}     
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to docker registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ steps.prep.outputs.docker_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build final image and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prep.outputs.docker_tags }}
```
