### ISSUE TITLE
Cache does not seem to be used

### ISSUE THREAD

**Issue by rmasclef** [docker/build-push-action#159]
### Behaviour

Hi ! Thank you for your great peace of work here !

It looks like the cache feature is not used during `docker build`.

Or I may have misunderstood something ! 🤷‍♂️ (I've never used buildx yet, only Buildkit but without thinking about the caching part).

Thank you for your help !

#### Expected behaviour

I think Golang and Alpine images should almost always be retrieved by cache

> Regarding the `setup-buildx` action, it would be great to use caching too so that we don't loose around 13s on every action trigger

#### Actual behaviour

At this time it is not

> Cache works well if I relaunch the action without making any changes

### Configuration

```
name: ci
on: [pull_request,release]
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_NAME }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      -
        name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ github.event.repository.name }}:${{ github.head_ref }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
```

here is the Dockerfile:

```
FROM golang:1.15-alpine AS builder
WORKDIR /project
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o backend-ads-api ./cmd/...

FROM alpine:3.12
COPY --from=builder /project/backend-ads-api .
ENTRYPOINT ["/backend-ads-api"]
```

and the .dockerignore if it helps:

```
.git
.gitignore
.dockerignore
.github

.idea

Dockerfile

*test.go
README.md
LICENSE
```

### Logs

[logs_42.zip](https://github.com/docker/build-push-action/files/5324462/logs_42.zip)
