### ISSUE TITLE
Git issues when run "docker buildx build" on "self-hosted" runner

### ISSUE THREAD

**Issue by socheatsok78** [docker/build-push-action#161]
#### Steps to reproduce this issue

1. The repo is private
1. The workflow is running on a self-hosted **ubuntu** server
1. Workflow trigger on **Release** event
1. After the **Login to AmazonECR** finished
1. Then the **Development: Build, Tag and Push Image** or **Production: Build, Tag and Push Image** step started with the following error.

#### Actual behaviour

```
📣 Buildx version: 0.4.2
🏃 Starting build...
/usr/bin/docker buildx build --build-arg NODE_ENV=development --build-arg VUE_APP_VERSION=v1.0.0-beta.3 --tag ***/***:dev-latest --tag ***/***:v1.0.0-beta.3 --iidfile /tmp/docker-build-push-G1Z21e/iidfile --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-build-push-G1Z21e/tmp-1777537-D7uyw3e8Uh8c --file ./Dockerfile --push https://github.com/soramitsukhmer/nbcp-fast-frontend.git#tags/v1.0.0-beta.3
time="2020-10-05T02:01:16Z" level=warning msg="invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: "
docker/setup-buildx-action#1 [internal] load git source https://github.com/soramitsukhmer/nbcp-fast-f...
docker/setup-buildx-action#1 0.104 Initialized empty Git repository in /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/1/fs/
docker/setup-buildx-action#1 0.954 fatal: could not read Username for 'https://github.com': No such device or address
docker/setup-buildx-action#1 ERROR: failed to fetch remote https://github.com/soramitsukhmer/nbcp-fast-frontend.git: exit status 128
------
 > [internal] load git source https://github.com/soramitsukhmer/nbcp-fast-frontend.git#tags/v1.0.0-beta.3:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: failed to fetch remote https://github.com/soramitsukhmer/nbcp-fast-frontend.git: exit status 128
Error: The process '/usr/bin/docker' failed with exit code 1
```

### Configuration

* Repository URL (if public): **private repo**
* Build URL (if public): **private repo**

```yml
name: Release Docker Image
on:
  release:
    types: [published]
jobs:
  build:
    name: Build, Tag and Push Image
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to AmazonECR
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.AWS_ECR_REGISTRY }}
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - # Development --------------------
      name: "Development: Build, Tag and Push Image"
      if: "github.event.release.prerelease"
      id: docker_build_dev
      uses: docker/build-push-action@v2
      env:
        DOCKER_CONTAINER_TAG: dev-latest
      with:
        push: true
        build-args: NODE_ENV=development,VUE_APP_VERSION=${{ github.event.release.tag_name }}
        tags: |
          ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:dev-latest
          ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.event.release.tag_name }}
    - # Production --------------------
      name: "Production: Build, Tag and Push Image"
      if: "!github.event.release.prerelease"
      id: docker_build_prod
      uses: docker/build-push-action@v2
      env:
        DOCKER_CONTAINER_TAG: latest
      with:
        push: true
        build-args: NODE_ENV=production,VUE_APP_VERSION=${{ github.event.release.tag_name }}
        tags: |
          ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
          ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.event.release.tag_name }}
```

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
[logs_1995.zip](https://github.com/docker/setup-buildx-action/files/5324861/logs_1995.zip)
