### ISSUE TITLE
rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile

### ISSUE THREAD

**Issue by brmdbr** [docker/build-push-action#164]
### Troubleshooting

I copied a standard template from the readme but for me it throws an error.

### Behaviour

Error thrown on build and publish step. I've played around with adding or removing the "context: 1" param but they both fail. Maybe I'm missing something. 

#### Expected behaviour

Build and publish to Dockerhub

#### Actual behaviour

failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount973901029/Dockerfile: no such file or directory

![image](https://user-images.githubusercontent.com/2796318/95128056-35bd1500-0759-11eb-9c15-477e63095deb.png)

```yml
name: Build and publish to DockerHub

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: xxxx/app:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

```
Dockerfile
`#BUILD
FROM node:14-buster-slim AS builder

WORKDIR /app

COPY . .

RUN cd client && npm install && npm run build
RUN cd server && npm install && npm run build

#SERVE
FROM node:14-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

WORKDIR /app/server

CMD ["npm", "run", "start:prod"]`
