### ISSUE TITLE
Does not publish to GitHub packages but does publish to DockerHub

### ISSUE THREAD

**Issue by lskatz** [docker/build-push-action#167]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

I ran my github actions to create a container on dockerhub and github, but only the dockerhub image appears.
There is no error given.

#### Steps to reproduce this issue

1.  Use yml file here: https://github.com/lskatz/container-test/blob/2c744d86fbf14e0e8eef797dd57f8fd84bed7c31/.github/workflows/build-and-push-container.yml
    * Uses a combination of the "complete workflow" and the "github workflow"
    * Logs into DockerHub
    * Logs into GitHub
    * Creates `TAGS` for both DockerHub and GitHub 
    * Builds and pushes
2.  Action does not result in error here: https://github.com/lskatz/container-test/runs/1216075563?check_suite_focus=true
3.  DockerHub produces an image here: https://hub.docker.com/layers/lskatz/container-test/sha-2c744d86/images/sha256-828922ab2f186f74e1e811778b0e8ecfd4954e6216f5e12638b2c6598604135e?context=repo
4. GitHub does not produce a package here: https://github.com/lskatz/container-test/packages?package_type=Docker

#### Expected behaviour

Should produce a package at GitHub and DockerHub

#### Actual behaviour

Does not Produce a package at GitHub

### Configuration

* Repository URL (if public): https://github.com/lskatz/container-test
* Build URL (if public): 
   * https://github.com/lskatz/container-test/packages?package_type=Docker
   * https://hub.docker.com/layers/lskatz/container-test

```yml
# https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/guides/publishing-docker-images
name: github-docker
on: 
  push:
    branches:
      - main



env:      
  DOCKER_PASSWORD:   ${{  secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME:   lskatz
  CI_PROJECT_NAME:   container-test
  github_repository: lskatz/container-test
  tag: fake-tag

jobs:
  push_to_registry:
    name: Push Docker image to multiple registries v2
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - name: Prepare env
        id:   prep
        run: |
          DOCKER_IMAGE=${{ env.github_repository }}
          VERSION=${GITHUB_SHA}
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=edge
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          TAGS="$TAGS,ghcr.io/${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
            TAGS="$TAGS,ghcr.io/${DOCKER_IMAGE}:${MINOR},ghcr.io/${DOCKER_IMAGE}:${MAJOR},ghcr.io/${DOCKER_IMAGE}:latest"
          elif [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
            TAGS="$TAGS,ghcr.io/${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          fi          
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lskatz
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

```

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

[logs_42.zip](https://github.com/docker/build-push-action/files/5335361/logs_42.zip)
