### ISSUE TITLE
400 Bad Request when pushing manifest to GCR using v1.0.2

### ISSUE THREAD

**Issue by akalineskou** [docker/build-push-action#168]
#### Steps to reproduce this issue

1. Use docker/setup-buildx-action@v1.0.2 to set up docker buildx
2. Push to GCR

#### Expected behaviour

> Tell us what should happen
It should push correctly to GCR as with v1.0.1

#### Actual behaviour

> Tell us what happens instead
I get this error 

docker/setup-buildx-action#24 pushing manifest for us.gcr.io/REDACTED
docker/setup-buildx-action#24 pushing manifest for us.gcr.io/REDACTED 0.2s done
docker/setup-buildx-action#24 ERROR: failed commit on ref "manifest-sha256:013abc4ac51e93f9aca0650ba16921c3794ca76a69d2aad7a8bb2ff20122b7c0": unexpected status: 400 Bad Request
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = failed commit on ref "manifest-sha256:013abc4ac51e93f9aca0650ba16921c3794ca76a69d2aad7a8bb2ff20122b7c0": unexpected status: 400 Bad Request
Error: The process '/usr/bin/docker' failed with exit code 1

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: Workflow

env:
  GCR_URL: us.gcr.io
  GC_PROJECT_ID: ID_HERE

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GCR_URL }}
          username: _json_key
          password: SECRET_HERE

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ env.GCR_URL }}/${{ env.GC_PROJECT_ID }}/IMAGE_TAG_HERE
```

### Logs
Can't really post the logs since it's for a private repository
