### ISSUE TITLE
anything special about the path: /tmp/.buildx-cache ?

### ISSUE THREAD

**Issue by DiveInto** [docker/build-push-action#175]
I am trying to build docker image with cache, I follow the doc at [caching-dependencies-to-speed-up-workflows](https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action), and find it doesn't work, after several attempts, I find that the problem seems related to the `path` parameter, the doc [caching-dependencies-to-speed-up-workflows](https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action) suggest in order to cache node packages, we should set path to `~/.npm`, but it doesn't work, while if I change path to `/tmp/.buildx-cache`, it works, is there anything special about this magic path?

---

I setup a demo repo to try the Action: https://github.com/DiveInto/hi-ci-cd

for the config that fails to using cache, the action log is [here](https://github.com/DiveInto/hi-ci-cd/runs/1238361498?check_suite_focus=true), you can tell from the step: Build and Push, the cache is not working.

the workflow config is [here](https://github.com/DiveInto/hi-ci-cd/blob/75ed9521e1e84d55a5a8b119e178bef1805cd171/.github/workflows/build-push-img-with-cache.yaml):

```yaml
# the config that cache not working

name: build & push img with cache

on:
  push:
    branches: 
      - master
      - build-with-cache

jobs:
  job-build-with-cache:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        uses: actions/checkout@v2

      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-buildx-dir-${{ hashFiles('frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile-npm
          tags: diveinto/hi-ci-cd:latest
          cache-from: type=local,src=~/.npm
          cache-to: type=local,dest=~/.npm
```

While after change to `/tmp/.buildx-cache`, the cache works. 

- the action log: https://github.com/DiveInto/hi-ci-cd/runs/1238368575?check_suite_focus=true
- the workflow config: https://github.com/DiveInto/hi-ci-cd/blob/183e2e6b94d969aba46f1db5181d2318bdfba942/.github/workflows/build-push-img-with-cache.yaml#L26

```yaml
# the config that works
name: build & push img with cache

on:
  push:
    branches: 
      - master
      - build-with-cache

jobs:
  job-build-with-cache:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        uses: actions/checkout@v2

      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-dir-${{ hashFiles('frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile-npm
          tags: diveinto/hi-ci-cd:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
```
