### ISSUE TITLE
Seems to have failed due to resource issue

### ISSUE THREAD

**Issue by tianhaoz95** [docker/build-push-action#178]
### Troubleshooting

Before sumbitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

The docker build process fails with the following error:

```bash
failed to solve: rpc error: code = Unknown desc = unexpected status: 403 Forbidden
Error: The process '/usr/bin/docker' failed with exit code 1
```

Example run: https://github.com/tianhaoz95/iwfp/runs/1263285548

#### Steps to reproduce this issue

1. Use a `Dockerfile` that combines node 10 and Java 8 and some type of node server: https://github.com/tianhaoz95/iwfp/blob/master/Dockerfile
2. Run it with a workflow pushing to GitHub: https://github.com/tianhaoz95/iwfp/blob/master/.github/workflows/release__server-emulator-image.yml
3. See build failure like this: Example run: https://github.com/tianhaoz95/iwfp/runs/1263285548

#### Expected behaviour

It should build the image.

#### Actual behaviour

It crashed.

### Configuration

* Repository URL (if public): https://github.com/tianhaoz95/iwfp
* Build URL (if public): https://github.com/tianhaoz95/iwfp/runs/1263285548

```yml
name: Release Server Emulator Image
on:
  pull_request:
    branches:
      - master
    paths:
      - "functions/**"
      - "Dockerfile"
      - ".github/workflows/release__*"
  push:
    branches:
      - master
jobs:
  release__server-emulator-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.2"
      - run: npm install
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: get_tag
        id: get_tag
        working-directory: scripts
        env:
          USERNAME: ${{ github.repository_owner }}
        run: |
          source query_image_tag.sh
          echo "::set-output name=image_tag::ghcr.io/$USERNAME/iwfp-server:$USE_TAG_NAME"
      - uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          push: true
          tags: ${{ steps.get_tag.outputs.image_tag }}
      - uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          push: false
          tags: ${{ steps.get_tag.outputs.image_tag }}
```

From https://github.com/docker/buildx/issues/101 this failure seems to be related to insufficient resources?

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
@tianhaoz95 

> `#9 ERROR: unexpected status: 403 Forbidden`

Looks like an issue with GitHub Container Registry. Are you aware of this @clarkbw?

Btw, you can optimize these steps:

```yaml
      - uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          push: true
          tags: ${{ steps.get_tag.outputs.image_tag }}
      - uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          push: false
          tags: ${{ steps.get_tag.outputs.image_tag }}
```

With:

```yaml
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.get_tag.outputs.image_tag }}
```
