### ISSUE TITLE
Not pushing

### ISSUE THREAD

**Issue by Rawnly** [docker/build-push-action#190]
### Behaviour

I know this is probably a configuration issue, but I'd like to get some help if possible.

#### Expected behaviour

> I'd expect to publish. new container tag

#### Actual behaviour

it won't completee]

### Configuration

* Repository URL (if public): [Rawnly/actions-container-test](https://github.com/Rawnly/actions-container-test)
* Build URL (if public): https://github.com/Rawnly/actions-container-test/runs/1282435564

```yml
name: ci
on: push
jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - id: prep
        run: |
          echo ::set-output name=tags::ghcr.io/rawnly/sample:${GITHUB_REF#refs/tags/v}
      - uses: docker/setup-qemu-action@v1.0.1
      - id: buildx
        uses: docker/setup-buildx-action@v1.0.2
      - uses: docker/login-action@v1.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }} # - must be in GitHub Secrets!
      - uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
#           context: .
#           file: ./Dockerfile
          tags: latest 
          push: ${{ github.event_name != 'pull_request' }}
#           platforms: linux/amd64,linux/arm64,linux/386
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
```

### Logs

> Download the [log file of your build](https
[1_ci_page_2.txt](https://github.com/docker/build-push-action/files/5410407/1_ci_page_2.txt)
[1_ci.txt](https://github.com/docker/build-push-action/files/5410408/1_ci.txt)
