### ISSUE TITLE
buildx push to Github Registry failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden

### ISSUE THREAD

**Issue by den-is** [docker/build-push-action#200]
`docker/build-push-action@v2` fails to push to github-registry

**Error output**
```
#17 [stage-1 6/6] COPY --from=build /app/dist/ /www
#17 DONE 0.1s

#18 exporting to image
#18 exporting layers
#18 exporting layers 0.9s done
#18 exporting manifest sha256:b8fe69f6b744d1df193aabf059c9b1a1fe01b64b0eeb609fe79b6fbeb6924cf0 done
#18 exporting config sha256:bc623042f7e4cf526244a41ec5785c9383b66c4042d0dd3ae73d37b1277415d8 done
#18 pushing layers 0.0s done
#18 ERROR: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

This is complete workflow
```yaml
jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparation
      id: prep
      run: |
        TAGS="ghcr.io/${{ github.repository }}:${{ github.sha }}"
        if [[ $GITHUB_REF == ref/head/master ]]; then
          TAGS="$TAGS,ghcr.io/${{ github.repository }}:latest"
        fi
        echo ::set-output name=tags::${TAGS}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Packages registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        push: true
        file: src/Dockerfile
        tags: ${{ steps.prep.outputs.tags }}
```

**Initialization and start-up logs** ...   logs between initialization and error belong to usual successful image build.
```
Run docker/setup-buildx-action@v1
📣 Buildx version: 0.4.2
🔨 Creating a new builder instance...
/usr/bin/docker buildx create --name builder-publish-2 --driver docker-container --driver-opt image=moby/buildkit:v0.8-beta --buildkitd-flags --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host --use
builder-publish-2
🏃 Booting builder...
/usr/bin/docker buildx inspect --bootstrap
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:v0.8-beta
#1 pulling image moby/buildkit:v0.8-beta 2.0s done
#1 creating container buildx_buildkit_builder-publish-20
#1 creating container buildx_buildkit_builder-publish-20 2.5s done
#1 DONE 4.5s
Name:   builder-publish-2
Driver: docker-container

Nodes:
Name:      builder-publish-20
Endpoint:  unix:///var/run/docker.sock
Status:    running
Flags:     --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
Platforms: linux/amd64, linux/386
🛒 Extracting available platforms...
linux/amd64,linux/386

Run docker/login-action@v1
🔑 Logging into docker.pkg.github.com...
🎉 Login Succeeded!

📣 Buildx version: 0.4.2
🏃 Starting build...
/usr/bin/docker buildx build --build-arg NPM_PACKAGE_TOKEN_d1b7="***" --tag ghcr.io/example-org/my-app:1e18820e41155ea00af28b0a797d050264fb9766 --iidfile /tmp/docker-build-push-H8uVDy/iidfile --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-build-push-H8uVDy/tmp-3156-RV9qOFc1bIxW --file src/Dockerfile --push https://github.com/example-org/my-app.git#heads/deploy-den-gh-actions
time="2020-10-23T15:49:10Z" level=warning msg="invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: "
#1 [internal] load git source https://github.com/example-org...
#1 0.041 Initialized empty Git repository in /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/1/fs/
#1 0.195 1e18820e41155ea00af28b0a797d050264fb9766	refs/heads/deploy-den-gh-actions
#1 0.438 From https://github.com/example-org/my-app
#1 0.438  * [new branch]      deploy-den-gh-actions -> heads/deploy-den-gh-actions
#1 0.438  * [new branch]      deploy-den-gh-actions -> origin/deploy-den-gh-actions
#1 DONE 0.5s

#3 [internal] load metadata for docker.io/library/node:12-alpine
#3 DONE 0.5s

#2 [internal] load metadata for docker.io/library/nginx:stable-alpine
#2 DONE 0.7s
```

**Comment by crazy-max** [comment]
@den-is You log on to `docker.pkg.github.com` but try to push to `ghcr.io`. You can't do that. To connect to `ghcr.io` [read this note](https://github.com/docker/login-action#github-container-registry).

**Comment by den-is** [comment]
thanks @crazy-max
yeah got confused with registry links. posted issue before finding that documentation page (and actually carefully reading it)
https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages#authenticating-to-github-packages

![image](https://user-images.githubusercontent.com/5287237/97086926-61843a00-1637-11eb-88c0-fa61a44a60b1.png)

Unfortunately had to return to `docker.pkg.github.com` since `ghcr.io` is not visible in GH packages UI (at the moment of writing)

**Comment by den-is** [comment]
@crazy-max issue is not solved. Still 403 but with different text.

Today authentication and image name fixes - didn't actually fix the problem
Buildx is still failing with:
```
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = unexpected status: 403 Forbidden
```
```yaml
jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparation
      id: prep
      run: |
        REGISTRY="docker.pkg.github.com"
        IMAGE="${REGISTRY}/${{ github.repository }}/${{ github.event.repository.name }}"
        TAGS="${IMAGE}:${{ github.sha }}"
        if [[ $GITHUB_REF == ref/head/master ]]; then
          TAGS="${TAGS},${IMAGE}:latest"
        fi
        echo ::set-output name=tags::${TAGS}
    - name: Docker Buildx setup
      uses: docker/setup-buildx-action@v1
    - name: Login in to registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Push to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        file: src/Dockerfile
        build-args: |
          NPM_PACKAGE_TOKEN_d1b7="${{ secrets.NPM_PACKAGE_TOKEN_d1b7 }}"
        tags: ${{ steps.prep.outputs.tags }}
```
**Initialization**
```
...
Run docker/login-action@v1
🔑 Logging into docker.pkg.github.com...
🎉 Login Succeeded!
# --------------------
Run docker/build-push-action@v2
📣 Buildx version: 0.4.2
🏃 Starting build...
/usr/bin/docker buildx build --build-arg NPM_PACKAGE_TOKEN_d1b7="***" --tag docker.pkg.github.com/example-org/my-app/my-app:c7c6023ea9af524234444387000a2553aa20a7f6 --iidfile /tmp/docker-build-push-8RVwsf/iidfile --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-build-push-8RVwsf/tmp-3034-k9IcoU4X5lva --file src/Dockerfile --push https://github.com/example-org/my-app.git#heads/deploy-den-gh-actions
time="2020-10-26T08:08:24Z" level=warning msg="invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: "
#1 [internal] load git source https://github.com/example-org...
#1 0.034 Initialized empty Git repository in /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/1/fs/
#1 0.229 c7c6023ea9af524234444387000a2553aa20a7f6	refs/heads/deploy-den-gh-actions
#1 0.484 From https://github.com/example-org/my-app
#1 0.484  * [new branch]      deploy-den-gh-actions -> heads/deploy-den-gh-actions
#1 0.484  * [new branch]      deploy-den-gh-actions -> origin/deploy-den-gh-actions
#1 DONE 0.5s

#3 [internal] load metadata for docker.io/library/node:12-alpine
#3 ...
...
# usual build
...
#18 exporting to image
#18 exporting layers
#18 exporting layers 1.0s done
#18 exporting manifest sha256:65a39d9de33f06b9b0bfcc4a1d263b35c11f65619c2d4b8af4253e8620a01b45 done
#18 exporting config sha256:c14e402195f459fe81fa566401906e32668263bc838fe0bcf2ab7c5ed635ce27 done
#18 pushing layers
#18 pushing layers 0.9s done
#18 ERROR: unexpected status: 403 Forbidden
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = unexpected status: 403 Forbidden
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = unexpected status: 403 Forbidden
```

I don't have full root privileges on that repo. But I definitely can write to that repo. Docs state that everyone with write permissions can push package.
https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/publishing-a-package

More detailed error output, if possible, might do a better job.
