### ISSUE TITLE
Not pushing to Docker Hub

### ISSUE THREAD

**Issue by matjazmav** [docker/build-push-action#207]
I'm trying to push to the DockerHub https://hub.docker.com/r/matjazmav/wfdb but nothing happens. All steps are successful but if you check DockerHub there is no image. What am I missing?

**Action configuration** ([more](https://github.com/matjazmav/wfdb-docker/blob/master/.github/workflows/docker-image.yml)): 
```yml
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: matjazmav
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push the Docker image
        uses: docker/build-push-action@v2.0.1
        with:
          tags: |
            matjazmav/wfdb:latest
            matjazmav/wfdb:${{ steps.extractversion.outputs.version }}
```

**Logs** ([more](https://github.com/matjazmav/wfdb-docker/runs/1315180155?check_suite_focus=true#step:5:1951)):
```
...
#6 exporting to image
#6 exporting layers
#6 exporting layers 1.3s done
#6 writing image sha256:9746f89d5e0faaafbc22e926e0efcc7afa29954fce2b3e16868c213a98a30391 done
#6 naming to docker.io/matjazmav/wfdb:latest done
#6 naming to docker.io/matjazmav/wfdb:10.6.2 done
#6 DONE 1.3s
🛒 Extracting digest...
sha256:9746f89d5e0faaafbc22e926e0efcc7afa29954fce2b3e16868c213a98a30391
...
```

**Comment by crazy-max** [comment]
@matjazmav You're missing `push: true`:

```yaml
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: matjazmav
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push the Docker image
        uses: docker/build-push-action@v2.0.1
        with:
          push; true
          tags: |
            matjazmav/wfdb:latest
            matjazmav/wfdb:${{ steps.extractversion.outputs.version }}
```
