### ISSUE TITLE
Build artifacts in previous steps are not showing up in resulting Docker image

### ISSUE THREAD

**Issue by jkupcho** [docker/build-push-action#209]
### Behaviour
Previously, build artifacts created in previous steps would show up in the Docker image, with v2 this is no longer working. I'm not sure if this is due to how files are being handled within the environment.

#### Expected behaviour

> vendor/bundle directory available within the image

#### Actual behaviour

> vendor/bundle directory is not added to the image

```yml    
- name: Use Ruby
   uses: ruby/setup-ruby@v1
   with:
     ruby-version: 2.7
     bundler-cache: true
- run: |
    bundle config path vendor/bundle
    bundle config bin vendor/bin
    bundle install
- name: Set up QEMU
   uses: docker/setup-qemu-action@v1
- name: Set up Docker Buildx
   uses: docker/setup-buildx-action@v1
- name: Login to DockerHub
   uses: docker/login-action@v1
   with:
     username: yoink
     password: yoink
- name: Build and Push to Docker Hub
  uses: docker/build-push-action@v2
  with:
    push: true
    tags: yoink/yoink:latest
```

Any help would be appreciated!

**Comment by crazy-max** [comment]
@jkupcho The default behavior of this action is to use the Git context invoked by your workflow if no `context` is specified. That's why data from previous steps are not available. To solve this you have to use the [Path context](https://github.com/docker/build-push-action#path-context):

```yaml
- name: Build and Push to Docker Hub
  uses: docker/build-push-action@v2
  with:
    context: .
    push: true
    tags: yoink/yoink:latest
```
