### ISSUE TITLE
Error with multi line secrets

### ISSUE THREAD

**Issue by cageyv** [docker/build-push-action#210]
#### Steps to reproduce this issue

1. create any multi line github secret
aaaaaaaa
bbbbbbb
ccccccccc
2. try to build 

#### Expected behaviour

> Usually the behavior is for secrets

#### Actual behaviour

> Many empty secrets created one after another by the number of new lines. Text from secrete as is secrete ID

### Logs
> `buildx call failed with: secret missing ID`
> `--secret id=MY_SECRET,src=/tmp/docker-build-push-U0StQW/tmp-3228-au9Z9dz63faF --secret id=,src=/tmp/docker-build-push-U0StQW/tmp-3228-iNa5xa6xv3PV --secret id=XXXXXX___TEXT_FROM_SECRET_XXXXXXXX,src=/tmp/docker-build-push-U0StQW/tmp-3228-p4A8fDoTE0em`

 It look like some parsing error. Maybe this PR and code can help: #201

**Comment by crazy-max** [comment]
@cageyv Do you have a link to your workflow/repo please? Or can you just paste it here for repo? Thanks.

**Comment by crazy-max** [comment]
@cageyv I've created a PR to handle multi-line value for secrets. Can you make a test with `uses: crazy-max/docker-build-push-action@secret-multiline`?

```yaml
secrets: |
  GIT_AUTH_TOKEN=abcdefghi,jklmno=0123456789
  "MYSECRET=aaaaaaaa
  bbbbbbb
  ccccccccc"
  FOO=bar
  "EMPTYLINE=aaaa
  
  bbbb
  ccc"
```

| Key                | Value                                            |
|--------------------|--------------------------------------------------|
| `GIT_AUTH_TOKEN`   | `abcdefghi,jklmno=0123456789` |
| `MYSECRET`         | `aaaaaaaa\nbbbbbbb\nccccccccc` |
| `FOO`              | `bar` |
| `EMPTYLINE`        | `aaaa\n\nbbbb\nccc` |

**Comment by cageyv** [comment]
@crazy-max sorry for late answer, I invited you to repo with a error 

Also this fix give me a new error:
```
Warning: *** is not a valid secret
Warning: *** is not a valid secret
Warning: *** is not a valid secret
Warning: *** is not a valid secret (91 lines - one per secret line)
/usr/bin/docker buildx build --tag test:latest --platform linux/amd64 --output type=local,dest=out --secret id=key1,src=/tmp/docker-build-push-4i36oJ/tmp-3010-uDmcjnI3mnyz --secret id=key2,src=/tmp/docker-build-push-4i36oJ/tmp-3010-ZcRwH2I4YeT3 --file ./Dockerfile .
```

Secret with error: `gpg --export | base64` 
Secret without error: `gpg --export | base64 -w 0` or `gpg --export | base64 -b`  (for macos)

**Comment by crazy-max** [comment]
@cageyv Is your kvp secret "quoted"?:

```yaml
secrets: |
  "MYSECRET=${{ secrets.GPG_KEY }}"
```

**Comment by gustavovalverde** [comment]
@crazy-max if I attempt this, I get `Quote Not Closed: the parsing is finished with an opening quote at line 14`

**Comment by Powertrain** [comment]
Hoping to help others who find this thread.
Adding a comma between secrets worked for me. 

```dockerfile
secrets: |
            "GCP_JSON_KEY=${{ secrets.GCP_JSON_KEY }}",
            "GCP_JSON_KEY2=${{ secrets.GCP_JSON_KEY2}}"
```

**Comment by miker985** [comment]
@gustavovalverde the problem is your JSON key, as provided, has double quotes in it. This breaks things and the workaround is [noted at the bottom of the secrets page](https://docs.docker.com/build/ci/github-actions/secrets/)

> Double escapes are needed for quote signs.

I looked into the best way to escape the double quotes and realized there was a more straight-forward way - `auth` provides a file output that can be easily passed to build-push-action

```yaml
     - name: Auth to Google Cloud
       id: auth
       uses: 'google-github-actions/auth@v2'
       with:
         credentials_json: '${{ secrets.GCP_JSON_KEY }}'
         token_format: 'access_token'

    - name: Auth to Google Artifact Registry
      run: |-
        echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://us-docker.pkg.dev

...

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          secret-files: |
            "file_based_secret=${{ steps.auth.outputs.credentials_file_path }}"
          ...
```
