### ISSUE TITLE
support `build-args` from steps' outputs (::set-output)

### ISSUE THREAD

**Issue by morlay** [docker/build-push-action#211]
Last version, we could pass build-args like

```yaml
jobs:
  build:
    steps:
      - id: prepare
        run: echo ::set-output name=build_args::VERSION=$(VERSION),BASE_DISTRIBUTION=$(BASE_DISTRIBUTION)    
      - uses: docker/build-push-action@v2
        with:
          build-args: ${{ steps.prepare.outputs.build_args }}
```

Since `build-args` not support csv format, `--build-arg` not process as expect (explode to multi).

Could we added a special splitter to handle this?

Or just like this did.
https://github.community/t/set-output-truncates-multiline-strings/16852
May add this to README.

**Comment by crazy-max** [comment]
@morlay Instead of using `::set-output` command, I think you can use the [github-script action](https://github.com/actions/github-script):

```yaml
jobs:
  build:
    steps:
      - uses: actions/github-script@v3
        id: build_args
        with:
          result-encoding: string
          script: return `VERSION=${process.env.VERSION}\nBASE_DISTRIBUTION=${process.env.BASE_DISTRIBUTION}`
      - uses: docker/build-push-action@v2
        with:
          build-args: ${{ steps.build_args.outputs.result }}
```
