### ISSUE TITLE
Using --load parameter with multiple platforms throws an error

### ISSUE THREAD

**Issue by bhautikpip** [docker/build-push-action#214]
I am having issue with running --load param with multiple platform arguments. I am running following build action.

```
-  name: Build docker image
   uses: docker/build-push-action@v2
   with:
      context: .
      file: ./Dockerfile
      load: true
      platforms: linux/amd64,linux/arm64
      tags: amazon/aws-xray-daemon:alpha
```

I am able to run this with single platform (eg linux/amd64). Is this a known issue? Is there any timeline for a fix? I found one [issue](https://github.com/docker/buildx/issues/59) in buildx repo.
