### ISSUE TITLE
How to use only push side

### ISSUE THREAD

**Issue by rodrigorodrigues** [docker/build-push-action#219]
Hi all,

I already use `jib maven plugin` to build the docker image then I'm trying to use _only_ the `push` part but it seems is trying to also build the image.

Does anyone know if is that possible to achieve? I have tried in different ways with custom builder and context path but getting same error, following yml configuration.

https://github.com/rodrigorodrigues/microservices-design-patterns/blob/master/.github/workflows/docker-build-push-image-authentication-service.yml

context: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build the Docker image with Maven
      - name: Build
        run: |
          mvn clean install -q -pl authentication-service -am -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dspring.profiles.active=travis jib:dockerBuild
      # Login to Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push the Docker image
      - name: Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: fielcapao/microservices-design-patterns:authentication-service

custom builder

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: false

      # Build the Docker image with Maven
      - name: Build
        run: |
          mvn clean install -pl authentication-service -am -B -Dspring.profiles.active=travis jib:dockerBuild
      # Login to Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push the Docker image
      - name: Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: fielcapao/microservices-design-patterns:authentication-service

Error:

	Run docker/build-push-action@v2
	📣 Buildx version: 0.4.2
	🏃 Starting build...
	/usr/bin/docker buildx build --tag ***/microservices-design-patterns:authentication-service --iidfile /tmp/docker-build-push-LfaVqe/iidfile --file ./Dockerfile --push .
	time="2020-11-06T20:13:32Z" level=warning msg="invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: "
	#2 [internal] load .dockerignore
	#2 transferring context: 2B 0.0s done
	#2 DONE 0.1s

	#1 [internal] load build definition from Dockerfile
	#1 transferring dockerfile: 2B 0.0s done
	#1 DONE 0.1s
	failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount572794755/Dockerfile: no such file or directory
	Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount572794755/Dockerfile: no such file or directory

Thanks

**Comment by crazy-max** [comment]
@rodrigorodrigues 

> I'm trying to use only the push part but it seems is trying to also build the image.

That's not the purpose of this action but you can use `docker push` in a shell step:

```yaml
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1
  - name: Build
    run: |
      mvn clean install -q -pl authentication-service -am -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dspring.profiles.active=travis fielcapao/microservices-design-patterns:authentication-service
  - name: Login to DockerHub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  - name: Push
    run: |
      docker push fielcapao/microservices-design-patterns:authentication-service
```

**Comment by rodrigorodrigues** [comment]
Thanks @crazy-max for quick response you're absolute right!
 
Docker build is made by maven plugin `jib:dockerBuild`

**Comment by akhilerm** [comment]
@crazy-max , I am having a similar use case. The build is being done [here](https://github.com/openebs/node-disk-manager/blob/015fbd6931385388f0d077377d36e7c4315abd8a/.github/workflows/build.yml#L98). I only want to use the push feature. (Need to push to dockerhub, quay etc).

From the above discussion got to know that this action is for build+push and to use `docker push` for pushing the image. But for pushing multiarch images `docker push` wont work. 

Currently I am manually pushing to other registries using this https://github.com/tonistiigi/repo-copy. Would like to know if the same thing can somehow be achieved using the `build-push-action` or should we create a new github action, like `repo-copy-action` to achieve the same.

**Comment by akhilerm** [comment]
Went ahead and created an action for the same. It is available at [repo-copy-action](https://github.com/akhilerm/repo-copy-action). Would be great if you could take a look into it. Havent got it into a complete working state yet.

**Comment by crazy-max** [comment]
@akhilerm Yes you can push multi platform images with this action, see https://github.com/docker/build-push-action#multi-platform-image.

> (Need to push to dockerhub, quay etc).

To push to multi registries, see https://github.com/docker/build-push-action#push-to-multi-registries

**Comment by akhilerm** [comment]
@crazy-max But that involves build+push right? I only need to use the push feature. Suppose, I already have a multiplatform image available in dockerhub. After performing some testing on that image, I need to push it to quay. 

I tried only using `push` and `tags` from the action inputs. But it seems to be not the correct way.

**Comment by akhilerm** [comment]
I created a new [tag-push-action](https://github.com/akhilerm/tag-push-action) with just the functionality to retag and push a multiplatform image. Still have to add the functionality to specify multiple destination tags. But basic features are now functional.

**Comment by moander** [comment]
Push multiple tags "without" build:

```yaml
    - run: echo 'FROM ${{ env.SOURCE_IMAGE }}' > /tmp/Dockerfile.source

    - uses: docker/build-push-action@v5
      with:
        context: .
        file: /tmp/Dockerfile.source
        tags: ${{ steps.meta.outputs.tags }}
```
