### ISSUE TITLE
Feature request: provide way to add --force-rm and --compress arguments to docker build command

### ISSUE THREAD

**Issue by RollerKnobster** [docker/build-push-action#224]
When building heavy images in tight circumstances, keeping the disk clean and the image lean is very much desirable. However, right now there seems to be no way to provide these arguments.

If not documented, perhaps these are already taking place implicitly? Otherwise, it would be really great to have them as action input arguments.

**Comment by RollerKnobster** [comment]
In case of anyone responsible finding this suitable, a [branch](https://github.com/RollerKnobster/build-push-action/commit/0cdfbc43b4e9a2c1177b31a6c17f331d9dbce1d3) composed according to [the contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) is ready to be published.

**Comment by crazy-max** [comment]
@RollerKnobster `--force-rm` and `--compress` are currently not supported by buildkit. As @tonistiigi told me, compression doesn't really make sense when used with GitHub Actions and I agree with that unless you have a specific use case?

**Comment by Ornias1993** [comment]
@crazy-max It should be supported though:

> * `compression=[uncompressed,gzip]`: choose compression type for layer, gzip is default value

was added to the buildkit readme 17 months ago...

**Comment by crazy-max** [comment]
@Ornias1993 

> was added to the buildkit readme 17 months ago...

`--compress` is a flag for the classic builder `docker build ...` which is not available in buildx but you can use the `compression` field for `image` type:

```yaml
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: user/app:latest
          outputs: type=image,compression=gzip,push=true
```

List of supported compression types: https://github.com/moby/buildkit#imageregistry

Tracked in https://github.com/docker/buildx/issues/11
