### ISSUE TITLE
Using actions expression in tags

### ISSUE THREAD

**Issue by baetheus** [docker/build-push-action#226]
### Troubleshooting

Before sumbitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

I've confirmed that the following github expression represents the commit sha via the following step:

```
      - name: Troubleshooting
        run: echo $VALUE
        env:
          VALUE: ${{ github.sha }}
```

This will echo the sha to the workflow logs under the Troublshooting step.

### Behaviour

While trying to use the expression ${{ github.sha }} in the tags input of docker/build-push-action@v2 the assigned tag does not include the sha.

#### Steps to reproduce this issue

1. Setup a Dockerfile that will always work.
2. Use the sample docker build-push-action workflow

```yaml
name: Troubleshooting

on:
  push:
    branches:
      - troubleshooting

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1


      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: org/repo:troubleshooting-${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```

3. Check for the image at `org/repo:troubleshooting-<COMMIT_SHA>`

#### Expected behaviour

The pushed image should be tagged with `org/repo:troubleshooting-<COMMIT_SHA>`.

#### Actual behaviour

The pushed image is tagged with `org/repo:troubleshooting-`.

### Configuration

* Repository URL (if public): Unfortunately private
* Build URL (if public): Also private

```yml
# See Above
```

### Logs

Also private.

### Notes

I assume this issue is because I don't understand some nuance of [contexts](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions). If this is the case I'm hoping a quick response will set me in the right direction. If it's not the case I will put together a public repository with no private data to reproduce the issue. Either way, thank you for your time.

**Comment by crazy-max** [comment]
@baetheus 

> I assume this issue is because I don't understand some nuance of contexts.

Depends on the event triggered. Can you add the following step at the end of your job to check the context please?:

```yaml
    -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
```
