### ISSUE TITLE
@v2 multistage buildx crossbuild for platforms:linux/arm/v6,linux/arm/v7 succeeds but gives manifest without v6 and v7 qualifiers at ghcr.io

### ISSUE THREAD

**Issue by mskyttner** [docker/build-push-action#234]
# Behaviour

Using the @v2 build-push-action with buildx to generate docker images for ARM, the build and push succeeds with images available at https://github.com/users/mskyttner/packages/container/package/duckdb-cli-arm.

The manifest at https://github.com/users/mskyttner/packages/container/package/duckdb-cli-arm lists both the linux/arm/v6 and linux/arm/v7 (see the OS/Arch tab) images as just `linux/arm`.

This causes confusion with regards to what architecure these two ARM images at GHCR.io targets, and differs from the behaviour for the same images when they're pushed with the same buildx parameters to Docker Hub.

#### Steps to reproduce this issue

1. Use this workflow file: https://github.com/mskyttner/duckdb-cli-builds/blob/main/.github/workflows/push-duckdb-cli-arm.yml
2. Inspect the GitHub Package with the images at: https://github.com/users/mskyttner/packages/container/package/duckdb-cli-arm

#### Expected behaviour

That these images would have OS/Arch qualifiers like at hub.docker.com, see https://hub.docker.com/r/mskyttner/duckdb/tags, ie the two first arm images would be "linux/arm/v6" and "linux/arm/v7".

#### Actual behaviour

Instead both those get OS/Arch listed as just "linux/arm".

### Configuration

* Repository URL (if public): https://github.com/mskyttner/duckdb-cli-builds
* Build URL (if public): https://github.com/mskyttner/duckdb-cli-builds/runs/1413032056?check_suite_focus=true

```yml
name: duckdb CLI arm push

on:
  workflow_dispatch:
  push:
    paths:
    - 'arm/**'
    - '.github/workflows/push-duckdb-cli-arm.yml'

jobs:
  duckdb-cli-arm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    -
      name: Set Environment Variables
      run: |
        IMG=duckdb-cli-arm
        echo "BUILD_VER=1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        echo "IMG=${IMG}" >> $GITHUB_ENV
        echo "IMAGE=ghcr.io/${{ github.repository_owner }}/${IMG}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV
 
    -
      name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
        install: true

    -
      name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    -
      name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        context: ./arm
        file: ./arm/Dockerfile
        labels: |
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
          org.opencontainers.image.ref.name=${{ env.GIT_REF }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ env.BUILD_VER }}
        tags: |
          ${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:${{ env.GIT_REF }}
          ${{ env.IMAGE }}:${{ env.GIT_SHA }}
          ${{ env.IMAGE }}:${{ env.BUILD_VER }}
        push: true
        platforms: linux/arm/v6,linux/arm/v7,linux/amd64
```

### Logs

Those should be available from here: [logs](https://github.com/mskyttner/duckdb-cli-builds/runs/1413032056?check_suite_focus=true)

I think the relevant part is where the manifest is put together, this is the end of the log for this step, where that happens.

Somewhere the "linux/arm/v6" and "linux/arm/v7" both get mangled into "linux/arm", unlike on Docker Hub, if pushing there instead.

```bash
#27 [linux/arm/v7 stage-1 6/6] WORKDIR /data
#27 DONE 0.0s

#39 exporting to image
#39 exporting layers
#39 exporting layers 1.2s done
#39 exporting manifest sha256:57f66b46eeec66ba7b8e989964da64af56a5474d15e63bed025d2b8c5a03faf8 done
#39 exporting config sha256:996f2bce031460976f8f5748817506cb1cc63efa68c30904e948d720115ed942 done
#39 exporting manifest sha256:72aae7f8c60abcb1c92f166ab5136c60553213213fea9c97a1eeca5fb97e9c5d done
#39 exporting config sha256:e7effcc368be08ebb192da6835fc837877ca52513abfe8e8fdabb03267eb890f done
#39 exporting manifest sha256:1592722d9ed5e90388b07237138d9ba8dfe8c6e8ee1aee573a47402881004d78 done
#39 exporting config sha256:b7aa3035020ec10d031aa5f76b083b09e366e94bc804f0c601d9c78dd47f0bec
#39 exporting config sha256:b7aa3035020ec10d031aa5f76b083b09e366e94bc804f0c601d9c78dd47f0bec done
#39 exporting manifest list sha256:106c452cef95b78e91344d02de7b26463ebc4149bc8cebd35f2a5227dd735e3e done
#39 pushing layers
#39 pushing layers 7.3s done
#39 pushing manifest for ghcr.io/mskyttner/duckdb-cli-arm:latest
#39 pushing manifest for ghcr.io/mskyttner/duckdb-cli-arm:latest 9.8s done
#39 pushing layers
#39 pushing layers 0.7s done
#39 pushing manifest for ghcr.io/mskyttner/duckdb-cli-arm:main
#39 pushing layers
#39 pushing manifest for ghcr.io/mskyttner/duckdb-cli-arm:main 10.2s done
#39 pushing layers 0.9s done
#39 pushing manifest for ghcr.io/mskyttner/duckdb-cli-arm:2c61e8c
#39 pushing manifest for ghcr.io/mskyttner/duckdb-cli-arm:2c61e8c 9.5s done
#39 pushing layers
#39 pushing layers 0.6s done
#39 pushing manifest for ghcr.io/mskyttner/duckdb-cli-arm:1.0.6
#39 pushing manifest for ghcr.io/mskyttner/duckdb-cli-arm:1.0.6 5.6s done
#39 DONE 45.8s
🛒 Extracting digest...
sha256:106c452cef95b78e91344d02de7b26463ebc4149bc8cebd35f2a5227dd735e3e
```
