### ISSUE TITLE
Values for "tags:" containing mixed case repo slug generates buildx error

### ISSUE THREAD

**Issue by mskyttner** [docker/build-push-action#237]
#### Steps to reproduce this issue

1. Set up a GitHub repo that is not all lowercase (such as "KTH-Library")
2. Set up an gh action which uses buildx action with a "tags:" value that contains a mixed case repo slug/string, for example based on {{ github.repository_owner }}
3. Run the action and trigger the error (see the logs)

#### Expected behaviour

Using a tag for the image name which contains mixed case should either work or automatically translate "tags:" values (which may often involve the repo slug) to lowercase. 

#### Actual behaviour

Instead a build error is triggered.

### Configuration

* Repository URL (if public): https://github.com/KTH-Library/kontarion
* Build URL (if public): https://github.com/KTH-Library/kontarion/actions

### Logs

See https://github.com/KTH-Library/kontarion/actions

### Workaround

This workflow file works around the mixed case with ` OWNER="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"`, which otherwise stops the run since only lower case "tags:" values are allowed.

```yml
name: kontarion push

on:
  workflow_dispatch:
  push:
    paths:
    - '1.7.0/**'
    - '.github/workflows/push-kontarion.yml'

jobs:
  kontarion-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    -
      name: Set Environment Variables
      run: |
        IMG=kontarion
        OWNER="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
        echo "BUILD_VER=1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        echo "IMG=${IMG}" >> $GITHUB_ENV
        echo "IMAGE=ghcr.io/${OWNER}/${IMG}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV
 
    -
      name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        version: latest
        install: true

    -
      name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    -
      name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    -
      name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        context: ./1.7.0/
        file: ./1.7.0/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        labels: |
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
          org.opencontainers.image.ref.name=${{ env.GIT_REF }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ env.BUILD_VER }}
        tags: |
          ${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:${{ env.GIT_REF }}
          ${{ env.IMAGE }}:${{ env.GIT_SHA }}
          ${{ env.IMAGE }}:${{ env.BUILD_VER }}
        load: true
        platforms: linux/amd64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
    - run: docker push ${{ env.IMAGE }}:latest

    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

```

**Comment by Juu-** [comment]
Hi @mskyttner,

Even with all tag char in lowercase, I can't push my image to the ghcr.io registry.

Do you find a workaround or something to do it ?

Thanks,
Juu'

**Comment by crazy-max** [comment]
@Juu- GHCR allows this kind of slug `ghcr.io/OWNER/IMAGE_NAME` as stipulated in [their doc](https://docs.github.com/en/free-pro-team@latest/packages/guides/migrating-to-github-container-registry-for-docker-images#domain-changes). So in your case it should be `ghcr.io/juu-/IMG_NAME:latest`.

**Comment by Juu-** [comment]
Hi @crazy-max ,

Thank you for your quick response !

Her is now the command return:

```
/usr/bin/docker buildx build --tag ghcr.io/juu-/vivaio_backend:latest --iidfile /tmp/docker-build-push-Mq0kSf/iidfile --file ./Dockerfile --builder builder-build-2 --push .
time="2020-12-12T17:54:10Z" level=warning msg="invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: "
invalid tag "ghcr.io/juu-/vivaio_backend:latest": invalid reference format
Error: buildx call failed with: invalid tag "ghcr.io/juu-/vivaio_backend:latest": invalid reference format ```

**Comment by crazy-max** [comment]
@Juu- Well, looks like you're hitting a weird behavior here. Maybe because of the dash at the end of your username: ["A name component may not start or end with a separator"](https://docs.docker.com/engine/reference/commandline/tag/#extended-description). Suggest to open a support ticket to GitHub about this: https://support.github.com/contact.

**Comment by Juu-** [comment]
Wahoo,

I wouldn't expect that !
I'm gonna open a support ticket to Github like you suggest and come back here for updates.

Merci beaucoup @crazy-max !

**Comment by Juu-** [comment]
Here is my topic to the community: https://github.community/t/my-user-name-end-with-a-dash/149446.

Wait and see,
Juu'

**Comment by crazy-max** [comment]
Closing this. Let me know if it has been resolved on the GitHub side.

**Comment by crazy-max** [comment]
@mskyttner Can you test with `docker/build-push-action@sanitize-tags`?

**Comment by crazy-max** [comment]
After consideration about what have been done in #341, I think it adds an unnecessary complexity that should rather be handled upstream by GitHub. Another solution is to use our [metadata action](https://github.com/docker/metadata-action) to generate tags that are sanitized.

@mskyttner Using your workflow it will look like this:

```yaml
name: kontarion push

on:
  workflow_dispatch:
  push:
    paths:
      - '1.7.0/**'
      - '.github/workflows/push-kontarion.yml'

jobs:
  kontarion-push:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/kontarion
        tags: |
          type=raw,value=1.0.${{ github.run_number }},priority=1000
          type=ref,event=branch
          type=sha
          type=raw,value=latest
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    -
      name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        context: ./1.7.0
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
```
