### ISSUE TITLE
failed to solve: rpc error: code = Unknown desc = unexpected status: 502 Bad Gateway

### ISSUE THREAD

**Issue by robert-scheck** [docker/build-push-action#239]
#### Steps to reproduce this issue

1. Trigger a new workflow run

#### Expected behaviour

Successful push to Docker Hub and Quay.i (a scheduled workflow using the same workflow YAML file worked earlier today quite fine, looked like this):

```
#39 exporting to image
#39 exporting layers
#39 exporting layers 1.6s done
#39 exporting manifest sha256:6e32a4e976405899ee4c7d9d289c5a557580c848cda11c7532bbf8514c238a86 done
#39 exporting config sha256:9a349d0c016c1a8675c999101c31fcc39b3e0e4ede9beaffb21fb0eaea9de39d done
#39 exporting manifest sha256:13b0104f8058f2ac4349dbb304867e12b39de32401419469b896c03d741764bd done
#39 exporting config sha256:4bf54786b8f5fad6f19c4b546043ecf19ef5181efc8bd3d2b12aa580fc2767a7 done
#39 exporting manifest sha256:8d400a3ffaec659b5c946dbde7d317b9f5d0ae2e0b517cdf486444e67b29e4c1 done
#39 exporting config sha256:64d66d665cdd543a2153ebb9e49e52cadded2a4408811d51bf697f3ca642707f done
#39 exporting manifest sha256:0f9232fc8a8ca4be1e281f6080d323f694f4231dc8dd9f63bf52798c0130a315 done
#39 exporting config sha256:8a7e57de25f6e1357ba394e101ff2281ea5aac2ca4cfbf2eec7cc6dbaf4bfb3f done
#39 exporting manifest sha256:6a5a8d195e373e393c0bbcd94f9ae222c6bc53618e11fad14e828a2e344e8572 done
#39 exporting config sha256:8e1db268a808efc9909b0b1e5b50ddf89d2d7e7db802c85d2dc64a7648746a3a done
#39 exporting manifest sha256:8709a074607ae77c48884a4dbacfd0e4fae5b3f44a4602fafb03d27afddd882a done
#39 exporting config sha256:a6f48bc20f3552e0e85131c7ab77f90309491fa11022e5c40eab672e1e788767 done
#39 exporting manifest sha256:b86a5ffa98d2917197a4deebfbcf4ce788dced4ab1dbf3e48806073c1ccdd49f done
#39 exporting config sha256:53aae91ac43f1cb2c4dd96097a3e12fc3f8856f5917db286b7c3595b97c5b6e1 done
#39 exporting manifest list sha256:7c568fd9e3ce2ff3bf7ed0d6c9ed84d7b5bb9f472c2f5f0c4095c6cae38436fe done
#39 pushing layers
#39 pushing layers 2.9s done
#39 pushing manifest for docker.io/rpki/rpki-client:nightly
#39 pushing manifest for docker.io/rpki/rpki-client:nightly 4.5s done
#39 pushing layers 4.4s done
#39 pushing manifest for quay.io/rpki/rpki-client:nightly
#39 pushing manifest for quay.io/rpki/rpki-client:nightly 12.8s done
#39 DONE 26.3s
```

#### Actual behaviour

The same workflow YAML file leads currently to this push failure:

```
#39 exporting to image
#39 exporting layers
#39 exporting layers 1.6s done
#39 exporting manifest sha256:aa911b0aecf3abf9712e632bc79ddd368e9f88d479b42ad9ba7ca4186c643e61 done
#39 exporting config sha256:19dbaa68c89052ff33fe32d9a9fe36621dc17f68c4ddbe1f597ef5aaf600dcac done
#39 exporting manifest sha256:1e5d337220918567bb333109292ab7826f763442c6e596708a5ab7bbb08d853f done
#39 exporting config sha256:0c6703aa6a267f709bf68998662fd94c5989f42f6a2cc368031a259fe6f23dd5 done
#39 exporting manifest sha256:61d6feffcf9b150bf779055ab3405cf3818113a1aacb723eacbe1ce6efede325 done
#39 exporting config sha256:3b9c7311f7a544afbffd533f6ad9b5485e8d1811facbacf2cdf1c8e70b0769a4 done
#39 exporting manifest sha256:9998d66af8177854033b57bb1a00a895bd7a4f1fdc543b1cc4b1a7ab131a973a done
#39 exporting config sha256:d5e1ea70230884b832f0b2b157487983ee2aafb39b23cfff0e7f73e2c3387285 done
#39 exporting manifest sha256:f084592e799179ebef9a1e0d4c069ce027c4605bc665971704002c9a05816b3d done
#39 exporting config sha256:7f31c6b3c7d1c0145e7308bd9d153f271ac106cefe0fbc2df26a5c1384e9ff32 done
#39 exporting manifest sha256:6a5066c53e8a81cd3e1e0d7058fe24feab566a259658a69c3da876409552965e done
#39 exporting config sha256:a3c9b90e348175d62cba7eeba76d270fd92b66f50cada6edd4d2d8c38e2efc23 done
#39 exporting manifest sha256:3331774065bd961e39b95f5a1a4dd3848fc2a19db6e9791c27c9206d36cd809f done
#39 exporting config sha256:791b0d23aa9783acb198dab3bbfe2e44c8611573ce1867f00c114c3a188bddba done
#39 exporting manifest list sha256:0b7bbd74b6d426b14b6fc75327d6d7c44e6a68baed8f82f714a1b20045b8c9ed done
#39 pushing layers
#39 pushing layers 1.5s done
#39 pushing manifest for docker.io/rpki/rpki-client:edge
#39 pushing layers 0.1s done
#39 pushing manifest for docker.io/rpki/rpki-client:edge 4.2s done
#39 ERROR: unexpected status: 502 Bad Gateway
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = unexpected status: 502 Bad Gateway
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = unexpected status: 502 Bad Gateway
```

Re-running the workflow for three times didn't change anything, so not a temporary problem as it seems.

### Configuration

```yaml
name: Build and push OCI image

on:
  schedule:
    - cron: '5 3 * * *'  # UTC
  push:
    branches:
      - master
      - '*.*p*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=rpki/rpki-client
          QUAY_IMAGE=quay.io/rpki/rpki-client
          VERSION=noop
          PORTABLE_COMMIT=noop
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
            PORTABLE_COMMIT=master
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            PORTABLE_COMMIT=${VERSION}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            PORTABLE_COMMIT=${VERSION}
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=edge
            fi
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION},${QUAY_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}p[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest,${QUAY_IMAGE}:latest"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          BUILD_ARGS="VERSION=${PORTABLE_COMMIT}"
          echo ::set-output name=args::${BUILD_ARGS}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Quay Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Multi-arch Dockerfile
        run: sed -e 's/^\(FROM\) \(alpine:.*\)/ARG ARCH=\n\1 ${ARCH}\2/' -i Dockerfile
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          build-args: ${{ steps.prep.outputs.args }}
          labels: |
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.label-schema.version=${{ steps.prep.outputs.version }}
            org.label-schema.build-date=${{ steps.prep.outputs.created }}
            org.label-schema.vcs-ref=${{ github.sha }}
```

* Repository URL (if public): https://github.com/rpki-client/rpki-client-container
* Build URL (if public): https://github.com/rpki-client/rpki-client-container/runs/1455375425
* YAML Workflow: https://github.com/rpki-client/rpki-client-container/blob/master/.github/workflows/image.yml

### Logs
[Raw logs (gzipped)](https://github.com/docker/build-push-action/files/5598911/build.log.gz)
