### ISSUE TITLE
1. Build does not fail and shows warning instead. 2. Documentation shows wrong input type "build-args" instead of "build_args" 

### ISSUE THREAD

**Issue by dor-cyolo** [docker/build-push-action#242]
#### Steps to reproduce this issue

1. As shown in documentation - 

Use **build-args** to in order to send arguments to docker build  -
```
build-args: |
            arg1=value1
            arg2=value2
```
Taken from your documentation. 

#### Expected behaviour

> Argument should be passed to the docker build, Otherwise, if configured improperly - build should fail.

#### Actual behaviour

> Build does not fail (And it should!) since argument syntax has changed to **build_args** with **-** instead of  **-** but -
It doesn't say that on your documentation page.

> Tell us what happens instead

It shows the  **warning** below and actually does not accept the **build-args** syntax.
 
### The WARNING I get 
![Screen Shot 2020-12-01 at 20 10 08](https://user-images.githubusercontent.com/67296474/100780420-5f6d8200-3412-11eb-806b-3c9ff1c186bd.png)

### Configuration
```
uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyolosec/idac
          dockerfile: cmd/idac/Dockerfile
          tags: ha
          build-args: |
            GIT_COMMIT_HASH=${{ env.GIT_COMMIT_HASH }}
```

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

**It did work after I changed the input to build_args (Underscore instead if dash)**
