### ISSUE TITLE
Quotes Not Supported For Secrets or Build-Args

### ISSUE THREAD

**Issue by malkam03** [docker/build-push-action#245]
### Behavior

When you provide a secret value with quotes, like a JSON. The action fails with:
```log
> Run docker/build-push-action@v2
📣 Buildx version: 0.4.2
Error: Invalid Opening Quote: a quote is found inside a field at line 1
```

Escaping the quotes or using single quotes doesn't help either, tried:
```
{"host":"host","user":"user","pass":"pass"}
'{"host":"host","user":"user","pass":"pass"}'
{'host':'host','user':'user','pass':'pass'}
"{'host':'host','user':'user','pass':'pass'}"
{\"host\":\"host\",\"user\":\"user\",\"pass\":\"pass\"}
'{\"host\":\"host\",\"user\":\"user\",\"pass\":\"pass\"}'
``` 

#### Steps to reproduce this issue

1. Set a secret with quotes. E.g: `SERVER` with value `{"host":"host","user":"user","pass":"pass"}`
2. Use that secret for either the secret or build-args:
```yml
-
  	name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          file: ./Dockerfile
          build-args: |
            SERVER=${{ secrets.SERVER }}
          secrets: |
            SERVER=${{ secrets.SERVER }}
```
3. Run the workflow

#### Expected behaviour

> Expected to set the secret value to either the build-args or secrets so it can be used at build.

#### Actual behaviour

> The parsing of the values return `Error: Invalid Opening Quote: a quote is found inside a field at line 1`

### Configuration

* Repository URL (if public): Not public, but you can use the info provided above to reproduce the error.
* Build URL (if public): Not public, but you can use the info provided above to reproduce the error.

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue. 

Can't do this, the logs are not public.
