### ISSUE TITLE
Add *complete* example workflow yaml file

### ISSUE THREAD

**Issue by olgabot** [docker/build-push-action#25]
Hello,
I am adding this Action via this PR (https://github.com/nf-core/kmermaid/pull/56) and can't seem to get it to work (yaml below). Can you provide a *complete* minimal working example to guide the way for new users? Thank you!
Warmest,
Olga

```yaml
name: Build Docker images
# This workflow tests building the docker image so I stop committing
# bad Dockerfiles and breaking the build
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker images
        uses: docker/build-push-action@v1.0.1
        with:
          repository: nfcore/kmermaid
          push: false
```

**Comment by AnthonyWC** [comment]
I think u need to include the checkout (arguably should be a default..)
```yaml
name: Build Docker images
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v1

      - name: Build Docker images
        uses: docker/build-push-action@v1.0.1
        with:
          repository: nfcore/kmermaid
          push: false
```
