### ISSUE TITLE
Pretty big cache

### ISSUE THREAD

**Issue by MarcelCoding** [docker/build-push-action#252]
### Troubleshooting
The cache can grow with big images pretty fast, because old entries aren't deleted.

### Configuration

* Repository URL (if public): https://github.com/MarcelCoding/docker-desktop-vnc/blob/02fb4a97d5a75e40c467b856538efa443d1077cc/.github/workflows/docker-publish.yml#L28-L60
* Build URL (if public): https://github.com/MarcelCoding/docker-desktop-vnc/runs/1549446282?check_suite_focus=true#logs

```yml
[...]

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

[...]

      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.prepare.outputs.image }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: .

[...]
```

### Logs
[logs_37.zip](https://github.com/docker/build-push-action/files/5688147/logs_37.zip)

### My soloution
Add a configuration option `clean-cache`, witch executes he following command `docker system prune -f --filter "until=5h"`.

**Comment by crazy-max** [comment]
@MarcelCoding 

> The cache can grow very quickly with large images, since old entries are not deleted.

Yes you're right atm caches are copied over the existing cache so it's keep growing. Can you open an issue on [buildkit repo](https://github.com/moby/buildkit) about that please? In the meantime you can do this:

```yaml
[...]

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

[...]

      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.prepare.outputs.image }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          context: .

[...]

      - name: Move cache
        run:
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

cc. @tonistiigi

**Comment by MarcelCoding** [comment]
@crazy-max that means that the `cache-to` option does not export the entire Docker cache, just the one for the current images?

**Comment by crazy-max** [comment]
@MarcelCoding 

> that means that the cache-to option does not export the entire Docker cache, just the one for the current images?

[`cache-to`](https://github.com/docker/buildx#--cache-tonametypetypekeyvalue) exports the build cache for the current image being built with buildkit yes. If you are implying that the cache can be shared between different images, this is not the case. See https://github.com/docker/build-push-action/issues/153#issuecomment-703182778.

**Comment by MarcelCoding** [comment]
Ok, thanks for the help, i will create an issue at the builtkit repo. For implementing a option to clean the cache/remove old versions of the cache.

**Comment by zero88** [comment]
Hi @crazy-max 
Can I use [buildkit registry cache](https://github.com/moby/buildkit#registry-push-image-and-cache-separately) within[ `local registry`](https://hub.docker.com/_/registry) by [GitHub service container](https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers), then caching `registry volume` as GitHub cache. 
After each run, just prune cache local registry to keep small as possible.

However, I'm not sure about GitHub service container is able to create volume for service container and your GitHub action support that (because I'm only see caching `inline` option)

**Comment by malobre** [comment]
https://github.com/docker/buildx/pull/535 will fix this and make using cache a breeze:
```yml
[...]

      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: user/app:latest
          cache-from: type=gha
          cache-to: type=gha
```

**Comment by zero88** [comment]
I used it for caching
https://github.com/zero88/gh-registry/blob/main/README.md#usage

**Comment by rafis** [comment]
@malobre how to fix this?

moby/buildkit:buildx-stable-1 => buildkitd github.com/moby/buildkit v0.8.3 81c2cbd8a418918d62b71e347a00034189eea455

```
error: failed to solve: rpc error: code = Unknown desc = unknown cache exporter: "gha"
102
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = unknown cache exporter: "gha"
```

```
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true
```

**Comment by malobre** [comment]
Server side is in progress: https://github.com/moby/buildkit/pull/1974

**Comment by jauderho** [comment]
FWIW, there's a syntax error in the code block below. There is a missing "|" that took me a while to find and correct. 

This should be the correct invocation:

>       - name: Move cache
>         run: |
>           rm -rf /tmp/.buildx-cache
>           mv /tmp/.buildx-cache-new /tmp/.buildx-cache





> 
> 
> @MarcelCoding
> 
> > The cache can grow very quickly with large images, since old entries are not deleted.
> 
> Yes you're right atm caches are copied over the existing cache so it keeps growing. Can you open an issue on [buildkit repo](https://github.com/moby/buildkit) about that please? In the meantime you can do this:
> 
> ```yaml
> 
> [...]
> 
>       - name: Move cache
>         run:
>           rm -rf /tmp/.buildx-cache
>           mv /tmp/.buildx-cache-new /tmp/.buildx-cache
> ```
> 
> cc. @tonistiigi

**Comment by crazy-max** [comment]
@jauderho https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache

**Comment by ahgraber** [comment]
Given that moby/buildkit#1974 was just merged, what does the timeline look like to use cache `type=gha` in build-push-action?

**Comment by crazy-max** [comment]
You can test the gha cache exporter using [this workflow](https://github.com/docker/build-push-action/pull/406#issuecomment-879184394) while waiting for  buildx 0.6 and BuildKit 0.9 to be GA.

**Comment by jauderho** [comment]
I just tried this out on one of my workflows. See https://github.com/jauderho/dockerfiles/actions/workflows/cloudflared.yml

Looks like the "Setup Buildx" step now takes longer but I'm assuming that's due to the rest not yet being merged in. More importantly, the "Build and push" step looks to be much faster.

Nice job!

**Comment by crazy-max** [comment]
@jauderho 

> Looks like the "Setup Buildx" step now takes longer but I'm assuming that's due to the rest not yet being merged in. More importantly, the "Build and push" step looks to be much faster.

Yes that's it, buildx is built on-fly atm, that's why it takes more time for the setup step.

**Comment by jauderho** [comment]
Awesome. Looking forward to everything being merged in.

**Comment by crazy-max** [comment]
@jauderho 

> Looks like the "Setup Buildx" step now takes longer

Buildx [0.6.0-rc1](https://github.com/docker/buildx/releases/tag/v0.6.0-rc1) has been released. I've updated [the workflow](https://github.com/docker/build-push-action/pull/406#issuecomment-879184394) to use it so now it should be faster than building from source.

**Comment by jauderho** [comment]
Hmm, not sure if I am doing something wrong here but after updating to call buildx 0.6.0-rc1, it does not seem to trigger the caching.

Here is my action: https://github.com/jauderho/dockerfiles/blob/main/.github/workflows/cloudflared.yml

With buildx 0.6.0-rc1

- First build (40m, uncached but expected) https://github.com/jauderho/dockerfiles/actions/runs/1034517548
- Second build (should show as cached in logs but looks like it is rebuilding from scratch) https://github.com/jauderho/dockerfiles/actions/runs/1034655356

Compare this to 2 days ago (which has the expected behavior)

- First build (34m, uncached but expected) https://github.com/jauderho/dockerfiles/actions/runs/1027888442
- Second build (2m, cached) https://github.com/jauderho/dockerfiles/actions/runs/1027997222

**Comment by crazy-max** [comment]
@jauderho 

Use `image=moby/buildkit:master` instead of `image=moby/buildkit:v0.9.0-rc1`.

**Comment by jauderho** [comment]
@crazy-max 

Per your suggestion, updated to use image=moby/buildkit:master but it does not appear to make a difference.

* First build (31m) https://github.com/jauderho/dockerfiles/actions/runs/1035009487
* Second build () https://github.com/jauderho/dockerfiles/actions/runs/1035310379

**Comment by crazy-max** [comment]
@jauderho 

As you're on a monorepo building multi Docker images with different context, you should use a specific `scope` for each one of them to avoid cache collision/invalidation. For example in your [cloudflared workflow](https://github.com/jauderho/dockerfiles/blob/4dde16ecd5056d658465707b3466fb856ac4e6c0/.github/workflows/cloudflared.yml#L72-L73):

```yaml
cache-from: type=gha,scope=cloudflared
cache-to: type=gha,scope=cloudflared
```

**Comment by jauderho** [comment]
I decided to use the workflow name for the scope and it appears to work nicely.

`cache-from: type=gha, scope=${{ github.workflow }}`
` cache-to: type=gha, scope=${{ github.workflow }}`

It's blazing fast now @ 44s!

https://github.com/jauderho/dockerfiles/actions/runs/1035582157

**Comment by jauderho** [comment]
@crazy-max 

Now that new buildkit and buildx are released, can I revert back to just 

>         uses: docker/setup-buildx-action@v1
>         with:
>           version: v0.6.0-rc1
>           driver-opts: image=moby/buildkit:master
>           buildkitd-flags: --debug

Or do I switch to 

>         uses: docker/setup-buildx-action@v1
>         with:
>           version: v0.6.0
>           driver-opts: image=moby/buildkit:v0.9.0

**Comment by crazy-max** [comment]
@jauderho [GitHub virtual environments](https://github.com/actions/virtual-environments) don't have buildx 0.6.0 ([0.5.1 atm](https://github.com/docker/build-push-action/runs/3096831142?check_suite_focus=true#step:5:4)) so you have to explicitly specify buildx version in your workflow. On the other hand [BuildKit default image](https://github.com/docker/buildx/blob/ab09846df70df822fd32b9d0c715dc0605344618/driver/bkimage/bkimage.go#L4) is up to date (0.9.0) so the following step should be enough:

```yaml
    uses: docker/setup-buildx-action@v1
    with:
      version: v0.6.0
```

**Comment by fearphage** [comment]
FYI this has been [updated](https://github.com/docker/build-push-action/runs/3193075170?check_suite_focus=true#step:5:4), buildx 0.6.0 is in the images now.

**Comment by ksurl** [comment]
does this mean I can remove my step for cache setup and just use:

```
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Prepare docker image name
        id: image_names
        run: |
          IMAGES="${GITHUB_REPOSITORY/docker-/},ghcr.io/${GITHUB_REPOSITORY/docker-/}"
          echo ::set-output name=images::${IMAGES}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.image_names.outputs.images }}
          tags: |
            type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      #- name: Set up build cache
        #uses: actions/cache@v2
        #with:
          #path: /tmp/.buildx-cache
          #key: ${{ runner.os }}-buildx-${{ github.sha }}
          #restore-keys: |
            #${{ runner.os }}-buildx-

      - name: Login to GitHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #cache-from: type=local,src=/tmp/.buildx-cache
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          #cache-to: type=local,dest=/tmp/.buildx-cache
```

**Comment by jauderho** [comment]
@ksurl 

That's correct.

**Comment by ksurl** [comment]
works great. this can be closed probably

**Comment by crazy-max** [comment]
> works great. this can be closed probably

This issue is about the `local` cache so we keep it opened until moby/buildkit/issues/1896 is fixed. Thanks.

**Comment by hritvikpatel4** [comment]
Can someone tell me what I am doing wrong here?
My builds started failing suddenly

```yaml
name: Apache Atlas Docker Image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: apache-atlas

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/Dockerfile.ubuntu
            image: ghcr.io/hritvikpatel4/apache-atlas
            tag: ubuntu-bionic
          - dockerfile: ./docker/Dockerfile.centos
            image: ghcr.io/hritvikpatel4/apache-atlas
            tag: centos7
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=1073741824
        
      # - name: Log in to Docker Hub
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to the GitHub container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: hritvikpatel4
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: type=raw,value=${{ matrix.tag }}
          # images: |
          #   ntwine/${{ env.IMAGE_NAME }}
          #   ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

https://github.com/hritvikpatel4/apache-atlas-docker/actions/runs/2515089533 (FAILED build log)
