### ISSUE TITLE
Pushing to GitHub Container Registry fails with insufficient_scope: authorization failed

### ISSUE THREAD

**Issue by chadsugithub** [docker/build-push-action#254]
### Troubleshooting

Before sumbitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. Create a new GitHub repo.
2. Clone the new repo.
3. Unzip the attached hello-world.zip to the new repo.
4. [Enable GitHub Container Registry](https://docs.github.com/en/free-pro-team@latest/packages/guides/enabling-improved-container-support).
5. Generate a new PAT with all the scopes enabled (unnecessary, could be just those packages related scopes).
6. Create a new repo secret "CR_PAT" of which value is the generated PAT.
7. Push the files to GitHub and it will trigger the workflow.

#### Expected behaviour

The Docker image should be pushed to GitHub.

#### Actual behaviour

buildx call failed with: failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed

### Configuration

* Repository URL (if public): https://github.com/chadsugithub/hello-world
* Build URL (if public): https://github.com/chadsugithub/hello-world/actions/runs/424079714

```yml
name: Docker - Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Client
        file: ./Client/Docker/Dockerfile.linux
        tags: ${{ github.repository_owner }}/hello:linux-x64
        push: true
```

### Logs
[hello-world.zip](https://github.com/docker/build-push-action/files/5698432/hello-world.zip)

[logs.zip](https://github.com/docker/build-push-action/files/5698428/logs.zip)
