### ISSUE TITLE
Unauthorized push with the docker-container driver

### ISSUE THREAD

**Issue by juherr** [docker/build-push-action#258]
Hi,
I think the issue is maybe not related to build-push-action but I don't know where it is.

### Troubleshooting
I'm using `Sonatype Nexus Repository Manager OSS 3.27.0-03` as the Docker registry.
When I use the `docker` driver, the push is working.
When I use the `docker-container` driver, the push is unauthorized.

### Working configuration

```yml
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ${{ env.DOCKER_REGISTRY }}/<name>:latest
            ${{ env.DOCKER_REGISTRY }}/<name>:${{ steps.tag-version.outputs.version }}
          #push: true
          load: true
      - name: Push docker image on Nexus Repository
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/<name>:latest
          docker push ${{ env.DOCKER_REGISTRY }}/<name>:${{ steps.tag-version.outputs.version }}
```

### Debug configuration

```yml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v1
      - name: Deploy docker image on Nexus Repository
        uses: docker/build-push-action@v2
        with:
          context: .
          #push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ${{ env.DOCKER_REGISTRY }}/<name>:latest
            ${{ env.DOCKER_REGISTRY }}/<name>:${{ steps.tag-version.outputs.version }}
          outputs: type=oci,dest=/tmp/image.tar

      - name: Import image in containerd
        run: |
          sudo ctr i import --base-name ${{ env.DOCKER_REGISTRY }}/<name> --digests --all-platforms /tmp/image.tar
      - name: Push image with containerd
        run: |
          sudo ctr --debug i push --user "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" ${{ env.DOCKER_REGISTRY }}/<name>:latest
          sudo ctr --debug i push --user "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" ${{ env.DOCKER_REGISTRY }}/<name>:${{ steps.tag-version.outputs.version }}
```

### Debug logs

```
...
time="2020-12-18T08:24:26Z" level=debug msg=push digest="sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1" mediatype=application/vnd.oci.image.config.v1+json size=6134
time="2020-12-18T08:24:26Z" level=debug msg="checking and pushing to" digest="sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1" mediatype=application/vnd.oci.image.config.v1+json size=6134 url="https://<registry>/v2/<name>/blobs/sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1"
time="2020-12-18T08:24:26Z" level=debug msg="do request" digest="sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1" mediatype=application/vnd.oci.image.config.v1+json request.header.accept="application/vnd.oci.image.config.v1+json, */*" request.header.user-agent=containerd/1.3.9+azure request.method=HEAD size=6134 url="https://<registry>/v2/<name>/blobs/sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1"
...
time="2020-12-18T08:24:27Z" level=debug msg="fetch response received" digest="sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1" mediatype=application/vnd.oci.image.config.v1+json response.header.accept-ranges=bytes response.header.connection=keep-alive response.header.content-length=113 response.header.content-security-policy="sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation" response.header.content-type=application/json response.header.date="Fri, 18 Dec 2020 08:24:27 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.server=nginx/1.17.10 response.header.www-authenticate="BASIC realm=\"Sonatype Nexus Repository Manager\"" response.header.x-content-type-options=nosniff response.header.x-xss-protection="1; mode=block" response.status="401 Unauthorized" size=6134 url="https://<registry>/v2/<name>/blobs/sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1"
time="2020-12-18T08:24:27Z" level=debug msg=Unauthorized digest="sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1" header="BASIC realm=\"Sonatype Nexus Repository Manager\"" mediatype=application/vnd.oci.image.config.v1+json size=6134
time="2020-12-18T08:24:27Z" level=debug msg="do request" digest="sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1" mediatype=application/vnd.oci.image.config.v1+json request.header.accept="application/vnd.oci.image.config.v1+json, */*" request.header.user-agent=containerd/1.3.9+azure request.method=HEAD size=6134 url="<registry>/v2/<name>/blobs/sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1"
...
time="2020-12-18T08:24:27Z" level=debug msg="fetch response received" digest="sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1" mediatype=application/vnd.oci.image.config.v1+json response.header.connection=keep-alive response.header.date="Fri, 18 Dec 2020 08:24:27 GMT" response.header.server=nginx/1.17.10 response.header.www-authenticate="BASIC realm=\"Sonatype Nexus Repository Manager\"" response.header.x-content-type-options=nosniff response.status="401 Unauthorized" size=6134 url="https://<registry>/v2/<name>/blobs/sha256:fbbf16cf7f08b0bc1bd2f49c58aca6c707f4dc782b5987b454428876bd3f3dd1"
...
```

**Comment by crazy-max** [comment]
@juherr Can you post the failing workflow and logs too please? Thanks.

**Comment by juherr** [comment]
### Failing configuration

```yml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      - name: Deploy docker image on Nexus Repository
        # TODO replace by jib-maven-plugin
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ${{ env.DOCKER_REGISTRY }}/<name>:latest
            ${{ env.DOCKER_REGISTRY }}/<name>:${{ steps.tag-version.outputs.version }}
```

### Failing logs

```
#7 exporting to image
#7 exporting layers
#7 exporting layers 6.8s done
#7 exporting manifest sha256:0e3fd26444cf254d8bd2bfbb6f5c92b39a14bd73e6c9d2218d1a0fdc55921ca1 0.0s done
#7 exporting config sha256:6fb501aaefdb7ef09847cbc6125744254ff8be1b4439c2b7d11fe41d0e41cb3b done
#7 pushing layers
#7 pushing layers 6.4s done
#7 pushing manifest for <registry>/<name>:<version>
#7 pushing manifest for <registry>/<name>:<version> 0.3s done
#7 pushing layers 0.4s done
#7 pushing manifest for <registry>/<name>:latest
#7 pushing manifest for <registry>/<name>:latest 0.2s done
#7 ERROR: failed commit on ref "manifest-sha256:0e3fd26444cf254d8bd2bfbb6f5c92b39a14bd73e6c9d2218d1a0fdc55921ca1": unexpected status: 400 Bad Request
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = failed commit on ref "manifest-sha256:0e3fd26444cf254d8bd2bfbb6f5c92b39a14bd73e6c9d2218d1a0fdc55921ca1": unexpected status: 400 Bad Request
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed commit on ref "manifest-sha256:0e3fd26444cf254d8bd2bfbb6f5c92b39a14bd73e6c9d2218d1a0fdc55921ca1": unexpected status: 400 Bad Request
```

**Comment by crazy-max** [comment]
@juherr Looks linked to docker/buildx#457. Have you tried to push with buildx locally?

**Comment by juherr** [comment]
No, I didn't. 

To be honest, I was just using buildx because of https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md#auto-push-is-currently-not-implemented-for-docker-driver but I've never used buildx locally before.

But what surprised me is the `400 Bad Request` from the containerd push.

**Comment by crazy-max** [comment]
Ok can you try with the latest stable release of buildx please? (v0.5.1 atm):

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          buildkitd-flags: --debug
```

And another test with `docker` driver:

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          driver: docker
```
