### ISSUE TITLE
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory Error

### ISSUE THREAD

**Issue by GoodGuyMarco** [docker/build-push-action#26]
My job:

```
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Build and push docker image
                uses: docker/build-push-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    dockerfile: Dockerfile
                    repository: my/repository
                    tag_with_ref: true
```

What am I missing here? Dockerfile lives in my repositoryies root.

**Comment by danielivert** [comment]
Hello @GoodGuyMarco, you need to checkout your code before running the action. Try doing this:

```
build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            -   name: Build and push docker image
                uses: docker/build-push-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    dockerfile: Dockerfile
                    repository: my/repository
                    tag_with_ref: true
```
