### ISSUE TITLE
failed to read dockerfile

### ISSUE THREAD

**Issue by ionutvilie** [docker/build-push-action#264]
### Behaviour

when using custom docker file names the action fails . 

```
buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount967127233/build.Dockerfile: no such file or directory
```

#### Steps to reproduce this issue

when the value of the file key is set to `./Dockerfile` it works when is set to `./build.Dockerfile` it fails. 

#### Expected behaviour

The action should be able to use a custom file name `./build.Dockerfile`

#### Actual behaviour

> buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount967127233/build.Dockerfile: no such file or directory

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Env Values
        run: |
          git_commit_short=$(git rev-parse --short HEAD)
          echo "GIT_COMMIT_SHORT=$git_commit_short" >> $GITHUB_ENV
          git_url=$(git config --get remote.origin.url | sed "s/git@//g;s/\.git//g;s/:/\//g")
          echo "GIT_URL=$git_url" >> $GITHUB_ENV
          git_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "GIT_BRANCH=$git_branch" >> $GITHUB_ENV
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SDK_REPO_SSH_KEY }}
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm install
      - run: npm run build-dev

      # v2 works with 3 new actions (login, setup-buildx and setup-qemu)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_HOST }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ env.DOCKER_REGISTRY_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY_HOST }}/${{ env.DOCKER_REGISTRY_PROJECT }}/${{ env.APP }}:latest
            ${{ env.DOCKER_REGISTRY_HOST }}/${{ env.DOCKER_REGISTRY_PROJECT }}/${{ env.APP }}:${{ env.GIT_COMMIT_SHORT }}
          build-args: |
            SDK_SSH_KEY=${{ env.SDK_SSH_KEY }}
            VCS_REF=${{ env.GIT_COMMIT_SHORT }}
            VCS_URL=${{ env.GIT_URL }}
            VCS_BRANCH=${{ env.GIT_BRANCH }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Save Configuration
        run: |
          printf "{ \"image\" : { \"name\" : \"%s\", \"tag\" : \"%s\"}, \"action\" : \"%s\"}" \
          "${{ env.DOCKER_REGISTRY_HOST }}/${{ env.DOCKER_REGISTRY_PROJECT }}/${{ env.APP }}" \
          "${{ env.GIT_COMMIT_SHORT }}" \
          "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" \
          > data.json && cat data.json

      - name: "Upload Build Data Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: build-data
          path: ${{ env.PROJCT_BUILD_DATA }}
          retention-days: 5
```

### Logs

```bash
Run docker/build-push-action@v2
  with:
    context: .
    file: ./build.Dockerfile
    push: true
    tags: ***/dev/opsdash:latest
  ***/dev/opsdash:4b1ee15
  
    build-args: SDK_SSH_KEY=***
  
  VCS_REF=4b1ee15
  VCS_URL=
  VCS_BRANCH=build-pipeline
  
    pull: false
    no-cache: false
    load: false
    github-token: ***
  env:
    APP: opsdash
    DOCKER_FILE: ./build.Dockerfile
    DOCKER_REGISTRY_PROJECT: dev
    DOCKER_REGISTRY_HOST: ***
    DOCKER_REGISTRY_PASS: ***
    DOCKER_REGISTRY_USER: ***
    SDK_SSH_KEY: ***
  
    PROJCT_BUILD_DATA: data.json
    GIT_COMMIT_SHORT: 4b1ee15
    GIT_URL: ...
    GIT_BRANCH: build-pipeline
📣 Buildx version: 0.4.2
🏃 Starting build...
/usr/bin/docker buildx build --build-arg SDK_SSH_KEY=*** --build-arg VCS_REF=4b1ee15 --build-arg VCS_URL=... --build-arg VCS_BRANCH=build-pipeline --tag ***/dev/opsdash:latest --tag ***/dev/opsdash:4b1ee15 --iidfile /tmp/docker-build-push-fwPjdv/iidfile --file ./build.Dockerfile --push .
time="2020-12-24T08:08:17Z" level=warning msg="invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: "
#1 [internal] load build definition from build.Dockerfile
#1 transferring dockerfile: 0.0s
#1 transferring dockerfile: 2B 0.0s done
#1 DONE 0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount967127233/build.Dockerfile: no such file or directory
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount967127233/build.Dockerfile: no such file or directory
```
