### ISSUE TITLE
Hang on the "pushing layers" step

### ISSUE THREAD

**Issue by uptownhr** [docker/build-push-action#265]
### Behaviour
Pushing layers step goes on forever and does not complete.

#### Steps to reproduce this issue

1. Goto https://github.com/Penguin-Web-Services/lovio-api/runs/1606612128?check_suite_focus=true
2. Review logs line 278
3. Notice how it does not progress

#### Expected behaviour

> I'd expect given the exporting layers is about 22.7s, the pushing of layers to take maybe 1 min and finish.

#### Actual behaviour

> Get's stuck on this step and hangs. Waited over 10 minutes.

### Configuration

* Repository URL (if public): https://github.com/Penguin-Web-Services/lovio-api
* Build URL (if public): https://github.com/Penguin-Web-Services/lovio-api/runs/1606646666?check_suite_focus=true

```yml
name: Publish Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_dockerfile:
    name: run docker build for Production
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: docker.pkg.github.com/penguin-web-services/lovio-api/api
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: testing
        run: echo ${{ github.repository_owner }}
      - name: testing tags
        run: echo ${{ steps.docker_meta.outputs.tags }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

```

### Logs

> I am still waiting on the job to finish / fail, before being able  to download logs. But this is where it gets stuck

```
#20 exporting to image
#20 exporting layers
#20 exporting layers 21.1s done
#20 exporting manifest sha256:b9d2e72babca3466483c298b29c291952d53368c3d77ebff0e21f5cc880b063b done
#20 exporting config sha256:20713dcebd728dea7ef65de99c3eb2f77479dc7872d503a0869a8ccca359b427 done
#20 pushing layers
```
