### ISSUE TITLE
Feature Request: Ability to check for existing image via manifest and retag

### ISSUE THREAD

**Issue by AnthonyWC** [docker/build-push-action#27]
This GHA is a good start; I'd like to suggest for the ability to check for existing docker image on the registry without downloading or building a local image by directing using docker registry API.

This is especially useful when doing a CI/CD workflow where you promote non-master to master; so there isn't an actual need to rebuild docker image but simply re-tag existing docker image.

**Comment by AnthonyWC** [comment]
A typical workflow maybe where image is promoted via a PR, so you would build image in any non-master branch, then you'd tag it with branch name (for simplicity) and push that image to registry.

This image acts as your dev/test image; when when for production you'd create a PR to promote this image to master branch.  This is where the manifest check is useful as you'd just need to check for the existence of the non-master branch (as it has to already exist to get promoted); and you just retag also via the API with the manifest.

I know this works at least for dockerhub as the registry backend.

**Comment by davidkarlsen** [comment]
Another usecase is that the image is built (and tested) during CI, so the last step is simply to tag and push to another registry.

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

This new version should fix your issue using the `cache-from` and `cache-to` [inputs](https://github.com/docker/build-push-action#inputs):

```yaml
jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: user/app:latest
          cache-from: type=registry,ref=user/app
          cache-to: type=inline
```

Don't hesitate if you have any questions.
