### ISSUE TITLE
How to can I tag a container without a push?

### ISSUE THREAD

**Issue by Zimtir** [docker/build-push-action#270]
As developer, I want to make a GitHub Action that can build a docker image when a new PR was provided without the push to a container registry.
I want to execute a Docker build and use the local build in other steps by tag.

Flow:

- Build image
- Tag image

Example of the failed flow:

https://github.com/Zimtir/SENT-template/runs/1674324645?check_suite_focus=true

**Comment by crazy-max** [comment]
@Zimtir You can use conditional value in your workflow like:

```yaml
      - name: build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: 9e3u2f0b1/sent-template:latest
          file: ./docker/web/Dockerfile.production
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          context: .
```
