### ISSUE TITLE
unknown blob error on push

### ISSUE THREAD

**Issue by r-s-sandbox** [docker/build-push-action#271]
### Behaviour
I am using v2 build push action and have started noticing intermittent failures during docker push with an unknown blob error.

Here is part of the job:
```yml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: docker.pkg.github.com/${{ github.repository }}/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
```

### Logs

```bash
1a4f5de7f684: Layer already exists
13545bbbc98b: Layer already exists
c67dd3decb62: Layer already exists
unknown blob
Error: exit status 1
Usage:
exit status 1
  github-actions build-push [flags]

Flags:
  -h, --help   help for build-push
```
