### ISSUE TITLE
Run `dpkg --print-architecture` some times get failure.

### ISSUE THREAD

**Issue by gsmlg** [docker/build-push-action#275]
### Troubleshooting

```log
 > [linux/amd64 6/8] RUN ARCH=`dpkg --print-architecture`   curl -sSfLo kubectl "https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/${ARCH}/kubectl"   && chmod +x kubectl   && sudo mv kubectl /usr/local/bin/kubectl:
------
Dockerfile:27
--------------------
  26 |     # install kubectl
  27 | >>> RUN ARCH=`dpkg --print-architecture` \
  28 | >>>   curl -sSfLo kubectl "https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/${ARCH}/kubectl" \
  29 | >>>   && chmod +x kubectl \
  30 | >>>   && sudo mv kubectl /usr/local/bin/kubectl
  31 |     
--------------------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c ARCH=`dpkg --print-architecture`   curl -sSfLo kubectl "https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/${ARCH}/kubectl"   && chmod +x kubectl   && sudo mv kubectl /usr/local/bin/kubectl]: exit code: 22
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c ARCH=`dpkg --print-architecture`   curl -sSfLo kubectl "https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/${ARCH}/kubectl"   && chmod +x kubectl   && sudo mv kubectl /usr/local/bin/kubectl]: exit code: 22
```

### Behaviour

Runing `dpkg --print-architecture` some times get a failure.

#### Steps to reproduce this issue

My docker file:

```dockerfile
FROM docker.io/gsmlg/code-server:v3.8.0

ENV container=docker
ENV LC_ALL=C

# update package list
RUN sudo apt-get update && sudo apt-get upgrade -y

# install useful packages
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
  git \
  gnupg \
  lsb-release \
  silversearcher-ag \
  tzdata \
  vim

# install nodejs
RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo bash - && \
  sudo apt-get install -y -qq nodejs && \
  sudo npm install -g yarn

# install golang
RUN sudo apt-get install -y -qq golang

# install kubectl
RUN ARCH=`dpkg --print-architecture` \
  curl -sSfLo kubectl "https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/${ARCH}/kubectl" \
  && chmod +x kubectl \
  && sudo mv kubectl /usr/local/bin/kubectl

# install skaffold
RUN ARCH=`dpkg --print-architecture` \
  curl -sSfLo skaffold "https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-${ARCH}" \
  && chmod +x skaffold \
  && sudo mv skaffold /usr/local/bin/skaffold

# clean cache install
RUN sudo rm -rf /var/cache/* && sudo rm -rf /tmp/*
```

Github action:

```yaml
name: docker-buildimage-editor-server

on:
  push:
    branches: master
    paths:
      - "docker/editor-server/**"
      - ".github/workflows/docker-buildimage-editor-server.yml"

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/editor-server/
          file: docker/editor-server//Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: docker.io/gsmlg/editor-server:latest
```

#### Expected behaviour

It should success build image

#### Actual behaviour

Sometimes fail with `failed to solve: rpc error: code = Unknown desc = executor failed running . code 22 `

### Configuration

* Repository URL (if public): 

[repo](https://github.com/gsmlg/Foundation/blob/master/.github/workflows/docker-buildimage-editor-server.yml)

* Build URL (if public): 

[action link](https://github.com/gsmlg/Foundation/runs/1706889727?check_suite_focus=true)

```yml
name: docker-buildimage-editor-server

on:
  push:
    branches: master
    paths:
      - "docker/editor-server/**"
      - ".github/workflows/docker-buildimage-editor-server.yml"

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/editor-server/
          file: docker/editor-server//Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: docker.io/gsmlg/editor-server:latest
```

### Logs

>  [logs_91.zip](https://github.com/docker/build-push-action/files/5830597/logs_91.zip)
