### ISSUE TITLE
Use branch name in tag

### ISSUE THREAD

**Issue by splitbrain** [docker/build-push-action#276]
### Behaviour

I'm trying to use the branch name to tag the resulting Docker image, but that seems not to work for some reason. It's as if the variable isn't expanded? I'm not sure sure if I'm doing it wrong or if this is a bug.

#### Steps to reproduce this issue

I'm trying to use ``${GITHUB_REF##*/}`` in the docker tag name

#### Expected behaviour

The above is run on push to a branch named `docker`. I would expect it to build `splitbrain/dokuwiki:docker`

#### Actual behaviour

The action fails with `buildx call failed with: error: invalid tag "splitbrain/dokuwiki:${GITHUB_REF##*/}": invalid reference format`

### Configuration

* Repository URL:  https://github.com/splitbrain/dokuwiki/tree/docker/docker
* Build URL: https://github.com/splitbrain/dokuwiki/runs/1723345686

```yml
name: Publish Docker image
on:
    push:
        branches: [ master, stable, docker ]
jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v2
            -
                name: What
                run: echo splitbrain/dokuwiki:${GITHUB_REF##*/}
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: splitbrain
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    context: ./docker
                    file: ./docker/Dockerfile
                    platforms: linux/amd64,linux/arm64,linux/386
                    push: true
                    tags: splitbrain/dokuwiki:${GITHUB_REF##*/}
                    build-args: |
                        BRANCH=${GITHUB_REF##*/}
```

### Logs

[logs_1084.zip](https://github.com/docker/build-push-action/files/5831915/logs_1084.zip)

**Comment by crazy-max** [comment]
@splitbrain 

[`run:`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun) runs command-line programs using the operating system's shell. In your case `bash` on `ubuntu-latest`.

[`with:`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith) is a map of the input parameters defined by the action so can't interpret shell.

So what you can do in your case is:

```yaml
name: Publish Docker image
on:
    push:
        branches: [ master, stable, docker ]
jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v2
            -
                name: What
                run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: splitbrain
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    context: ./docker
                    file: ./docker/Dockerfile
                    platforms: linux/amd64,linux/arm64,linux/386
                    push: true
                    tags: splitbrain/dokuwiki:${{ env.BRANCH }}
                    build-args: |
                        BRANCH=${{ env.BRANCH }}
```

More info https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

**Comment by splitbrain** [comment]
Ahh, I knew I was missing something here. Thanks a lot.

**Comment by karoonp** [comment]
If you follow 'Publishing Docker images' doc
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

make sure you have this tags input in the Extract metadata step

```
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
```
