### ISSUE TITLE
Unable to install with apk - executor failed running / failed to solve / rpc error

### ISSUE THREAD

**Issue by troykelly** [docker/build-push-action#279]
#### Steps to reproduce this issue

1. Create a `Dockerfile` that contains
```text
RUN apk --no-cache add vlc
```
2. Allow the Dockerfile to pass through `build-push-action` for `linux/arm/v6`
3. Watch the failure

#### Expected behaviour

1. vlc should install

#### Actual behaviour

```text
 > [linux/arm/v6 2/5] RUN apk --no-cache add vlc:
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apk --no-cache add vlc]: exit code: 1
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apk --no-cache add vlc]: exit code: 1
```

### Configuration

* Repository URL (if public): https://github.com/aperim/docker-vlc-multicast
* Build URL (if public): https://github.com/aperim/docker-vlc-multicast/runs/1739541490?check_suite_focus=true

```yml
name: ci

on:
  release:
    types: [published]

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prepare
        run: |
          VERSION=edge

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi

          if [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=${GITHUB_REF##*/}
          fi

          echo ::set-output name=version::${VERSION}
          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CI_PAT }}
      -
        name: Build web and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
          # platforms: linux/amd64
          push: true
          build-args: |
              VERSION=${{ steps.prepare.outputs.version }}
              BUILD_DATE=${{ steps.prepare.outputs.build_date }}
              VCS_REF=${GITHUB_SHA::8}
          tags: |
            aperimau/vlc-multicast:${{ steps.prepare.outputs.version }}
            aperimau/vlc-multicast:latest
            ghcr.io/aperim/vlc-multicast:${{ steps.prepare.outputs.version }}
            ghcr.io/aperim/vlc-multicast:latest
```

### Logs

```text
 > [linux/arm/v6 2/5] RUN apk --no-cache add vlc:
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apk --no-cache add vlc]: exit code: 1
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apk --no-cache add vlc]: exit code: 1
```
