### ISSUE TITLE
Execute permission not preserved when COPYed to scratch container

### ISSUE THREAD

**Issue by deefdragon** [docker/build-push-action#280]
## Behaviour
I am working with a scratch container (Not actually scratch. I have a base container that has the certs loaded into it, but is basically scratch), and in said container I copy in the binary executable (main)

Before copying it in, in a previous step, I set permissions to 777 or +x using chmod. Upon running build-push, the file in the container that gets uploaded only has the permissions `-rw-r--r--` (checked using dive)

**When built locally** using docker build, the permissions are the expected `-rwxrwxrwx`

I am currently changing it via the --chmod trigger in ADD, but it still feels like this permissions change is an issue that needs to be addressed.

### Steps to reproduce this issue (in the job)

1. compile an executable
2. set permissions of executable to 777
3. build-push using following file

```
FROM scratch
COPY main /
CMD ["/main"]
```

### Expected behaviour
After the file is added to the binary, it has the permissions needed to execute
### Actual behaviour

`  Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/main": permission denied: unknown` gotten when attempting to use the container due to permissions set as `-rw-r--r--` (checked via dive)

## Configuration

```yml
        #Relavent sections included only
      - name: Archive api binary
        uses: actions/download-artifact@v2
        with:
          name: api.binary
          path: cmd/api/main

      - name: Update permissions of executable
        run: chmod 777 cmd/api/main

      - name: print file info.
        run: ls cmd/api/ -al

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: <registry>/api:latest
          context: ./cmd/api
          file: ./cmd/api/dockerfile
```

## Logs
[job.log](https://github.com/docker/build-push-action/files/5847008/job.log)
