### ISSUE TITLE
Docker build cannot get proper context

### ISSUE THREAD

**Issue by mariusmitrofan** [docker/build-push-action#281]
Repository URL = https://github.com/Rungutan/sentry-performance-monitoring

Current pipeline:

```
name: ci

on:
  push:
    branches: deployment-automation

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Build and push Sentry Base image
        id: docker_build_sentry_basse
        uses: docker/build-push-action@v2
        with:
          context: ./docker/sentry
          file: ./docker/sentry/Dockerfile
          no-cache: true
          push: true
          tags: |
            rungutancommunity/sentry-base:latest
            public.ecr.aws/x7u7j5v7/sentry-base:latest
```

Problem:

```
📣 Buildx version: 0.4.2
🏃 Starting build...
/usr/bin/docker buildx build --tag rungutancommunity/sentry-base:latest --tag public.ecr.aws/x7u7j5v7/sentry-base:latest --iidfile /tmp/docker-build-push-E2XUU3/iidfile --file ./docker/sentry/Dockerfile --no-cache --push ./docker/sentry
time="2021-01-23T10:21:05Z" level=warning msg="invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: "
unable to prepare context: path "./docker/sentry" not found
Error: buildx call failed with: unable to prepare context: path "./docker/sentry" not found
```

And the docker context should not be an issue because:

```
.
├── docker
│   ├── bash
│   │   └── Dockerfile
│   ├── clickhouse-client
│   │   └── Dockerfile
│   ├── relay
│   │   ├── Dockerfile
│   │   └── docker-alt-entrypoint.sh
│   ├── sentry
│   │   ├── Dockerfile
│   │   └── sentry.conf.py
│   └── snuba
│       └── Dockerfile
```

So...what's actually going on ... ?
