### ISSUE TITLE
Push to multiple, non Docker Hub, failing → reverts to docker hub for the second one

### ISSUE THREAD

**Issue by Gompje** [docker/build-push-action#285]
### Troubleshooting
I'm not using the Docker Hub, but Digital Ocean & Github Packages. 

At first I was getting the dreaded 503 alerts from DO b/c I was testing a lot (moving over from Gitlab+k8s). Remembering how DO can act up sometimes - I wanted to be sure it was DO and not my image creating. Turned out to be both.. 
but to be to the point: I wanted to have a fall back and the idea of having 2 versions of the same container in different registries sounded awesome → one with the code for me and me team have access to and one to be deployed.

Therefore I wanted to use the multitag/push option. (or how do you call it). 

### Behaviour

When using multiple tag/push to at least 2 different registries, same tag. once, the second push always seems to go to `registry-1.docker.io` no matter what is put first/last. 

→ when using just one (either in my case) pushing works as expected

#### Steps to reproduce this issue
1. use the multi tag option like this
```
    - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            registry.digitalocean.com/${{ steps.docker_meta.outputs.tags }}
            ghcr.io/${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
```
2. observe somehow the second push sends it to `registry-1.docker.io`
3. use only one of them → works

### notes
can someone please confirm this? I admit I'm a bit short on sleep and this was driving me crazy, like I'm seeing ghosts. I can live with the one push option. and I'm more than happy to help debug this.

**Comment by crazy-max** [comment]
@Gompje

I would need the entire workflow and logs to help you on this. Thanks.

Also `${{ steps.docker_meta.outputs.tags }}` is a list of tags with the registry and repo path included. Not only tags. See https://github.com/crazy-max/ghaction-docker-meta/runs/1794286074?check_suite_focus=true#step:3:27 as an example.

**Comment by Gompje** [comment]
@crazy-max 

this what that ${{ ...outputs.tags }} contains:
```
  daktadeo/multipass-rocks:develop
  daktadeo/multipass-rocks:sha-cd00d42
```
I'm not setting the registry there, I'm doing that before the tagging like in the snippet.

The rest of the workflow is irrelevant in the way that it is just building the project, composer update, yarn and things like that. I will see if I can get the complete output log from the relevant steps.. just a minute

**Comment by crazy-max** [comment]
Can you post the entire worklow anyway? I think the issue in your workflow is with the docker meta step not properly defined.

**Comment by Gompje** [comment]
[workflow.log](https://github.com/docker/build-push-action/files/5896441/workflow.log)

is this enough? I took the log from the build stage, and removed the container building log itself + artifact downloading/ and just a whole lot of base64 and progress bars. 

this is what I find strange:
```
2021-01-29T20:39:12.9400608Z #66 [auth] daktadeo/multipass-rocks:pull,push token for registry-1.docker.io
2021-01-29T20:39:12.9402023Z #66 sha256:76c78fd6eb459ee3a01aef398d578ab6972adf0eb3a3d1d385c882f2c3c5963d
2021-01-29T20:39:12.9403049Z #66 DONE 0.0s
2021-01-29T20:39:12.9403316Z 
```

**Comment by Gompje** [comment]
Oh! I see now, I forgot a crucial bit: this is the step for the meta:

```
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
           images: daktadeo/multipass-rocks # list of Docker images to use as base name for tags
           tag-sha: true # add git short SHA as Docker tag
```
that must have been confusing, I'm sorry! :)

**Comment by crazy-max** [comment]
Ok so if you want to handle multi registries you should use something like this:

```yaml
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
           images: |
             registry.digitalocean.com/daktadeo/multipass-rocks
             ghcr.io/daktadeo/multipass-rocks
           tag-sha: true

...

    - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
```
