### ISSUE TITLE
How to specify branch that triggered the CI Pipe

### ISSUE THREAD

**Issue by pschmidtke** [docker/build-push-action#289]
### Troubleshooting

Before sumbitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. Set up a trigger on specific branch in ci.yml such as : 
2. Run the CI Pipe
3. Fails to run on the correct dockerfile from the correct branch (is using master instead)

#### Expected behaviour

> Tell us what should happen

Same as other github actions I'd expect this to use the currently checked out branch for the docker build and push.

#### Actual behaviour

> Tell us what happens instead

In the build and push step, it's building from the master branch instead of my selected branch.

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: build_and_push_release
on:
  push:
    branches: [ hotfix-x ]
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
     -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ${{matrix.registry}}/${{matrix.namespace}}/${{matrix.targetenv}}:citest
#${{steps.tag.outputs.tag}}
```

### Logs
How can I specify which branch to use? I tried with: ref: ${{ github.ref}} already, not working as well.
