### ISSUE TITLE
Support secret file mount

### ISSUE THREAD

**Issue by ngraef** [docker/build-push-action#293]
The action currently supports `secrets` which are string values that the action writes to temporary files behind the scenes. It would be nice to be able to mount a secret file that already exists on disk, passing the arguments through to the builder's `--secret` option.

For example, say I construct a `.npmrc` file earlier in the workflow and want to mount it as a secret in order to pull from a private registry in the Dockerfile:

```yaml
env:
  NPM_REGISTRY: myorg.jfrog.io/myorg/api/npm/npm/

jobs:
  build:
    # ...
    steps:
      # ...

      # This could also be encapsulated as an action. Either way, a .npmrc file is generated.
      - name: NPM auth
        run: |
          cat <<EOF > "$HOME/.npmrc"
          @myorg:registry=https://$NPM_REGISTRY
          //$NPM_REGISTRY:_password=$(echo -n "${{ secrets.NPM_PASSWORD }}" | openssl base64)
          //$NPM_REGISTRY:username=${{ secrets.NPM_USER }}
          //$NPM_REGISTRY:email=${{ secrets.NPM_EMAIL }}
          //$NPM_REGISTRY:always-auth=true
          EOF

      - name: Install NPM dependencies
        run: npm ci

      # ... Testing and checks using the installed node modules

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          secrets: npmrc=$HOME/.npmrc  # <-- This writes the string "$HOME/.npmrc" as file contents. Not what we want.
```

With the current version of this action, I have to either read in the file and store it as env/output in a previous step or store the full contents of the file as a GitHub secret:

```yaml
secrets: |
  "npmrc=${{ secrets.JFROG_NPMRC }}"
```

Storing the different variables and dynamically constructing the file is more convenient because I don't have to regenerate the file every time the credentials are rotated.

Secret file mounts could be supported with a new input:

```yaml
secret-files: npmrc=$HOME/.npmrc
```

or a special syntax in the `secrets` input:

``` yaml
secrets: file:npmrc=$HOME/.npmrc
```

**Comment by crazy-max** [comment]
@ngraef 

> `secrets: npmrc=$HOME/.npmrc  # <-- This writes the string "$HOME/.npmrc" as file contents. Not what we want.`

Action inputs don't support/expand shell. You have to use the `env` def: `${{ env.HOME }}/.npmrc`

> With the current version of this action, I have to either read in the file and store it as env/output in a previous step or store the full contents of the file as a GitHub secret

Ok if you want to expose the content of this file I think you can use `GITHUB_ENV` for this purpose:

```yaml
env:
  NPM_REGISTRY: myorg.jfrog.io/myorg/api/npm/npm/

jobs:
  build:
    # ...
    steps:
      # ...

      # This could also be encapsulated as an action. Either way, a .npmrc file is generated.
      - name: NPM auth
        run: |
          cat <<EOF > "$HOME/.npmrc"
          @myorg:registry=https://$NPM_REGISTRY
          //$NPM_REGISTRY:_password=$(echo -n "${{ secrets.NPM_PASSWORD }}" | openssl base64)
          //$NPM_REGISTRY:username=${{ secrets.NPM_USER }}
          //$NPM_REGISTRY:email=${{ secrets.NPM_EMAIL }}
          //$NPM_REGISTRY:always-auth=true
          EOF
          echo "npmrc=$(cat $HOME/.npmrc)" >> $GITHUB_ENV

      - name: Install NPM dependencies
        run: npm ci

      # ... Testing and checks using the installed node modules

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          secrets: npmrc=${{ env.npmrc }}
```

**Comment by ngraef** [comment]
> Action inputs don't support/expand shell. You have to use the `env` def: `${{ env.HOME }}/.npmrc`

Good point 👍. I was thinking `"$HOME/.npmrc"` would get passed through and `exec` would take care of expanding it.

>  I think you can use `GITHUB_ENV` for this purpose

I'd rather not have the npmrc floating around in env.

**Comment by crazy-max** [comment]
@ngraef 

> I'd rather not have the npmrc floating around in env.

Agree, that was just a quick fix. Will think about a proper way to handle that.

**Comment by vorant94** [comment]
i saw support for secret files was implemented, but I can't quite make it work... can somebody please help what am i doing wrong?

here is the Dockerfile
```dockerfile
FROM node:18-alpine
WORKDIR /usr/local/app

COPY package*.json ./
RUN --mount=type=secret,id=npmrc,target=/usr/local/app/.npmrc \
    npm ci

COPY . .
RUN npm run build:ssr

EXPOSE 4000
CMD ["npm", "run", "serve:ssr"]
```

and here is the GitHub workflow (i'm copying npmrc instead of creating one from scratch in order to keep custom registry config for scoped packages in the repo). in the logs it says `Warning: secret file $HOME/.npmrc not found`
```yml
name: Build Docker image

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate NPM
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > $HOME/.npmrc
          cat .npmrc >> $HOME/.npmrc

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: vorant94-io/api:latest
          secret-files: |
            npmrc=$HOME/.npmrc
```

**Comment by crazy-max** [comment]
@vorant94 This works as well:

```yaml
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: vorant94-io/api:latest
          secret-files: |
            npmrc=${{ env.HOME }}/.npmrc
```

**Comment by vorant94** [comment]
@crazy-max for some reason for me it does't work... just tried and still got warning of "secret file not found", but anyway thanks

**Comment by askalski85** [comment]
For anyone struggling as I did, here is how to make it work
```
- uses: docker/build-push-action@v5
  with:
    tags: myimagetag:1.2.3
    secret-files: |
      netrc=${{ runner.home }}/.netrc
```

netrc is the id you will use inside of your docker recipe like:
```
RUN --mount=type=secret,id=netrc,dst=/root/.netrc 
```

What will not work:
- adding quotes to the file path or around the whole statement `netrc=${{ runner.home }}/.netrc` will cause error for some reason
- using bash variables directly, like `$HOME` will not work as bash variables will not be expanded, bad example: `netrc=$HOME/.netrc`
- using `${{ env.HOME }}` won't work, use `${{ runner.home }}` instead, bad example: `netrc=${{ env.HOME }}/.netrc`
- the regular docker syntax `id=netrc,src=${{ env.NETRC_FILE }}` won't work

Please correct me if I am wrong. And I hope this will help someone in future.
Cheers!
