### ISSUE TITLE
multistage dockerfile fails to load from one stage to another

### ISSUE THREAD

**Issue by deitch** [docker/build-push-action#294]
### Behaviour

A multistage build - in this case on an alternate runner - is failing to copy a file from one stage to another. The error is:

```
------
166
 > [linux/arm64 runner 1/2] COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt:
167
------
168
Dockerfile:26
169
--------------------
170
  24 |     ARG OS=linux
171
  25 |     
172
  26 | >>> COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
173
  27 |     COPY --from=build /go/src/app/dist/bin/${BINARY}-${OS}-${TARGETARCH} ${BINARY}
174
  28 |     
175
--------------------
176
error: failed to solve: rpc error: code = Unknown desc = failed to compute cache key: "/etc/ssl/certs/ca-certificates.crt" not found: not found
177
```

Results should be available [here](https://github.com/equinix/cloud-provider-equinix-metal/runs/1886356502?check_suite_focus=true)

The yaml is [here](https://github.com/equinix/cloud-provider-equinix-metal/blob/master/.github/workflows/release.yaml), relevant parts below::

```yaml
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ format('{0}:{1}', env.IMAGE_NAME, steps.tagname.outputs.tag) }}
          ${{ format('{0}:{1}', env.IMAGE_NAME, 'latest') }}
```

Dockerfile is pretty straightforward [here](https://github.com/equinix/cloud-provider-equinix-metal/blob/master/Dockerfile), relevant parts below:

```dockerfile
root@nginx-7848d4b86f-kmjnf:/# %                                                                                                                                                                         FROM alpine:3.11 as certs

RUN apk --update add ca-certificates

# builder
# lots of other stuff

# Create Docker image of just the binary
FROM scratch as runner

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
```

The stage it is copying from is basically just getting certs, and then copying it to a `scratch` image.

#### Steps to reproduce this issue

I have not been able yet to reproduce it outside of the above repo. So far it has happened only on the linux/arm64 build.

#### Expected behaviour

> Tell us what should happen

It should build.

#### Actual behaviour

> Tell us what happens instead

It fails

### Configuration

* Repository URL (if public):  https://github.com/equinix/cloud-provider-equinix-metal/
* Build URL (if public):  https://github.com/equinix/cloud-provider-equinix-metal/runs/1886356502?check_suite_focus=true

yam is [here](https://github.com/equinix/cloud-provider-equinix-metal/blob/master/.github/workflows/release.yaml), relevant part below.

```yml
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ format('{0}:{1}', env.IMAGE_NAME, steps.tagname.outputs.tag) }}
          ${{ format('{0}:{1}', env.IMAGE_NAME, 'latest') }}

```

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

[logs_219.zip](https://github.com/docker/build-push-action/files/5971159/logs_219.zip)

I am rerunning the jobs, in case it is transient, but even if it is, we should know.
