### ISSUE TITLE
Multiple platforms feature is not supported

### ISSUE THREAD

**Issue by samip5** [docker/build-push-action#302]
#### Steps to reproduce this issue

1. Use the action and specify multiple platforms.
2. It fails

#### Expected behaviour

It should run.

#### Actual behaviour

The action fails.

### Configuration

* Repository URL (if public):  https://github.com/samip5/archlinux-docker
* Build URL (if public): https://github.com/samip5/archlinux-docker/actions/runs/585114776/

```yml
on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Docker to use experimental mode.
        run: sudo cp daemon.json /etc/docker/daemon.json && sudo systemctl restart docker
      - name: Debug information
        run: |
         whoami
         id
         sudo docker info
      - name: Build minimal
        uses: docker/build-push-action@v2.3.0
        with:
         build-args: ARCH=arm32v6 ARCH=arm32v7 ARCH=amd64
         file: Dockerfile
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
         
      - name: Build with devel tools
        uses: docker/build-push-action@v2.3.0
        with:
         file: Dockerfile.devel
         build-args: ARCH=arm32v6 ARCH=arm32v7 ARCH=amd64
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
         
      - name: Build with devel and yay
        uses: docker/build-push-action@v2.3.0
        with:
         file: Dockerfile.devel-yay
         build-args: ARCH=arm32v6 ARCH=arm32v7 ARCH=amd64
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
```

### Logs

[logs_10.zip](https://github.com/docker/build-push-action/files/6016728/logs_10.zip)

**Comment by crazy-max** [comment]
@samip5 

`error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")`

You have to use our setup-buildx-action and setup-qemu-action actions to be able to build a multi-platform image. See https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

**Comment by samip5** [comment]
@crazy-max Unfortunately, that does not work either. That outputs the same error.

The workflow file:
```yml
name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          use: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
     # - name: Setup Docker to use experimental mode.
     #  run: sudo cp daemon.json /etc/docker/daemon.json && sudo systemctl restart docker
      - name: Debug information
        run: |
         whoami
         id
         sudo docker info
      - name: Build minimal
        uses: docker/build-push-action@v2.3.0
        with:
         build-args: ARCH=arm32v6 ARCH=arm32v7 ARCH=amd64
         file: Dockerfile
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
         
      - name: Build with devel tools
        uses: docker/build-push-action@v2.3.0
        with:
         file: Dockerfile.devel
         build-args: ARCH=arm32v6 ARCH=arm32v7 ARCH=amd64
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
         
      - name: Build with devel and yay
        uses: docker/build-push-action@v2.3.0
        with:
         file: Dockerfile.devel-yay
         build-args: ARCH=arm32v6 ARCH=arm32v7 ARCH=amd64
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
```
