### ISSUE TITLE
Obtuse error trying to upgrade v1 to v2

### ISSUE THREAD

**Issue by vadi2** [docker/build-push-action#306]
### Troubleshooting
I have no idea what this is talking about:

```
#2 [internal] load .dockerignore
#2 sha256:deaafd3c664fd3623a7b0c9655d8085709eb18ddcfb75210988c356e8089bf95
#2 transferring context: 2B done
#2 DONE 0.0s
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount710637985/Dockerfile: no such file or directory
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount710637985/Dockerfile: no such file or directory
```
https://github.com/Mudlet/mudlet-package-repo/runs/1986007445?check_suite_focus=true

#### Steps to reproduce this issue

1. Try to upgrade from v1 to v2 following steps
2. Regret
3.

#### Expected behaviour

> Tell us what should happen

#### Actual behaviour

> Tell us what happens instead

### Configuration

* Repository URL (if public):  https://github.com/Mudlet/mudlet-package-repo/pull/119/files
* Build URL (if public): 

```yml
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build image and push to Dockerhub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mudlet/mudlet-package-repo:latest
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
```

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
@vadi2 You're using the [Path context](https://github.com/docker/build-push-action/#path-context) but you don't checkout your code. What you miss is `actions/checkout@v2` step:

```yaml
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build image and push to Dockerhub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mudlet/mudlet-package-repo:latest
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
```

Please check the [Usage section](https://github.com/docker/build-push-action/#usage) in the README.
