### ISSUE TITLE
Unable to reserve cache with key ...

### ISSUE THREAD

**Issue by oittaa** [docker/build-push-action#308]
#### Steps to reproduce this issue

1. Create a build with caching and multiple architectures with the following guides https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache and https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
2. See that the caching fails. For example: see "Post Cache Docker layers" step at at https://github.com/oittaa/imagemagick-docker/runs/1988235197?check_suite_focus=true
3. "Unable to reserve cache with key Linux-build-x-f5704f2edff20f637074dfde721a5e106e64ffc6, another job may be creating this cache."

#### Expected behaviour

Caching should work

#### Actual behaviour

Caching failed

### Configuration

* Repository URL (if public): https://github.com/oittaa/imagemagick-docker/
* Build URL (if public): https://github.com/oittaa/imagemagick-docker/runs/1988235197?check_suite_focus=true

```yml
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-build-x-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-x-
      - name: Build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.arch }}
          context: ./build
          file: ./Dockerfile  
          push: false
          load: true
          tags: oittaa/imagemagick:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            CI=true
      - name: Tests
        run: ./test.sh

```

### Logs

[logs_8.zip](https://github.com/docker/build-push-action/files/6054898/logs_8.zip)
