### ISSUE TITLE
build-args non-functional for delivering more than one k/v set

### ISSUE THREAD

**Issue by gladiatr72** [docker/build-push-action#310]
### Troubleshooting

This is... odd that this has to be brought up with... well, you folks, but here goes...

 Currently `build-push-action@v2` key, _build-args_ requires a string.  Regardless of what `getInputList()` actually does, `--build-arg` does not configure more than a single key.   This is a known... non-issue that is addressable  with multiple iterations of `--build-arg` on the command line.

See [set-build-time-variables](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg) docs

#### Steps to reproduce this issue

1.  with a job step of
```
        -
          name: Build the Docker image
          uses: docker/build-push-action@v2

          with:
            push: true
            tags: gladiatr72/python:${{ env.PYTHON_VERSION }}
            build-args: PYTHON_VERSION=${{ env.PYTHON_VERSION}}\nBUILD_ARGS='--enable optimizations --with-lto'
```
The above syntax does not work.. was an attempt to follow the expectations of that field from the tests.

#### Expected behaviour

> 
> The action should correctly parse the build-arg string into an appropriate docker CLI invocation.
> `--build-arg KEYA=VALA --build-arg KEYB=KEYB`

#### Actual behaviour

> The  Docker documentation and the Internet insists trying to pass multiple arguments with a single `--build-arg` does not work and will never work.  As claimed by the aforementioned entities, multiple key/val sets must be injected with the same number of `--build-arg` flags.

### Configuration

* Repository URL (if public): gladiatr72/actions-test
* Build URL (if public):  https://github.com/gladiatr72/actions-test/actions/runs/611841318

```yml
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

    if-you-build-it:
      env:
        PYTHON_VERSION: "3.6.13"

      runs-on: ubuntu-latest

      steps:
        -
          uses: actions/checkout@v2
        -
          name: setup buildx
          uses: docker/setup-buildx-action@v1
        -
          name: login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        -
          name: Build the Docker image
          uses: docker/build-push-action@v2

          with:
            push: true
            tags: gladiatr72/python:${{ env.PYTHON_VERSION }}
            build-args: PYTHON_VERSION=${{ env.PYTHON_VERSION}}\nBUILD_ARGS='--enable optimizations --with-lto'
```

### Logs

[5_Build the Docker image.txt](https://github.com/docker/build-push-action/files/6064764/5_Build.the.Docker.image.txt)

**Comment by crazy-max** [comment]
@gladiatr72 Explained here: https://github.com/docker/build-push-action#inputs

```yaml
        -
          name: Build the Docker image
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: gladiatr72/python:${{ env.PYTHON_VERSION }}
            build-args: |
              PYTHON_VERSION=${{ env.PYTHON_VERSION}}
              BUILD_ARGS=--enable optimizations --with-lto
```
