### ISSUE TITLE
ARM64 missing from manifest from buildx builds

### ISSUE THREAD

**Issue by h1nk** [docker/build-push-action#314]
#### Steps to reproduce this issue

1. Run Docker Engine on a Raspberry Pi 3 Model B w/ Ubuntu 20.04.2 LTS
2. Build an image with platform set as either `linux/arm64` or `linux/arm64/v8`
3. Pull build image from registry

#### Expected behaviour

Image to be found in manifest from registry and pulled

#### Actual behaviour

```
# docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:19:31 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:17:22 2021
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
# docker pull ghcr.io/h1nk/test
Using default tag: latest
latest: Pulling from h1nk/test
no matching manifest for linux/arm64/v8 in the manifest list entries
```

```
# docker buildx imagetools inspect ghcr.io/h1nk/test
Name:      ghcr.io/h1nk/test:latest
MediaType: application/vnd.oci.image.index.v1+json
Digest:    sha256:e365268f1b84f96096d44368bf230b56d6774fd144322d4dfa9444b2ac95ef30
           
Manifests: 
  Name:      ghcr.io/h1nk/test:latest@sha256:884b2d34fdb6e43b9136f77ea2b494b5e3a5b9db13abab6f16348b122e25aa78
  MediaType: application/vnd.oci.image.layer.v1.tar+gzip
             
  Name:      ghcr.io/h1nk/test:latest@sha256:bfdf7b082edbc5a81770e6238c6d8cd6095e71de034eb89925785d9f6e0a607d
  MediaType: application/vnd.oci.image.layer.v1.tar+gzip
             
  Name:      ghcr.io/h1nk/test:latest@sha256:f8409535c0bd51c22b0c4fbc8be6bee041eaddee0b1ce1ffd48efc0aa656d38f
  MediaType: application/vnd.buildkit.cacheconfig.v0
```

### Configuration

* Repository URL (if public): https://github.com/h1nk/arm-docker-action-test
* Build URL (if public): https://github.com/users/h1nk/packages/container/package/test

```yml
name: CI

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git project
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Print available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      # See: https://github.com/docker/login-action#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Show builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Show available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64/v8
          push: true
          cache-to: type=registry,ref=ghcr.io/h1nk/test
          cache-from: type=registry,ref=ghcr.io/h1nk/test
          tags: ghcr.io/h1nk/test
      - name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```

### Logs

https://github.com/h1nk/arm-docker-action-test/runs/2047667885
