### ISSUE TITLE
Dockerfile with Multistage build stops at first stage

### ISSUE THREAD

**Issue by mvadu** [docker/build-push-action#315]
### Behaviour

- dockerfile: [dockerfile](https://github.com/AdysTech/mi_atc_reader/blob/eff6c8bdadd9eb85d7b23dd49e1a09ca04a7e931/Dockerfile) has one base setup, which is used by two subsequent stages. Per following the last example in the [dockerfile documentation](https://docs.docker.com/develop/develop-images/multistage-build/)

- github action : [build-multiplatform_image.yml](https://github.com/AdysTech/mi_atc_reader/blob/eff6c8bdadd9eb85d7b23dd49e1a09ca04a7e931/.github/workflows/build-multiplatform_image.yml)

#### Steps to reproduce this issue

1. Copy the docker file referenced above
2. trigger a build (or refer to build log at [here](https://github.com/AdysTech/mi_atc_reader/pull/4/checks?check_run_id=2063233005))

#### Expected behaviour

> there should be 19 steps, and it should build a base_image, then use it to run pytest, and finally use the baseimage package final image. intermediate image with pytest is discorded. 

#### Actual behaviour

> Only first 10 steps in the docker file are recognized, and the built image is incomplete.
Last step in the build log are 
```log
#14 [linux/arm/v7 base_setup  8/10] RUN cp py-bluetooth-utils/bluetooth_utils.py .
#14 sha256:0ee19688f05c72e3c1b5d1cb94e4c4beeda10d5feec00bd04f6d99ad77517a74
#14 DONE 0.2s

#16 [linux/arm/v7 base_setup  9/10] COPY config_default.yml config_default.yaml
#16 sha256:5452a2735121914fbe563055af2bfff611f834d4abe1c44bedd72097905c3f0a
#16 DONE 0.0s

#17 [linux/arm/v7 base_setup 10/10] COPY mi_atc_reader.py mi_atc_reader.py
#17 sha256:8fea35d8e8375d4420b654401522f31e19ec0791df9599d39405566c1d1ccbc7
#17 DONE 0.0s
```
### Configuration

* Repository URL (if public): https://github.com/AdysTech/mi_atc_reader/pull/4
* Build URL (if public): https://github.com/AdysTech/mi_atc_reader/pull/4/checks?check_run_id=2063233005

```yml
name: build-multiplatform-dockerimage
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  build_image:
    name: build a multi platform Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: false
            
```

### Logs

> 
[logs_3.zip](https://github.com/docker/build-push-action/files/6106124/logs_3.zip)

**Comment by crazy-max** [comment]
@mvadu Your multistage build is incorrect:

* `from` > `FROM`
* [This stage is skipped](https://github.com/AdysTech/mi_atc_reader/blob/eff6c8bdadd9eb85d7b23dd49e1a09ca04a7e931/Dockerfile#L15-L17) because not called or last stage

Not sure about the intention with your workflow but if you want to call [this stage](https://github.com/AdysTech/mi_atc_reader/blob/eff6c8bdadd9eb85d7b23dd49e1a09ca04a7e931/Dockerfile#L15-L17) and [this one](https://github.com/AdysTech/mi_atc_reader/blob/eff6c8bdadd9eb85d7b23dd49e1a09ca04a7e931/Dockerfile#L19-L27) you have to create 2 build-push-action steps and call the right stage (optional for the last one):

```Dockerfile
FROM python:3 AS base_setup

RUN apt-get install libbluetooth-dev
RUN pip install bluepy
RUN pip install pybluez
RUN pip install requests
RUN pip install dynaconf
RUN git clone https://github.com/mvadu/py-bluetooth-utils.git --depth=1
RUN cp py-bluetooth-utils/bluetooth_utils.py .

#copy the default config file
COPY config_default.yml config_default.yaml 
COPY mi_atc_reader.py mi_atc_reader.py

FROM base_setup AS second
RUN pip install pytest
RUN python -m pytest mi_atc_reader.py -rA

FROM base_setup AS third
LABEL "contact"="info@adystech.com"
LABEL repo="https://github.com/AdysTech/mi_atc_reader/"
LABEL version="1.0"
LABEL description="Provides a python script as a docker service  \
which can read BLE advertisements from Xiaomi Smart Bluetooth Thermometer & Hygrometer. \
Thermometers needs to be running custom open source firmware from pvvx or atc1441"
ENTRYPOINT python ./mi_atc_reader.py
#ENTRYPOINT /bin/bash
```

```yaml
name: build-multiplatform-dockerimage
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  build_image:
    name: build a multi platform Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build second
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: false
          target: second

    - name: Build third
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: false
          target: third
```
