### ISSUE TITLE
rpc error

### ISSUE THREAD

**Issue by fragaLY** [docker/build-push-action#316]
#### Steps to reproduce this issue

Run ci.

#### Expected behaviour

Docker image pushed.

#### Actual behaviour

Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c npm install --production]: exit code: 1

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: ci

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Preparation step
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      # Npm install
      - name: NPM installation
        run: npm install --only=prod --silent
      # Npm build
      - name: NPM building
        run: npm run build
      # Docker steps
      - name: Set up QEMU
        if: github.ref == 'refs/heads/develop'
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/develop'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/develop'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: EXAMPLE/EXAMPLE:latest
```
