### ISSUE TITLE
load sometimes doesn't load

### ISSUE THREAD

**Issue by champo** [docker/build-push-action#321]
### Behaviour

Trying to run a command with a just built image _sometimes_ fails to find the image:
```
 $ docker run --rm -t -v "${GITHUB_WORKSPACE}:/src/android/apolloui/build/outputs/" muun_android:latest
Unable to find image 'muun_android:latest' locally
docker: Error response from daemon: pull access denied for muun_android, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

The build step runs ok and has no notable differences in output between correct and failed runs.

#### Expected behaviour

The `muun_android` image to be found and run. In https://github.com/muun/apollo/runs/2203961523?check_suite_focus=true it succeded (see the Inspect step cause the build failed due to something unrelated)

### Configuration

* Repository URL (if public): https://github.com/muun/apollo
* Build URL (if public): https://github.com/muun/apollo/runs/2204358021?check_suite_focus=true

```yml
name: pr
on: pull_request
jobs:
  pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@154c24e1f33dbb5865a021c99f1318cfebf27b32
        with:
          buildkitd-flags: --debug

      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Build
        uses: docker/build-push-action@9379083e426e2e84abb80c8c091f5cdeb7d3fd7a
        with:
          load: true
          tags: muun_android:latest
          file: android/Dockerfile
          context: .

      - name: Inspect
        run: |
            docker images 
      - name: Build apollo
        run: |
          docker run --rm -t -v "${GITHUB_WORKSPACE}:/src/android/apolloui/build/outputs/" muun_android:latest
      - name: Upload APK
        uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571
        with:
          name: apk
          path: apk/prod/release/apolloui-prod-release-unsigned.apk
```

### Logs

[logs_8.zip](https://github.com/docker/build-push-action/files/6213799/logs_8.zip)

**Comment by benhjames** [comment]
This is happening to us too. It's super weird because we have three identical workflows set up (with different image names) - two of them succeed but one of them is constantly failing with the above error.

<details>
<summary>The workflow file:</summary>

```yml
name: Docker

on:
  push:
    # Publish `staging` as Docker `latest` image.
    branches:
      - staging

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: ml-intents

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # This is the a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # So now we can use GitHub actions' own caching for Docker layers!
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.IMAGE_NAME }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ env.IMAGE_NAME }}-

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: intents/Dockerfile
          load: true
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "staging" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          echo Listing docker images...
          docker image ls

          echo Tagging image...
          docker tag $IMAGE_NAME:latest $IMAGE_ID:$VERSION
          echo Tagged image successfully!

          echo Pushing image...
          docker push $IMAGE_ID:$VERSION
          echo Pushed image successfully!

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```
</details>

The runner gets to the `docker tag $IMAGE_NAME:latest $IMAGE_ID:$VERSION` line and errors out with `Error response from daemon: No such image: ml-intents:latest` as above. `docker image ls` does not list the built image either.

The two successful workflows have much smaller images (500Mb and 2Gb) whereas the failing image is a lot bigger (5Gb). Could that be an influencing factor here?

**Comment by crazy-max** [comment]
@champo @benhjames Cannot repro locally or [with GHA](https://github.com/crazy-max/buildx-bug/actions). Maybe it fails silently because of [insufficient disk space](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources):

> Each virtual machine has the same hardware resources available.
> * 2-core CPU
> * 7 GB of RAM memory
> * 14 GB of SSD disk space

You have at your disposal 14GB (actually I would say 9GB by removing the pre-installed middleware) on the runner:

```
/dev/sdb1        14G  4.1G  9.0G  32% /mnt
```

Can you add this step at the end of your workflow (before `Move cache` for you @benhjames) and give me the output:

```yaml
- name: Disk
  if: always()
  run: |
    df -h
    docker buildx du
```
