### ISSUE TITLE
[Compatibility Issue]  build push action v1.1.1 vs v2.0

### ISSUE THREAD

**Issue by ParthiBa** [docker/build-push-action#324]
### Troubleshooting
I am actually trying MS Learn exercise , where we are using github actions to create and deploy pods to Azure Kubernetes Service .   

[MS Learn URL](https://docs.microsoft.com/en-us/learn/modules/aks-deployment-pipeline-github-actions/7-exercise-build-production-image)
#### Steps to reproduce this issue

1. you will need github account and optionally you might need an azure account 
2. GIThub url is available in above exercise 
3.Follow that exercise , and upgrade build-push-action to v2.0 instead v1.1.1 .    Yaml files in that exerciese suggest us to use v1.1.1

#### Expected behaviour

> Build and push to registry should happen sucessfully
#### Actual behaviour

> Everthing passed , but images were absent in registry 

```yml
# paste your YAML workflow file here and remove sensitive data
# Below code is working
  uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_NAME }}

# Below code is not working 
uses: docker/build-push-action@v2.0
        with:
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_NAME }}

```

\

**Comment by crazy-max** [comment]
@ParthiBa 

Looking at the [example provided](https://docs.microsoft.com/en-us/learn/modules/aks-deployment-pipeline-github-actions/7-exercise-build-production-image):

```yaml
name: Build and push the tagged build to production

on:
  push:
    tags:
      - 'v*'

jobs:
  build_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push production image
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_NAME }}
          repository: contoso-website
          tag_with_ref: true
```

It can be done like this with v2:

```yaml
name: Build and push the tagged build to production

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ${{ secrets.ACR_NAME }}/contoso-website
      -
        name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
```
