### ISSUE TITLE
Working directory is not applying to docker/build-push-action@v2

### ISSUE THREAD

**Issue by dszymczuk** [docker/build-push-action#327]
### Troubleshooting

I saw that `docker/build-push-action@v2` is not applying a **working-directory** setup.
Here is my GitHub action file:

```yaml
name: Push docker images

on:
  push:

defaults:
  run:
    working-directory: ./api # here I setup working directory for flow

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Build Docker Image - API
        uses: docker/build-push-action@v2
        with:
          file: dockerfiles/api/Dockerfile
          context: .
          push: false
          tags: myimage:latest
```

#### Expected behaviour

Build image without error

#### Actual behaviour

```
/usr/bin/docker buildx build --tag myimage:latest --iidfile /tmp/docker-build-push-ed2Vyp/iidfile --file dockerfiles/api/Dockerfile .

error: could not find dockerfiles/api: stat dockerfiles/api: no such file or directory
Error: buildx call failed with: error: could not find dockerfiles/api: stat dockerfiles/api: no such file or directory
```

#### Fix

To fix this I have to pass `file` and `context` as path from root. In this case is:
```yaml
name: Push docker images

on:
  push:

defaults:
  run:
    working-directory: ./api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REPOSITORY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Build Docker Image - API
        uses: docker/build-push-action@v2
        with:
          file: api/dockerfiles/api/Dockerfile
          context: ./api
          push: false
          tags: myimage:latest
```

With this fix I can build my image.
