### ISSUE TITLE
Feature request: Timestamp based tag

### ISSUE THREAD

**Issue by assapir** [docker/build-push-action#33]
I would like to have some time stamp based tag - built in. Can be done using `(date +%s)` or similar.
I could try to contribute it myself, but I couldn't find out where the actual script that run :(

**Comment by BerriJ** [comment]
+1 for this!

**Comment by jayhendren** [comment]
@crazy-max Do you have any info/docs on how to add a timestamp tag?  I couldn't find anything in the existing docs.

**Comment by crazy-max** [comment]
@jayhendren Using [`{{date '<format>'}}` global expression](https://github.com/docker/metadata-action#date-format) with the [`raw` type](https://github.com/docker/metadata-action#typeraw) tag in [metadata-action](https://github.com/docker/metadata-action) like:

```yaml
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
