### ISSUE TITLE
Create tag version and latest

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [docker/build-push-action#330]
Hi, 
I would like to know if it's possible to have a behavior like this:
When someone pushes on master, GithubActions will push docker with `:latest`
When someone creates a new tag of the library,  GithubActions will push docker with the exact tag generated.

Is it possible to have these behaviors?

**Comment by crazy-max** [comment]
@AlessandroMinoccheri Sure with something like that using the [meta action](https://github.com/crazy-max/ghaction-docker-meta):

```yaml
name: ci

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: name/app
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, 'master') }}
            type=ref,event=tag
          flavor: |
            latest=false
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
