### ISSUE TITLE
Error response from daemon: No such image: moby/buildkit:buildx-stable-1

### ISSUE THREAD

**Issue by thiagomeireless** [docker/build-push-action#332]
### Behaviour

With no changes to the build process, today we started receiving an error when trying to build the image using this action. Error ocurred 3 times in a row.

`Error: buildx call failed with: error: Error response from daemon: No such image: moby/buildkit:buildx-stable-1`

#### Steps to reproduce this issue

1. `docker pull moby/buildkit:buildx-stable-1`

#### Expected behaviour

Build the image without errors

#### Actual behaviour

An error ocurred while trying to use the image `moby/buildkit:buildx-stable-1`

### Configuration

```yml
on:
  push

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      ECR_REGISTRY: "***.dkr.ecr.us-east-1.amazonaws.com"

    steps:
      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Docker layers
        id: cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_REGISTRY }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            ENVIRONMENT=Test
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          target: production
          tags: ${{ env.ECR_REGISTRY }}/ims-test:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

### Logs
[logs_85.zip](https://github.com/docker/build-push-action/files/6253361/logs_85.zip)
