### ISSUE TITLE
Git context always checks out the branch tip

### ISSUE THREAD

**Issue by hanazuki** [docker/build-push-action#336]
### Behaviour

Using Git context with the default settings, build-push-action always checks out the branch tip regardless the commit for which the workflow run is triggered.
This causes confusing Actions results when multiple commits are pushed successively to the same branch or when Actions workflow for some old commit is triggered to re-run.

Expected fix is to make build-push-action check out $GITHUB_SHA instead of $GITHUB_REF.

#### Steps to reproduce this issue

1. Push a commit with a Dockerfile and the following GitHub actions job definition.
2. Push another commit with a modified Dockerfile to the same branch.
3. Rerun the Actions workflow for the first commit.

#### Expected behaviour

Step 3 should build image using Dockerfile from Step 1.

#### Actual behaviour

Step 3 uses Dockerfile from Step 2.

### Configuration

* Repository URL (if public): https://github.com/hanazuki/build-push-action-test
* Build URL (if public): https://github.com/hanazuki/build-push-action-test/actions/runs/721615893

This repository has two commits: the [good commit](https://github.com/hanazuki/build-push-action-test/commit/6cdb58acd28c0ec14f5f365ba0789932c674abe0) and [bad commit](https://github.com/hanazuki/build-push-action-test/commit/637e0c54cee1fb6b7b0294732fd88ffc86829596). The bad commit is now the tip of the master branch.
The good commit has a Dockerfile that builds successfully while the bad commit has a Dockerfile that fails to build.

During the Actions job for the good commit, restarted after the bad commit is pushed to the branch, build-push-action checks out the bad commit. For that reason, CI for good commit fails.

```yml
name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
```

### Logs

[logs_3.zip](https://github.com/docker/build-push-action/files/6262732/logs_3.zip)

**Comment by hanazuki** [comment]
A workaround is to specify context URI with commit SHA. But I'm not sure this works for all the event types.

```yaml
    - uses: docker/build-push-action@v2
      with:
        context: ${{github.server_url}}/${{github.repository}}.git#${{github.sha}}
        secrets: |
          GIT_AUTH_TOKEN=${{github.token}}
```
