### ISSUE TITLE
Get https://ghrc.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by disapointmntPanda** [docker/build-push-action#340]
I am using github actions to build and push my images to github registry.

This is my deploy file,

```
name: Build and Push

on:
  push:
    branches:
      - develop

jobs:

 
  build_and_push_to_github_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: dev
          tags: ghrc.io/ownerin/customer-service-backend:${{ github.sha }}
```

*Here owner is in captinal like `OwnerIN` but tags doesn't support capital letter so I am using `ownerin`*

But when job is run I get below error. Build is successful, error occures on push step.

```
...
pushing ghrc.io/ownerin/customer-service-backend:0679931b537b724ca21e6ef53178d4bf0725b4b5 with docker:
error: Get https://ghrc.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: buildx call failed with: error: Get https://ghrc.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I followed the docs and repo descibed [here][1]

  [1]: https://github.com/docker/build-push-action/blob/master/docs/advanced/push-multi-registries.md
