### ISSUE TITLE
volume mount

### ISSUE THREAD

**Issue by hiaselhans** [docker/build-push-action#343]
### Troubleshooting

In order to keep the image layer size small i'd like to mount a runner directory in the container.
I tried to add `build-args: -v ./mnt:/root` but still see the huge file created in the image...

Is that something that can be done with build-push@v2?

#### Steps to reproduce this issue

```
      - name: create mountpoint
        run: mkdir mnt
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/user/package:latest
          build-args: -v ./mnt:/root
```

```
VOLUME /root
RUN mkdir test
RUN touch test/test1
RUN touch test/test2
RUN fallocate -l 1G test/largefile.img

RUN tar -cf /root/large_dir.tar -C test .
```

#### Expected behaviour

/root should be a mounted directory
