### ISSUE TITLE
How to set the cache when using a build matrix?

### ISSUE THREAD

**Issue by eitsupi** [docker/build-push-action#351]
Thank you for providing this very useful action.

#### Steps to reproduce this issue

I'm using a build matrix to run two builds in parallel and using GitHub cache.

#### Expected behaviour

Both builds use cache.

#### Actual behaviour

Cache seems to be working on only one side and not the other.

![image](https://user-images.githubusercontent.com/50911393/117459812-c45f7200-af86-11eb-8666-013c4e98fb13.png)

### Configuration

* Repository URL : https://github.com/eitsupi/r-ver
* Build URL : https://github.com/eitsupi/r-ver/actions/runs/819626997

```yml
name: Docker build and push

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "main"
      - "fix/workflow"
    tags:
      - v*
    paths:
      - "dockerfiles/**"
      - "scripts/**"
      - ".github/workflows/docker-build-push.yml"
      - "buildargs.json"
  pull_request:

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Automated update') && !contains(github.event.head_commit.message, 'CI ignore')"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          content=$(jq -r 'tostring' buildargs.json)
          echo "::set-output name=matrix::$content"
          echo $content
  echo_matrix:
    needs: generate_matrix
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.generate_matrix.outputs.matrix }}"
          echo "${{fromJson(needs.generate_matrix.outputs.matrix)}}"
  build_and_push:
    needs: generate_matrix
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push builder
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/builder:${{ matrix.r_version }}
          build-args: |
            VARIANT=${{ matrix.r_version }}
            CRAN_URL=${{ matrix.cran }}
          file: dockerfiles/builder.Dockerfile
          target: builder
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=A Docker image of R version ${{ matrix.r_version }}
            org.opencontainers.image.title=${{ github.repository }}/builder:${{ matrix.r_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Build and push r-ver
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:${{ matrix.r_version }}
          build-args: |
            VARIANT=${{ matrix.r_version }}
            CRAN_URL=${{ matrix.cran }}
          file: dockerfiles/builder.Dockerfile
          target: r-ver
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=A Docker image of R version ${{ matrix.r_version }}
            org.opencontainers.image.title=${{ github.repository }}:${{ matrix.r_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

### Logs

[logs_72.zip](https://github.com/docker/build-push-action/files/6442012/logs_72.zip)

**Comment by crazy-max** [comment]
@eitsupi You can change the `Cache Docker layers` step by specifying a better fingerprint for the key using a matrix attribute like:

```
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.r_version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.r_version }}-
            ${{ runner.os }}-buildx-
```
