### ISSUE TITLE
buildx call failed with: error: denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by lucasmaj** [docker/build-push-action#363]
I am just getting started with GitHub actions. Trying to build and push a container to ghcr.io as following
```
-
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/Protocol/Dockerfile
        push: true
        tags: user/app:latest
```

but I am getting error "buildx call failed with: error: denied: requested access to the resource is denied". What am I doing wrong?

I tried to following https://github.com/marketplace/actions/docker-login (animated gif section) but I can't find how to get there.

Pulling hair out.
