### ISSUE TITLE
Getting 403 Forbidden when trying to push to github packages

### ISSUE THREAD

**Issue by KiqoCode** [docker/build-push-action#366]
Hi,

I have the following action yml setup:

```
name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64
          tags: |
            docker.pkg.github.com/twisted-inc/go-host/go-host:latest
```

Build works fine but push fails with 403 Forbidden, any ideas?
