### ISSUE TITLE
Question: list vs YAML array for imputes 

### ISSUE THREAD

**Issue by tpolekhin** [docker/build-push-action#367]
Hello!
I was wondering why use multi-line string `list` instead of YAML array for inputs?
Maybe it's a technical limitation and it's okay if so I just wanted to check.

I'm trying to pass build args to the docker build with meta information and having difficulties because of this `list` type.
https://github.com/docker/metadata-action provides an easy way to inject meta labels for the container,
exporting a `list` of OCI labels that you can then use for `labels:` input. I guess they used a `list` type for their output to match this action input type.

I'm trying to reuse some of them as build args to also inject this information into the app binary:
```
      - name: Prepare image metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: repo/app

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDTIME=${{ steps.meta.outputs.labels['org.opencontainers.image.created'] }}
            VERSION=${{ steps.meta.outputs.labels['org.opencontainers.image.version'] }}
            REVISION=${{ steps.meta.outputs.labels['org.opencontainers.image.revision'] }}
```

I think it would be more convenient to work with JSON/YAML Arrays, just because there's a lot more supported tooling and operations than for just a list of strings.

Curious to get your opinion on this

**Comment by crazy-max** [comment]
@tpolekhin 

> I was wondering why use multi-line string list instead of YAML array for inputs?
> Maybe it's a technical limitation and it's okay if so I just wanted to check.

This is a limitation with the GitHub Actions toolkit itself yes (actions/toolkit#184).

> I guess they used a `list` type for their output to match this action input type.

The separator used by the metadata action for `tags` or `labels` output is lf (`\n`).

> I'm trying to reuse some of them as build args to also inject this information into the app binary, but it doesn't work because `steps.meta.outputs.labels` is not an array.

We could output labels, tags and other info using a JSON representation with a new output for this purpose:

```json
{
  "tags": [
    "name/app:1.2.3",
    "name/app:1.2",
    "name/app:sha-90dd603",
    "name/app:latest"
  ],
  "labels": {
    "org.opencontainers.image.title": "Hello-World",
    "org.opencontainers.image.description": "This your first repo!",
    "org.opencontainers.image.url": "https://github.com/octocat/Hello-World",
    "org.opencontainers.image.source": "https://github.com/octocat/Hello-World",
    "org.opencontainers.image.version": "1.2.3",
    "org.opencontainers.image.created": "2020-01-10T00:30:00.000Z",
    "org.opencontainers.image.revision": "90dd6032fac8bda1b6c4436a2e65de27961ed071",
    "org.opencontainers.image.licenses": "MIT"
  }
}
```

This way you could use the [`fromJSON` function](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson) expression to handle that:

```yaml
      - name: Prepare image metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: repo/app

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
```

**Comment by tpolekhin** [comment]
Thank you for a quick response on that!
Currently I use workaround, pretty similar to what you proposed actually :)
```
      - name: Extract meta image labels
        id: extract
        run: echo ::set-output name=labels::$(jq -r -c '.target."docker-metadata-action".labels' ${{ steps.meta.outputs.bake-file }})

      - name: Build and push operator image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDTIME=${{ fromJSON(steps.extract.outputs.labels)['org.opencontainers.image.created'] }}
            VERSION=${{ fromJSON(steps.extract.outputs.labels)['org.opencontainers.image.version'] }}
            REVISION=${{ fromJSON(steps.extract.outputs.labels)['org.opencontainers.image.revision'] }}
```

I would definitely appreciate if you can add json format output so I can throw away this intermediate step
