### ISSUE TITLE
build-arg not support multiline variable

### ISSUE THREAD

**Issue by k0st1an** [docker/build-push-action#374]
### Troubleshooting

I need to save a multiline variable to a file. But the result is a file with only one line. `secrets.DEPLOY_KEY` - multiline variable.

```
      - name: Build SCM container image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            VAULT_PASSWORD=${{ secrets.ANSIBLE_VAULT_PASSWORD }}
            PRIVATE_KEY=${{ secrets.DEPLOY_KEY }}
```

Dockerfile: 

```
ARG VAULT_PASSWORD
ARG PRIVATE_KEY
ENV PASSWORD $VAULT_PASSWORD
ENV KEY $PRIVATE_KEY
...
RUN echo "$PASSWORD" > /etc/vault.txt && \
    chmod 0600 /etc/vault.txt
RUN echo "$KEY" > /root/.ssh/id_rsa && \
    chmod 0600 /root/.ssh/id_rsa
```

![image](https://user-images.githubusercontent.com/426513/120068104-b2ee1f00-c087-11eb-9e80-f8fac95ef2c7.png)

#### Expected behaviour

```
cat /root/.ssh/id_rsa
-----BEGIN OPENSSH PRIVATE KEY-----
...
...
```

#### Actual behaviour

```
cat /root/.ssh/id_rsa
-----BEGIN OPENSSH PRIVATE KEY-----
```

One line only.

### PS

Working version if done manually: https://github.com/concourse/docker-image-resource/issues/79#issuecomment-259812953

**Comment by mindflayer** [comment]
I've just had the same problem. At the moment I fixed pointing to `uses: docker/build-push-action@v2.4.0`.

**Comment by crazy-max** [comment]
@k0st1an Like [secrets](https://github.com/docker/build-push-action/blob/master/docs/advanced/secrets.md#secrets), you need to place the key-value pair between quotes:

```yaml
      - name: Build SCM container image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            "VAULT_PASSWORD=${{ secrets.ANSIBLE_VAULT_PASSWORD }}"
            "PRIVATE_KEY=${{ secrets.DEPLOY_KEY }}"
```
