### ISSUE TITLE
Not caching node_modules

### ISSUE THREAD

**Issue by GeminiousDrigon** [docker/build-push-action#376]
#### Steps to reproduce this issue
I am testing our monorepo project for building our image in github actions. I tried to use the actions and tested for docker layer caching node_modules and next js builds. It seems that docker is not using the node_modules cache or the next js build cache. 

1. Tried to push updates. the build went successful and at this point the docker-push-action exported the cache successfully. I used the local cache and also moved the cache for the next build.
2. Tried to push new updates to check if it is using cache. note: I did not changes anything on the next js code I only updated the README.md in the frontend directory. I did not changes anything that will affect the next js app. At this point it should use the cache for node_modules and the next js build. but I found out that it did not use the cache.
3. Tried to push updates on backend directory (no changes on frontend directory). docker-push-action uses the cache just like it should.

### Configuration

* [Repository URL](https://github.com/GeminiousDrigon/first-kube)
* [Initial Build URL ](https://github.com/GeminiousDrigon/first-kube/actions/runs/897994670)
* [Cache Test Build URL ](https://github.com/GeminiousDrigon/first-kube/actions/runs/898023116)
* [Backend only changes Build URL ](https://github.com/GeminiousDrigon/first-kube/actions/runs/898037513) this works just fine.

# Workflow yaml
```
name: Build Frontend

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-kube-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: geminiousdrigon/first-kube-front:1.0.01
          cache-from: type=local,src=/tmp/.buildx-kube-cache
          cache-to: type=local,dest=/tmp/.buildx-kube-cache-new
      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-kube-cache
          mv /tmp/.buildx-kube-cache-new /tmp/.buildx-kube-cache
          

  no-cache-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          no-cache: true
          tags: geminiousdrigon/first-kube-front:1.0.01
          
```

I'm new here, I'm just testing things out.. I hope you guys will help me.. Thanks.

**Comment by hankei6km** [comment]
I am having a hard time with the same behavior.

This behavior seems to be caused by various factors.
The simplest cause is multi-stage behavior.


"docker build" cache only final stage layers.
Therefore, `deps` `builder` stages has not been caches when just builds final stage.

If you want to cache `deps` `builder` stages, use "target" in build job.


ie.
```
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: geminiousdrigon/first-kube-front:1.0.01
          cache-from: type=local,src=/tmp/.buildx-kube-cache
          cache-to: type=local,dest=/tmp/.buildx-kube-cache-new

      -
        name: Cache build stage
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          target: builder
          tags: builder_stage
          cache-from: type=local,src=/tmp/.buildx-kube-cache
          cache-to: type=local,dest=/tmp/.buildx-kube-cache-new

      -
        name: Cache deps stage
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          target: deps
          tags: deps_stage
          cache-from: type=local,src=/tmp/.buildx-kube-cache
          cache-to: type=local,dest=/tmp/.buildx-kube-cache-new

```


In many cases "target" can be solved, but sometimes I get an error that confuses me.

ie.

https://github.com/hankei6km/mardock/runs/2743414418?check_suite_focus=true
```
time="2021-06-04T05:56:15Z" level=error msg="(*service).Write failed" error="rpc error: code = Canceled desc = context canceled" expected="sha256:83d625e78795e1f30fbfa443c48c5616edef500f137fb4258a62289ac673da10" ref="sha256:83d625e78795e1f30fbfa443c48c5616edef500f137fb4258a62289ac673da10" total=4528
```



I hope this solution helps you.
