### ISSUE TITLE
Omitting target does not build all stages like command line does

### ISSUE THREAD

**Issue by jdforsythe** [docker/build-push-action#377]
### Troubleshooting

Before sumbitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

Multistage Dockerfile. One stage ("validation") is a throwaway - installs development dependencies and runs static analysis. On the command line, `docker build` builds all stages if you don't pass the `--target` flag and so this serves to fail the build if any of the static analysis fails.

The validation stage is "throwaway" because it's not required in any way by the final `release` stage. This is done to ensure dev dependencies never make it to the final image.

#### Steps to reproduce this issue

1. Make a multi-stage Dockerfile where one stage is not required for the final stage
2. Build with this action
3. Observe how that stage is never run

#### Expected behaviour

This is not documented anywhere that I can find in this repo and is surprising that it doesn't just work like the CLI `docker build`. If I don't supply a target stage, _it should build everything_. Or at least I should be able to pass a flag / value for "target" that makes it build everything.

The only suggestions I can find are to run two separate jobs, one with the validation stage as the target and the other with the final stage as the target. This defeats the purpose of the stages sharing common ancestors. All the common stages will be built twice, which costs time and build minutes.

#### Actual behaviour

This action _does not build the "validation" stage_. It's only building the stages required for the final stage.

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

Dockerfile:
```yml
ARG NPM_TOKEN

## base stage
FROM node:12.6-alpine AS base

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

## deps stage
FROM base AS dependencies
ARG NPM_TOKEN

RUN \ 
  # ... install apk dependencies
  && echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

RUN \
  ## install production dependencies to a separate folder (for layer caching)
  yarn install --production --modules-folder production_nm_folder --frozen-lockfile \
  ## install all dev and production dependencies
  && yarn install \
  && rm -f .npmrc

## validation stage
FROM dependencies AS validation

COPY . .

RUN \
  yarn run lint \
  && yarn run test \
  && yarn run check-deps

## compile stage
FROM dependencies AS compile

COPY . .

RUN yarn run raw-build

## release stage
FROM base AS release

COPY --from=dependencies /usr/src/app/production_nm_folder ./node_modules
COPY --from=compile /usr/src/app/lib ./lib

EXPOSE 8080

CMD ["node", "lib/index.js"]
```

Action:
```yml
name: Build Docker Image

on:

  ## when a release is published (not drafts)
  release:
    types: [published]

  ## on all pull requests (create, update, synchronize)
  pull_request:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:

  ## build image for testing purposes
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      ## build image (https://github.com/docker/build-push-action)
      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          push: false

  ## build and publish image
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:

      ## Generate tags (https://github.com/docker/metadata-action)
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag

      ## login to DockerHub for publishing (https://github.com/docker/login-action)
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ## build and push image (https://github.com/docker/build-push-action)
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
