### ISSUE TITLE
Passing file parameter fails

### ISSUE THREAD

**Issue by alwaysharsha** [docker/build-push-action#379]
### Behaviour

When I pass **file** parameter to set the docker filename it doesn't work as expected.

#### Steps to reproduce this issue

Below is the yml snippet of the workflow

```yml
      -
        name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./sample/debian8x64
          file: Dockerfile
          push: false
```

#### Expected behaviour

> It should honor the filename passed and just build the docker image

#### Actual behaviour

> It throws the following error, Just removing the file param works as expected.

Error:
```
/usr/bin/docker buildx build --iidfile /tmp/docker-build-push-zV9BpB/iidfile --file Dockerfile ./sample/debian8x64
time="2021-06-04T11:50:21Z" level=warning msg="No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load"
#1 [internal] load build definition from Dockerfile
#1 sha256:3f489a17dc9624e386a8533e06cd36e5ef0f1ce64c856a471d0cacec304ae9f0
#1 transferring dockerfile: 2B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:f1ee744a56bcf72543aff233a23f55d81a78dc88435beebd1f2b922bf896b09a
#2 transferring context: 2B done
#2 DONE 0.0s
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount624601022/Dockerfile: no such file or directory
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount624601022/Dockerfile: no such file or directory
```

**Comment by crazy-max** [comment]
@alwaysharsha The build command will use `./sample/debian8x64` as context and Dockerfile in './Dockerfile'. Looking at the error I guess your Dockerfile is in `./sample/debian8x64/Dockerfile`. If that's the case you can simply use:

```yaml
      -
        name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./sample/debian8x64
          file: Dockerfile
          push: false
```

https://docs.docker.com/engine/reference/commandline/build/#build-with-path
