### ISSUE TITLE
Experiencing unknown blob error on push

### ISSUE THREAD

**Issue by gudleik** [docker/build-push-action#38]
I have a workflow containing multiple jobs building and pushing images to Github Packages.
This works great most of the time, but sometimes a random job is failing during docker push with an `unknown blob` error.

The jobs are declared like this:

```yaml
  build-maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: XXX/YYY/maintenance
          path: maintenance
          target: production
          tag_with_sha: true
```

Tail of job output:

```
Successfully built c6ac9d5faeba
Successfully tagged docker.pkg.github.com/XXX/YYY/maintenance:sha-eac817d
Pushing image [docker.pkg.github.com/XXX/YYY/maintenance:sha-eac817d]
The push refers to repository [docker.pkg.github.com/XXX/YYY/maintenance]
1e64616ff473: Preparing
02e9da9d44c5: Preparing
3810cc0c140f: Preparing
3e207b409db3: Preparing
3e207b409db3: Layer already exists
3810cc0c140f: Layer already exists
unknown blob
Error: exit status 1
exit status 1
Usage:
  github-actions build-push [flags]

Flags:
  -h, --help   help for build-push
```

**Comment by prise6** [comment]
Any news on this 
Got same issue. I wonder if this linked to limited free space for public projet ?

**Comment by gudleik** [comment]
I tried building and pushing without using this package, and experienced same errors.
When I changed from using short prefixed sha (sha-abcdefg) to full sha as image tags, the problem disappeared.

Maybe you can make tagging a little more customizable, like
```yaml

# use full sha
uses: docker/build-push-action@v1
with:
  tag: ${{GITHUB_SHA}}

# prefixed short sha like today
uses: docker/build-push-action@v1
with:
  tag: sha-${{GITHUB_SHA::7}}
```
