### ISSUE TITLE
Multiple build-args not resulting in correct docker build syntax

### ISSUE THREAD

**Issue by NonsenseSynapse** [docker/build-push-action#380]
### Troubleshooting

Before sumbitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue
Using the following Dockerfile and Github Action:
<details><summary>Dockerfile</summary>
<p>

```Dockerfile
FROM alpine:3.7

ARG FIRST_ARG
RUN echo first arg: ${FIRST_ARG}

ARG SECOND_ARG
RUN echo second arg: ${SECOND_ARG}
```

</p>
</details>

<details><summary>Github Action</summary>
<p>

```yaml
name: Build Test

on:
  workflow_dispatch:
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Clone Github Repo
        uses: actions/checkout@master
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: nonsensesynapse/app:tag
          build-args:
            FIRST_ARG="First"
            SECOND_ARG="Second"
```

</p>
</details>

#### Expected behaviour
The correct docker syntax is to have a separate `--build-arg` for each argument.
```
docker build --progress=plain --build-arg FIRST_ARG="First" --build-arg SECOND_ARG="Second" - < Dockerfile
```
which gives me the following output:
```
#5 [2/3] RUN echo first arg: First
#5 sha256:398661483d922dc4c6b2cb85f72f84de0a8765d511cd2701aa496738019b5baf
#5 0.267 first arg: First
#5 DONE 0.3s

#6 [3/3] RUN echo second arg: Second
#6 sha256:379a45924550875394a9c34cf314ddc4ca9389b749d8205e6e6d36997773d21d
#6 0.331 second arg: Second
#6 DONE 0.4s
```

Source from [docker documentation](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg)

> $ docker build --build-arg HTTP_PROXY=http://10.20.30.2:1234 --build-arg FTP_PROXY=http://40.50.60.5:4567 .

#### Actual behaviour
When the action is run, the resulting docker build command is:

> /usr/bin/docker buildx build --build-arg FIRST_ARG="First" SECOND_ARG="Second" --tag ***/app:tag --iidfile /tmp/docker-build-push-3G4tPQ/iidfile --file Dockerfile--push .

With the echos in the provided Dockerfile, we get the steps:
```
#6 [2/3] RUN echo first arg: "First" SECOND_ARG="Second"
#6 sha256:7e57fb6b5e7addf0b970c568b43b010d06ced5c85668930a1d4ea722307cfd72
#6 0.077 first arg: "First" SECOND_ARG="Second"
#6 DONE 0.1s

#7 [3/3] RUN echo second arg: ${SECOND_ARG}
#7 sha256:733bb9263ba53b14a8ab83e857b26039e2a78195d6382568f10074cfd6f5ea16
#7 0.072 second arg:
#7 DONE 0.1s
```

Syntax errors are thrown if you try to include the `build-arg` key more than once
```yaml
build-args:
    FIRST_ARG="First"
build-args:
    SECOND_ARG="Second"
```
or if you pass in a list
```yaml
build-args:
    - FIRST_ARG="First"
    - SECOND_ARG="Second"
```

### Configuration

* Repository URL (if public): private repo
* Build URL (if public):  private repo

### Logs
Relevant log snippets included above.
