### ISSUE TITLE
When `push` is `false`, image is not available to use via tag

### ISSUE THREAD

**Issue by danilofuchs** [docker/build-push-action#388]
#### Steps to reproduce this issue

1. Follow the [Cache Guide](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md)
2. Set push to false
3. Add a step with `docker run` command referencing the tag

#### Expected behaviour

The second step (`docker run`) should be able to launch the tag `builder:latest`

#### Actual behaviour

```
Unable to find image 'builder:latest' locally
docker: Error response from daemon: pull access denied for builder, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Error: Process completed with exit code 125.
```

### Configuration

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: false # Do not push, only build and cache
          tags: builder:latest
          target: builder
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
         
      - name: E2E Tests
        run: docker run builder:latest /bin/sh -c 'yarn test:e2e;'
```
