### ISSUE TITLE
Cache not working when pulling from Google Container Registry (GCR)

### ISSUE THREAD

**Issue by sheehan1102** [docker/build-push-action#389]
### Behaviour

When attempting to use an existing GCR image as the cache, build-push-action successfully authenticates with Google Cloud, pulls the image, establishes the cache context, and then rebuilds the new image from scratch.

#### Expected behaviour

> If I pull the latest image from GCR to my local, and build a new image (with updated code/sha) the caching works as expected. This is the behavior I would expect from build-push-action.

#### Actual behaviour

> In a GCR registry, there is a default `name` attribute for new images, which is a git sha (or a portion of it). If I run build-push-action, and the latest GCR image has the same git sha as my current work, the cache works as expected. But when the code is updated and the sha changes, the cache no longer works.

### Configuration

```yml
- name: Build production image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/<project-id>/my-app:<sha>,gcr.io/<project-id>/my-app:latest
        build-args: |
          <multiple-build-args>
        cache-from: type=registry,ref=gcr.io/<project-id>/my-app:latest
        cache-to: type=inline
```
