### ISSUE TITLE
Golang static binary missing stuff

### ISSUE THREAD

**Issue by cpswan** [docker/build-push-action#395]
### Behaviour

```dockerfile
RUN go build -tags netgo -ldflags '-extldflags "-static"'
```
Creates a much smaller binary when run in a GitHub Action using the build-push-action versus running `docker build` or `docker buildx` outside of GitHub.

#### Steps to reproduce this issue

1. I run my [docker-image](https://github.com/atsign-company/filebin2/actions/workflows/docker-image.yml) Action to create a new [atsigncompany/filebin2:automated](https://hub.docker.com/layers/atsigncompany/filebin2/automated/images/sha256-24e97a81e276ce7f871420ec67004e201ae621f9bb682745cf0c3e5bc5b42d02?context=explore) image.
2. I try running the filebin2 application using GKE or local Docker compose
3. The app exits because a bunch of stuff that should be there is missing:
```
app_1  | panic: could not locate box "static"
app_1  |
app_1  | goroutine 1 [running]:
app_1  | github.com/GeertJohan/go%2erice.MustFindBox(...)
app_1  |        /app/vendor/github.com/GeertJohan/go.rice/box.go:110
app_1  | main.main()
app_1  |        /app/main.go:108 +0xfea
filebin2_app_1 exited with code 2
```

Contrast with [atsigncompany/filebin2:noaction](https://hub.docker.com/layers/atsigncompany/filebin2/noaction/images/sha256-5cb0e3f795053eb7abf6affaa9908591ca12874526c508aa85d5035f3644b9ce?context=explore)

#### Expected behaviour

The binary should be 27291000 bytes, as created by `docker build` or `docker buildx` outside of GitHub.

That binary can be found as /usr/local/bin/filebin2 inside [atsigncompany/filebin2:noaction](https://hub.docker.com/layers/atsigncompany/filebin2/noaction/images/sha256-5cb0e3f795053eb7abf6affaa9908591ca12874526c508aa85d5035f3644b9ce?context=explore)

#### Actual behaviour

The binary created by the build-push-action is 15309320 bytes, so it's missing 11981680 bytes of stuff

That binary can be found as /usr/local/bin/filebin2 inside [atsigncompany/filebin2:automated](https://hub.docker.com/layers/atsigncompany/filebin2/automated/images/sha256-24e97a81e276ce7f871420ec67004e201ae621f9bb682745cf0c3e5bc5b42d02?context=explore)

### Configuration

* Repository URL - https://github.com/atsign-company/filebin2
* Build URL - https://github.com/atsign-company/filebin2/actions/workflows/docker-image.yml

```yml
name: docker-image

on:
  workflow_dispatch:
    inputs:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          buildkitd-flags: --debug
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.10.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          file: ./Dockerfile.prod
          push: true
          tags: |
            atsigncompany/filebin2:automated
            atsigncompany/filebin2:latest
            atsigncompany/filebin2:GHA${{ github.run_number }}
          platforms: |
            linux/amd64
```

```dockerfile
FROM golang:buster AS build
RUN export DEBIAN_FRONTEND=noninteractive && \
  apt-get install -y make gcc libc-dev git
WORKDIR /app
RUN go get -u github.com/jstemmer/go-junit-report
RUN go get -u github.com/GeertJohan/go.rice/rice
COPY . .
RUN go build -tags netgo -ldflags '-extldflags "-static"'

FROM debian:stable-slim
ENV HOMEDIR=/home/filebin2
ENV USER_ID=1024
ENV GROUP_ID=1024
RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install ca-certificates -y && \
  update-ca-certificates && \
  mkdir -p $HOMEDIR && \
  mkdir -p /var/log/filebin && \
  addgroup --gid $GROUP_ID filebin2 && \
  useradd --system --uid $USER_ID --gid $GROUP_ID --shell /bin/bash \
    --home $HOMEDIR filebin2 && \
  chown -R filebin2:filebin2 $HOMEDIR && \
  chown -R filebin2:filebin2 /var/log/filebin
COPY --from=build --chown=filebin2:filebin2 /app/filebin2 \
  /usr/local/bin/filebin2
WORKDIR $HOMEDIR
USER filebin2
ENTRYPOINT ["/usr/local/bin/filebin2"]
```

### Logs

[logs_30.zip](https://github.com/docker/build-push-action/files/6717115/logs_30.zip) attached
