### ISSUE TITLE
When docker username and package name are same, GH secret of docker username overwrites the package name and put it as ***

### ISSUE THREAD

**Issue by royki** [docker/build-push-action#396]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour
Here is my Makefile to build a docker image - 

```makefile
LIBRARY = ekc-azure-proxy-server
PACKAGE_NAME = energyweb/${LIBRARY}
TAG_LATEST := $(shell rush list --json | jq .projects | jq -r '.[] | select(.name=="@energyweb/${LIBRARY}") | .version')

build-image:
	docker build --force-rm $(options) -t ${PACKAGE_NAME}:${TAG_LATEST} .
```
Here is the [CI Output](https://github.com/energywebfoundation/ekc-monorepo/runs/2932038079?check_suite_focus=true#step:11:1), which is working to build the docker image. (It is private repo, hence I'm pasting the result here)

```console
Successfully tagged energyweb/ekc-azure-proxy-server:0.0.1
```
Which is Nice and expected.

Now,  it's time to publish the image in docker hub. So I created two secret variable in GH Secrets (Actions secrets) as 
`DOCKER_USERNAME` and `DOCKER_PASSWORD`. In this case `DOCKER_USERNAME` is `energyweb`.

GH CI to Publishing Image to docker hub - 
```yaml
 - name: Push to Docker Hub
    uses: docker/build-push-action@v2
    with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       push: true
       tags: energyweb/ekc-azure-proxy-server:${{ steps.TAG_LATEST.output }}
```

From now, all my NPM package name as well as docker image name started coming as `***/ekc-azure-proxy-server:0.0.1`

Here is the Docker build output now .  [CI Output](https://github.com/energywebfoundation/ekc-monorepo/runs/2933934092?check_suite_focus=true#step:11:180)
```console
Successfully tagged ***/ekc-azure-proxy-server:0.0.1
```
#### Steps to reproduce this issue

1. Put same name in both npm package name and docker username as secret variable
2. Push it using `docker/build-push-action@v2`
3. check the build result.

#### Expected behaviour
> Tell us what should happen
It should be `energyweb/ekc-azure-proxy-server:0.0.1`

#### Actual behaviour
For docker build it is building as `***/ekc-azure-proxy-server:0.0.1` 
> Tell us what happens instead

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
name: Publish

on:
  push:
    branches:
      - 'DOI-*'

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  publish-packages:
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: Install Rush
        run: npm install -g @microsoft/rush

      - name: Rush install packages
        run: node common/scripts/install-run-rush.js install

      - name: Set .env file for ekc library
        run: echo "PROXY_URL=http://localhost:5000/api/v1" >> $HOME/work/ekc-monorepo/ekc-monorepo/packages/ekc/.env

      - name: Build packages
        run: node common/scripts/install-run-rush.js build --verbose

      - name: Lints packages
        run: node common/scripts/install-run-rush.js lint --verbose

      - name: Run test
        run: node common/scripts/install-run-rush.js test --verbose

      - name: Set npm credentials
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> $HOME/.npmrc

       - name: Publish in NPM packages
         run: node common/scripts/install-run-rush.js publish --apply --publish --include-all
         env:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Docker Build energyweb/ekc-azure-proxy-server image
        run: |
          cd $HOME/work/ekc-monorepo/ekc-monorepo/packages/azure-proxy-server
          make build-image

      - name: Retrieve TAG
        run: rush list --json | jq .projects | jq -r '.[] | select(.name=="@energyweb/ekc-azure-proxy-server") | .version'
        id: TAG_LATEST

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          push: true
          tags: energyweb/ekc-azure-proxy-server:${{ steps.TAG_LATEST.output }}

```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
2021-06-28T18:54:40.0024950Z Found online and idle hosted runner(s) in the current repository's organization account that matches the required labels: 'ubuntu-latest'
2021-06-28T18:54:40.0025019Z Waiting for a hosted runner in 'organization' to pick this job...
2021-06-28T18:54:46.0985857Z Current runner version: '2.278.0'
2021-06-28T18:54:46.1018055Z ##[group]Operating System
2021-06-28T18:54:46.1019067Z Ubuntu
2021-06-28T18:54:46.1019604Z 20.04.2
2021-06-28T18:54:46.1020107Z LTS
2021-06-28T18:54:46.1020688Z ##[endgroup]
2021-06-28T18:54:46.1021353Z ##[group]Virtual Environment
2021-06-28T18:54:46.1022101Z Environment: ubuntu-20.04
2021-06-28T18:54:46.1022708Z Version: 20210614.1
2021-06-28T18:54:46.1023889Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210614.1/images/linux/Ubuntu2004-README.md
2021-06-28T18:54:46.1025389Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210614.1
2021-06-28T18:54:46.1026379Z ##[endgroup]
2021-06-28T18:54:46.1028771Z ##[group]GITHUB_TOKEN Permissions
2021-06-28T18:54:46.1030535Z Actions: write
2021-06-28T18:54:46.1031141Z Checks: write
2021-06-28T18:54:46.1031801Z Contents: write
2021-06-28T18:54:46.1032508Z Deployments: write
2021-06-28T18:54:46.1033326Z Discussions: write
2021-06-28T18:54:46.1034019Z Issues: write
2021-06-28T18:54:46.1034666Z Metadata: read
2021-06-28T18:54:46.1035340Z Packages: write
2021-06-28T18:54:46.1036005Z PullRequests: write
2021-06-28T18:54:46.1036800Z RepositoryProjects: write
2021-06-28T18:54:46.1037612Z SecurityEvents: write
2021-06-28T18:54:46.1038266Z Statuses: write
2021-06-28T18:54:46.1039032Z ##[endgroup]
2021-06-28T18:54:46.1042445Z Prepare workflow directory
2021-06-28T18:54:46.1716961Z Prepare all required actions
2021-06-28T18:54:46.1729042Z Getting action download info
2021-06-28T18:54:46.3310458Z Download action repository 'actions/checkout@v2'
2021-06-28T18:54:48.0947834Z Download action repository 'actions/setup-node@v2-beta'
2021-06-28T18:54:48.2986130Z Download action repository 'docker/login-action@v1'
2021-06-28T18:54:48.4405050Z Download action repository 'docker/build-push-action@v2'
2021-06-28T18:54:48.7746010Z ##[group]Run actions/checkout@v2
2021-06-28T18:54:48.7746692Z with:
2021-06-28T18:54:48.7747126Z   fetch-depth: 0
2021-06-28T18:54:48.7747886Z   repository: ***foundation/ekc-monorepo
2021-06-28T18:54:48.7749080Z   token: ***
2021-06-28T18:54:48.7749501Z   ssh-strict: true
2021-06-28T18:54:48.7750062Z   persist-credentials: true
2021-06-28T18:54:48.7750601Z   clean: true
2021-06-28T18:54:48.7750985Z   lfs: false
2021-06-28T18:54:48.7751416Z   submodules: false
2021-06-28T18:54:48.7751870Z ##[endgroup]
2021-06-28T18:54:49.6152343Z Syncing repository: ***foundation/ekc-monorepo
2021-06-28T18:54:49.6153382Z ##[group]Getting Git version info
2021-06-28T18:54:49.6156094Z Working directory is '/home/runner/work/ekc-monorepo/ekc-monorepo'
2021-06-28T18:54:49.6159599Z [command]/usr/bin/git version
2021-06-28T18:54:49.6201718Z git version 2.32.0
2021-06-28T18:54:49.7193785Z ##[endgroup]
2021-06-28T18:54:49.7195312Z Deleting the contents of '/home/runner/work/ekc-monorepo/ekc-monorepo'
2021-06-28T18:54:49.7197214Z ##[group]Initializing the repository
2021-06-28T18:54:49.7198428Z [command]/usr/bin/git init /home/runner/work/ekc-monorepo/ekc-monorepo
2021-06-28T18:54:49.7199743Z hint: Using 'master' as the name for the initial branch. This default branch name
2021-06-28T18:54:49.7200799Z hint: is subject to change. To configure the initial branch name to use in all
2021-06-28T18:54:49.7201856Z hint: of your new repositories, which will suppress this warning, call:
2021-06-28T18:54:49.7202648Z hint: 
2021-06-28T18:54:49.7203592Z hint: 	git config --global init.defaultBranch <name>
2021-06-28T18:54:49.7204335Z hint: 
2021-06-28T18:54:49.7205265Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2021-06-28T18:54:49.7207202Z hint: 'development'. The just-created branch can be renamed via this command:
2021-06-28T18:54:49.7208107Z hint:
