### ISSUE TITLE
Cant generate and push source image to docker hub

### ISSUE THREAD

**Issue by kumaresan-subramani** [docker/build-push-action#397]
## issues

i am using below yml file but docker image not get generated and also can t oush source but **dockerHubDescription** is working fine

please refer below code

```
name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: klartdigi/cinibot_api
        short-description: ${{ github.event.repository.description }}
 
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
           repository: klartdigi/cinibot_api 
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./src/ApiGateways/BackOfficeGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```
