### ISSUE TITLE
How to use custom tag name 

### ISSUE THREAD

**Issue by kumaresan-subramani** [docker/build-push-action#403]
How to use custom tag name in `buoild and push` plugin

i am using like below but throws error

```
- name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
```

WHen i use command to generate docker image , i can use below command 

`docker build -t klartdigi/dockerex .`

I want something like this

```
- name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: `imageName`
```

Is it possbile here?
