### ISSUE TITLE
Can't generate docker image

### ISSUE THREAD

**Issue by kumaresan-subramani** [docker/build-push-action#405]
### Behaviour

Need to generate docker image and push to docker hub repository

#### Steps to reproduce this issue

1. create aspcore microservice app
2. then use `build-push-action` lik below

```
- name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Services/BackOffice/Identity/Identity.svc/Dockerfile
          push: true
          tags: klartdigi/cinibot_api

```

#### Expected behaviour

Need to generate docker and get push to docker hub

#### Actual behaviour

![image](https://user-images.githubusercontent.com/36756050/125426730-818ff778-610f-4c13-bdf4-dbf815fd1981.png)

### Configuration

* Repository URL (if public):  https://github.com/kumaresan-subramani/testing
* Build URL (if public):  https://github.com/kumaresan-subramani/testing/runs/3055211478

```yml
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: klartdigi/cinibot_api
        short-description: ${{ github.event.repository.description }}
 
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Services/BackOffice/Identity/Identity.svc/Dockerfile
          push: true
          tags: klartdigi/cinibot_api
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

```

## Note - my docker repo name 

![image](https://user-images.githubusercontent.com/36756050/125427037-4e82e6e1-383a-486f-8e48-a9641a7005eb.png)

### Logs

[logs_2.zip](https://github.com/docker/build-push-action/files/6807632/logs_2.zip)

**Comment by kumaresan-subramani** [comment]
@crazy-max , any suggestions

**Comment by crazy-max** [comment]
As you're using the Path context (`context: .`), you have to use the Checkout step as [explained in the README](https://github.com/docker/build-push-action/#path-context).

**Comment by kumaresan-subramani** [comment]
Thanks @crazy-max

**Comment by kumaresan-subramani** [comment]
is it possible to generate multiple dcker images like below


```
   -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          1 .context: .
          file: ./src/Services/BackOffice/Identity/Identity.svc/Dockerfile
          push: true
          tags: klartdigi/cinibot_api

         2. context: .
          file: ./src/Services/BackOffice/Concession/Concession.svc/Dockerfile
          push: true
          tags: klartdigi/cinibot_api

```
