### ISSUE TITLE
Cannot build an image when GitHub owner name contains uppercased characters

### ISSUE THREAD

**Issue by StephenWithPH** [docker/build-push-action#409]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md). :heavy_check_mark: 

#### Steps to reproduce this issue

1. Create a GitHub repository with an owner whose name contains at least one uppercase character.
1. Make a minimal Dockerfile.
1. Configure GitHub Actions per below.
1. Watch builds fail with the error below.

#### Expected behaviour

I am able to build a container image in a GitHub Action.

#### Actual behaviour

Build fails with the error below.

### Configuration

```yml
  docker:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'docker/login-action@v1'
        with:
          registry: 'ghcr.io'
          username: 'GitHub Actions'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - uses: 'docker/build-push-action@v2'
        with:
          push: false
```

### Logs

```
Error: buildx failed with: error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "MIGRATE": invalid reference format: repository name must be lowercase
```

### Commentary

#37 and #237 discuss roughly similar problems. Of note, the failure mode in this case is when _only building and __not__ pushing_. I think it's reasonable to accept container image registry character constraints when pushing. If in fact I am unable to _build_ an image because the containing git repository has an uppercase character, that seems like a different and more severe problem.
