### ISSUE TITLE
Specifying load and outputs causes image not loaded

### ISSUE THREAD

**Issue by jacek-jablonski** [docker/build-push-action#413]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

When you specify `load: true` and `outputs: type=docker,dest=/tmp/image.tar` image output is generated but it is not loaded. Is it desired behaviour?

#### Steps to reproduce this issue

```yaml
- name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: api/
          target: dev
          push: false
          load: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          outputs: type=docker,dest=/tmp/image.tar

- run: docker image ls  #  <- image not listed
```

#### Expected behaviour

Image tar should be generated and image should be loaded in docker context.

#### Actual behaviour

Image tar is generated but it is not loaded in docker context.

**Comment by crazy-max** [comment]
@jacek-jablonski 

> Is it desired behaviour?

Yes, `load` is a [shorthand for `--output=type=docker`](https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#load) so in your case `type=docker,dest=/tmp/image.tar` output will override it.

> Image tar should be generated and image should be loaded in docker context.

Atm multiple exporters are not supported (see moby/buildkit#1555). I'm not really sure what is your use case here but if you want the image loaded in docker and a tarball, you can do that:

```yaml
      -
        name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: api/
          target: dev
          push: false
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          outputs: type=docker,dest=/tmp/image.tar
      -
        name: Load image
        run: |
          docker load < /tmp/image.tar
```
