### ISSUE TITLE
Image not being pushed with v1

### ISSUE THREAD

**Issue by jlunaq** [docker/build-push-action#418]
Hey there,

I'm using v1 with the following configuration to build and publish the image:

```yaml
  publish_docker:
    runs-on: [self-hosted, tsa, myrunner]
    if: github.event.action == 'closed' && github.event.pull_request.merged && !needs.release.outputs.skip
    needs: release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker-local.registry.company.com
          repository: name/app
          build-args: GITHUB_USER=${{ secrets.GITHUB_USER }},GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tag_with_ref: true
````

When the action is ran, it seems that it builds the image correctly but it's not pushing that to the repo, it finishes with the message:
`Pushing image []`
And when I check the repo, I see that it was not actually pushed.

Do you know why it ends like this? I mean it ends without giving any error, just that message and it doesn't do the push process
