### ISSUE TITLE
Remove `v` from tags

### ISSUE THREAD

**Issue by felipecrs** [docker/build-push-action#42]
I think the action should have the option to remove the `v` from git tags that are semver. And I think it should be the default behavior.

Git tag: `v1.1.1` -> Docker tag: `1.1.1`

**Comment by SuperSandro2000** [comment]
The v is the default behavior on GitHub and probably shouldn't be changed as it would be inconsistent.

**Comment by felipecassiors** [comment]
@SuperSandro2000 what do you mean by "default behavior on GitHub"? 

We're talking about docker images, right? And I don't see any docker image with a `v` in its tags. Example: [`node:12.16.3`](https://hub.docker.com/layers/node/library/node/12.16.3/images/sha256-4adab503a6df17a232a96824e26d3a596948e6e13a3898e78f01d06666c3f5c4?context=explore)

**Comment by SuperSandro2000** [comment]
I was mistakenly thinking about tagging releases on got. NVM.

**Comment by sagikazarmark** [comment]
A few examples:

- https://hub.docker.com/r/prom/prometheus/tags
- https://hub.docker.com/_/fluentd?tab=tags
- https://hub.docker.com/r/kubernetesui/dashboard/tags

I don't think making it the default behavior is a good idea, it would probably break lots of existing workflows.

You can already have a simple workaround using [workflow commands](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter).

That being said, I could imagine this as a feature. As an alternative, I could imagine a regex with capture groups for the ref that could work for both tags, commits and branches (eg. `feature/whatever` could result in a tag called `whatever`)

**Comment by vandmo** [comment]
Posting a complete solution for any Googlers that end up here.
I think this is a little less magic than other solutions that I have found.

```yaml
name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Set Versions
      uses: actions/github-script@v4
      id: set_version
      with:
        script: |
          const tag = context.ref.substring(10)
          const no_v = tag.replace('v', '')
          const dash_index = no_v.lastIndexOf('-')
          const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
          core.setOutput('tag', tag)
          core.setOutput('no-v', no_v)
          core.setOutput('no-dash', no_dash)

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:latest
          ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:${{steps.set_version.outputs.no-dash}}
```
