### ISSUE TITLE
buildx failed with: error: failed to solve: blob not found

### ISSUE THREAD

**Issue by mmeendez8** [docker/build-push-action#422]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. Create a workflow that builds and pushes a container to ghcr.io following  https://github.com/docker/build-push-action/pull/4062
2. Worked fine for a while but suddenly error message appear

#### Expected behaviour

Build and push image caching layers.

#### Actual behaviour

> Tell us what happens instead
Error appears when exporting cache
```
------
 > exporting cache:
------
error: failed to solve: blob not found
Error: buildx failed with: error: failed to solve: blob not found
```

### Configuration

```yml
name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          IMAGE="ghcr.io/****"
          DOCKERFILE="Dockerfile"
          echo ::set-output name=image::${IMAGE}
          echo ::set-output name=dockerfile::${DOCKERFILE}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.0
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build production image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ${{ steps.prep.outputs.dockerfile }}
          push: true
          tags: ${{ steps.prep.outputs.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: deploy
```

### Logs

[build_docker.zip](https://github.com/docker/build-push-action/files/6902600/build_docker.zip)
