### ISSUE TITLE
Docker push failed due to authorization status: 401: authorization failed

### ISSUE THREAD

**Issue by ShixiangWang** [docker/build-push-action#423]
Hi, I am using the action to auto build and push docker image to dockerhub, however it fails in the last step.

```
#12 exporting to image
#12 pushing layers 1.0s done
#12 ERROR: authorization status: 401: authorization failed
------
 > exporting to image:
------
error: failed to solve: authorization status: 401: authorization failed
Error: buildx failed with: error: failed to solve: authorization status: 401: authorization failed
```
> https://github.com/openbiox/UCSCXenaShiny/runs/3200039791?check_suite_focus=true

![image](https://user-images.githubusercontent.com/25057508/127625458-e5853270-32fb-494c-9a51-d81a559ccc27.png)

I have properly set the username and token, the login step shows it works fine.

![image](https://user-images.githubusercontent.com/25057508/127625564-ee9f2a6d-218d-49d6-bf6a-4791fccb8328.png)

Any suggestion?

**Comment by ShixiangWang** [comment]
My yml

```
name: Auto-builds docker image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: name/app
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

```
