### ISSUE TITLE
Repository/image name should be lowercased automatically in cache parameters.

### ISSUE THREAD

**Issue by jbcpollak** [docker/build-push-action#424]
It appear the registry name is not lower-cased when used in the `cache-from` parameter. This appears related to https://github.com/docker/build-push-action/issues/37, but not exactly the same.

#### Steps to reproduce this issue

1. use ${{ github.repository}} in the `cache-from` parameter.

#### Expected behaviour

Would expect caching to work

#### Actual behaviour

> The build output this while trying to restore the cache:

```
#10 importing cache manifest from ghcr.io/My-Org/repo:main
#10 ERROR: invalid reference format: repository name must be lowercase
```

### Configuration

(This is an excerpt)

```yml
  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

....

      - name: Build and push dill to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          cache-to: type=inline,mode=max
```

**Comment by crazy-max** [comment]
Like I said in https://github.com/docker/build-push-action/issues/237#issuecomment-848673650, it adds an [unnecessary complexity](https://github.com/docker/build-push-action/pull/341/files) that should rather be handled upstream by GitHub.

Or you can add a step in your workflow:

```yaml
    - name: Format repo slug
      uses: actions/github-script@v4
      id: repo_slug
      with:
        result-encoding: string
        script: return `ghcr.io/${github.repository.toLowerCase()}`

    - name: Build and push dill to Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: ./docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ steps.repo_slug.outputs.result }}:main
        cache-to: type=inline
```
> I will add a section in the troubleshooting notes.

As a side note, `type=inline` does not support `mode=max`. See https://github.com/moby/buildkit#export-cache.
