### ISSUE TITLE
Tries to pull the image when image is available locally

### ISSUE THREAD

**Issue by genieai-vikas** [docker/build-push-action#425]
#### Steps to reproduce this issue

1. Create a dockerfile 

```
FROM test/base-node

COPY package.json /app/sdadministrator/package.json
```

2. Now we have to build the above dockerfile but as you can see  _test/base-node_ is the base image required.
3. So I am pulling the base image from ECR and tag that image with _test/base-node_
4. But even that image is present it's try to download the base image and gives error

`Error: buildx failed with: error: failed to solve: test/base-node: pull access denied, repository does not exist or may require authorization: authorization status: 401: authorization failed`

#### Expected behaviour

> It should have used the docker image present locally to build

#### Actual behaviour

> getting error
`Error: buildx failed with: error: failed to solve: test/base-node: pull access denied, repository does not exist or may require authorization: authorization status: 401: authorization failed`

```yml
  build-test:
    needs: build-base-node
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{needs.build-base-node.outputs.BRANCH_TAG}}
        run: |
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BASE_IMAGE }}:$IMAGE_TAG
          docker tag ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BASE_IMAGE }}:$IMAGE_TAG ${{ env.ECR_BASE_IMAGE }}
      - name: Build Base Node
        uses: docker/build-push-action@v2
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BASE_IMAGE }}
          context: src/microservices/test
          builder: ${{ steps.buildx.outputs.name }}
          file: ./src/microservices/test/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_APP_REPOSITORY }}:${{needs.build-base-node.outputs.BRANCH_TAG}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
```

P.S In the dockerfile I can't have a full ECR registry something like this

```
FROM xxxxxxxxx.dkr.ecr.us-west-1.amazonaws.com/test/base-node

COPY package.json /app/sdadministrator/package.json
```

**Comment by crazy-max** [comment]
@genieai-vikas

`docker/setup-buildx-action` will create a builder using the [`docker-container` driver](https://github.com/docker/buildx/blob/master/docs/reference/buildx_create.md#-set-the-builder-driver-to-use---driver) so that's why `test/base-node` image can't be pulled because this builder doesn't have access to `docker images`.

To solve that you can use a [local registry](https://github.com/docker/build-push-action/blob/master/docs/advanced/local-registry.md) in your workflow.

> P.S In the dockerfile I can't have a full ECR registry something like this

Why? If you can pull with `docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BASE_IMAGE }}:$IMAGE_TAG` you can use a build-arg to pass this registry value to your Dockerfile at build time. Also our [login-action is able to login against an ECR registry](https://github.com/docker/login-action#aws-elastic-container-registry-ecr).

From what I see you could use the following workflow:

```dockerfile
ARG BASE_IMAGE=test/base-node
FROM ${BASE_IMAGE}

COPY package.json /app/sdadministrator/package.json
```

```yaml
  build-test:
    needs: build-base-node
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build Base Node
        uses: docker/build-push-action@v2
        with:
          context: src/microservices/sdgateway
          builder: ${{ steps.buildx.outputs.name }}
          file: ./src/microservices/sdgateway/Dockerfile
          build-args: |
            BASE_IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BASE_IMAGE }}:$IMAGE_TAG
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_APP_REPOSITORY }}:${{needs.build-base-node.outputs.BRANCH_TAG}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
```

PS:
* `registry`, `repository` inputs don't exist in `docker/build-push-action@v2`.
* `actions/checkout@v1` looks deprecated (last update 2019) so I suggest to use `actions/checkout@v2`
* Don't use `docker/setup-buildx-action@master` but `docker/setup-buildx-action@v1`
