### ISSUE TITLE
question: short sha in tag

### ISSUE THREAD

**Issue by alextes** [docker/build-push-action#440]
Is there a way to tag with a short sha?

There's steps like so:
```yaml
- name: Set outputs
  id: vars
  run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
- name: Check outputs
  run: echo ${{ steps.vars.outputs.sha_short }}
```

but they don't seem visible to the "with tags" bit here:
```yaml
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            registry.digitalocean.com/gas-analysis/gas-analysis:latest
            registry.digitalocean.com/gas-analysis/gas-analysis:${{ github.sha }}
```

**Comment by crazy-max** [comment]
@alextes You can use our [metadata-action](https://github.com/docker/metadata-action) for that:

```yaml
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.digitalocean.com/gas-analysis/gas-analysis
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
