### ISSUE TITLE
intermediate layers when importing gha cache

### ISSUE THREAD

**Issue by dudicoco** [docker/build-push-action#441]
Hi,

I'm trying to find a workaround to GitHub's lack of support for docker image cache when pulling images.

I have tried using the action to build an image, using multiple `FROM` statements in my Dockerfile:
```Dockerfile
FROM mvdan/shfmt:v3.3.1 AS shfmt

FROM 06kellyjac/markdownlint-cli:0.28.1 AS markdownlint-cli

FROM hadolint/hadolint:v2.6.0 AS hadolint

FROM scratch

WORKDIR /shfmt

COPY --from=shfmt . .

WORKDIR /markdownlint-cli

COPY --from=markdownlint-cli . .

WORKDIR /hadolint

COPY --from=hadolint . .
```

Workflow:
```yaml
    - name: Cache Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        outputs: type=image
        cache-from: type=gha
        cache-to: type=gha,mode=max
```

I expected the intermediate layers for all of the images within the `FROM` statements to be available after the image is built, however when running `docker pull` for any of the images, the layers are not found locally and are pulled from dockerhub.

Is it possible to save the intermediate layers when importing cache?

Thanks
