### ISSUE TITLE
Authorization failed while using gha cache

### ISSUE THREAD

**Issue by mlissner** [docker/build-push-action#442]
#### Steps to reproduce this issue

1. Use the new gha cache
2. Push to a branch with Github Actions set up
3. Watch the log

#### Expected behaviour

I expected the build to get cached.

#### Actual behaviour

The action crashed when pushing the artifact to Github. The error is:

```
------
 > exporting to image:
------
error: failed to solve: authorization status: 401: authorization failed
Error: buildx failed with: error: failed to solve: authorization status: 401: authorization failed
```

### Configuration

The docs seem to say you need some particular variables, `ACTIONS_CACHE_URL`, and `ACTIONS_RUNTIME_TOKEN`, but maybe you get those by default when using Github Actions? Not sure.

* Repository URL (if public):  https://github.com/freelawproject/courtlistener
* Build URL (if public): https://github.com/freelawproject/courtlistener/runs/3405817350?check_suite_focus=true

```yml
name: docker build and test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag_flags: ["--exclude-tag selenium", "--tag selenium"]
    steps:
      - name: Check out solr
        uses: actions/checkout@v2-beta
        with:
          repository: freelawproject/courtlistener-solr-server
          ref: main
          path: courtlistener-solr-server
      - name: Set up solr permissions
        run: |
          cd courtlistener-solr-server
          sudo chown -R :1024 data
          sudo chown -R :1024 solr
          sudo find data -type d -exec chmod g+s {} \;
          sudo find solr -type d -exec chmod g+s {} \;
          sudo find data -type d -exec chmod 775 {} \;
          sudo find solr -type d -exec chmod 775 {} \;
          sudo find data -type f -exec chmod 664 {} \;
          sudo find solr -type f -exec chmod 664 {} \;
      - name: Check out CourtListener
        uses: actions/checkout@v2-beta
        with:
          path: courtlistener
      - name: Create the private settings file
        working-directory: courtlistener/cl/settings
        run: cp 05-private.example 05-private.py
      - name: Add AWS creds to settings
        working-directory: courtlistener/cl/settings
        run: |
          echo "AWS_ACCESS_KEY_ID = '${{ secrets.AWS_S3_DEV_ACCESS_KEY_ID }}'" >> 05-private.py
          echo "AWS_SECRET_ACCESS_KEY = '${{ secrets.AWS_S3_DEV_SECRET_ACCESS_KEY }}'" >> 05-private.py

      - name: Echo github actor name for debugging
        run: echo ${{ github.actor }}

      # Build and cache docker images so tests are always run on the latest
      # dependencies
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build latest docker django image
        uses: docker/build-push-action@v2
        with:
          file: docker/django/Dockerfile
          push: true
          tags: freelawproject/courtlistener-django:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build latest docker celery image
        uses: docker/build-push-action@v2
        with:
          file: docker/task-server/Dockerfile
          push: true
          tags: freelawproject/task-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

## Logs

[logs_8605.zip](https://github.com/docker/build-push-action/files/7035445/logs_8605.zip)

## Thank you!
