### ISSUE TITLE
Push image throw Error 405 Method Not Allowed

### ISSUE THREAD

**Issue by Se7en-IT** [docker/build-push-action#448]
Hi,
i have a 405 error when after build, push image to repository.
Any tips?

```yml
name: Deploy
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          BRANCH=${GITHUB_REF#refs/*/}
          [[ $BRANCH != 'master' ]] && BRANCH="develop"
          REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo $BRANCH
          echo $REPOSITORY
          echo "TAG_URL=ghcr.io/${REPOSITORY}:${BRANCH}" >> $GITHUB_ENV
   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.TAG_URL }}
```

### Logs

#10 exporting to image
#10 exporting layers
#10 exporting layers 18.0s done
#10 exporting manifest sha256:b180fd3b3629b91220dbdd481a7004273ac5bc8d63e6cc56d5de1d5d3e2de7b5 done
#10 exporting config sha256:a497b7f410318940ee81e59d909d68528949a518308294d13034d4cd9bad2ef0 done
#10 pushing layers
#10 ...

#11 [auth] ****/****:pull,push token for ghcr.io
#11 DONE 0.0s

#10 exporting to image
#10 ...

#12 [auth] ****/****:pull,push token for ghcr.io
#12 DONE 0.0s

#10 exporting to image
#10 pushing layers 0.5s done
#10 ERROR: unexpected status: 405 Method Not Allowed
------
 > exporting to image:
------
error: failed to solve: unexpected status: 405 Method Not Allowed
Error: buildx failed with: error: failed to solve: unexpected status: 405 Method Not Allowed
