### ISSUE TITLE
`ERROR: blob not found` when copying path in build with caching

### ISSUE THREAD

**Issue by iacobfred** [docker/build-push-action#449]
### Behaviour

When I use build-push-action, builds fail unless I specify `no-cache: true`.

Here is the redacted job YAML:
```
  build-react:
    name: Build React image
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.9]
    environment: integration
    steps:
    - name: Check out main branch
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    # THIS FAILS
    - name: Build image
      id: build
      continue-on-error: true
      uses: docker/build-push-action@v2
      with:
        build-args: |
          ENVIRONMENT=prod
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=gha,scope=react
        cache-to: type=gha,mode=max,scope=react
        context: .
        file: ./build/Dockerfile.react
        load: false
        push: true
        secret-files: ENV_FILE=./.env
        tags: ghcr.io/modularhistory/react:${{ github.sha }}
    # THIS SUCCEEDS
    - name: Build image (retry without cache)
      if: ${{ steps.build.outcome == 'failure' }}
      uses: docker/build-push-action@v2
      with:
        build-args: |
          ENVIRONMENT=prod
        context: .
        file: ./build/Dockerfile.react
        load: false
        push: true
        no-cache: true
        secret-files: ENV_FILE=./.env
        tags: ghcr.io/modularhistory/react:${{ github.sha }}
```

The `build` step always fails:
```
#6 [deployable  2/11] RUN mkdir -p --   /modularhistory/modularhistory   /modularhistory/frontend   /modularhistory/_static
#6 CACHED

#8 [deployable  3/11] WORKDIR /modularhistory/frontend
#8 CACHED

#18 [deployable  4/11] COPY --from=builder /modularhistory/frontend/.next /modularhistory/frontend/.next
#18 ERROR: blob not found
------
 > [deployable  4/11] COPY --from=builder /modularhistory/frontend/.next /modularhistory/frontend/.next:
------
Dockerfile.react:51
--------------------
  49 |     
  50 |     # Copy compiled JavaScript from the builder stage.
  51 | >>> COPY --from=builder /modularhistory/frontend/.next /modularhistory/frontend/.next
  52 |     
  53 |     # Install required dependencies.
--------------------
error: failed to solve: failed to compute cache key: blob not found
Error: buildx failed with: error: failed to solve: failed to compute cache key: blob not found
```

However, the fallback step that retries without cache succeeds.

Here is my `Dockerfile.react`:
```
##################################
# Stage 1
##################################

# https://hub.docker.com/_/node/
FROM node:lts-buster AS builder

# https://docs.docker.com/engine/reference/builder/#arg
ARG ENVIRONMENT=dev

# TODO: set NODE_ENV environment var

# Create required directories.
RUN mkdir -p -- \
  /modularhistory/modularhistory \
  /modularhistory/frontend

# Install project dependencies.
WORKDIR /modularhistory/frontend
COPY frontend/package*.json /modularhistory/frontend/
RUN npm set cache .npm; npm ci || (npm cache clean -f && npm ci)

# Add source code required for compiling JS.
COPY .env /modularhistory/.env
COPY core/static /modularhistory/core/static
COPY frontend /modularhistory/frontend

# Compile JavaScript.
RUN npm run build

##################################
# Stage 2
##################################

FROM node:lts-buster AS deployable

LABEL org.opencontainers.image.source https://github.com/ModularHistory/modularhistory

# Copy the ENVIRONMENT arg from the previous stage.
ARG ENVIRONMENT

# Create required directories.
RUN mkdir -p -- \
  /modularhistory/modularhistory \
  /modularhistory/frontend \
  /modularhistory/_static

WORKDIR /modularhistory/frontend

# Copy compiled JavaScript from the builder stage.
COPY --from=builder /modularhistory/frontend/.next /modularhistory/frontend/.next

# Install required dependencies.
COPY frontend/package*.json /modularhistory/frontend/
RUN if [ "$ENVIRONMENT" = "dev" ]; then npm ci --cache .npm; else npm ci --cache .npm --production; fi

# Copy necessary files.
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
COPY .env /modularhistory/.env
# TODO: Move these static files into frontend?
COPY core/static /modularhistory/core/static

# Grant necessary permissions to non-root user.
RUN chown -R www-data:www-data /modularhistory && \
  chmod g+w /usr/local/bin/wait-for-it.sh && \
  chmod g+w -R /modularhistory/_static

# Make .next directory writable in dev environment.
RUN if [ "$ENVIRONMENT" = "dev" ]; then chmod g+w -R /modularhistory/frontend/.next/; fi

# Expose port 3000.
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=7s --start-period=60s --retries=3 \
  CMD curl --fail http://localhost:3000/ || exit 1

# Switch from root to non-root user.
USER www-data

CMD npm run start
```

The same happens when I try to build other images with gha caching. They always fail to build unless I disable caching.

#### Expected behaviour

I would expect the build to succeed with caching enabled.

#### Actual behaviour

The build fails with caching enabled but succeeds with caching disabled.

### Configuration

* Repository URL (if public): https://github.com/ModularHistory/modularhistory

https://github.com/ModularHistory/modularhistory/blob/main/.github/workflows/integration.yml

### Logs

[logs_4071.zip](https://github.com/docker/build-push-action/files/7071094/logs_4071.zip)
