### ISSUE TITLE
ARM + Python venv + Buildx combo failing in multistage builds

### ISSUE THREAD

**Issue by leelavg** [docker/build-push-action#450]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

Trimmed down most of the steps:

1. Below commands aren't working as expected in arm builds
https://github.com/kadalu/kadalu/blob/f997b9720825ddb711734a1e86bce8c939b3a52c/extras/Dockerfile.builder#L20-L22
2. In a multistage build, considering above in a base image, it should install packages in venv and in component images, pkgs in venv is generally copied
3. However, venv is getting activated but pkgs in requirements file are being installed elsewhere
4. It's working fine for amd64 and failing for arm multiarch builds

#### Expected behaviour

> Tell us what should happen

1. Python packages should get installed in venv folder

#### Actual behaviour

> Tell us what happens instead

1. Python packages aren't getting installed in venv folder

### Configuration

* Repository URL (if public):  https://github.com/kadalu/kadalu
* Build URL (if public): https://github.com/kadalu/kadalu/runs/3408131848?check_suite_focus=true#step:10:1

```yml
# paste your YAML workflow file here and remove sensitive data
# From: https://github.com/kadalu/kadalu/blob/f997b9720825ddb711734a1e86bce8c939b3a52c/.github/workflows/on-release-tag.yml#L105-L140
      -
        name: Build Builder Image
        uses: docker/build-push-action@v2
        timeout-minutes: 260
        with:
          context: .
          file: extras/Dockerfile.builder
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            docker.io/kadalu/builder:${{ steps.vars.outputs.tag }}
            docker.io/kadalu/builder:latest
          build-args: |
            version=${{ steps.vars.outputs.tag }}
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=${{ steps.vars.outputs.tag }}
      -
        name: Build CSI Image and push
        uses: docker/build-push-action@v2
        timeout-minutes: 200
        with:
          context: .
          file: csi/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          target: prod
          push: true
          tags: |
            docker.io/kadalu/kadalu-csi:${{ steps.vars.outputs.tag }}
            docker.io/kadalu/kadalu-csi:latest
          build-args: |
            builder_version=${{ steps.vars.outputs.tag }}
            version=${{ steps.vars.outputs.tag }}
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=${{ steps.vars.outputs.tag }}
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

[logs_841.zip](https://github.com/docker/build-push-action/files/7074442/logs_841.zip)

### PS:
- Issue is debugged as part of https://github.com/kadalu/kadalu/issues/633
- Trimmed much of the info to avoid debug effort from your side and decrease noise
- Most probably this'll be related to underlying buildx however just checking if any other users faced the same in release CI which'll reduce overall time in reusing the fix
- Please let me know if more info is required

Thanks.
