### ISSUE TITLE
GAR error "cannot reuse body, request must be retried"

### ISSUE THREAD

**Issue by bchrobot** [docker/build-push-action#452]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

- [x] I have read `TROUBLESHOOTING.md`.

I wasn't sure from the "Cannot push to a registry" section whether your preference is for issues to be opened here or in the linked tools' repos.

### Behaviour

Pushing image to GAR sometimes fails with error:

```
ERROR: failed commit on ref "manifest-sha256:0f17d0ea56a824cc2efa0ad1ded3e1dc540cdb3d0468feebb0b5506853c90f82": cannot reuse body, request must be retried
```

#### Steps to reproduce this issue

1. Make and push a commit
2. See build stage of `build-push-action@v2` succeed
3. See push stage of `build-push-action@v2` fail with above error

It seems only to happen for commits that only touch files excluded from the Docker build context. However, the action does occasionally succeed this type of commit.

#### Expected behaviour

Push stage should succeed.

#### Actual behaviour

Push stage fails with error.

### Configuration

* Repository URL (if public): https://github.com/politics-rewired/fly-shortener
* Build URL (if public): https://github.com/politics-rewired/fly-shortener/runs/3461355947

```yml
name: CI/CD Pipeline

on:
  push:

jobs:
  publish-docker-image:
    if: github.ref == 'refs/heads/master'
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          buildkitd-flags: --debug

      # Caching strategy from: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
      - name: Cache Docker layers for ${{ matrix.service }}
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-fly-shortener-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-fly-shortener-

      - name: Get image tags
        id: image-tags
        run: |
          export GIT_SHA="${{ github.sha }}"
          export GIT_SHA_SHORT=${GIT_SHA:0:7}
          echo "::set-output name=sha::$GIT_SHA_SHORT"

      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: us-east4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push ${{ matrix.service }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            us-east4-docker.pkg.dev/assemble-services/apps/link-shortener:latest
            us-east4-docker.pkg.dev/assemble-services/apps/link-shortener:${{ steps.image-tags.outputs.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

### Logs

[1_Set up job.txt](https://github.com/docker/build-push-action/files/7076608/1_Set.up.job.txt)
[2_Checkout.txt](https://github.com/docker/build-push-action/files/7076607/2_Checkout.txt)
[3_Set up Docker Buildx.txt](https://github.com/docker/build-push-action/files/7076598/3_Set.up.Docker.Buildx.txt)
[4_Cache Docker layers for.txt](https://github.com/docker/build-push-action/files/7076606/4_Cache.Docker.layers.for.txt)
[5_Get image tags.txt](https://github.com/docker/build-push-action/files/7076609/5_Get.image.tags.txt)
[6_Login to GAR.txt](https://github.com/docker/build-push-action/files/7076604/6_Login.to.GAR.txt)
[7_Build and push.txt](https://github.com/docker/build-push-action/files/7076601/7_Build.and.push.txt)
[12_Post Build and push.txt](https://github.com/docker/build-push-action/files/7076605/12_Post.Build.and.push.txt)
[13_Post Login to GAR.txt](https://github.com/docker/build-push-action/files/7076602/13_Post.Login.to.GAR.txt)
[15_Post Set up Docker Buildx.txt](https://github.com/docker/build-push-action/files/7076603/15_Post.Set.up.Docker.Buildx.txt)
[16_Post Checkout.txt](https://github.com/docker/build-push-action/files/7076599/16_Post.Checkout.txt)
[17_Complete job.txt](https://github.com/docker/build-push-action/files/7076600/17_Complete.job.txt)

**Comment by crazy-max** [comment]
Any idea @jonjohnsonjr?

**Comment by jonjohnsonjr** [comment]
That error is coming from containerd, and I'm guessing it has to do with trying to tag a manifest twice. I've seen some weird behavior here with containerd before. Does this reproduce for other registries as well?

From the logs, you can see `latest` succeeds but `9df20d4` fails because the body is nil (maybe it's been consumed?). I think this is failing client side and never hitting AR.

```
2021-08-30T11:52:30.3730482Z #20 exporting to image
2021-08-30T11:52:30.3731060Z #20 exporting layers done
2021-08-30T11:52:30.3732346Z #20 exporting manifest sha256:0f17d0ea56a824cc2efa0ad1ded3e1dc540cdb3d0468feebb0b5506853c90f82 done
2021-08-30T11:52:30.3734438Z #20 exporting config sha256:a1abf24a596a2ba4f7bba8ae7e5bfbbbb39bf191650e5303e5bf72298a5932ed done
2021-08-30T11:52:30.3735696Z #20 pushing layers
2021-08-30T11:52:30.7846533Z #20 pushing layers 0.5s done
2021-08-30T11:52:30.7849034Z #20 pushing manifest for us-east4-docker.pkg.dev/assemble-services/apps/link-shortener:latest@sha256:0f17d0ea56a824cc2efa0ad1ded3e1dc540cdb3d0468feebb0b5506853c90f82
2021-08-30T11:52:30.8976654Z #20 pushing manifest for us-east4-docker.pkg.dev/assemble-services/apps/link-shortener:latest@sha256:0f17d0ea56a824cc2efa0ad1ded3e1dc540cdb3d0468feebb0b5506853c90f82 0.1s done
2021-08-30T11:52:31.3493672Z #20 pushing layers 0.3s done
2021-08-30T11:52:31.3497309Z #20 pushing manifest for us-east4-docker.pkg.dev/assemble-services/apps/link-shortener:9df20d4@sha256:0f17d0ea56a824cc2efa0ad1ded3e1dc540cdb3d0468feebb0b5506853c90f82
2021-08-30T11:52:31.4681656Z #20 pushing manifest for us-east4-docker.pkg.dev/assemble-services/apps/link-shortener:9df20d4@sha256:0f17d0ea56a824cc2efa0ad1ded3e1dc540cdb3d0468feebb0b5506853c90f82 0.2s done
2021-08-30T11:52:31.4704771Z #20 ERROR: failed commit on ref "manifest-sha256:0f17d0ea56a824cc2efa0ad1ded3e1dc540cdb3d0468feebb0b5506853c90f82": cannot reuse body, request must be retried
```

**Comment by bchrobot** [comment]
@jonjohnsonjr we had trouble getting `docker/login-action@v1` to work with GCR so we've only used `build-push-action@v2` against GAR.

It looks like containerd/containerd#3431 is where the error I'm encountering was added.

**Comment by jonjohnsonjr** [comment]
@dmcgowan any ideas?

**Comment by dmcgowan** [comment]
I have usually seen this show up in the past when a registry returns a redirect on PUT since the body has already started upload. I can't look at the registry log right now, but that is a known reason why the body is requested multiple times on push.

**Comment by jonjohnsonjr** [comment]
> I have usually seen this show up in the past when a registry returns a redirect on PUT since the body has already started upload.

Makes sense, thanks. We don't do that, so I'm guessing some other error is causing the request to fail, which can't be retried because the body was consumed?

> Pushing image to GAR sometimes fails with error:

How often does this happen? If it's not very frequent, it's possible that this is just some networking issue that needs to be retried?

I would say buildx should probably add some retries ~here: https://github.com/docker/buildx/blob/8d64b6484f9681a71233d439896b949064f3921c/util/imagetools/create.go#L157-L168

Unfortunately, there's nothing in https://github.com/containerd/containerd/pull/3431 that makes it easy to know that the request needs to be retried... so maybe containerd needs some mechanism to signal this? As a hack, you could look for the string `request must be retried`, but that's obviously not ideal.

**Comment by jonjohnsonjr** [comment]
If it happens roughly half the time, I wonder if there is some race condition here?

I see that at least some portion of pushes are happening in a separate goroutine: https://github.com/docker/buildx/blob/8d64b6484f9681a71233d439896b949064f3921c/vendor/github.com/containerd/containerd/remotes/docker/pusher.go#L239-L256

I'm not familiar enough with buildx/buildkit/containerd to reasonably trace through who's calling what, but this looks particularly gnarly and perhaps causing some races: https://github.com/docker/buildx/blob/8d64b6484f9681a71233d439896b949064f3921c/build/build.go#L545-L806

I see that containerd uses this tracker to determine the status of different refs: https://github.com/docker/buildx/blob/8d64b6484f9681a71233d439896b949064f3921c/vendor/github.com/containerd/containerd/remotes/docker/status.go#L53-L67

I'm guessing that something is calling containerd concurrently in an unsafe way. Alternatively, there might be some race condition in containerd causing this. I'm not sure.

**Comment by akhilerm** [comment]
Hitting the same error when trying to push the images using 
```
ctr images push  quay.io/akhilerm/node-disk-manager:latest docker.io/akhilerm/node-disk-manager:ci
```

I am hitting when running the above command with different tags. What I have seen so far is, the first push always works. But from the second push , its kind of flaky. with the error `ctr: failed commit on ref "index-sha256:15303a32445f10470c0a8acde338002985f909c9b275d988202ad5cf5e04b247": cannot reuse body, request must be retried`

**Comment by Sleepful** [comment]
Happened just now, "Re run all jobs" is good enough

**Comment by sanchezpaco** [comment]
Hi, I've been struggling with this problem and the only solution I've found is to add a label in docker buildx command.
Example:
```
docker --context $DOCKER_CONTEXT buildx build  --platform linux/amd64,linux/arm64 -t $CONTAINER_BASE_IMAGE --push --label "git-commit=$CI_COMMIT_SHA" .
```
In my case I was having the problem in 2 different pipelines that didn't touch the docker build context.

Maybe you'll need to change CI_COMMIT_SHA to something like a timestamp.

Hope this helps!

**Comment by gustavovalverde** [comment]
Another workaround for this is adding labels with timestamps using docker's metadata-action https://github.com/docker/metadata-action

```yaml
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: name/app
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```
