### ISSUE TITLE
cannot find package.json file

### ISSUE THREAD

**Issue by Ruoyu-Klaus** [docker/build-push-action#456]
### Behaviour

<img width="618" alt="210902213402" src="https://user-images.githubusercontent.com/57642283/131853274-e3b77084-a825-4706-9dc1-88025a0a2d3c.png">

> cannot build on GitHub action but can be built successfully in my local machine

**Comment by Ruoyu-Klaus** [comment]
I used multistage builds in my dockerfile

```
FROM node:alpine3.14 as builder

RUN apk --update add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata

RUN mkdir app

WORKDIR app

COPY package*.json .
RUN yarn 
COPY . .
RUN yarn build 

FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html
COPY --from=builder /app/build .

```

**Comment by crazy-max** [comment]
@Ruoyu-Klaus 

> successfully in my local machine

Don't think that's an issue with the action but your project. Check your gitignore (`admin_app/package.sjon` looks missing).

**Comment by Ruoyu-Klaus** [comment]
> @Ruoyu-Klaus
> 
> > successfully in my local machine
> 
> Don't think that's an issue with the action but your project. Check your gitignore (`admin_app/package.sjon` looks missing).


I don't think this is a gitignore issue either. as you can see it was successfully install packages on previous step  on 187-196 


> ### Behaviour
> <img alt="210902213402" width="618" src="https://user-images.githubusercontent.com/57642283/131853274-e3b77084-a825-4706-9dc1-88025a0a2d3c.png">
> 
> > cannot build on GitHub action but can be built successfully in my local machine

**Comment by crazy-max** [comment]
@Ruoyu-Klaus Can't tell without reproducer, do you have a link to your repo? Also `COPY package*.json` will not include anything in `/admin_app`.

**Comment by Ruoyu-Klaus** [comment]
Here is my code.

**Dockerfile**
```dockerfile
FROM node:alpine3.14 as builder

RUN apk --update add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata

RUN mkdir admin_app

WORKDIR /admin_app

COPY package*.json .
RUN yarn 
COPY . .
RUN yarn build 

FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html
COPY --from=builder /admin_app/build .

```

**dockerignore file** 

```
.git
.gitignore
node_modules/
build
.github/
```

**github action yml**

```
name: Admin CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  standard-check:
    name: build
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    
    # add some lint checkout here
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./admin/Dockerfile.prod
        push: true
        tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/test:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

```


I was wondering how is going wrong? I set the workdir at first begin and I did copy the entire directory into /admin_app by `copy . .` in my dockfile. It runs perfectly in my local machine with this dockerfile. 


It seems after  `COPY package.josn ` and `RUN yarn`, github action ignored package.json file by ` COPY . . ` for some reasons?

**Comment by mt-empty** [comment]
Was this fixed, I have the same issue. I wish to ignore `dist` directory. But even though I'm using `path context`, thje build is not successful when I have `dist` in my `.gitignore`.

Any solutions?

```yaml
name: CI to Docker Hub
on:
  push:
    branches: [devOps/mt/docker]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vision:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

```

.dockerignore

```
node_modules
npm-debug.log
.git
.gitignore
.github
.husky
.DS_Store
.vscode
.dockerignore
Dockerfile
*.md
.env*
```
