### ISSUE TITLE
Return image digest as action output

### ISSUE THREAD

**Issue by ngraef** [docker/build-push-action#46]
To better support [image pinning](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier), this action should output the image digest after pushing to a registry. The digest could then be used as a parameter for a future step in the workflow, like triggering a deployment.

**Comment by EronWright** [comment]
Here's a workaround to use in combination with the `tag_with_sha` option.  Simply put, compute the git short SHA and use it.

```
      - name: Get Git Short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${{ github.sha }} | cut -c1-7)"

      - name: Publish Docker Image
        uses: docker/build-push-action@v1
        with:
          repository: myorg/myrepository
          tag_with_sha: true

      - name: Use Docker Image (Example)
        run: docker pull "myorg/myrepository:sha-${{ steps.slug.outputs.sha7 }}"

```
