### ISSUE TITLE
Feature request: Allow specifying subdirectory with default git context

### ISSUE THREAD

**Issue by PiDelport** [docker/build-push-action#460]
When using git repository contexts, Docker allows specifying a subdirectory using the syntax `<repo>#<ref>:<subdir>`, as documented here:

* https://docs.docker.com/engine/reference/commandline/build/#git-repositories

BuildKit used to not support this feature, but as of BuildKit 0.9.0, it does:

* Release notes: https://github.com/moby/buildkit/releases/tag/v0.9.0
* https://github.com/moby/buildkit/issues/1684
* https://github.com/moby/buildkit/pull/2116

Can this action add support for this, to avoid the need to use checkouts to build subdirectories?

### Workaround

For the time being, specifying a full git context seems to work; for example, to build subdirectory `spam`:

```yaml
      - uses: docker/build-push-action@v2
        with:
          context: "https://github.com/${{ github.repository }}.git#${{ github.sha }}:spam"
```

However, this doesn't use the same logic for determining the default git context as the action does, so it might be fragile.

**Comment by PiDelport** [comment]
Related issues:

* https://github.com/docker/build-push-action/issues/120
* https://github.com/docker/build-push-action/issues/169
* https://github.com/docker/build-push-action/issues/346
* https://github.com/docker/build-push-action/issues/365

**Comment by crazy-max** [comment]
@PiDelport 

> However, this doesn't use the same logic for determining the default git context as the action does, so it might be fragile.

Indeed. I guess we could provide a magic var for this with something like:

```yaml
      - uses: docker/build-push-action@v2
        with:
          context: "{{ defaultContext }}"
```

**Comment by dimaqq** [comment]
IMO this is still way too hard to get right...
1. when does specifying `context: ...` require explicit checkout step? always? sometimes?
2. when things go wrong, build fails with mysterious `failed to fetch remote` 😕 

Ideally the UX could be something like this:
* in local checkout you do `cd some/sub/dir; docker build .`
* in the GHA, specify e.g. `subdir: some/sub/dir`

Or maybe:
* in local I ran `docker build -t xx -f subdir/docker/Dockerfile subdir`
* in the GHA, I'd specify `file: subdir/docker/Dockerfile` and `path: subdir`

**Comment by igorcosta** [comment]
The suggested workaround doesn't work for private repos.

```
      - uses: docker/build-push-action@v2
        with:
          context: "https://github.com/${{ github.repository }}.git#${{ github.sha }}:spam"
``` 

When I tried this, I get the following error. 

````
Error: buildx failed with: error: failed to solve: failed to read dockerfile: failed to fetch remote 

````
I suspect because it's a private repository, it doesn't work. I guess will work only with public repos.

**Comment by PiDelport** [comment]
Yes, for private repositories, you'll probably need to add credentials from an appropriate environment variable to the URL.

**Comment by simensol** [comment]
@PiDelport Do you have an example on how to add credentials to the URL?

**Comment by karm435** [comment]
@simensol you can use this for Private repos

```
with:
  push: true
  tags: user/app:latest
  secrets: |
      GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
```
