### ISSUE TITLE
Digest output is image ID, not RepoDigest

### ISSUE THREAD

**Issue by jsok** [docker/build-push-action#461]
### Troubleshooting

The output called `digest` is not in fact the digest that can be used to pull the image that was pushed to the repository.
The `metadata` output has the same ID listed as `"containerimage.digest"`.

#### Steps to reproduce this issue

1. Use docker/build-push-action@v2 to build and push any image
2. View the outputs of the step

#### Expected behaviour

> Tell us what should happen

The output named `digest` should contain the digest of the image, not the ID.

i.e. the output of `docker inspect $IMAGE | jq .[].RepoDigests`

#### Actual behaviour

> Tell us what happens instead

The output named `digest` contains the Image ID, i.e. the output of `docker inspect $IMAGE | jq .[].ID`

### Configuration

* Repository URL (if public): https://hub.docker.com/layers/163513701/sajari/docd/1.2.0/images/sha256-abe87bda82fdf472763c5782bd787154fd5196dbf37bb5b94b3c757df71f0de3?context=repo

DockerHub reports the Digest to be: `sha256:abe87bda82fdf472763c5782bd787154fd5196dbf37bb5b94b3c757df71f0de3`

* Build URL (if public):  https://github.com/sajari/docconv/runs/3377464865?check_suite_focus=true

`docker/build-push-action@v2` outputs a digest of `sha256:e72b6e4b4ed5763c94bfde0320282c8a3125152d8f2325d015c37a01eed2a9b2`

* Workflow definition: https://github.com/sajari/docconv/actions/runs/1148980570/workflow

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

[1_Publish Docker image.txt](https://github.com/docker/build-push-action/files/7118953/1_Publish.Docker.image.txt)

**Comment by crazy-max** [comment]
@jsok Can you rerun this workflow please? `metadata` output has been added recently (#412), I would like to see the output. Can you also add at the end of your workflow these steps:

```yaml
      -
        name: Check manifest
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect sajari/docd:${{ steps.meta.outputs.version }}
      -
        name: Inspect image
        if: github.event_name != 'pull_request'
        run: |
          docker pull sajari/docd:${{ steps.meta.outputs.version }}
          docker image inspect sajari/docd:${{ steps.meta.outputs.version }}
```

**Comment by jsok** [comment]
@crazy-max unfortunately I can't modify the workflow at this point in time, but I have re-run the workflow so that it pulls the latest version of this action.

The metadata shows the same image ID, not the digest reported by the remote.

See:
* https://github.com/sajari/docconv/runs/3583107491?check_suite_focus=true
![Screen Shot 2021-09-13 at 2 38 21 pm](https://user-images.githubusercontent.com/737907/133024821-f4ede41d-68cc-4f0b-b027-ad14893b5007.png)
* https://hub.docker.com/layers/sajari/docd/1.2.0/images/sha256-21c624dfe69e5cee36f23dfbe5ade4de371d537c4880ae5aa7e183caafb65887?context=explore
![Screen Shot 2021-09-13 at 2 38 37 pm](https://user-images.githubusercontent.com/737907/133024838-892447f5-5008-4dee-aabe-2a3def7db607.png)

**Comment by jeffhollan** [comment]
Can confirm I am seeing the same thing. The digest output here does not match the digest shown in the registry (in my case, ghcr.io).  So I'm  thinking need to write a small action to get the right diget so I can use as an output to pull via `digest`

**Comment by tobsenll** [comment]
I also can confirm that issue with an image pushed to AWS ECR. As stated the output "digest" seems to something else (didn't investigate but I believe it's the image id). With that I can't use the output to use it in another step to pull the image

**Comment by k3nda** [comment]
I had a same problem. 
I use workaround without using `docker/build-push-action` and use raw docker to build, push and output digest.
```
      - name: Build and push
        id: build-and-push
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
        run: |
          docker build -f docker/Dockerfile -t ${{ env.IMAGE }} .
          docker push ${{ env.IMAGE }}
          echo "::set-output name=digest::$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.IMAGE }} | cut -d'@' -f2)"
```

**Comment by jsok** [comment]
There's no need to abandon `docker/build-push-action`, the current `digest` output is a reference to the locally built image, e.g.:

```yaml
    - id: build
      uses: docker/build-push-action@v2
      with: { ... }
    - name: Get image digest
      id: digest
      run: echo "::set-output name=digest::$(docker inspect ${{ steps.build.outputs.digest }} | jq -r '.[].RepoDigests[0] | split("@") | .[1]')"
```

**Comment by jsok** [comment]
Having dug deeper on this issue, the `digest` output contains the remote digest **if you run `docker/setup-buildx-action`** before building.

If you do not call setup-buildx, then it seems to incorrectly populate `digest` with the local image ID as reported in the OP.

**Comment by lnhrdt** [comment]
I can also confirm that the digest is incorrect unless including the `docker/setup-buildx-action` step.

[The README](https://github.com/docker/build-push-action#usage) says the step is not required but assists with multi-platform images, export cache. I don't have those use-cases so I left it out. Given how `docker/build-push-action` produces incorrect digests without it, I'm inclined to think of it as required!

Thanks @jsok for sharing the fix.

**Comment by mattmoor** [comment]
I just hit this putting together a small sample, and can also confirm that the workaround "fixes" this, but this feels like a pretty bad bug.  Would the maintainers be receptive to a fix, if this is just a bandwidth problem?

**Comment by crazy-max** [comment]
> 

Thanks for your feedback, will take a look and come back to you.

**Comment by ndeloof** [comment]
Suggested workaround unfortunately doesn't work on ECR:

```
> Setting outputs
  digest=sha256:be1fd4e317d06d7c6d82586152de642e527f1fc71e9f6514b90f40b5659a7e77
  metadata={
    "containerimage.digest": "sha256:be1fd4e317d06d7c6d82586152de642e527f1fc71e9f6514b90f40b5659a7e77"
  }

docker inspect xxx:foo | jq .[].RepoDigests
[
  "xxx:foo@sha256:aa7ec75a318f3e4a879e0939d97c900d82440b1aea26cebea04bb4a722109092",
]
```
![screen 2021-12-23 à 17 24 54](https://user-images.githubusercontent.com/132757/147267390-4418dfb9-cfc8-4b64-897f-c5fea8cb4a01.png)

**Comment by crazy-max** [comment]
https://github.com/docker/buildx/pull/975 should fix this issue. You can try it with:

```yaml
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: https://github.com/crazy-max/buildx.git#moby-remotedgst
```
