### ISSUE TITLE
outputs.digest and outputs.metadata are not set when using docker/setup-buildx-action@v1 step

### ISSUE THREAD

**Issue by hkennyv** [docker/build-push-action#464]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

Hello, thank you for all of the awesome work on this. It's super useful, however I believe I've found a minor bug.

I was trying to use an image I built in a subsequent step using `outputs.digest`. I was successful but then tried to implement a build cache as seen in [this article](https://www.docker.com/blog/docker-github-actions/). However, it seems that in order to use the build cache and the `cache-from` and `cache-to` inputs, we need to run the `docker/setup-buildx-action@v1` step. After adding that step, it seems to break the `outputs.digest` and `outputs.metadata`.

#### Steps to reproduce this issue

I created a [repository](https://github.com/hkennyv/test-build-push-action) where this behavior is reproduced (see the 2 commits).

1. Add a Dockerfile to your repository

**Dockerfile**

```
FROM alpine
CMD ["echo", "hello world!"]
```

2. add a `.github/workflows/build.yml` file to your repository **without the docker/setup-buildx-action@v1** step

**.github/workflows/build.yml**

```yml
name: build

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build the image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ./Dockerfile
          context: .
      - name: Echo digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
```

3. Commit and push these 2 files up and you should see that the digest is set and successfully echo'd out

```
Setting outputs
  digest=sha256:5f4af4324157ff71b0107aaa1316c917b97d41d87a0052b031bc83ce764a764e
  metadata={
    "containerimage.digest": "sha256:5f4af4324157ff71b0107aaa1316c917b97d41d87a0052b031bc83ce764a764e"
  }
```

4. Change the `.github/workflows/build.yml` to include the **docker/setup-buildx/action@v1** step

**.github/workflows/build.yml (updated)**

```yml
name: build

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup docker build (breaks outputs.digest)
        uses: docker/setup-buildx-action@v1
      - name: Build the image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ./Dockerfile
          context: .
      - name: Echo digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
```

5. Commit the new changes and push up and notice that the image digest is **not** set nor echo'd

```
Setting outputs
  metadata=null
```

#### Expected behaviour

It's expected to output the image digest and metadata.

#### Actual behaviour

It doesn't output the image digest or metadata. Could it be due to `buildx.getImageID()` and `buildx.getMetadata()` returning null/falsy?

https://github.com/docker/build-push-action/blob/375f72aff65b645c51f122f04a776df8416b222b/src/main.ts#L36-L47

### Configuration

* Repository URL (if public): https://github.com/hkennyv/test-build-push-action
* Build URL (if public): https://github.com/hkennyv/test-build-push-action/actions

The configuration that is not behaving as expected:

```yml
name: build

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup docker build (breaks outputs.digest)
        uses: docker/setup-buildx-action@v1
      - name: Build the image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ./Dockerfile
          context: .
      - name: Echo digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

Logs w/o docker/setup-buildx-action@v1 step:

[logs_1.zip](https://github.com/docker/build-push-action/files/7201399/logs_1.zip)

Logs w/ docker/setup-buildx-action@v1 step:

[logs_2.zip](https://github.com/docker/build-push-action/files/7201391/logs_2.zip)
