### ISSUE TITLE
413 Request Entity Too Large with Node applications

### ISSUE THREAD

**Issue by jpcarpanezi** [docker/build-push-action#466]
### Behaviour
I'm trying to implement a build and push my Node.JS application CI/CD, but a error was returned every time with Node.JS Dockerfile only: `Error: buildx failed with: error: failed to solve: failed to copy: unexpected status: 413 Request Entity Too Large`. I've used docker/build-push-action@v2.7.0 with my .NET applications with 9 projects to push and i didn't have this error.

#### Steps to reproduce this issue

1. Setup Dockerfile with Node.JS project
```Dockerfile
FROM node:14.17.6-alpine
WORKDIR /usr/src/

COPY package*.json ./

RUN npm install

COPY . .

CMD ["node", "app.js"]
```
2. Setup Github Actions Workflow

#### Expected behaviour

> Builds should push with no issues as my .NET 5 applications using the same CI workflow.

#### Actual behaviour

> Build stopping with error `Error: buildx failed with: error: failed to solve: failed to copy: unexpected status: 413 Request Entity Too Large`

### Configuration

```yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and Push Gateway
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: mycustomregistry.com/project/my-tag:latest
```
