### ISSUE TITLE
How to build from another branch?

### ISSUE THREAD

**Issue by MinistrBob** [docker/build-push-action#467]
How to build from another branch?

I have workflow trigger on branch = gs-release, but `docker/build-push-action@v2` get codes from master.
```
on:
  push:
    branches: [ gs-release ]
    paths:
      - 'src/**'
      - 'public/**'      
      - 'Dockerfile'
      - '*.json'
  pull_request:
    branches: [ gs-release ]
    paths:
      - 'src/**'
      - 'public/**'      
      - 'Dockerfile'
      - '*.json'
```

I try use that:
```
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: devasteam/deva-crm:latest
          ref: 'gs-release'
```

but I get warning and that not help:
`Warning: Unexpected input(s) 'ref', valid inputs are ['allow', 'build-args', 'builder', 'cache-from', 'cache-to', 'context', 'file', 'labels', 'load', 'network', 'no-cache', 'outputs', 'platforms', 'pull', 'push', 'secrets', 'secret-files', 'ssh', 'tags', 'target', 'github-token']`
