### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories)

### ISSUE THREAD

**Issue by johannesjo** [docker/build-push-action#468]
### Troubleshooting
Check here for complete log:
https://github.com/johannesjo/super-productivity/runs/3685017502?check_suite_focus=true

### Behaviour
When executing git commands I get the error 

#### Expected behaviour
Git command works as intended.

#### Actual behaviour
Does not work.

### Configuration

* Repository URL (if public):  https://github.com/johannesjo/super-productivity
* Build URL (if public): https://github.com/johannesjo/super-productivity/runs/3685017502?check_suite_focus=true

```yml
name: Publish Docker image To hub.docker

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs: null

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: johannesjo/super-productivity

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
```

### Logs

https://github.com/johannesjo/super-productivity/runs/3685017502?check_suite_focus=true
