### ISSUE TITLE
Cannot access Internet while building an image on arm64

### ISSUE THREAD

**Issue by jamezrin** [docker/build-push-action#471]
### Troubleshooting

When building an image on an arm64 platform, the Dockerfile cannot access the internet, so things like installing dependencies fail.

#### Steps to reproduce this issue

Build an image with the arm64 platform

#### Expected behaviour

It should behave like the amd64 platform, having complete access to the network.

#### Actual behaviour

Any connection inside the Dockerfile fails, so the image build fails.

### Configuration

* Repository URL (if public): https://github.com/jamezrin/timeit-webapp
* Build URL (if public): https://github.com/jamezrin/timeit-webapp/runs/3708864481

```yml
name: Build Images and Deploy to Personal Registry

on:
  push:
    branches: [master]

concurrency:
  group: build-images
  cancel-in-progress: true

env:
  REGISTRY: registry.jamezrin.name

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Login to my Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: (frontend) Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./packages/frontend/Dockerfile
          tags: ${{ env.REGISTRY }}/timeit-webapp/timeit-frontend:latest
      - name: (backend) Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./packages/backend/Dockerfile
          tags: ${{ env.REGISTRY }}/timeit-webapp/timeit-backend:latest
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue
[logs_1137.zip](https://github.com/docker/build-push-action/files/7230048/logs_1137.zip)
