### ISSUE TITLE
I want to ask about platform

### ISSUE THREAD

**Issue by XRSec** [docker/build-push-action#477]
> I want to create a docker container for [CDR](https://github.com/cdr/code-server) and adapt M1

#### Dockerfile.yml

```dockerfile
RUN if test `uname -p` = "x86_64"; then wget -O /www/bak/code-server.rpm `curl https://api.github.com/repos/cdr/code-server/releases/latest | grep "browser_download_url"  | cut -d '"' -f 4 | grep amd64.rpm` --no-cookie --no-check-certificate; fi \
    if test `uname -p` = "aarch64"; then wget -O /www/bak/code-server.rpm `curl https://api.github.com/repos/cdr/code-server/releases/latest | grep "browser_download_url"  | cut -d '"' -f 4 | grep arm64.rpm` --no-cookie --no-check-certificate; fi
```
#### Github Action

```yaml
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            xrsec/vscode:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

#### Dockerfile.yml

```dockerfile
RUN wget -O /www/bak/code-server.rpm `curl https://api.github.com/repos/cdr/code-server/releases/latest | grep "browser_download_url"  | cut -d '"' -f 4 | grep amd64.rpm` --no-cookie --no-check-certificate
```

#### Dockerfile_Arm64.yml

```dockerfile
RUN wget -O /www/bak/code-server.rpm `curl https://api.github.com/repos/cdr/code-server/releases/latest | grep "browser_download_url"  | cut -d '"' -f 4 | grep arm64.rpm` --no-cookie --no-check-certificate
```
#### Github Action

```yaml
      - 
        name: Build and push Docker image with Amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            xrsec/vscode:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - 
        name: Build and push Docker image with Arm
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: true
          file: Docfile-Arm.yml
          tags: |
            xrsec/vscode:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

## however

Because I need to compile php74 and php56, the performance may be a little slow, so I want to listen to optimization suggestions. Thank you

**Comment by XRSec** [comment]
[Code-Server-Update](https://github.com/XRSec/Code-Server-Update)

[cdr/code-server](https://github.com/cdr/code-server)

**Comment by crazy-max** [comment]
@XRSec It sounds like this is your first time starting to use multi-platform support. Before using our GitHub actions, I suggest you check out the documentation to learn how to leverage cross-platform support for your Docker image. Here are some links to get you started:

* https://docs.docker.com/desktop/multi-arch/
* https://docs.docker.com/buildx/working-with-buildx/
* https://forums.docker.com/

Once you have something running on your computer, you can use multi platform support with our GitHub Actions: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

If you encounter issues with the GitHub Action, you can open a [bug report](https://github.com/docker/build-push-action/issues/new?assignees=&labels=&template=bug_report.md) by specifying the behavior, configuration, workflow and logs.

**Comment by XRSec** [comment]
I've used docker to compile images, but I haven't tried cross-platform compilation, so I have some doubts about your multi-system compilation. If a software needs to manually select software packages with corresponding architectures, how do you choose when Docker compiles images? I see that the output seems that every command will be executed by using the container of the specified architecture, but I love that you are not clear about its working mode, and at present, you have not found any specific compilation process and case about github action multi-architecture in your documents.

**Comment by XRSec** [comment]
I hope you can add these links to the README, which is really my negligence. Sorry to bother you, thank you.

**Comment by XRSec** [comment]
@crazy-max

**Comment by XRSec** [comment]
@crazy-max 
I want to know how to complete my steps by using your action? For example, specify dockerfiles of different system architectures in action at the same time

amd64 > Dockerfile
arm64 > DockerfileArm

I've read all the documents you sent, but I haven't found a specific workflow yet.

**Comment by XRSec** [comment]
```yml
name: CobaltStrike Build

on: push

jobs:
  build_job_amd64:
    name: CobaltStrike Build Amd64
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - 
        name: Download Java-Amd64
        run: wget -O .github/jdk.rpm https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm --no-cookie --no-check-certificate
      - 
        name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            xrsec/cobaltstrike:4.4
            xrsec/cobaltstrike:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build_job_arm64:
      name: CobaltStrike Build Arm64
      runs-on: ubuntu-latest
      steps:
        - 
          name: Private Actions Checkout
          uses: actions/checkout@v2.3.4
        - 
          name: Docker Setup QEMU
          uses: docker/setup-qemu-action@v1.2.0
        - 
          name: Docker Setup Buildx
          uses: docker/setup-buildx-action@v1.6.0
        - 
          name: Download Java-Arm64
          run: |
            rm -rf .github/jdk.rpm
            wget -O .github/jdk.rpm https://download.oracle.com/java/17/latest/jdk-17_linux-aarch64_bin.rpm --no-cookie --no-check-certificate
        - 
          name: Docker Login
          uses: docker/login-action@v1.10.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - 
          name: Build and push Docker images
          uses: docker/build-push-action@v2.7.0
          with:
            context: .
            platforms: linux/arm64
            push: true
            tags: |
              xrsec/cobaltstrike:4.4
              xrsec/cobaltstrike:latest
            cache-from: type=gha
            cache-to: type=gha,mode=max
```
