### ISSUE TITLE
can not use the file generated by last step

### ISSUE THREAD

**Issue by mar-heaven** [docker/build-push-action#483]
### Troubleshooting

i just generated files before,but can not be founded when building image
### Behaviour
 ERROR: "/log.txt" not found: not found

#### Steps to reproduce this issue
this is part of my yml 
```
# build images
      - name: build wheel
        run: |
           touch log.txt
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caesar123/ireaders:${{ env.IMAGE_TAG }}
```
this is part of my dockerfile
```
# dockerfile
COPY log.txt /tmp/log.txt
```

#### Expected behaviour

> i hope can use generated file when build image,thanks!

#### Actual behaviour

> the file cannot be founded
