### ISSUE TITLE
Can I ignore a file using .gitignore if the file is used in the build process?

### ISSUE THREAD

**Issue by mt-empty** [docker/build-push-action#484]
I'm using a multi stage dockerfile and I wish to ignore `dist` directory using `.gitignore`. 

But even though I'm using `path context`, the build is not successful when I have `dist` in my `.gitignore`.

Any solutions?

```yaml
name: CI to Docker Hub
on:
  push:
    branches: [devOps/mt/docker]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vision:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

```

dockerfile

```dockerfile
FROM node:14-alpine AS BUILD_STAGE

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

FROM gcr.io/distroless/nodejs:14

WORKDIR /app

COPY --from=BUILD_STAGE /usr/src/app ./

EXPOSE 3000

CMD ["server.js"]

```

.dockerignore

```
node_modules
npm-debug.log
.git
.gitignore
.github
.husky
.DS_Store
.vscode
.dockerignore
Dockerfile
*.md
.env*
```
