### ISSUE TITLE
Using tag on release as Docker tag in v2

### ISSUE THREAD

**Issue by Cecilia-Sensalari** [docker/build-push-action#491]
Hi,
I have been using v1 but I now have to migrate to v2 in order to use buildx.
I used to build and push to Docker Hub on release an image with tag `latest` and with a tag that was the same of the release tag (e.g. `v1.1` from release `v1.1`) using `tag_with_ref`. However based on this [Stack overflow](https://stackoverflow.com/questions/67984172/github-actions-github-event-release-tag-name-always-null) issue and this [issue on GitHub](https://github.com/docker/build-push-action/issues/116#issuecomment-692143724) I have the feeling that this is no longer possible with version 2, without any extra steps in the yaml pipeline.

This is the code with v1 that allowed me to do that (the last two lines in particular):
```yml
name: Push DockerHub CI
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: myrepository
          tags: latest
          tag_with_ref: true
```
Most examples I find are related to `on push` and are not related to `on release`.

Are these suggestions on stack overflow and the GitHub issue valid? If not, could one point me to the documentation where this scenario is explained with v2? And if this is not possible with v2, are there plans in supporting it in the future so we don't need to use a custom action to support this feature from v1?
