### ISSUE TITLE
Add git action secrets to env var

### ISSUE THREAD

**Issue by b2r2** [docker/build-push-action#496]
Hello everyone!

I tried setting env from git action secrets, but this method did not work for me #https://github.com/docker/build-push-action/issues/390 what's wrong?

Dockerfile:

```
# syntax=docker/dockerfile:1.2
FROM golang:1.17.1-alpine3.14 as build

RUN sed -i 's/https\:\/\/dl-cdn.alpinelinux.org/http\:\/\/mirror.clarkson.edu/g' /etc/apk/repositories && apk add git --no-cache
WORKDIR /usr/local/app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN go build -ldflags "-s -w" ...

FROM alpine:3.14 as myapp

RUN sed -i 's/https\:\/\/dl-cdn.alpinelinux.org/http\:\/\/mirror.clarkson.edu/g' /etc/apk/repositories && apk add ca-certificates --no-cache

RUN --mount=type=secret,id=TOKEN \
    export TOKEN=$(cat /run/secrets/TOKEN)

WORKDIR /usr/local/app
COPY --from=build /usr/local/app/myapp /bin/myapp

CMD /bin/myapp
```

git action workflow:

```
...
    steps:
      -
        name: Check code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_LOGIN}}/${{ secrets.DOCKER_NAME }}:latest
          secrets: |
            "TOKEN=${{ secrets.TOKEN_DEV }}"
```

Inside the application, I get env variable through simple function:
```
func GetEnv(key string, defaultVal string) string {
	if value, exists := os.LookupEnv(key); exists {
		return value
	}

	return defaultVal
}
```
