### ISSUE TITLE
GHA cache doesn't work when building multiple images

### ISSUE THREAD

**Issue by princemaple** [docker/build-push-action#497]
~Is this by design and what is the recommended way of using it?~

~If it's a bug, please confirm. Thanks!~

Looks like it's been confirmed as a bug.

```
# ...

  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: my-own-registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push App
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: my-own-registry/my-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

^ This takes 28s to finish after the first run

The following takes 4 minutes every single run. And the second app is actually simpler, so it shouldn't have taken much longer.

The truth is the cache is not used at all.

```
# ...

  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: my-own-registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push App
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: my-own-registry/my-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push App 2
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: my-own-registry/my-other-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
```
