### ISSUE TITLE
Example for Cache-Froms option

### ISSUE THREAD

**Issue by robpc** [docker/build-push-action#50]
Can an example of how to use the `cache-froms` option in a github workflow be added to the documentation? I was unable to figure out a way to use it that actually took advantage of the option. Looking at the [go utility code](https://github.com/docker/github-actions/pull/17), it just adds the option to the build command, but that will do nothing when there is no local cache (ie a CB scenario like this). In my experience you need to pull the image first and the [original issue](https://github.com/docker/build-push-action/issues/7#issue-582971038) asks for that as well. I did some testing and was unable to get it to work. It was indistinguishable from not using it. 

```yaml
- name: Docker Build
  uses: docker/build-push-action@v1
  with:
    registry: quay.io
    repository: ${{ env.quayio_repo }}
    username: ${{ env.quayio_user }}
    password: ${{ secrets.QUAY_AUTH }}
    tags: >-
      ${{ env.docker_tag }},
      ${{ env.docker_cache_tag }}
    cache_froms: ${{ env.quayio_repo }}:${{ env.docker_cache_tag }}
```
My [original comment](https://github.com/docker/build-push-action/issues/7#issuecomment-625844246) from the original issue.

**Comment by hholst80** [comment]
Unless this feature works with service it makes very little sense to use it to us if we require cache-from. I think we have the correct understanding how it should be used, but it looks very ugly.

```
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker.pkg.github.com
        run: docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Pull cache from docker.pkg.github.com
        run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
      - uses: docker/build-push-action@v1
        with:
          username: hholst80
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hholst80/test
          tags: latest
          cache_froms: docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache
      - name: Tag new cache image
        run: docker tag hholst80/test:latest docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache
      - name: Push cache to docker.pkg.github.com
        run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache
```
