### ISSUE TITLE
Test image with multiple tags from metadata-action

### ISSUE THREAD

**Issue by sim642** [docker/build-push-action#506]
There's an example on how to load and test an image with a fixed tag: https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md. But I'm using metadata-action to potentially build and push images with multiple tags, thus just trying to run `${{ steps.meta.outputs.tags }}` won't work.

Previously I didn't use gha cache and then `${{ steps.build.outputs.digest }}` seemed to work for `docker run`. But since adding caching (and thus `docker/setup-buildx-action`), this doesn't work anymore:
```
 docker: Error response from daemon: No such image: sha256:6507963a29515198ef9813243ad16cd47e864a05594682b66e0de32fbc9196e2.
```
I guess it's somehow related to #461, but I don't really care what digest is what and where it's shown. I just want to run the loaded image.

I also tried `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}`, but that doesn't work for running the locally loaded image either:
```
Unable to find image 'ghcr.io/goblint/analyzer@sha256:53a5a659327deceb4ea5f1a9e89d6648cd8069d2b5bc59d7b75d1199987fd768' locally
```

**How is this supposed to be done?**

**Comment by crazy-max** [comment]
@sim642 

> How is this supposed to be done?

Pretty much the same as the example from https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md:

```yaml
name: ci

on:
  push:
    branches:
      - 'master'

env:
  TEST_TAG: myapp:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: name/app
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

**Comment by sim642** [comment]
The example completely misses my entire point of _multiple tags_ given by the metadata-action. The example just hardcodes a single tag. When using metadata-action to dynamically determine tags, some builds may get multiple and there might not be a single tag that's always present. Even the `latest` tag wouldn't be applied to _all_ builds (e.g. edge or PRs).

The value of `${{ steps.meta.outputs.tags }}` is separated by newlines (or commas if reconfigured), but neither is suitable to be passed as an image name argument to `docker run`, if there happen to be multiple tags built simultaneously.

**Comment by crazy-max** [comment]
@sim642 Don't really get your point of using the metadata action in the step that exports the image to docker to be able to test it but you can use the [`${{ steps.meta.outputs.version }}` output](https://github.com/docker/metadata-action#outputs):

```yaml
      -
        name: Test
        run: |
          docker run --rm name/app:${{ steps.meta.outputs.version }}
```

Or the [JSON output](https://github.com/docker/metadata-action#json-output-object):

```yaml
      -
        name: Test
        run: |
          docker run --rm ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
```
