### ISSUE TITLE
Login failed : eu.gcr.io

### ISSUE THREAD

**Issue by cvalentin-dkt** [docker/build-push-action#508]
Hello,

i try to build & push to my GCP Registry, but I can't authenticate on the build-push :/

docker/login-action@v1 => Success
docker/build-push-action@v2 => Failed

Github Action : 
```

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry:	eu.gcr.io
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push ${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: eu.gcr.io/${{ env.GCP_PROJECT_ID }}/fastapi:${{ steps.version.outputs.version }}
```

Output : 
![image](https://user-images.githubusercontent.com/81801129/143057372-f7b55b84-465a-400f-8f67-fab51772461a.png)
![image](https://user-images.githubusercontent.com/81801129/143057455-c9b07ecb-98b0-43b9-991e-4afcb8139fca.png)

Have you idea ?
