### ISSUE TITLE
secrets passed to docker/build-push-action as undefined

### ISSUE THREAD

**Issue by udos** [docker/build-push-action#509]
I am trying to create and push an image of my VueJs app which uses Auth0 for authentication.

building it locally works well.

building it with build-push-action does not. my assumption is that I am doing something wrong and the error is on my side :|

to me it appears as if env variable **_VUE_APP_AUTH_DOMAIN_** is being passed to docker/build-push-action as **_undefined_** resulting in this url:

- https://_**undefined**_/authorize?scope=xxx

instead something like the following should be passed:

- https://some-specific-subdomain.auth0.com/authorize?client_id=

the secret is configured as following:

- **_VUE_APP_AUTH_DOMAIN=some-specific-subdomain.auth0.com_**

my yml looks like this:

```yml
name: Dockerize and Push to Docker Hub

on:
  pull_request:
    branches: ['master']

jobs:
  dockerize-pr:
    if: ${{ github.event_name == 'pull_request' }}
    name: dockerize on pull request
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      # vue app env variables - BEGIN
      VUE_APP_AUTH_DOMAIN: ${{ secrets.VUE_APP_AUTH_DOMAIN_DEV }}
      # note: I also tried to set a clear text variable -> still "undefined"
      #VUE_APP_AUTH_DOMAIN: some-specific-subdomain.auth0.com
      VUE_APP_AUTH_CLIENTID: ${{ secrets.VUE_APP_AUTH_CLIENTID_DEV }}
      # vue app env variables - END
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: udos/ts-ui
          tags: |
            type=ref,event=pr
            type=ref,event=tag
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

I would really appreaciate if you guys could have a look and potentially point out the place where I am missing something. thanks!
