### ISSUE TITLE
Unexpected dockerignore behaviour

### ISSUE THREAD

**Issue by igorGevaerd** [docker/build-push-action#511]
### Behaviour

The following `.dockerignore` file produced different docker images when running on github actions than when it was executed on my machine:
```.dockerignore
/**

!/api
!/config
!/extensions
!/public
!/favicon.ico
!/package.json
!/yarn.lock
```

#### Steps to reproduce this issue

1. clone a Strapi repo (eg https://github.com/kevinadhiguna/strapi-dockerize);
2. `docker build -t local-test-build:1 -f Dockerfile .`;
3. define an github actions job using `docker/build-push-action@v2`;
4. compare both images produced, paying attention to the directories defined on the on the `.dockerignore` file previously described.

#### Expected behaviour

> Both images created should have the same files inside their directories, even the ones defined on the `.dockerignore` file

#### Actual behaviour

> On the image built locally, directories such as `/api` or `/config` have their content copied from the repository. But it is not happening with the images from the workflow, which the directories are completely empty.

### Configuration

* Repository URL (if public): https://github.com/kevinadhiguna/strapi-dockerize (not mine, but works as an example) 
* Build URL (if public): xxx

```yml
---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
    - api/**
    - config/**
    - extensions/**
    - public/**
    - .dockerignore
    - Dockerfile
    - favicon.ico
    - package.json
    - yarn.lock
  push:
    branches:
    - main
    paths:
    - api/**
    - config/**
    - extensions/**
    - public/**
    - .dockerignore
    - Dockerfile
    - favicon.ico
    - package.json
    - yarn.lock
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Short SHA
      id: sha
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.ABC }}
        password: ${{ secrets.XYZ }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha8 }}
          ghcr.io/${{ github.repository }}:latest
```

**Comment by crazy-max** [comment]
@igorGevaerd This is a known issue that should be fixed since [buildx 0.7.1](https://github.com/docker/buildx/releases/tag/v0.7.1)

But looks like GitHub Runners have not been updated yet and are still using [buildx 0.7.0](https://github.com/docker/build-push-action/runs/4442303020?check_suite_focus=true#step:6:4) so I would suggest to add the [`setup-buildx-action`](https://github.com/docker/setup-buildx-action) step in the meantime:

```yaml
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.1

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha8 }}
          ghcr.io/${{ github.repository }}:latest
```
