### ISSUE TITLE
Unable to provide git reference to checkout in docker build

### ISSUE THREAD

**Issue by EmteZogaf** [docker/build-push-action#516]
### Troubleshooting

The wrong git reference is used as docker build context when it differs from current workflow context.

### Behaviour

I have two workflows, where the second is triggered when the first succeeds. The second workflow is executed in the default branch. no matter in which branch/tag the first workflow has been executed. To be able to checkout the same git reference i can use the context property `${{ github.event.workflow_run.head_branch }}` and use this for the `ref` input parameter in the `actions/checkout` action. But the `docker/build-push-action` has no git reference input parameter. It is always checking out the git reference the workflow is executed in.

#### Steps to reproduce this issue

1. Set up to workflows _A_ and _B_ where B is triggered after the successful execution of A.
2. Create and checkout a new branch and commit changes to Dockerfile (e.q. change `MAINTAINER`).
3. Push the new branch to github.

#### Expected behaviour

In workflow _B_ the `docker/build-push-action` action should use the same git reference as the `actions/checkout` action has used for the checkout or there should be an input parameter to overwrite the default git reference to be used in the docker build step similar to the `actions/checkout` action. The resulting docker image should contain the changes of the branch workflow _A_ was executed in.

#### Actual behaviour

The `docker/build-push-action` always using the git reference given by the github context of the workflow _B_ which is the github repository's default branch (e.q. `main`).

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

Workflow _A_
```yml
name: A
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Dockerfile exists
      run: test -f Dockerfile
```
Workflow _B_
```yml
name: B
on:
  workflow_run:
    workflows: ["A"]
    types: [completed]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
```

**Comment by crazy-max** [comment]
@EmteZogaf If you use the Git context with this action it will not use files from your `Checkout Repository` step at all but the ref that triggered your workflow as shown [here](https://github.com/docker/build-push-action/blob/b1aeb1103e6b3b5648dbd6deaf0559919456ca6b/src/context.ts#L42-L54)

Suggest to use the [Path context](https://github.com/docker/build-push-action#path-context) instead with `context: .`:

```yaml
name: B
on:
  workflow_run:
    workflows: ["A"]
    types: [completed]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
```
