### ISSUE TITLE
Error: buildx failed with: error: failed to solve: lstat /tmp/buildkit-mount ... no such file or directory

### ISSUE THREAD

**Issue by chjeningka** [docker/build-push-action#517]
### Behaviour
Since Dec 13th, all builds on our maven project have starting failing when trying to build the docker image from our Java jar (placed in the /target dir by maven): 

```
Error: buildx failed with: error: failed to solve: lstat /tmp/buildkit-mount270447651/target: no such file or directory
```

#### Steps to reproduce this issue

1. Use build-push-action with no issues for several months
2. ???

The only thing I could spot that was different from a successful build was an update from 0.7.1+azure-1 to 0.7.0+azure-1 in buildx
What was also suspicious is that when it tries to transfer the build context, in the last successful run it was several kilobytes and in the (now) failing one(s) it is only a few bytes, which would indicate to me it is failing to transfer the build context for some reason?

Otherwise I don't have a good way to reproduce this, all the code is private and we've had no issues until now.

#### Expected behaviour

Should successfully access files from maven build in previous step, and use it in the Dockerfile as normal.

#### Actual behaviour

Since Dec 13th, failing with: 
```
Error: buildx failed with: error: failed to solve: lstat /tmp/buildkit-mount270447651/target: no such file or directory
```

### Configuration

* Repository URL (if public): (private)
* Build URL (if public): (private)

```yml
name: Push some-service artifacts

on:
  push:
    branches:
      - develop
    paths:
      - 'some-service/**'
  workflow_dispatch:

env:
  <removed>

jobs:
  deploy-artifacts:
    name: 'Deploy artifacts'
    environment: development
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
      - uses: actions/checkout@v2

      # Setup the Java environment, and Maven credentials
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Make mvnw executable
        run: chmod +x mvnw

      # Setup settings.xml
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: <removed>

      # Setup environment variables to be used for publishing and tagging
      - name: Set timestamp env var
        run: |
          echo "TIMESTAMP=$(date "+%Y%m%d%H%M%S")" >> $GITHUB_ENV
      - name: Set prerelease env var
        run: |
          echo "PRERELEASE=$(echo "-$TIMESTAMP.$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Set artifact and version env vars
        run: |
          echo "ARTIFACT=$(./mvnw help:evaluate -f ./some-service/pom.xml -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "VERSION=$(./mvnw help:evaluate -f ./some-service/pom.xml -Dexpression=project.version -Drevision=${PRERELEASE} -q -DforceStdout)" >> $GITHUB_ENV

      # Login to Artifactory for the emulator container
      - name: Login to artifactory
        run: |
          docker login ${{ env.ARTIFACTORY_REGISTRY }} -u ${ARTIFACTORY_USERNAME} --password ${ARTIFACTORY_PASSWORD}
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      # Build all modules
      - name: Build packages and install them
        run: ./mvnw clean install -B --no-transfer-progress

      # Build and Publish Jar to Artifactory
      - name: Publish package to Artifactory Snapshots
        run: ./mvnw clean deploy -B --no-transfer-progress -pl some-service
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      # Setup & Login Docker to Artifactory & Google Cloud Registry
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Docker to Artifactory Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ARTIFACTORY_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Login Docker to Google Cloud Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GCLOUD_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      # Push Docker images to repositories
      - name: Build and push Docker Images
        uses: docker/build-push-action@v2
        with:
          context: some-service/
          file: some-service/Dockerfile
          push: true
          tags: |
            ${{ env.ARTIFACTORY_REGISTRY }}/${{ env.ARTIFACTORY_REPOSITORY }}/${{ env.ARTIFACT }}:latest
            ${{ env.ARTIFACTORY_REGISTRY }}/${{ env.ARTIFACTORY_REPOSITORY }}/${{ env.ARTIFACT }}:${{ env.VERSION }}
            ${{ env.GCLOUD_REGISTRY }}/${{ env.GCLOUD_REPOSITORY }}/${{ env.ARTIFACT }}:latest
            ${{ env.GCLOUD_REGISTRY }}/${{ env.GCLOUD_REPOSITORY }}/${{ env.ARTIFACT }}:${{ env.VERSION }}

```

### Logs

I can't post everything, but here are the relevant logs:
```
Current runner version: '2.285.1'
Operating System
  Ubuntu
  20.04.3
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20211209.3
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211209.3/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211209.3
Virtual Environment Provisioner
  1.0.0.0-main-20211208-1
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
Download action repository 'actions/setup-java@v2' (SHA:5f00602cd1b2819185d88dc7a1b1985f598c6705)
Download action repository 'whelk-io/maven-settings-xml-action@v4' (SHA:4637f7c31534ec06928b10da807735657a921266)
Download action repository 'docker/setup-buildx-action@v1' (SHA:94ab11c41e45d028884a99163086648e898eed25)
Download action repository 'docker/login-action@v1' (SHA:f054a8b539a109f9f41c372932f1ae047eff08c9)
Download action repository 'docker/build-push-action@v2' (SHA:a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229)
...
Run ./mvnw clean deploy -B --no-transfer-progress -pl some-service
  ./mvnw clean deploy -B --no-transfer-progress -pl some-service
  shell: /usr/bin/sh -e ***0***
...

[INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ some-service ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:29 min
[INFO] Finished at: 2021-12-14T07:21:04Z
[INFO] ------------------------------------------------------------------------

...

Run docker/setup-buildx-action@v1
Docker info
  /usr/bin/docker version
  Client:
   Version:           20.10.11+azure-2
   API version:       1.41
   Go version:        go1.16.8
   Git commit:        dea9396e184290f638ea873c76db7c80efd5a1d2
   Built:             Wed Nov 17 23:49:46 2021
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  
  Server:
   Engine:
    Version:          20.10.11+azure-2
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.16.8
    Git commit:       847da184ad5048b27f5bdf9d53d070f731b43180
    Built:            Thu Nov 18 00:21:59 2021
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.4.12+azure-1
    GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
   runc:
    Version:          1.0.2
    GitCommit:        52b36a2dd837e8462de8e01458bf02cf9eea47dd
   docker-init:
    Version:          0.19.0
    GitCommit:        
  /usr/bin/docker info
  Client:
   Context:    default
   Debug Mode: false
   Plugins:
    buildx: Docker Buildx (Docker Inc., 0.7.1+azure-1)
    compose: Docker Compose (Docker Inc., 2.1.1+azure-2)
  
  Server:
   Containers: 1
    Running: 1
    Paused: 0
    Stopped: 0
   Images: 22
   Server Version: 20.10.11+azure-2
   Storage Driver: overlay2
    Backing Filesystem: extfs
    Supports d_type: true
    Native Overlay Diff: false
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: cgroupfs
   Cgroup Version: 1
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
   Swarm: inactive
   Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
   runc version: 52b36a2dd837e8462de8e01458bf02cf9eea47dd
   init version: 
   Security Options:
    apparmor
    seccomp
     Profile: default
   Kernel Version: 5.11.0-1022-azure
   Operating System: Ubuntu 20.04.3 LTS
   OSType: linux
   Architecture: x86_64
   CPUs: 2
   Total Memory: 6.789GiB
   Name: fv-az190-761
   ID: 6ASE:4GFF:22QI:7MQP:6754:5BWP:2QKV:G5B6:3O77:ZI3Y:WQRN:3UCX
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Username: githubactions
   Registry: https://index.docker.io/v1/
   Labels:
   Experimental: false
   Insecure Registries:
    127.0.0.0/8
   Live Restore Enabled: false
  
Creating a new builder instance
Booting builder
Inspect builder
BuildKit version
  moby/buildkit:buildx-stable-1 => buildkitd github.com/moby/buildkit v0.9.3 8d2625494a6a3d413e3d875a2ff7dd9b1ed1b1a9

...

Run docker/build-push-action@v2
  with:
    context: some-service/
    file: some-service/Dockerfile
    push: true
    tags: <omitted>
  
    load: false
    no-cache: false
    pull: false
    github-token: ***
  env:
...
Docker info
/usr/bin/docker buildx build --tag <omitted> --iidfile /tmp/docker-build-push-Rk0voq/iidfile --metadata-file /tmp/docker-build-push-Rk0voq/metadata-file --file some-service/Dockerfile --push some-service/
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 491B 0.0s done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context:
#2 transferring context: 2B done <-- SUSPICIOUS?
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/adoptopenjdk/openjdk11@sha256:dff0d568f419ded8076980f07ed92d7e339c9fc0b84340dd5bec4f90d487d7d2
#3 ...

#4 [auth] adoptopenjdk/openjdk11:pull token for registry-1.docker.io
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/adoptopenjdk/openjdk11@sha256:dff0d568f419ded8076980f07ed92d7e339c9fc0b84340dd5bec4f90d487d7d2
#3 DONE 0.7s

#7 [internal] load build context
#7 transferring context: 2B 0.0s done
#7 DONE 0.0s

#5 [1/4] FROM docker.io/adoptopenjdk/openjdk11@sha256:dff0d568f419ded8076980f07ed92d7e339c9fc0b84340dd5bec4f90d487d7d2
#5 resolve docker.io/adoptopenjdk/openjdk11@sha256:dff0d568f419ded8076980f07ed92d7e339c9fc0b84340dd5bec4f90d487d7d2 done
#5 sha256:339de151aab4bc06eed8409daae147c408478cb538dacb90cc63f19ad4eba80b 2.80MB / 2.80MB 0.1s done
#5 extracting sha256:339de151aab4bc06eed8409daae147c408478cb538dacb90cc63f19ad4eba80b
#5 sha256:c6f92ee85ef800cac0fd34e5ad380263a81173ee61b021b25b9fe3650adca4eb 10.49MB / 43.30MB 0.2s
#5 sha256:b43e9138b02c0568445c5e748f4767703cac0fa480302332c1790707a850e639 6.39MB / 6.39MB 0.2s done
#5 extracting sha256:339de151aab4bc06eed8409daae147c408478cb538dacb90cc63f19ad4eba80b 0.2s done
#5 sha256:c6f92ee85ef800cac0fd34e5ad380263a81173ee61b021b25b9fe3650adca4eb 27.26MB / 43.30MB 0.3s
#5 extracting sha256:b43e9138b02c0568445c5e748f4767703cac0fa480302332c1790707a850e639
#5 sha256:c6f92ee85ef800cac0fd34e5ad380263a81173ee61b021b25b9fe3650adca4eb 30.41MB / 43.30MB 0.5s
#5 extracting sha256:b43e9138b02c0568445c5e748f4767703cac0fa480302332c1790707a850e639 0.2s done
#5 sha256:c6f92ee85ef800cac0fd34e5ad380263a81173ee61b021b25b9fe3650adca4eb 38.80MB / 43.30MB 0.6s
#5 sha256:c6f92ee85ef800cac0fd34e5ad380263a81173ee61b021b25b9fe3650adca4eb 43.30MB / 43.30MB 0.8s
#5 sha256:c6f92ee85ef800cac0fd34e5ad380263a81173ee61b021b25b9fe3650adca4eb 43.30MB / 43.30MB 0.9s done
#5 extracting sha256:c6f92ee85ef800cac0fd34e5ad380263a81173ee61b021b25b9fe3650adca4eb
#5 extracting sha256:c6f92ee85ef800cac0fd34e5ad380263a81173ee61b021b25b9fe3650adca4eb 1.0s done
#5 DONE 1.9s

#6 [2/4] RUN addgroup -S appuser && adduser -S -G appuser appuser
#6 DONE 1.9s

#8 [3/4] COPY --chown=appuser:appuser target/**.jar /home/appuser/app.jar
#8 ERROR: lstat /tmp/buildkit-mount693681329/target: no such file or directory
------
 > [3/4] COPY --chown=appuser:appuser target/**.jar /home/appuser/app.jar:
------
Dockerfile:9
--------------------
   7 |     USER appuser
   8 |     
   9 | >>> COPY --chown=appuser:appuser target/**.jar /home/appuser/app.jar
  10 |     WORKDIR /home/appuser/
  11 |     
--------------------
error: failed to solve: lstat /tmp/buildkit-mount693681329/target: no such file or directory
Error: buildx failed with: error: failed to solve: lstat /tmp/buildkit-mount693681329/target: no such file or directory
```

**Comment by chjeningka** [comment]
Posting here for others running across this strange issue, credit to one of our team members for figuring this out!

He found that from version 0.7.0 to 0.7.1 buildx changed how wildcards are processed in dockerfiles:
https://github.com/docker/buildx/releases/tag/v0.7.1

In our file we have this line that uses wildcards:
```
COPY --chown=appuser:appuser target/**.jar /home/appuser/app.jar
```

We didn't want to change this for now, so the simplest solution was to specify the version like so:
```
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v1
  with:
     version: v0.7.0
```
