### ISSUE TITLE
docker pull access denied

### ISSUE THREAD

**Issue by chaiyd** [docker/build-push-action#524]
logs 
```
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.84kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B 0.0s done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/openjdk:8u312-slim-bullseye
#3 ...

#4 [auth] library/openjdk:pull token for registry-1.docker.io
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/library/openjdk:8u312-slim-bullseye
#3 DONE 0.4s

#11 [internal] load build context
#11 DONE 0.0s

#17 [auth] library/builder:pull token for registry-1.docker.io
#17 DONE 0.0s

#5 [stage-0  1/10] FROM docker.io/library/openjdk:8u312-slim-bullseye@sha256:25efb6e0609b95af243b4e3ce2c27dbc1022ef2a4db2164b7afa066c0db18137
#5 resolve docker.io/library/openjdk:8u312-slim-bullseye@sha256:25efb6e0609b95af243b4e3ce2c27dbc1022ef2a4db2164b7afa066c0db18137 done
#5 sha256:25efb6e0609b95af243b4e3ce2c27dbc1022ef2a4db2164b7afa066c0db18137 549B / 549B done
#5 sha256:3da584e507d1fd0355e830e5a448b087c2d9e7a293f5d5adcb082249444dea8e 1.16kB / 1.16kB done
#5 sha256:9afd0fe33df7e1513c21d04a7bf1ec0997c8ecb270fd56d4368c49373fd2452c 7.52kB / 7.52kB done
#5 sha256:2bbde5250315969db657b55bd8b2f5507fb659c0cf7f135edc84b684ffeab44a 1.58MB / 1.58MB 0.1s done
#5 sha256:115191490c27ffaa2624b0351dec9b9899456b3cd3abb6a2aa7470a4e4000512 212B / 212B 0.1s done
#5 CANCELED

#9 FROM docker.io/library/builder:latest
#9 resolve docker.io/library/builder:latest 0.1s done
#9 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
------
 > FROM docker.io/library/builder:latest:
------
error: failed to solve: failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error: buildx failed with: error: failed to solve: failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

![image](https://user-images.githubusercontent.com/34934673/147066534-c9fa9d77-3267-4305-b9c4-802b1e5854be.png)

**Comment by crazy-max** [comment]
Can you post your workflow or a link to your repo?

**Comment by chaiyd** [comment]
> Can you post your workflow or a link to your repo?

- https://github.com/chaiyd/nacos-docker.git
```
name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
#       - name: Log in to the Container registry
#         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GIT_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            chaiyd/nacos
#            ghcr.io/${{ github.repository }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./build
          file: ./build/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
