### ISSUE TITLE
How to run image?

### ISSUE THREAD

**Issue by JasonFreeberg** [docker/build-push-action#525]
Read through the README but couldn't find anything on this. How do I run the image after I've built it? Example:

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: test_build

      - run: docker image ls
      
      - name: Run image against tests
        run: docker run test_build /usr/src/ff_bot/setup.py test
```

The image doesn't show when I run `docker image ls`.
