### ISSUE TITLE
Question: how to pass arguments to go build inside Dockerfile?

### ISSUE THREAD

**Issue by tobiasehlert** [docker/build-push-action#526]
I have a Dockerfile that is supposed to build an application in go and I want to specify parameter with the `-ldflags` option. On this way I can specify the version of application, that has been released.

From what I can see, there is no possibility to add that parameter to the action that would allow some values be passed in from the GitHub workflow into the Dockerfile by using _ARG_.

Can the [docker/build-push-action#inputs](https://github.com/docker/build-push-action#inputs) be used for such thing as forwarding arguments (ARG) into the the Dockerfile that I can add to the _go build_ command?

**Comment by crazy-max** [comment]
@tobiasehlert You can with `build-args` input:

```yaml
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            ARG1=foo
            ARG2=bar
          push: true
          tags: user/app:latest
```
