### ISSUE TITLE
Action doesn't perform git checkout

### ISSUE THREAD

**Issue by BeyondEvil** [docker/build-push-action#528]
#### Expected behaviour

According to README:

> By default, this action uses the Git context so you don't need to use the actions/checkout action to checkout the repository because this will be done directly by buildkit. 

#### Actual behaviour

Checkout doesn't happen.

### Configuration

This

```yml
      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: ${{ env.ECR_REGISTRY }}/proxyco/madmax-api:stable
```

fails with error:

```
/usr/local/bin/docker buildx build --tag ***.dkr.ecr.us-west-2.amazonaws.com/proxyco/madmax-api:stable --iidfile /tmp/docker-build-push-s6cfCu/iidfile --metadata-file /tmp/docker-build-push-s6cfCu/metadata-file --push ./app
error: unable to prepare context: path "./app" not found
Error: buildx failed with: error: unable to prepare context: path "./app" not found
```

I have to explicitly do a checkout first, for the build to be successful.

```yml
      - uses: actions/checkout@v2

      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: ${{ env.ECR_REGISTRY }}/proxyco/madmax-api:stable
```

It's a private repo.

This is run on a self-hosted runner using ubuntu-latest.

What am I doing wrong?

**Comment by actualben** [comment]
You're specifying a path context string (`./app`) which overrides the described automagic. 

It looks like you want to specify a subdir on your build. You can still have most of the automagic by specifying the context as a full git repo URL in the way described by the [docker build docs' description of Git Repo URLs](https://docs.docker.com/engine/reference/commandline/build/#git-repositories). You'd use one with a trailing `:app`. Something like:

```yaml
context: https://github.com/proxyco/madmax-api#${{ env.GITHUB_REF }}:app
```

To make it a bit more reusable you can do something like:

```yaml

jobs:
  buildo:
    runs-on: ubuntu-latest
    env:
      CONTEXT_SUBDIR: app
    steps:
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          # your ecr details here
      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY}}#${{ env.GITHUB_REF }}:${{ env.CONTEXT_SUBDIR }}
          push: true
          tags: ${{ env.ECR_REGISTRY }}/proxyco/madmax-api:stable

```
