### ISSUE TITLE
Pass platform dependent build parameters

### ISSUE THREAD

**Issue by spuder** [docker/build-push-action#529]
This step works great to build multiple platforms simultaneously `platforms: linux/amd64,linux/arm64`

```
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: spuder/openscad:latest
```

However there does not appear to be a way to pass a platform dependent environment variable to the build step. 

For example, say you have a Dockerfile like this

```
ARG ARCH=x86_64 # aarch64
RUN wget https://files.openscad.org/OpenSCAD-2021.01-${ARCH}.AppImage
```

How would you set `ARCH` to x86_64 for the `linux/amd64` builds, but `aarch64` for the `linux/arm64` builds?

**Comment by crazy-max** [comment]
@spuder You can use the `TARGETPLATFORM` arg that is part of the [ARGs in the global scope](https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope) that will match the target platform available.

See https://github.com/crazy-max/docker-docker/blob/782b584781cd0130798a6640c37d40476c532a10/Dockerfile-20.10#L14-L23 as an example to use it.

**Comment by spuder** [comment]
Ah thank you for the quick response. 

I mostly got it working by using `matrix`, but I think `TARGETPLATFORM` will be a cleaner solution

```
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - download_arch: x86_64
            platforms: linux/amd64
          - download_arch: aarch64
            platforms: linux/arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.platforms }}
          buildargs: ARCH=${{matrix.buildargs }}
          push: true
          tags: spuder/openscad:latest
          ```
