### ISSUE TITLE
RUN echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} >> ./.npmrc not cached with local cache

### ISSUE THREAD

**Issue by anthonyma94** [docker/build-push-action#534]
#### Steps to reproduce this issue

1. Run action.
2. Run action again.
3. View all cached actions.

#### Expected behaviour

Everything should be cached as nothing has changed.

#### Actual behaviour

`RUN echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} >> ./.npmrc` step is not cached, therefore the `yarn install` after is not cached either.

### Configuration

```Dockerfile
...
FROM node:lts-alpine AS deps
ARG GITHUB_TOKEN

WORKDIR /app

COPY package.json yarn.lock ./
RUN echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} >> ./.npmrc
RUN echo @companyname:registry=https://npm.pkg.github.com/ >> ./.npmrc
RUN yarn install --frozen-lockfile
RUN echo > ./.npmrc
...
```

```yml
name: Build Docker Image
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

### Logs

Attached the log for build and push step.
[log.txt](https://github.com/docker/build-push-action/files/7808880/log.txt)
