### ISSUE TITLE
buildx call failed with: error: denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by Recedivies** [docker/build-push-action#535]
Hi, I am trying to build and push a container to dockerhub as following
```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: devopsdockeruh/coursepage:latest
```
Unfortunately I am getting error "buildx call failed with: error: denied: requested access to the resource is denied". Am I doing wrong?
