### ISSUE TITLE
Failed to compute cache key: "/tsconfig.json": not found

### ISSUE THREAD

**Issue by bennodev19** [docker/build-push-action#537]
### Behavior

If I trigger the `build-and-deploy-backend` workflow
it starts creating the Docker Image but fails at the line `23` in the `server/Dockerfile`:
```
  22 |     COPY ./src ./src
  23 | >>> COPY ./tsconfig.json ./
```
See: https://github.com/bennodev19/dronies-watch/runs/4813916640?check_suite_focus=true

Locally it builds without any problem. Tested on MacOS and Windows10.

`build-and-deploy-backend`
```yaml
# *

jobs:
  build-and-deploy-backend:
    name: 🛠 Build Backend Image for Prod & Push to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v2

      - name: 🐳 Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: 🐳 Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🐳 Build and push Docker Image to DockerHub
         id: docker_build
         uses: docker/build-push-action@v2
         with:
          context: .
          file: server/Dockerfile # Path to the Dockerfile from which to build the Docker Image from (default {context}/Dockerfile)
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```
See full file: https://github.com/bennodev19/dronies-watch/blob/master/.github/workflows/release.yaml

`server/Dockerfile`
```
FROM node:lts-alpine

RUN mkdir -p /app
WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
RUN yarn install

COPY src ./src
COPY tsconfig.json ./

RUN yarn build

CMD [ "yarn", "start" ]

EXPOSE 5000
```
See full file: https://github.com/bennodev19/dronies-watch/blob/master/server/Dockerfile

#### Expected behavior

It should build the Image without the mentioned issue, like it does on a local machine.

#### Actual behavior

It crashes with this error message:
```
Dockerfile:23
--------------------
  21 |     # Move required app source into the working directory referenced with './'
  22 |     COPY ./src ./src
  23 | >>> COPY ./tsconfig.json ./
  24 |     
  25 |     # For debugging:
--------------------
error: failed to solve: failed to compute cache key: "/tsconfig.json": not found
Error: buildx failed with: error: failed to solve: failed to compute cache key: "/tsconfig.json": not found
```
See: https://github.com/bennodev19/dronies-watch/runs/4813916640?check_suite_focus=true

### Configuration

- Repository URL:  https://github.com/bennodev19/dronies-watch

**Comment by bennodev19** [comment]
This was my issue. I didn't specify the `context` correctly, as the Dockerfile was running in the root of the project, but needed to run in the `./server` folder.

**Comment by g4c3** [comment]
for me worked:
# Node Image

```
FROM node:11.13.0-alpine as node_base_image
WORKDIR /root
COPY ["package*.json","./"]
# Installing node modules using npm install
RUN ["npm", "install"]
# Keycloak Image
FROM jboss/keycloak:15.0.2
# Copy custom folder which contain custon login and registration page
COPY custom /opt/jboss/keycloak/themes/custom
# Copy node modules from node image to keycloak image
COPY --from=node_base_image /root/ ./opt/jboss/keycloak/themes/custom/common/resources
COPY --from=node_base_image /root/ ./opt/jboss/keycloak/themes/keycloak/common/resources 
```

**Comment by ramonpaolo** [comment]
I change the service context(context of *.dockerfile)

From:
```
node:
    build: 
      context: ./docker
      dockerfile: ./node-dev.dockerfile
    image: upload_file_s3_node_dev
    container_name: upload_file_s3_node_dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:rw
      - /app/node_modules
    environment:
            - NODE_ENV=development
    networks:
      - network
```

To:
```
node:
    build: 
      context: .
      dockerfile: ./docker/node-dev.dockerfile
    image: upload_file_s3_node_dev
    container_name: upload_file_s3_node_dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:rw
      - /app/node_modules
    environment:
            - NODE_ENV=development
    networks:
      - network
```
