### ISSUE TITLE
How to push without building?

### ISSUE THREAD

**Issue by chessai** [docker/build-push-action#538]
I don't see a way to push without building. For context, I'm using `nix` to build a docker image in CI, and I would like to push the image to dockerhub, but obviously I don't need docker to build the image for me given that nix is already doing it.

**Comment by chessai** [comment]
The following seems to work:
```yaml
- name: Build docker image
  run: |
    nix build .#docker.x86_64-linux
- name: Login to DockerHub
  uses: docker/login-action@v1
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_PASSWORD }}
- name: Push docker image to DockerHub
  run: |
    docker load < result
    docker push owner/repo:tag
```

**Comment by chessai** [comment]
If there's no plan to support this, feel free to close. The above works for my use case.

**Comment by crazy-max** [comment]
@chessai Not possible with this action but your workflow seems to be a good pattern for your use case.

**Comment by alonbl** [comment]
Seems like required feature, I need also push without build, why couple these?

**Comment by ThiefMaster** [comment]
I'd like to have this feature as well. My usecase is "better security": I want to automatically build the image (and store it as an artifact) when pushing a tag, but use a protected github environment to require manual approval for triggering the final step of actually publishing the image to the registries.

**Comment by ThiefMaster** [comment]
@crazy-max None of the "workarounds" of using `docker push` seem to work well when you want to automatically generate the tags using `docker/metadata-action`... or is there some magic that will push all the tags specified in the image?

**Comment by ThiefMaster** [comment]
I don't see how this works when generating multiple tags via metadata. This example in the docs does everything within steps of a single job - but if I want to use a protected environment for the actual publishing, I need to use two *jobs*.

Currently I have this:

```yaml
      - name: Extract metadata (tags, labels) for Docker 👀
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            getindico/indico
            ghcr.io/ThiefMaster/indico
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.indico_version }}
            type=semver,pattern={{major}}.{{minor}}.x,value=${{ steps.version.outputs.indico_version }}

      - name: Build Docker image 🚢
        uses: docker/build-push-action@v4
        with:
          context: indico/worker
          build-args: tag=${{ steps.version.outputs.indico_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/indico-image.tar

      - name: Test if Indico works 🧪
        run: |
          cp indico.env.sample indico.env
          ./test.sh

      - name: Upload build artifact 🔼
        uses: actions/upload-artifact@v3
        with:
          name: image
          retention-days: 1
          path: /tmp/indico-image.tar
```

Then I have a second job which uses the protected environment to run only after manual confirmation:

```yaml
      - name: Download build artifact 🔽
        uses: actions/download-artifact@v3
        with:
          name: image
          path: /tmp/indico-image.tar
      - name: Import image 🔃
        run: |
          docker load --input /tmp/indico-image.tar
          docker image ls -a
```

So now the question is, how do I get the action to take this already-built image and upload all the tags it has in the next step.
