### ISSUE TITLE
Prevent adding latest tag

### ISSUE THREAD

**Issue by nodesocket** [docker/build-push-action#540]
It seems the tag `latest` is automatically being applied when running this action. How can I prevent adding the `latest` tag?

```yaml
      - name: Extract metadata (tags, labels) for Docker image
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
