### ISSUE TITLE
{{defaultContext}} is invalid yaml

### ISSUE THREAD

**Issue by deviantintegral** [docker/build-push-action#541]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

I'm trying the new `{{defaultContext}}` variable to build an image in a subdirectory with a git context: https://github.com/marketplace/actions/build-and-push-docker-images#usage

However, even a basic example throws "You have an error in your yaml syntax". I thought perhaps it needed to be a quoted string, and while that resolves the syntax error the action doesn't replace the template variable.

#### Steps to reproduce this issue

1. Try to build with the following workflow: https://github.com/pbkhrv/rtl_433-hass-addons/blob/73a51d224f55e2f10d4ed85fd5be7aa76902a8f5/.github/workflows/builder.yml
2. See the error in the related build log: https://github.com/pbkhrv/rtl_433-hass-addons/actions/runs/1712808308

#### Expected behaviour

The default string shown in the docs should work.

### Configuration

* Repository URL (if public): https://github.com/pbkhrv/rtl_433-hass-addons
* Build URL (if public): https://github.com/pbkhrv/rtl_433-hass-addons/actions/runs/1712808308

```yml
name: Build rtl_433 images

on:
  push:
  pull_request:

jobs:
  build:
    name: Build rtl_433 addon
    runs-on: ubuntu-latest

    steps:

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: {{defaultContext}}:rtl_433
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          ghcr.io/pbkhrv/rtl_433-hass-addons:latest
```

**Comment by crazy-max** [comment]
@deviantintegral Not released yet, you can test with `uses: docker/build-push-action@master`

**Comment by crazy-max** [comment]
@deviantintegral Should be ok now.

**Comment by deviantintegral** [comment]
Thanks! I think the docs may be published onto the Marketplace page before the actions are updated, as that's where I originally read about the feature. Regardless, glad this is sorted 🙌

**Comment by limbic-derek** [comment]
I'm having the exact same issue. w/ v2.8.0. It immediately fails and says I have a syntax error, like so:
```
You have an error in your yaml syntax on line 38
```

Here's my entire .yml:
```yml
name: Build Base Docker Container Image
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/base
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - 
       name: Docker Setup Buildx
       uses: docker/setup-buildx-action@v1.6.0

      - 
        name: Log in to GHCR
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2.8.0
        with:
          context: {{defaultContext}}:base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

I'm trying to build a `Dockerfile` in a subdir called `base`.

Any guidance?
