### ISSUE TITLE
Multiple build args don't get parsed correctly

### ISSUE THREAD

**Issue by thclark** [docker/build-push-action#543]
The `build-args` parameter behaves as a single `build-arg`.

#### Reproduction 1

1. Set your build file with comma separated list (consistent to the platforms argument)
```yml
      - name: Build and push
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: "GDAL_VERSION=${{ matrix.gdal }},BASE_IMAGE=${{ steps.vars.outputs.base_image }},INSTALL_DEV_TOOLS=${{ steps.vars.outputs.install_dev_tools }}"
          push: true
          tags: mytag
```
2. Run the action. It starts because the .yml file is valid.
3. Fails in the action because it uses the whole string as a single build arg, instead of separate build args:
![Screenshot 2022-01-21 at 12 14 20](https://user-images.githubusercontent.com/7223170/150525507-a14121dd-dcd8-450e-86fe-56389fe9561c.png)

#### Reproduction 2

1. Set your build file with comma separated list (consistent to the platforms argument)
```yml
      - name: Build and push
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args:
          - GDAL_VERSION=${{ matrix.gdal }}
          - BASE_IMAGE=${{ steps.vars.outputs.base_image }}
          - INSTALL_DEV_TOOLS=${{ steps.vars.outputs.install_dev_tools }}
          push: true
          tags: mytag
```
2. Edit in the github editor online - the linter tells you that it's not expecting a list:
![Screenshot 2022-01-21 at 11 53 39](https://user-images.githubusercontent.com/7223170/150524154-49fd179c-7590-49f0-addc-ac4ce11dfd53.png)

3. Run the action. It fails to start because incorrect type is detected, GitHub UI shows:
![Screenshot 2022-01-21 at 11 55 58](https://user-images.githubusercontent.com/7223170/150524481-994b9398-d653-4a92-839e-592b2aaa0833.png)

#### Reproduction 3

1. Same as Reproduction 2 but with array syntax because yaml is ambiguous about so many things...
![Screenshot 2022-01-21 at 11 54 26](https://user-images.githubusercontent.com/7223170/150524491-c46dff56-25d1-4bbc-8b81-62003846edfa.png)

2. Same result as Reproduction 2:
![Screenshot 2022-01-21 at 11 55 58](https://user-images.githubusercontent.com/7223170/150524481-994b9398-d653-4a92-839e-592b2aaa0833.png)

#### Expected behaviour

Both an array and a comma-separated string should be accepted as a list argument and each item in the list given its own `build-arg` flag in the call to `docker buildx build`. In reproduction above, I'd expect the command to be:
```
/usr/bin/docker buildx build --build-arg GDAL_VERSION=2.4.1 --build-arg BASE_IMAGE=python:3.8-slim-buster --build-arg INSTALL_DEV_TOOLS=false --platform linux/amd64,linux/arm64 -blahblahotherstuff .
```

#### Actual behaviour

The docs specify that build args are a list, but only accept a string
```
/usr/bin/docker buildx build --build-arg GDAL_VERSION=2.4.1,BASE_IMAGE=python:3.8-slim-buster,INSTALL_DEV_TOOLS=false --platform linux/amd64,linux/arm64 -blahblahotherstuff .
```

## Maybe not quite a workaround

I thought I could force this to work by manually prefixing all but the first build arg:
```yml
      - name: Build and push
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: "GDAL_VERSION=${{ matrix.gdal }} --build-arg BASE_IMAGE=${{ steps.vars.outputs.base_image }} --build-arg INSTALL_DEV_TOOLS=${{ steps.vars.outputs.install_dev_tools }}"
          push: true
          tags: my tags
```

That issues the correct command (which if copied verbatim into my local terminal works fine) but somehow doesn't actually pick up the build args - not sure what on earth is causing that.
