### ISSUE TITLE
Build cache for export step takes ~300s to complete

### ISSUE THREAD

**Issue by anthonyma94** [docker/build-push-action#545]
I followed the docs [here](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md) to use caching in my actions, but my job takes an extremely long time (300s on average) to prepare and export build cache to GitHub. Is there a reason the caching takes so long?

YAML file:
```
build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/<registry_name>/api:${{ github.event.release.tag_name }}
            ghcr.io/<registry_name>/api:latest
          build-args: |
            APP=api
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
```
