### ISSUE TITLE
gha cache is not working in matrix builds

### ISSUE THREAD

**Issue by Tirke** [docker/build-push-action#546]
### Behaviour

I'm building the same multi-stage image with only one `ARG` that makes the effective build different.
The images are build in parallel with a matrix build.
Here is a downsized sample of I'm really doing (only two services here)

```
build_push_services_image:
    name: Build and publish Docker images for services on github
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [worker, institution]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Build and push image
        uses: docker/build-push-action@v2
        timeout-minutes: 10
        with:
          context: .
          build-args: |
            PROJECT=${{ matrix.service }}
          load: false
          push: false
          tags: |
            ${{ env.DOCKER_TARGET_REPOSITORY }}/${{ matrix.service }}:preprod
          cache-from: type=gha, scope=${{ matrix.service }}
          cache-to: type=gha,mode=max, scope=${{ matrix.service }}
```

#### Steps to reproduce this issue

1. Use a `gha` cache with a matrix build.
2. One of the image will not fully use the cache

#### Expected behaviour

Good caching behavior each image is using a cache.

#### Actual behaviour

One of the two images being built will only have a few operations cached. I've try tinkering with `cache scope` with no success.

**Comment by kilbiller** [comment]
Try removing the space, I had the same problem some time ago and this worked `type=gha,scope=${{ matrix.service }}`.

**Comment by crazy-max** [comment]
@Tirke Might be the same behavior as https://github.com/docker/build-push-action/issues/539#issuecomment-1014367548 when you don't define any [output](https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#output). Try with `type=cacheonly`:

```yaml
      - name: Build and push image
        uses: docker/build-push-action@v2
        timeout-minutes: 10
        with:
          context: .
          build-args: |
            PROJECT=${{ matrix.service }}
          tags: |
            ${{ env.DOCKER_TARGET_REPOSITORY }}/${{ matrix.service }}:preprod
          outputs: type=cacheonly
          cache-from: type=gha,scope=${{ matrix.service }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service }}
```

**Comment by crazy-max** [comment]
@BeyondEvil `cacheonly` is a dummy exporter introduced in https://github.com/docker/buildx/pull/337 for buildkit backend in docker engine so you're able to skip all exporters because it will create an image by default. Here we are using a `docker-container` builder so this is not necessary but it allows to hide this warning message when your build starts:

```
WARNING: No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
```

You can also use the env var `BUILDX_NO_DEFAULT_LOAD=1`. 

In this workflow https://github.com/docker/build-push-action/issues/546#issuecomment-1024976978 it's just about to warm the cache.

**Comment by carlthome** [comment]
How would `push: true` change the above? I'm also not seeing any CACHED on job retry, within a build matrix.

Tried `outputs: type=cacheonly` unsuccessfully (`Error: buildx failed with: ERROR: push and "cacheonly" output can't be used together`).

```yaml
      - name: Build and push ${{ matrix.image }} image
        uses: docker/build-push-action@v4
        with:
          context: images/${{ matrix.image }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            AUTHORS=${{ github.repository_owner }},${{ github.actor }},${{ github.triggering_actor }}
            SOURCE=${{ github.repositoryUrl }}
            VERSION=${{ github.run_id }}-${{ github.run_attempt }}
            REVISION=${{ github.sha }}
          sbom: true
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}/${{ matrix.image }}:${{ github.sha }}
          cache-from: type=gha,scope=${{ github.ref_name }}-${{ matrix.image }}
          cache-to: type=gha,scope=${{ github.ref_name }}-${{ matrix.image }},mode=max
```
