### ISSUE TITLE
Image not cached using Docker caching example from docs

### ISSUE THREAD

**Issue by mn-git-hub** [docker/build-push-action#550]
### Behaviour
Using the [example workflow from the docs](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#local-cache) to build with a buildx local cache directory that is then kept in the Github Actions cache results in Docker layers still being downloaded by buildx.  The workflow's "Cache Docker Layers" step successfully restores the cache once it is warmed up, but the "Build and push" step shows layers being downloaded.
 
#### Steps to reproduce this issue

1. Create a new repo with a simple Dockerfile.
2. Add a Github Actions workflow using the [example workflow from the docs](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#local-cache).
3. Push an update to trigger a build and warm the cache.
4. Push another update to trigger another build.

#### Expected behaviour

The base image specified in the Dockerfile should be in buildx's cache and the buildx logs should simply show "CACHED" after processing the FROM line.

#### Actual behaviour

The logs show "CACHED" but then show the progress lines of various layers of the base image being downloaded.

### Configuration

* Repository with example:  https://github.com/mn-git-hub/actions-cache-test 
* Build with warmed up cache that shows the downloading: https://github.com/mn-git-hub/actions-cache-test/actions/runs/1758301913  

The only change from the example workflow config is that push is disabled.  I tried with push enabled but hit an auth issue with Dockerhub which is beyond the scope of this issue.  Also, even in that build, the cache issue was still present. 
```yml
# from https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: user/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

### Logs

[1_docker.txt](https://github.com/docker/build-push-action/files/7953757/1_docker.txt)

**Comment by crazy-max** [comment]
@mn-git-hub 

> The logs show "CACHED" but then show the progress lines of various layers of the base image being downloaded.

```
2022-01-27T20:26:00.4200322Z #10 exporting cache
2022-01-27T20:26:00.4200743Z #10 preparing build cache for export
2022-01-27T20:26:00.7000693Z #10 preparing build cache for export 0.3s done
2022-01-27T20:26:00.7001648Z #10 writing layer sha256:29fe44765632f6ee4f801a3f0643ae341fb15a1aceeea058a995142c68760fef 0.0s done
2022-01-27T20:26:00.7002252Z #10 writing layer sha256:5c69ac0246d0815a09c65c7b9a19e8a486a5ba057aed0c83bce1794bdd856f67 0.0s done
2022-01-27T20:26:00.7002764Z #10 writing layer sha256:5eb5b503b37671af16371272f9c5313a3e82f1d0756e14506704489ad9900803
2022-01-27T20:26:01.4533255Z #10 writing layer sha256:5eb5b503b37671af16371272f9c5313a3e82f1d0756e14506704489ad9900803 0.7s done
2022-01-27T20:26:01.4534058Z #10 writing layer sha256:7600197c19c2f186f0f508a79881ab7c5c4783f50cc3d62e50e8a3b8758a583e done
2022-01-27T20:26:01.4534602Z #10 writing layer sha256:8a371635d6fff6fa09b89a67aa19db524724389ec7c463e8cc35f83a2e20a990 done
2022-01-27T20:26:01.4535077Z #10 writing layer sha256:c332063af182b898527b2f08584a40b1e228ea260c17a187675474d68aa08ffb
```

These logs are just about the cache exporter. Nothing to do with the base image. Here it will export the cache to the local folder as stipulated in your build step: `cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max`.

You can check that behavior if you remove the `cache-to` input:

```yaml
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: user/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: user/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
```

Looking at your logs everything looks fine to me.
