### ISSUE TITLE
Not respecting `login` modifications

### ISSUE THREAD

**Issue by loagencydev** [docker/build-push-action#551]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. override docker config to accept an insecure repo (`echo "{ \"insecure-registries\": [\"custom-repo.net\"] }" | sudo tee /etc/docker/daemon.json`)
1. use [login-action](https://github.com/docker/login-action) to log into the private nexus repository with insecure configs
2. try to push to the repository with [build-push-action@v2](https://githjub.com/docker/build-push-action)
3. get the error `http: server gave HTTP response to HTTPS client`

#### Expected behaviour

> after adding the insecure configs to `daemon.json`, the push should also work with insecure repo

#### Actual behaviour

> getting the error `http: server gave HTTP response to HTTPS client`

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: Push to Nexus

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set insecure registry
        run: |
          echo "{ \"insecure-registries\": [\"custom-repo.net\"] }" | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            custom-repo.net/lo-agency/polaris
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Nexus Container Registry
        uses: docker/login-action@v1 
        with:
          registry: custom-repo.net
          username: ${{ secrets.NX_USERNAME }}
          password: ${{ secrets.NX_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### Logs
[logs_16.zip](https://github.com/docker/build-push-action/files/7965604/logs_16.zip)

**Comment by crazy-max** [comment]
@loagencydev You're using a `docker-container` builder with [`docker/setup-buildx-action@v1`](https://github.com/docker/setup-buildx-action#about) so it doesn't use the dockerd configuration. You have to use the [BuildKit daemon configuration](https://github.com/docker/setup-buildx-action#buildkit-daemon-configuration) like https://github.com/docker/build-push-action/issues/353#issuecomment-873641064:

```yaml
name: Push to Nexus

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            custom-repo.net/lo-agency/polaris
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            [registry."custom-repo.net"]
              http = true
              insecure = true
      -
        name: Login to Nexus Container Registry
        uses: docker/login-action@v1 
        with:
          registry: custom-repo.net
          username: ${{ secrets.NX_USERNAME }}
          password: ${{ secrets.NX_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
