### ISSUE TITLE
Error: buildx failed with: error: failed to solve: authorization status: 401: authorization failed

### ISSUE THREAD

**Issue by Lerring** [docker/build-push-action#556]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. create action as per yaml below and push to branch

#### Expected behaviour

> Image is built and pushed to docker

#### Actual behaviour

> errors with

```
#7 exporting to image
#7 pushing layers 0.5s done
#7 ERROR: authorization status: 401: authorization failed
------
 > exporting to image:
------
error: failed to solve: authorization status: 401: authorization failed
```

### Configuration

```yml

name: ci

on:
  push:
    branches:
      - 'main'
      - 'fancy'
      - 'pants'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Gattic meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: gattic/base
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
