### ISSUE TITLE
Build args 

### ISSUE THREAD

**Issue by shyam-ks** [docker/build-push-action#557]
I am trying to setup docker build in Github actions

```
- name: build-1
        run: |
          docker build . --build-arg JFROG_USERNAME=${{ secrets.JFROG_CREDS_USR }} --build-arg JFROG_PWD=${{ secrets.JFROG_CREDS_PSW }} 

      - name: build-2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: JFROG_USERNAME=${{ secrets.JFROG_CREDS_USR }},JFROG_PWD=${{ secrets.JFROG_CREDS_PSW }}
```
I have two args inside  Dockerfile

ARG JFROG_PWD
ARG JFROG_USERNAME

### Behaviour
In Dockerfile  the command is =  value="${JFROG_USERNAME}" 

The first one (build-1) builds successfully, the Second one fails because the whole build args value is going to a single variable. like below
value="***,JFROG_PWD=***"

Expected behavior - value="***"

I'm not able to figure out why the 2 build args are not setting values to their respective args inside Dockerfile when I am using docker/build-push-action@v2
