### ISSUE TITLE
How build and push multiple docker image with same repo and same version, but different name?

### ISSUE THREAD

**Issue by patsevanton** [docker/build-push-action#561]
Hello!
Thanks for build-push-action

I have github action
```
name: Build & publish drill4net images
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image Drill4Net.Agent.Service
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./src/Agent/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

I want to add build and push a new docker image from this source.
I try to add code to github action
```
      - name: Build and push Docker image Dockerfile-dril4net-distribution
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./src/Dockerfile-dril4net-distribution
          push: true
          tags: $same-repo/dril4net-distribution:$same-version
          labels: ???
```
How build multiple docker image with same repo and same version, but different name?

**Comment by crazy-max** [comment]
If you're using different Dockerfiles then you have to dedup build steps. For efficiency you could use a matrix like:

```yaml
name: Build & publish drill4net images
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./src/Agent/Dockerfile
            image: ghcr.io/username/image1
          - dockerfile: ./src/Dockerfile-dril4net-distribution
            image: ghcr.io/username/image2
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image Drill4Net.Agent.Service
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

**Comment by bhundven** [comment]
I'm curious if there are any tips for versioning/tagging images separately with this build type?

**Comment by ariwijayaikd** [comment]
@crazy-max can it use env value from the github yml file like this?
```
env:
  REGISTRY:
  IMAGE_NAME:
  REGISTRY_GH: ghcr.io
  IMAGE_NAME_GH: 

jobs:
  build:
    needs: scan
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        include:
          - image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          - image: ${{ env.REGISTRY_GH }}/${{ env.IMAGE_NAME_GH}}
```
