### ISSUE TITLE
Question: Cache expiration policy

### ISSUE THREAD

**Issue by steveoh** [docker/build-push-action#565]
```yml
      - name: 📦 Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./src/api/Dockerfile
          builder: ${{ steps.builder.outputs.name }}
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

When using github actions, it seems they have a 7 day sliding cache expiration policy.

> GitHub will remove any cache entries that have not been accessed in over 7 days.

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy

If we use this action to cache our docker layers and access them within the 7 day period they will not get evicted. How do you suggest we expire the cache to get layer updates?
