### ISSUE TITLE
Possible issue when building with Tini

### ISSUE THREAD

**Issue by netphantom** [docker/build-push-action#57]
I have the following dockerfile
```
FROM python:3.8-slim

# Packages that we need
COPY requirements.txt /app/
WORKDIR /app

# build the venv and install the requirements
RUN python3 -m venv app_env
RUN pip install -r requirements.txt

# use TINI
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--", "myapp"]
CMD "-h"
```
When I run it on my computer with 
`docker build -t dockerfile .  `

I am able to run and see the help of the application with the command
`docker run -t dockerfile`

However, if I pull the container from github, with the command
`docker run -t docker.pkg.github.com/myrepo/myapp`

I have an error:
`[FATAL tini (7)] exec myapp failed: No such file or directory`

I got the same error, no matter what argument is passed to the container

The rule that I use in the github action is
```
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/dockerfile
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/myapp
          tags: latest
          username: ${{ github.ref }}
          password: ${{ secrets.GH_TOKEN }}
```
