### ISSUE TITLE
Feature Request: skip Push on Unchanged Digest

### ISSUE THREAD

**Issue by somdoron** [docker/build-push-action#58]
I have a monorepo with multiple docker images and I would like to publish an image only if the digest of the image is not present in the registry, regardless of the tag. I'm using fluxcd and right now because a tag is pushed on every push to master, all the pods are being restarted.

I suggest the option `skipUnchangedDigest` to the build-push-action and when set to true the action will skip the push if the digest already present.

Bazel build supports this with skipUnchangedDigest flag to the container_push rule, code is here:
https://github.com/bazelbuild/rules_docker/blob/06c5419265e84baf168ba4d3982f45fe1fe312b4/container/go/cmd/pusher/pusher.go#L132
https://github.com/bazelbuild/rules_docker/blob/06c5419265e84baf168ba4d3982f45fe1fe312b4/container/go/cmd/pusher/pusher.go#L163

**Comment by hadim** [comment]
I am also interested in this feature for a multi Docker images repository.

**Comment by hadim** [comment]
@zappy-shu  is that something you guys could add?

**Comment by somdoron** [comment]
I looked further into that because docker builds non-reproducible images I don't think it would be possible.  [Kaniko](https://github.com/GoogleContainerTools/kaniko#--reproducible) does support reproducible builds, someone already created a [github action for kaniko](https://github.com/aevea/action-kaniko), so I think we have a better change adding to the kaniko action

**Comment by hadim** [comment]
What do you mean by "builds non-reproducible images"? The digest won't be the same for the exact same build? How can my local builds be cached if that's the case? Or maybe there is something I don't get in what you're saying.

**Comment by somdoron** [comment]
It will be cached, however the final digest of the image will be different on every run. 
Because of a timestamp in the image and nondeterministic order of files in the tar file.

Run `DOCKER_BUILDKIT=1 docker build .` twice on the same docker file and you will end up with two different digests.

**Comment by hadim** [comment]
Thanks for the details but I still don't get how the caching mechanism can works if two layers do the exact same thing but end up with a different digest (cuz of timestamps, etc)?

**Comment by somdoron** [comment]
Sorry, you are right, if you get *all layers* from cache this will work, however, if you re-create a layer that is identical to a layer in the registry you will get a different final digest because of the timestamp of the identical layer (and non-deterministic order of files).

So this issue is applicable in this project as well.

As aside, projects like kaniko and bazel solve this by using a constant timestamp (usually EPOCH) and a deterministic order of files.

**Comment by hadim** [comment]
In my GA I use the following options:

```yaml
          cache_froms: ${{ env.PROJECT_ID }}/my_image:latest
          always_pull: true
```

I am excepting the image from my registry to be pull before the build. But the image is rebuilt even when no files related to the Docker build mechanism has been modified.

When I build locally without modifying the Dockerfile (and related files), the build is skipped using cached layers.

Do you understand how is that possible?

**Comment by somdoron** [comment]
Which registry are you using? Github registry currently has a bug and you cannot use it with cache_froms. Anyway, to use cache from your github actions must use buildkit and specify inline cache flag, like the following:

```
      - uses: docker/build-push-action@v1.1.0
        name: builder
        env:
          DOCKER_BUILDKIT: 1
        with:
          registry: not.docker.pkg.github.com
          repository: XX/YY
          cache_froms: not.docker.pkg.github.com/XX/YY:latest
          build_args: BUILDKIT_INLINE_CACHE=1
```

**Comment by hadim** [comment]
I am using the Google Container Registry. I will try `BUILDKIT=1`.

**Comment by somdoron** [comment]
and `build_args: BUILDKIT_INLINE_CACHE=1`

**Comment by somdoron** [comment]
Another note, you must built in once with BUILDKIT_INLINE_CACHE before you can use it.

**Comment by hadim** [comment]
Unfortunately, it does not work. I build once with `BUILDKIT_INLINE_CACHE` and I pushed a commit a second time where I only modified something not related to the build.

```yaml
name: Build and Push Docker Images

env:
  PROJECT_ID: my-project-id

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build my-image
        uses: docker/build-push-action@v1.1.0
        env:
          DOCKER_BUILDKIT: 1
        with:
          repository: ${{ env.PROJECT_ID }}/my-image
          path: base
          build_args: BASE_IMAGE=ubuntu:20.04,BUILDKIT_INLINE_CACHE=1
          username: _json_key
          password: ${{ secrets.GCR_PUSH_KEY }}
          registry: gcr.io
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true
          push: true
          cache_froms: ${{ env.PROJECT_ID }}/my-image:latest
          always_pull: true
```

```Dockerfile
ARG BASE_IMAGE="ubuntu:20.04"

FROM ${BASE_IMAGE}

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update --fix-missing && \
    apt install --no-install-recommends -y \
    wget bzip2 ca-certificates libglib2.0-0 libxext6 \
    libsm6 libxrender1 git mercurial subversion && \
    apt clean

ENV CONDA_PATH "/opt/conda"
ENV PATH "$CONDA_PATH/bin:$PATH"

ADD ./bootstrap.sh /bootstrap.sh
ADD ./entrypoint.sh /entrypoint.sh
RUN bash /bootstrap.sh

SHELL ["/bin/bash", "--login", "-c"]
ENTRYPOINT ["/entrypoint.sh"]
```

Could the `BASE_IMAGE` `ARG` be an issue?
