### ISSUE TITLE
buildx failed with: error: failed to solve: server message: insufficient_scope: authorization failed

### ISSUE THREAD

**Issue by lapplislazuli** [docker/build-push-action#580]
Hi, 

I get the same error as https://github.com/docker/build-push-action/issues/223 
But I am not certain how to resolve it. 

I have a perfectly fine Docker CI but I can't push to the GHCR, with the error message: 

```
#13 exporting to image
#13 pushing layers 0.6s done
#13 ERROR: server message: insufficient_scope: authorization failed
------
 > exporting to image:
------
error: failed to solve: server message: insufficient_scope: authorization failed
Error: buildx failed with: error: failed to solve: server message: insufficient_scope: authorization failed
```

I think this is due to image naming, and for #223 it was resolved by changing the image name. 
However, I do need different names than the exact `user/repo/image:version` naming.

If I remove the push, everything is fine.

#### Steps to reproduce this issue

(I think)

1. Create any docker image
2. Have various names that differ from repository name 
3. try to push them, using ghcr login

#### Expected behaviour

> Push the updated image(s), with correct tags. 

#### Actual behaviour

> Authorization error, failed CI

### Configuration

* [ Repository URL](https://github.com/ciselab/CodeBert-CodeToText-Reproduction)
* [Build URL](https://github.com/ciselab/CodeBert-CodeToText-Reproduction/runs/5736969435?check_suite_focus=true)

```yml
name: ci

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'main'
      - 'master'
    tags: 
        - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2      
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ciselab/codebert-code2text
            ciselab/codebert-codetotext-reproduction/codebert-code2text
            ghcr.io/ciselab/codebert-code2text
            ghcr.io/ciselab/codebert-codetotext-reproduction/codebert-code2text
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Login to Github Package Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_USER }}
          password: ${{ secrets.CISELAB_CI_PAT }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

The CI_USER and CISELAB_CI_PAT are two secrets that work perfectly well on console, I can push any Image name to the ghcr.io manually.

### Logs

[logs_8.zip](https://github.com/docker/build-push-action/files/8371699/logs_8.zip)

**Comment by crazy-max** [comment]
@lapplislazuli 

```yaml
        with:
          # list of Docker images to use as base name for tags
          images: |
            ciselab/codebert-code2text
            ciselab/codebert-codetotext-reproduction/codebert-code2text
```

Following tags can't be pushed to `ghcr.io` as it's not the same registry. You can add another login step to login against Docker Hub if that's your intention.
