### ISSUE TITLE
Docker secrets not accessible

### ISSUE THREAD

**Issue by nidalhaddad** [docker/build-push-action#581]
### Behaviour
I am trying to pass secrets to my docker image through GH actions and i am not able to
These are my dockerfile and GH yaml.

```
#Origin, Node version 16.13.2 with npm version 8.1
FROM debian


RUN --mount=type=secret,id=TOKEN \
    export TOKEN=$(cat /run/secrets/TOKEN) 

CMD [ "/bin/bash"]
```

```
    -  name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build & Push image
      uses: docker/build-push-action@v2
      with:
        file: /server/Dockerfile
        secrets: |
            "TOKEN=${{ secrets.TESTING }}"
        push: true
        tags: XXXXX/XXXXlatest
    

``` 

When i access my docker container i can't see the env var TOKEN anywhere. 
AM i missing something  ? 
Thank you
