### ISSUE TITLE
Logging in to two Docker registries?

### ISSUE THREAD

**Issue by roderik** [docker/build-push-action#59]
I'm trying to build a docker container, from a private container on dockerhub, and push it to the github registry.

For public dockerhub packages, this works splendidly
```
  docker-rabbitmq:
    runs-on: ubuntu-latest
    needs: lerna
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Build the container
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: xxx/yyy/rabbitmq
          tag_with_ref: true
          dockerfile: ./packages/yyy/containers/rabbitmq/Dockerfile
          cache_froms: xxx/yyy/rabbitmq:latest
          path: ./packages/yyy/containers/rabbitmq/
```

But for a private container, this fails because we are not logged in to DockerHub.

I tried to add the following before the build-push-action, but that does not get picked up

```
      - uses: azure/docker-login@v1
        with:
          username: "xxx"
          password: "xxx"
```

Any ideas on how to do this?

**Comment by roderik** [comment]
FYI, if your containers do not have the same name, this is a workaround

```
  docker-zzz:
    runs-on: ubuntu-latest
    needs: lerna
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: azure/docker-login@v1
        with:
          username: "xxx"
          password: "xxx"

      - run: |
          docker pull xxx/yyy:3.9.1

      - name: Build the container
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: xxx/yyy/zzz
          tag_with_ref: true
          dockerfile: ./packages/yyy/containers/zzz/Dockerfile
          cache_froms: xxx/yyy/zzz:latest
          path: ./packages/yyy/containers/zzz/
```
