### ISSUE TITLE
How to use artifacts in build-push-action?

### ISSUE THREAD

**Issue by KEGustafsson** [docker/build-push-action#592]
I tried to figuring out how to use artifacts in build-push-action, but didn't find the info?

I can upload and download artifacts in GH action. I can see that artifacts are in correct folder, but after starting `docker/build-push-action@v2` action and doing `ADD "folder"` in docker build `Dockerfile`, folder is not containing just downloaded artifacts.

It seems that `docker buildx build` is loading git source, but not the one I have checked out.
How this should be done?

**Comment by crazy-max** [comment]
@KEGustafsson If you could post a repro (workflow + simple dockerfile + logs) that would help to understand the issue. Thanks.

**Comment by KEGustafsson** [comment]
@crazy-max Here is one example what I'm trying to do
https://gist.github.com/KEGustafsson/d57419e6f82f9fda98f37f6d7d0e04df

So, it I download artifact to temp and then ADD it to docker, content is missing just downloaded artifact.

**Comment by crazy-max** [comment]
Looks like you're using the Git context. As [explained in the README](https://github.com/docker/build-push-action#git-context):

> Be careful because **any file mutation in the steps that precede the build step
> will be ignored, including processing of the `.dockerignore` file** since
> the context is based on the Git reference. However, you can use the
> [Path context](#path-context) using the [`context` input](#inputs) alongside
> the [`actions/checkout`](https://github.com/actions/checkout/) action to remove
> this restriction.

So use the Path context instead:

```yaml
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          images: <user>/<repo>
          tags: latest
```
