### ISSUE TITLE
`outputs.digest` and `outputs.imageid` not showing anything

### ISSUE THREAD

**Issue by Sidduppal** [docker/build-push-action#596]
### Behaviour
`echo "${{ steps.docker_build.outputs.imageid }}"` or `echo "${{ steps.docker_build.outputs.digest }}"` does not print the imageID or digest. The image builds and caches properly.

#### Expected behavior

Output should be echoed when using `echo "${{ steps.docker_build.outputs.imageid }}"` or `echo "${{ steps.docker_build.outputs.digest }}"`

#### Actual behaviour

Nothing is echoed.

```
Run echo ""
  echo ""
  shell: /usr/bin/bash -e {0}

```
### Configuration

```yml
name: test
on:
  workflow_dispatch:
    inputs:
      path:
        description: Path to the tool
        required: true
        type: string

jobs:
  import_tool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: false
          tags: fastqc-test
          cache-from: type=gha
          cache-to: type=gha
      - name: Image digest
        run: |
          echo "${{ steps.docker_build.outputs.imageid }}" 
```

**Comment by crazy-max** [comment]
As you're using the `setup-buildx-action` it will create a [`docker-container` builder](https://github.com/docker/buildx/blob/master/docs/reference/buildx_create.md#docker-container-driver) ([default behavior](https://github.com/docker/setup-buildx-action#about)).

In your `Build and push` step you don't specify any output (either push or load) so build result will only remain in build cache. (a warning message should be visible in your logs when your build starts)

You can use the [`load` input](https://github.com/docker/build-push-action/#inputs) and the `imageid` should be available:

```
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: false
          load: true
          tags: fastqc-test
          cache-from: type=gha
          cache-to: type=gha
```
