### ISSUE TITLE
buildx failed with: error: failed to solve

### ISSUE THREAD

**Issue by ZebcoWeb** [docker/build-push-action#597]
i get this error when action runs:

`Error: buildx failed with: error: failed to solve: process "/bin/sh -c apt update &&     apt upgrade" did not complete successfully: exit code: 1`

Workflow code:
`name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zebco/player-tracker:latest`

**Comment by exploitact** [comment]
how were you able to fix this?

**Comment by gunnarwustl** [comment]
I'm currently getting something similar related to dpkg failing during my apt-get install layer within the buildx task. Still working out why this fails when using provided docker buildx actions but not when simply running docker build via shell actions.

**Comment by JosephKnecht-lab** [comment]
I am also getting this exact error... 

@ZebcoWeb It would be nice to post the solution if you have it. 

Thanks

**Comment by huboh** [comment]
same thing over here, the job ran successfully yesterday and today, I've been getting same error

**Comment by JosephKnecht-lab** [comment]
It worked for me after setting up QEMU. 

Try to include this in your GitHub actions steps.

```
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
```

**Comment by huboh** [comment]
I had QEMU is already setup, this are the steps 👇
`
  steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} ........
`

**Comment by huboh** [comment]
I had QEMU is already setup, this are the steps 👇

```yml
steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: `docker/setup-buildx-action@v2`

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} ........
```
