### ISSUE TITLE
exporting to image: EOF

### ISSUE THREAD

**Issue by alinturbut** [docker/build-push-action#599]
#### Steps to reproduce this issue

1. Not sure why this reproduces. I have a multi-target Dockerfile, all except one image work

#### Expected behaviour

> Expecting to build & push the image. 

The image is built locally, but I am getting a strange error (see Actual behaviour). All my other images are built with the same configuration. I don't know where to pick this up from. 

This is a private repository and I've tried upgrading my plan thinking it was size (even though all images have the same size).

If I set push: false, the build is succesful.

#### Actual behaviour

```
#31 [auth] sharing credentials for ***
#31 DONE 0.0s

#30 exporting to image
#30 19.66 error: failed to do request: Post "https://***/v2/dev/db-migration/blobs/uploads/": EOF
```

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
  docker-image-migration:
    runs-on: ubuntu-latest
    needs: run-tests
    env:
      IMAGE: ${{ secrets.DEV_ECR_REPOSITORY_URL }}/dev/db-migration
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DEV_ECR_REPOSITORY_URL }}
          username: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          target: migration
          tags: ${{ env.IMAGE }}:${{ env.TAG }}
          file: Dockerfile
```

### Logs

```
#30 24.83 retrying in 4s
#30 28.21 error: failed to do request: Post "https://***/v2/dev/db-migration/blobs/uploads/": EOF
#30 pushing layers 9.8s done
#30 ERROR: failed to do request: Post "https://***/v2/dev/db-migration/blobs/uploads/": EOF
------
 > exporting to image:
#30 24.30 retrying in 4s
#30 24.31 error: failed to do request: Post "https://***/v2/dev/db-migration/blobs/uploads/": EOF
#30 24.31 retrying in 4s
#30 24.82 error: failed to do request: Post "https://***/v2/dev/db-migration/blobs/uploads/": EOF
#30 24.82 retrying in 4s
#30 24.83 error: failed to do request: Post "https://***/v2/dev/db-migration/blobs/uploads/": EOF
#30 24.83 retrying in 4s
#30 24.83 error: failed to do request: Post "https://***/v2/dev/db-migration/blobs/uploads/": EOF
#30 24.83 retrying in 4s
#30 28.21 error: failed to do request: Post "https://***/v2/dev/db-migration/blobs/uploads/": EOF
------
error: failed to solve: failed to do request: Post "https://***/v2/dev/db-migration/blobs/uploads/": EOF
Error: buildx failed with: error: failed to solve: failed to do request: Post "https://***/v2/dev/db-migration/blobs/uploads/": EOF

```
