### ISSUE TITLE
Is ghactions caching expected to work correctly when actions used twice, with testing in between?

### ISSUE THREAD

**Issue by BogdanSorlea** [docker/build-push-action#602]
#### Steps to reproduce this issue

```
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          target: production
          platforms: linux/${{ matrix.platform-architecture }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          load: true # as in leave it locally on the runner so we can use it for testing and push it later
          tags: |
            sometag:${{ needs.resolve-tags-and-branch.outputs.docker-tag }}-${{ matrix.platform-architecture }}
      - name: Check docker image size within limits
        uses: wemake-services/docker-image-size-limit@master
        with:
          image: "sometag:${{ needs.resolve-tags-and-branch.outputs.docker-tag }}-${{ matrix.platform-architecture }}"
          size: "1.15GB"
      - name: verify no .env files are left in the image
        run: |
          echo "Fail if env files found..."
          docker run --rm sometag:${{ needs.resolve-tags-and-branch.outputs.docker-tag }}-${{ matrix.platform-architecture }} /bin/sh -c "find / -type f -name '.env*' -exec false {} +"
          echo "OK"
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          target: production
          platforms: linux/${{ matrix.platform-architecture }}
          cache-from: type=local,src=/tmp/.buildx-cache-new
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          push: true
          tags: |
            sometag:${{ needs.resolve-tags-and-branch.outputs.docker-tag }}-${{ matrix.platform-architecture }}
```

#### Expected behaviour

> Build times optimized as expected due to the use of cache

#### The Question

> Can we expect such a setup to work well with the cache setup?

#### Alternative Question

> Do you plan to maybe develop some hooks on this action, as to run whatever testing routines we would like to throw at the built image (e.g. spec tests or similar), which would between building and pushing the image, this way avoiding duplication of the same action invocation code?

**Comment by crazy-max** [comment]
> Do you plan to maybe develop some hooks on this action, as to run whatever testing routines we would like to throw at the built image (e.g. spec tests or similar), which would between building and pushing the image, this way avoiding duplication of the same action invocation code?

The purpose of this action is to match buildx UX. Running containers for testing between builds is out of scope for now but you can check this doc to test your image before pushing it: https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md

> Is ghactions caching expected to work correctly when actions used twice, with testing in between

It should but depends if in between steps files changed and could invalidate your cache. Not sure without your Dockerfile.

Also I suggest to use the `type=gha` cache because with `type=local`, caches are copied over the existing cache so it keeps growing but in your case it might be ok. Another thing is your don't need the first `cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max` as it's already pushed with the last one. I don't see you're using the `actions/cache` as shown in our example: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#local-cache. Please post your complete workflow.

Here is how it should look like with `type=gha`:

```yaml
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          target: production
          platforms: linux/${{ matrix.platform-architecture }}
          cache-from: type=gha
          load: true # as in leave it locally on the runner so we can use it for testing and push it later
          tags: |
            sometag:${{ needs.resolve-tags-and-branch.outputs.docker-tag }}-${{ matrix.platform-architecture }}
      - name: Check docker image size within limits
        uses: wemake-services/docker-image-size-limit@master
        with:
          image: "sometag:${{ needs.resolve-tags-and-branch.outputs.docker-tag }}-${{ matrix.platform-architecture }}"
          size: "1.15GB"
      - name: verify no .env files are left in the image
        run: |
          echo "Fail if env files found..."
          docker run --rm sometag:${{ needs.resolve-tags-and-branch.outputs.docker-tag }}-${{ matrix.platform-architecture }} /bin/sh -c "find / -type f -name '.env*' -exec false {} +"
          echo "OK"
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          target: production
          platforms: linux/${{ matrix.platform-architecture }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            sometag:${{ needs.resolve-tags-and-branch.outputs.docker-tag }}-${{ matrix.platform-architecture }}
```
