### ISSUE TITLE
Buildx failed from a `insufficient_scope: authorization failed` error

### ISSUE THREAD

**Issue by T145** [docker/build-push-action#603]
[logs_3115.zip](https://github.com/docker/build-push-action/files/8596729/logs_3115.zip)
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

https://github.com/T145/black-mirror/blob/master/.github/workflows/publish_docker.yml

#### Expected behaviour

Successful upload

#### Actual behaviour

https://github.com/T145/black-mirror/runs/6239599043?check_suite_focus=true

### Configuration

* Repository URL (if public): https://github.com/T145/black-mirror
* Build URL (if public): https://github.com/T145/black-mirror/pkgs/container/black-mirror

```yml
# https://docs.docker.com/ci-cd/github-actions/
name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
  schedule:
    - cron: "0 6 * * */3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/t145/black-mirror:latest
          cache-from: type=registry,ref=t145/black-mirror:buildcache
          cache-to: type=registry,ref=t145/black-mirror:buildcache,mode=max
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
