### ISSUE TITLE
docker/build-push-action 403 api rate limit

### ISSUE THREAD

**Issue by lucab85** [docker/build-push-action#605]
### Troubleshooting

The `docker/build-push-action@v2` fails with a 403 error about the GitHub API rate limit. Probably the `GITHUB_TOKEN` env not correctly set.

### Behaviour

My Dockerfile include the following step:

```
RUN installGithub.r --deps TRUE \
       jhudsl/ariExtra jhudsl/ari jhudsl/text2speech jhudsl/didactr
```

#### Steps to reproduce this issue

The CI pipeline set the two environment variables
```
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and fails at the following workflow step:

```
      - name: Build and push x86
        id: docker_build_x86
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lucab85/avg:devel
          platforms: linux/amd64
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

#### Expected behaviour

I was expecting a successful build and push to Docker Hub.

#### Actual behaviour

```
#9 ERROR: process "/bin/sh -c installGithub.r --deps TRUE        jhudsl/ariExtra jhudsl/ari jhudsl/text2speech jhudsl/didactr" did not complete successfully: exit code: 1
------
 > [6/9] RUN installGithub.r --deps TRUE        jhudsl/ariExtra jhudsl/ari jhudsl/text2speech jhudsl/didactr:
#9 245.5 Error: Failed to install 'unknown package' from GitHub:
#9 245.5   HTTP error 403.
#9 245.5   API rate limit exceeded for 20.114.207.124. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
#9 245.5 
#9 245.5   Rate limit remaining: 0/60
#9 245.5   Rate limit reset at: 2022-05-02 16:08:31 UTC
#9 245.5 
#9 245.5   To increase your GitHub API rate limit
#9 245.5   - Use `usethis::create_github_token()` to create a Personal Access Token.
#9 245.5   - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
------
```

### Configuration

* Repository URL (if public): https://github.com/lucab85/avg/tree/devel
* Build URL (if public): https://github.com/lucab85/avg/actions/workflows/ci-devel.yml

```yml
name: ci-devel

on:
  push:
    branches:
      - 'devel'

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push x86
        id: docker_build_x86
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lucab85/avg:devel
          platforms: linux/amd64
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARM
        id: docker_build_arm
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lucab85/avg:devel
          platforms: linux/arm64/v8
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build_x86.outputs.digest }}
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
