### ISSUE TITLE
denied: installation not allowed to Create organization package

### ISSUE THREAD

**Issue by kohanyirobert** [docker/build-push-action#606]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

I've read the troubleshooting page, but didn't see anything that would fit what I'm experiencing.

### Behaviour

I have two personal public repo's [this one](https://github.com/kohanyirobert/cv) and [this other one](https://github.com/kohanyirobert/gitpod-workspace-cv).

The second repo has a [`Dockerfile`](https://github.com/kohanyirobert/gitpod-workspace-cv/blob/main/Dockerfile) that references a Docker image from the first repo like this

```
FROM gitpod/workspace-base@sha256:87dea615c27cb27e251aee4795a3fe3ccabc09e480e6292e4127ab20736bc2b8
# ghcr.io/kohanyirobert/cv:latest
COPY --from=ghcr.io/kohanyirobert/cv@sha256:3f344f1164a3524855813f70459403f6b6b443b55b6bc27ed3589311a40b3fed
...
```

I've tried giving read permissions for the second repo in the first repo's _Package Settings_ 
![image](https://user-images.githubusercontent.com/1104829/166713068-78033168-6e9e-4410-b25c-9ae6dbc93ddf.png)
but it didn't change a thing (on the picture there's only a single entry - the repo can access itself in a read-write fashion which works).

(This builds locally by the way.)

I have [this workflow](https://github.com/kohanyirobert/gitpod-workspace-cv/actions/runs/2270460018/workflow) in the second repo, but when it is triggered while the image is built the push fails, [here are the logs from the last run](https://github.com/kohanyirobert/gitpod-workspace-cv/runs/6291942778?check_suite_focus=true#step:3:359).

#### Expected behaviour

I was expecting this to be working, meaning the image built by second repo's workflow pushed to the repo's container registry/repository (the same works for the first repo, where I build and push an image there - [here's the workflow](https://github.com/kohanyirobert/cv/blob/main/.github/workflows/build-and-push-image.yml)).

#### Actual behaviour

```
#9 ERROR: denied: installation not allowed to Create organization package
------
 > pushing ghcr.io/kohanyirobert/gitpod-workspace-cv:latest with docker:
------
error: denied: installation not allowed to Create organization package
Error: buildx failed with: error: denied: installation not allowed to Create organization package
```

### Configuration

* [Repository URL](https://github.com/kohanyirobert/gitpod-workspace-cv)
* [Build URL](https://github.com/kohanyirobert/gitpod-workspace-cv/runs/6291942778?check_suite_focus=true)

```yml
name: Build and push image

on:
  push:
    branches:
      - main
    paths-ignore:
      - .editorconfig
      - .gitignore
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
```

### Logs

[logs_6.zip](https://github.com/docker/build-push-action/files/8621709/logs_6.zip)

**Comment by crazy-max** [comment]
@kohanyirobert Don't think that's the right place to ask this as this is GitHub related but looks like an issue with your PAT permissions: https://stackoverflow.com/questions/66863763/github-action-error-during-push-docker-image

Suggest you open a support ticket to GitHub about this: https://support.github.com/contact

**Comment by kohanyirobert** [comment]
I've seen this post at StackOverflow. Based on [this](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio) I don't think I have a PAT issue, since as suggested by the docs PAT is discouraged. Anyways, I'll look into it some, maybe you're right this is more of a GitHub issue.

**Comment by kohanyirobert** [comment]
Figured it out, leaving here the solution for whoever finds this.

The default permission for the `GITHUB_TOKEN` automatically created for workflow runs **by default is read only**. Needs to be changed in the _Settings_ > _Actions_ > _General_ section.

![image](https://user-images.githubusercontent.com/1104829/166800242-1b0992ae-7233-4981-abc4-f44127372f75.png)

This was set to read/write in my other repo and I never changed it or don't remember, so I assumed read/write to be the default.

This can be changed on a per workflow/job basis also, so what I'm suggesting here is not the best solution, but works!

Sorry for the trouble @crazy-max!

**Comment by mk-pmb** [comment]
Edit: I should have read the StackOverflow link before trying GitHub's docs. The solution there works for me:

```yaml
jobs:
  build_and_maybe_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
```


<details><summary>Previously in this post: GitHub's docs weren't helpful (click to expand)</summary>

As seen in the screenshot, the help text above that setting recommends using finer-grained permssions in the workflow settings, usually at job level. However,

```yaml
    permissions:
      contents: write
```

didn't seem sufficient when I tried. What permission do we need? The error message I have is exactly the issue title ("denied: installation not allowed to Create organization package") but in [the help page](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#account-permissions), the only mention of "package" is the paragraph recommending fine-grained tokens. I also tested `organization_private_registries` and `organization_codespaces`, they fail the workflow instantly with error "Unexpected value".

So are fine-grained tokens the best strategy here?

</details>
