### ISSUE TITLE
Output from a build

### ISSUE THREAD

**Issue by moos3** [docker/build-push-action#614]
So we have a pipeline that uses this, but one of the issues we are having is passing the name the built image from this step to another job because the image name with tag isn't returned just the digest is. Any suggestion on this? workflow looks lik this 

Build -> Run Tests -> Run security -> Approved  (Merge) -> Build Image -> run tests again -> another sec scan -> push to ECR -> Deploy Helm update.

**Comment by 4141done** [comment]
Hello!  I'm not affiliated with `build-push-action` but I just went through this so thought I'd offer what worked for me:

Referencing [this issue](https://github.com/docker/build-push-action/issues/554) here's what worked for me:

```
name: build-and-test
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

defaults:
  run:
    shell: bash

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image_name: ${{ steps.get-build-name.outputs.image_name }}

    steps:
      # ... truncated ...
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ... truncated ...

      - name: Build and push
        id: docker-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: _internal/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - id: get-build-name
        run: |
          imageName=${{ fromJSON(steps.docker-push.outputs.metadata)['image.name'] }}
          echo "::set-output name=image_name::$imageName"

      # ... truncated ...

  run-unit-tests:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    container:
      image: ${{needs.build-and-push-image.outputs.image_name}}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}


      # ... truncated ...
```

Key points:

1. Defining `outputs` at the top of the job that pushes the image
2. Setting that output with the `get-build-name` step
3. The image name can now be accessed via `${{needs.<build job name>.outputs.image_name}}` in any subsequent job that defines the build job as `needs`

Hope that helps.
