### ISSUE TITLE
Cannot push to github container registry

### ISSUE THREAD

**Issue by adamsong** [docker/build-push-action#617]
### Behaviour

Attempting to push to the github container registry, with either GITHUB_TOKEN or a PAT returns 'User cannot be authenticated with the token provided.'

#### Steps to reproduce this issue

1. Try run a workflow that pushes to the github container registry [(example)](https://github.com/adamsong/CursedBot-ts/blob/79387f4f0c35d60339062ce27fc6f4381731af0e/.github/workflows/docker-image.yml)
2. Get error

#### Expected behaviour

> Container should be pushed

#### Actual behaviour

> Container isn't pushed, error

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: Docker Image CI

on:
  push:
    branches: [ master ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/adamsong/cursedbot-ts:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_PAT }}
          
      - name: Write digest
        run: |
          echo "${{ steps.docker_build.outputs.digest }}"
```

### Logs

[logs_24.zip](https://github.com/docker/build-push-action/files/8691963/logs_24.zip)
