### ISSUE TITLE
Cannot build/push to Docker Hub registry with Azure generated workflow

### ISSUE THREAD

**Issue by NadymVanSchaik** [docker/build-push-action#618]
### Behaviour
I created an AppService on Azure. I connected the repository on GitHub using the Deployment Centre of Azure. Azure created an action for me in my GitHub. This Action had serveral bugs, which I already fixed. But now it gets stuck on the "Build and push container image to registry" step. I want to push to a Docker Hub registry. 

#### Steps to reproduce this issue

1. Create an AppService using Azure
2. Using the Deployment centre, set up automated deployment using GitHub
3. An action has appeared in the Github repository containing the application. This action will fail.

#### Expected behaviour

The actions should run without any problem and deploy the repository to the Azure AppService. A Docker Hub registry is used for this project. The login into the Docker Hub suceeds, but the actual build/push fails. 

#### Actual behaviour

An error is thrown and the build/push action is not completed (see attached logs)

### Configuration

* Repository URL (if public): https://github.com/NadymVanSchaik/Fontys-S6-Gateway
* Build URL (if public): https://github.com/NadymVanSchaik/Fontys-S6-Gateway/actions/runs/2307750153

```yml
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Nadym-Fontys-S6-Gateway

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  login: 
    runs-on: 'ubuntu-latest'
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.AzureAppService_ContainerUsername_7b5852a302044732967f88a5ec6b8a45 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e0c19723af224c7aafab29494fdfd062 }}
  
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7b5852a302044732967f88a5ec6b8a45 }}/fontys-s6-gateway:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Nadym-Fontys-S6-Gateway'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6490176cf3174ecc812188cd925647b5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7b5852a302044732967f88a5ec6b8a45 }}/fontys-s6-gateway:${{ github.sha }}'
```

### Logs
[logs_23.zip](https://github.com/docker/build-push-action/files/8698278/logs_23.zip)
