### ISSUE TITLE
Help Request: Error: buildx failed with: error: failed to solve: failed to fetch anonymous token: unexpected status: 403 Forbidden

### ISSUE THREAD

**Issue by abraunegg** [docker/build-push-action#628]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. Attempt to Build and Push to Docker

#### Expected behaviour

Build completes and pushes to Docker without error

The goal here is to build Docker images for Fedora, Debian and Alpine across a number of architectures for the OneDrive Client for Linux and to start republishing images on DockerHub for folk to use

#### Actual behaviour

The build process errors out with the following error message:
```
Error: buildx failed with: error: failed to solve: failed to fetch anonymous token: unexpected status: 403 Forbidden
```
![image](https://user-images.githubusercontent.com/4956234/171542403-7e9ceb24-c3c5-430d-92cf-4f812d96fa89.png)

I dont quite understand where or what token is attempting to be accessed or from where ... nothing obvious ... 

However, *some* of the images are actually pushed to Docker .... *confused*

![image](https://user-images.githubusercontent.com/4956234/171542456-df897aea-2d82-4251-9a77-110beb82546e.png)

### Configuration

* Repository URL (if public): https://github.com/abraunegg/onedrive
* Build URL (if public): 

```yml
name: Build Docker Images Testing

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:

env:
  DOCKER_HUB_SLUG: abraunegg/onedrive

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [ fedora, debian, alpine ]
        include:
          - flavor: fedora
            dockerfile: ./contrib/docker/Dockerfile
            platforms: linux/amd64
          - flavor: debian
            dockerfile: ./contrib/docker/Dockerfile-debian
            platforms: linux/amd64,linux/arm64,linux/arm/v7
          - flavor: alpine
            dockerfile: ./contrib/docker/Dockerfile-alpine
            platforms: linux/amd64,linux/arm64

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Docker meta
        id: docker_meta
        uses: marcelcoding/ghaction-docker-meta@v1
        with:
          tag-edge: true
          images: |
            ${{ env.DOCKER_HUB_SLUG }}
            ghcr.io/${{ github.repository }}
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
          flavor: ${{ matrix.flavor }}
          main-flavor: ${{ matrix.flavor == 'debian' }}

      - uses: docker/setup-qemu-action@v1
        if: matrix.platforms != 'linux/amd64'

      - uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.flavor }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.flavor }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.XXXX }}
          password: ${{ secrets.YYYY }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

### Logs

[logs_731.zip](https://github.com/docker/build-push-action/files/8820280/logs_731.zip)
