### ISSUE TITLE
Custom Linux Version

### ISSUE THREAD

**Issue by clean99** [docker/build-push-action#629]
### Troubleshooting
Hi, I meet a trouble when using this action, looks like mongodb-memory-server doesn't support alpine version Linux, but I can't figure out how to config the Linux version in this action [Can't run mongodb-memory-server on Linux Alpine](https://github.com/nodkz/mongodb-memory-server/issues/32)

### Behaviour
![Screen Shot 2022-06-07 at 11 41 25 AM](https://user-images.githubusercontent.com/53188310/172291047-28890fe5-aca1-4055-bd4c-0f90450e229f.png)

failed when starting an instance of mongo
#### Steps to reproduce this issue

1. create an mongodb-memory-server in my code
2. trigger build and push action
3. failed with above information

#### Expected behaviour

successfully start the mongo instance

### Configuration

* Repository URL (if public): https://github.com/scnu-lib/scnu-lib-be-node
* Build URL (if public): https://github.com/scnu-lib/scnu-lib-be-node/pull/4/checks

```yml
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Ali Docker
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
        username: ${{ secrets.ALI_DOCKER_HUB_USN }}
        password: ${{ secrets.ALI_DOCKER_HUB_PWD }}
    - name: Build and push
      id: docker_build
      env:
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/scnu-lib/scnu-lib-be:0.1.0
```

### Logs

[logs_19.zip](https://github.com/docker/build-push-action/files/8849956/logs_19.zip)
