### ISSUE TITLE
COPY failed: no such file or directory

### ISSUE THREAD

**Issue by ayedo** [docker/build-push-action#63]
First of all: Thank you very much for your work on this GitHub actions. It looks very promising, but I could not get it to work so far.

Here is my configuration:

```
   - name: Build and Push Docker Image
      uses: docker/build-push-action@v1
      with:
          dockerfile: ./backend/guide/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: some/repo
          tags: latest
```

Here is the Dockerfile:

```
FROM openjdk:11-jre-slim
COPY ./core/build/libs/core.jar core.jar
ENTRYPOINT ["java","-jar","/core.jar"]
```

I keep on getting, the following error:

```
Step 2/3 : COPY core/build/libs/core.jar core.jar
COPY failed: stat /var/lib/docker/tmp/docker-builder622038188/core/build/libs/core.jar: no such file or directory
```

I've also tried the following:

```
FROM openjdk:11-jre-slim
COPY core/build/libs/core.jar core.jar
ENTRYPOINT ["java","-jar","/core.jar"]
```

But it did not work either.

When I ssh into the runner machine, I can use docker build just find, and everything works.

Can somebody spot my mistake? I'm close to losing my mind :)

Thanks.
