### ISSUE TITLE
Tests in docker-compose passes only locally, not on github actions

### ISSUE THREAD

**Issue by FlockiiX** [docker/build-push-action#631]
#### Steps to reproduce this issue

1. Clone this [repository](https://github.com/FlockiiX/Login-Registration-Backend)
2. Run `docker-compose -f docker-compose-test.yml up`

#### Expected behavior
Tests should succeed locally and on Github actions

#### Actual behaviour
Tests only succeed locally but fails on Github actions

#### Note
All tests pass if you clone the repository and run the tests on your PC with docker-compose. I have also tested it on another machine already.
The test that fails checks if the HTTP response code is 400 but only on Github actions is 403 instead.
### Configuration

* Repository URL (https://github.com/FlockiiX/Login-Registration-Backend): 
* Build URL (https://github.com/FlockiiX/Login-Registration-Backend/actions/runs/2479554626): 

Workflow (test.yml):
```yml
name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: docker-compose -f docker-compose-test.yml up --abort-on-container-exit --exit-code-from app
```
Docker-Compose (docker-compose-test.yml):
```yml
version: '3.9'
services:
  app:
    build:
      context: .
      target: test
    container_name: app
    depends_on:
      - db
      - maildev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_MAIL_HOST=maildev
    ports:
      - "8080:8080"
  db:
    image: 'postgres:latest'
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
volumes:
  db-data:
```
### Logs
[logs_23.zip](https://github.com/docker/build-push-action/files/8883741/logs_23.zip)
