### ISSUE TITLE
dial tcp: lookup *** on 192.168.20.1:53: no such host Issue

### ISSUE THREAD

**Issue by rection** [docker/build-push-action#633]
### Troubleshooting

I am trying my image to push a private registry behind of the nginx reverse proxy. I don't use personal dns server in my system. So, I added my domain and ip address to /etc/hosts file.  

I checked resolvectl status. Github action looks just `` Current DNS Server:  192.168.20.1`` line. I changed to other dns servers as ``1.1.1.1`` , ``127.0.0.1``, ``8.8.8.8``. I got same error except dns server ip address changes.

### Behaviour

Github action or build-push-action doesn't look /etc/hosts file for find domain address. My except was using /etc/hosts for find the docker registry. 

#### Steps to reproduce this issue

1. Use private docker registry.
2. Use /etc/hosts for find domain.

#### Expected behaviour

> Successfully push to private docker registry using /etc/hosts file. I can push images manually. I am trying to do with github actions.

#### Actual behaviour

> ![image](https://user-images.githubusercontent.com/43282745/173369211-265a4ffc-9116-4492-8f9e-bee8d922b185.png)

```yml

name: Create a new docker image for update poetry dependency
on: [ workflow_dispatch, push ]
jobs:
  updatepoetrydependency:
    runs-on: [self-hosted, linux, x64, gitea]
    steps:
    
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: builder1

      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .workflow/Dockerfile
          builder: ${{ steps.builder1.outputs.name }}
          platforms: linux/arm/v7
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/poetryimage:latest
```

**Comment by crazy-max** [comment]
@rection Does an `nslookup` in your workflow work?:

```yaml
    steps:
    
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lookup
        run: nslookup ${{ secrets.REGISTRY_URL }}
```

Also is your domain publicly available with valid certs or self-signed ones? If the later then you have to set the registry configuration for the buildkit daemon when using `docker/setup-buildx-action`: https://github.com/docker/setup-buildx-action#buildkit-daemon-configuration

See https://github.com/docker/buildx/blob/master/docs/guides/custom-registry-config.md for more info.
