### ISSUE TITLE
Add File error

### ISSUE THREAD

**Issue by roiding** [docker/build-push-action#641]
#### Steps to reproduce this issue

1. Just let the workflow runs
#### Expected behaviour

> Tell us what should happen
Build the image successful
#### Actual behaviour

> Tell us what happens instead
it gives me error:
```
Error: buildx call failed with: error: failed to solve: failed to compute cache key: failed to calculate checksum of ref x5psoaxv98mluiw02u451wqqv::f8321s0lkme9b2lbcinqbzguz: failed to walk /tmp/buildkit-mount2833513632/target: lstat /tmp/buildkit-mount2833513632/target: no such file or directory
```
### Configuration

* Repository URL (if public):  https://github.com/roiding/personal_api
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```
```yml
name: 打包并生成Docker镜像
on:
  push:
    tags:
      - 'v*'
jobs:
  package-and-make-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: 设置java环境
        uses: actions/setup-java@v1
        with:
            java-version: 1.8
      - name: 设置maven环境
        uses: stCarolas/setup-maven@v4.4
        with:
            maven-version: 3.8.2
      - name: 生成jar包
        run: mvn clean package -Dmaven.test.skip=true
      - name: 查看文件目录
        run: ls ${{ github.workspace }}/target
      - name: 生成版本号
        id: version_step
        run: |
          echo "##[set-output name=version;]VERSION=${GITHUB_REF#$"refs/tags/v"}"
          echo "##[set-output name=version_tag;]maodou38:${GITHUB_REF#$"refs/tags/v"}"
          echo "##[set-output name=latest_tag;]maodou38:latest"
      - name: 设置QEMU虚拟机
        uses: docker/setup-qemu-action@v1
      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          -
      - name: 登陆DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USER_NAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: 准备镜像名称
        id: read-docker-image-identifiers
        run: |
            echo VERSION_TAG=$(echo ${{ steps.version_step.outputs.version_tag }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
            echo LATEST_TAG=$(echo ${{ steps.version_step.outputs.latest_tag  }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: 打包并推送Docker镜像
        id: docker_build
        uses: docker/build-push-action@v3
        with:
            push: true
            tags: |
              ${{env.VERSION_TAG}}
              ${{env.LATEST_TAG}}
            build-args: |
              ${{steps.version_step.outputs.version}}
```
### Logs
[logs_15.zip](https://github.com/docker/build-push-action/files/9016671/logs_15.zip)
