### ISSUE TITLE
Question: How to access platform as variable?

### ISSUE THREAD

**Issue by sandreas** [docker/build-push-action#644]
Hello,

I'm trying to perform a multiplatform build with the following file and would like to add the currently building `platform` (`linux/amd64`, `linux/arm64`, etc.) as an `ARG` for the docker file (see last line). How is that possible?

Thank you.

```yml
name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: tone/
          platforms: linux/amd64,linux/arm64
          #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: sandreas/tone:${{ github.ref_name }}
          build-args: |
            REF_NAME=${{ github.ref_name }}
            PLATFORM=${{ ??? }} # HOW?
```
