### ISSUE TITLE
github build-push-action@v2 with Private submodule fails.

### ISSUE THREAD

**Issue by vishalsinhgadhvi** [docker/build-push-action#646]
### Troubleshooting

The github action "checkout" works fine on a private submodule when we pass the github token alongside. But the docker build-push-action fails with an error even though we pass the github token.

"git@github.com: Permission denied (publickey).
#1 1.420 fatal: Could not read from remote repository.
#1 1.420 
#1 1.420 Please make sure you have the correct access rights
#1 1.420 and the repository exists."

### Behaviour
The build-push-action fails with an error.
#### Steps to reproduce this issue

1. Create a submodule with a private repository.
2. Try the build-push-action by passing github token for authentication.

#### Expected behaviour

> Build push action should either authenticate the cloning of a private repository (submodule), or at the first stage when we are already doing the git submodule checkout then why is build-push-action again doing the same and failing.

```yml
      - name: Checkout private submodule repo
        uses: actions/checkout@v3
        with:
          repository: organization/private repo
          path: my repo 
          token: ${{ env.gh_token }}
        
      - name: Run build
        run: git submodule update --remote --merge

      - name: Docker Push
        uses: docker/build-push-action@v2
        with:
          appname: ${{ env.APP_NAME }}
          appid: ${{ env.APP_ID }}
          tag: ${{ needs.Git_Tag.outputs.tag }}
          dockerfile_path: Dockerfile
          registry: quay.io
          quay_username: ${{ env.quay_username }}
          quay_password: ${{ env.quay_password }}
          image_registry: ${{ env.image_registry }}
          jfrog_username: ${{ env.jfrog_username }}
          jfrog_password: ${{ env.jfrog_password }}
          gh_token: ${{ env.gh_token }}
```
