### ISSUE TITLE
Can't set build_arg from env

### ISSUE THREAD

**Issue by dfreilich** [docker/build-push-action#65]
I've tried to set a build_arg from an env I set earlier with Github Actions, but I seem to be unable to. Am I doing something wrong, or is there a real issue here? 

```
jobs:
  deliver-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine version
        id: version
        run: echo "::set-env name=PACK_VERSION::`echo ${{ github.event.release.tag_name }} | cut -d "v" -f2`"
        shell: bash
      - name: Build and Push Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dfreilich/pack
          tags: latest
          dockerfile: .github/workflows/delivery/docker/Dockerfile
          build_args: PACK_VERSION=`${{ env.PACK_VERSION }}
```
