### ISSUE TITLE
build-push to Github Container Rigistry 403/499 errors

### ISSUE THREAD

**Issue by williamcroberts** [docker/build-push-action#651]
### Behaviour

We have a build in Github Actions that pushes the images to Github Container Registry. This has been working fine and all of the sudden today 4 out of 15 container images failed to push due to either 403 Forbidden or 499 Broken Pipe.

#### Steps to reproduce this issue

See build https://github.com/tpm2-software/tpm2-software-container/actions/runs/2659055308

#### Expected behaviour

We expect that the builds would push, we don't know if something changed in the builder or if this a GHCR issue?

### Configuration

* 
* Build URL (if public): https://github.com/tpm2-software/tpm2-software-container/actions/runs/2659055308

```yml
name: Publish
on:
  [ push, workflow_dispatch]
jobs:
  publish-image:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [
          "fedora-30", "fedora-32", "fedora-34", "fedora-34-libressl",
          "opensuse-leap-15.2", "opensuse-leap",
          "ubuntu-18.04", "ubuntu-20.04",
          "ubuntu-20.04.arm32v7", "ubuntu-20.04.arm64v8",
          "fedora-32.ppc64le",
          "alpine-3.15",
          "ubuntu-20.04-ossl3", "ubuntu-22.04", "ubuntu-22.04-mbedtls-3.1"
        ]
    if: "github.repository_owner == 'tpm2-software'"
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Check Diff for Changes
        uses: technote-space/get-diff-action@v6
        with:
          FILES: |
            ${{ matrix.distro }}.docker.m4
          PATTERNS: |
            modules/*
      -
        name: Build the Dockerfiles
        run: make -j $(nproc)
        if: env.GIT_DIFF
      -
        name: Setup QEMU
        run: |
          sudo apt-get update
          sudo apt-get install qemu binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: env.GIT_DIFF
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: env.GIT_DIFF
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: env.GIT_DIFF
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ matrix.distro }}.docker
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.distro }}:latest
        if: env.GIT_DIFF
```

### Logs

[logs_41.zip](https://github.com/docker/build-push-action/files/9096958/logs_41.zip)
