### ISSUE TITLE
`.dockerignore` seems to get ignored

### ISSUE THREAD

**Issue by jojomatik** [docker/build-push-action#655]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

See https://github.com/jojomatik/blockcluster/commit/069521dea4d37353cf905d5830fd87875267bf81 

1. Create `.dockerignore` which includes file that will lead the build to break
2. Run action

#### Expected behaviour

File does not enter the build process, build succeeds.

Example, after I also added the "unwanted" files to tsconfig's exclude clause: https://github.com/jojomatik/blockcluster/commit/ff5506e275945a6d422f37f6801f451450da24b4
https://github.com/jojomatik/blockcluster/actions/runs/2724934010

#### Actual behaviour

File does enter the build proces, build fails: https://github.com/jojomatik/blockcluster/commit/069521dea4d37353cf905d5830fd87875267bf81 https://github.com/jojomatik/blockcluster/actions/runs/2724858338

### Configuration

* Repository URL (if public): https://github.com/jojomatik/blockcluster/commit/069521dea4d37353cf905d5830fd87875267bf81 
* Build URL (if public): https://github.com/jojomatik/blockcluster/actions/runs/2724858338

https://github.com/jojomatik/blockcluster/blob/069521dea4d37353cf905d5830fd87875267bf81/.github/workflows/publish.yml

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
@jojomatik Looking at https://github.com/jojomatik/blockcluster/blob/069521dea4d37353cf905d5830fd87875267bf81/.github/workflows/publish.yml#L109-L118:

```yaml
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha,scope=blockcluster
          cache-to: type=gha,scope=blockcluster,mode=max
          build-args: |
            git_sha=${{github.sha}}
            git_ref=${{github.ref}}
```

You're using a [Git context](https://github.com/docker/build-push-action#git-context) and as stipulated in the README, `.dockerignore` is ignored in this case.

Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.
