### ISSUE TITLE
Is it possible to use the action only for testing purposes?

### ISSUE THREAD

**Issue by cgr71ii** [docker/build-push-action#659]
Hi,

I'm using this action in order to easily install and use docker for testing purposes. In my action, I want to select when I want to make a build from the source or download the image from docker hub. My configuration is:

```yaml
context: .
load: true # If true, once the image has been pulled or built, it will be available from docker
pull: ${{ env.DOCKER_IMAGE_PULL }}
push: false
tags: ${{ env.DOCKER_IMAGE_TAG }}
```

When the use wants to build from source, `$DOCKER_IMAGE_PULL=false`, and when downloading from docker hub, `$DOCKER_IMAGE_PULL=true`. In both cases, the action makes a build, but I don't want to make a build from source in the case that I've already downloaded the image from docker hub. If the image has been downloaded according to the configuration of `pull`, why is, anyhow, making a build again if it could find the image on docker hub?

**Comment by jedevc** [comment]
To be able to detect if the image is the same configuration, you'll need to pull/push using a cache - for this purpose, an inline cache would probably suffice. Otherwise, buildkit has no way to verify that the image that is pulled is actually the same as the one that would be built.

**Comment by cgr71ii** [comment]
Thank you for your answer! Is there not an easiest way to keep docker installation (e.g. `docker run`) and skip the build step?

**Comment by cgr71ii** [comment]
Well, I think I got it. In case someone is with the same use case, I've disabled `docker/setup-buildx-action@v2` when I want to pull from Docker Hub and enabled it when I want to build. When I want to pull, I've added a new step in order to pull the image. Action `docker/setup-buildx-action@v2` gives support in order to run `docker pull`, `docker run`, ...

```yaml
      -  uses: actions/checkout@v3
         if: ${{ env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id }}
         with:
            submodules: 'recursive'
            ref: ${{ env.BUILD_REF }}
      -  name: Set up Docker Buildx
         if: ${{ env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id }}
         uses: docker/setup-buildx-action@v2
      -  name: Test docker
         if: ${{ env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id }}
         run: |
            docker pull hello-world > /dev/null
            docker run --rm hello-world > /dev/null
      -  name: Build and export to Docker
         if: ${{ env.CREATE_BUILD == 'true' && (env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id) }}
         uses: docker/build-push-action@v3
         with:
            context: .
            load: true # If true, once the image has been pulled or built, it will be available from docker
            push: false
            tags: ${{ env.DOCKER_IMAGE_TAG }}
      -  name: Pull image
         if: ${{ env.CREATE_BUILD == 'false' && (env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id) }}
         run: |
            docker pull "$DOCKER_IMAGE_TAG"
      -  name: Run tests
         if: ${{ env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id }}
         run: |
            # .......
```

Thank you for the support!
