### ISSUE TITLE
INPUT_REPOSITORY seems to be changing

### ISSUE THREAD

**Issue by dudo** [docker/build-push-action#67]
```
Run docker/build-push-action@v1
  with:
    username: $GITHUB_ACTOR
    password: ***
    registry: docker.pkg.github.com
    tags: latest
    tag_with_ref: false
    tag_with_sha: false
    path: .
    always_pull: false
    add_git_labels: false
    push: true
  env:
    INPUT_REPOSITORY: cardbinder/web_app/web_app

...

Login Succeeded
Building image [docker.pkg.github.com/cardbinder/web_app:latest]
Sending build context to Docker daemon  429.1kB

...

name unknown: docker image push is only supported with a tag of the format :owner/:repo_name/:image_name.
		Please add an image name to "cardbinder/web_app" tag. e.g. "cardbinder/web_app/<image_name>"
Error: exit status 1
```

My env seems to be getting clobbered or something. When I run this with `with` and hard code the `repository` key, it works fine. I don't want to hard code it, though, so that my actions work without any configuration.

Here's the whole action yaml I'm using:

```
on:
  push:
    branches:
      - develop
name: Docker Latest
jobs:
  docker:
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
      - name: Set ENV
        run: |
          echo ::set-env name=INPUT_REPOSITORY::$GITHUB_REPOSITORY/${GITHUB_REPOSITORY##*/}
      - uses: docker/build-push-action@v1 # https://github.com/marketplace/actions/build-and-push-docker-images
        with:
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: latest

```
