### ISSUE TITLE
docs: Please clarify purpose of input `builder`

### ISSUE THREAD

**Issue by polarathene** [docker/build-push-action#675]
The purpose of the `builder` input is not clear.

https://github.com/docker/build-push-action/blob/965c6a410d446a30e95d35052c67d6eded60dad6/README.md?plain=1#L204

It just links directly to a related action, but there is nothing there with examples of using this action with that one and the `builder` input relation.

This action README has no example or description of `builder` input in use, although I have seen a project workflow that uses it like so:

```yml
builder: ${{ steps.buildx.outputs.name }}
```

As the input is optional, is this something implicitly handled? In what situation would you use it?

**Comment by polarathene** [comment]
```
/usr/bin/docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max --iidfile /tmp/docker-build-push-zsEAUY/iidfile --output type=docker,dest=/tmp/docker-image-built.tar --platform linux/amd64,linux/arm64 --tag testing:ci --metadata-file /tmp/docker-build-push-zsEAUY/metadata-file .

error: docker exporter does not currently support exporting manifest lists
Error: buildx failed with: error: docker exporter does not currently support exporting manifest lists
```

Adding the `builder` input resolved that. Presumably the error is due to building for more than one platform (_due to manifest list_), or something else related to the configuration?:

```yml
  # Support ARM64 builds on AMD64 host:
  - name: 'Set up QEMU'
    uses: docker/setup-qemu-action@v2.0.0
    with:
      platforms: arm64

  - name: 'Set up Docker Buildx'
    uses: docker/setup-buildx-action@v2.0.0
    id: buildx

  - name: 'Build images locally'
    uses: docker/build-push-action@v3.1.1
    with:
      builder: ${{ steps.buildx.outputs.name }}
      context: .
      tags: testing:ci
      platforms: linux/amd64,linux/arm64
      cache-from: type=local,src=/tmp/.buildx-cache
      cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      # Export AMD64 image for upload-artifact step, allowing other jobs to use it:
      # https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#docker
      outputs: type=docker,dest=/tmp/docker-image-built.tar
```

The README only mentions `setup-buildx-action` being important for multi-platform builds, exports and other features.

I haven't checked yet, but besides only building for a single platform, if I remove `outputs` perhaps `builder` is not needed either.
