### ISSUE TITLE
`subdir not supported yet` while it should be supported

### ISSUE THREAD

**Issue by jkulak** [docker/build-push-action#676]
### Behaviour

It is a simple repository with a Dockerfile (in a subdirectory). I want to build the image and push it to Docker Hub. It fails.

#### Steps to reproduce this issue

1.  Fork https://github.com/jkulak/gh-actions-test
2. Commit any new file/change
3. Actions will run, and there will be an ERROR

#### Expected behaviour

It seems like a simple/basic use case for `build-push-action`. I would expect it build the Docker image and push it to Docker Hub.

#### Actual behaviour

Build fails. Seems like the action can not find the `Dockerfile`, which is located in the `./app` directory of the repository.

```
#1 [internal] load git source https://github.com/***/gh-actions-test.git#7915aa22036b623876c4e04eeda5754b72aafaeb:app
#1 ERROR: subdir not supported yet
```

### Configuration

* Repository URL (if public): https://github.com/jkulak/gh-actions-test
* Build URL (if public): https://github.com/jkulak/gh-actions-test/runs/7976332899?check_suite_focus=true

```yml
name: Docker Image CI

on:
    push:
        branches: ["*"]

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: "{{defaultContext}}:app"
                  push: true
                  tags: grabtrack/app:latest
```

### Logs

[logs_4.zip](https://github.com/docker/build-push-action/files/9403730/logs_4.zip)

Also:

```
1s
Run docker/build-push-action@v3
  with:
    context: {{defaultContext}}:app
    push: true
    tags: grabtrack/app:latest
    load: false
    no-cache: false
    pull: false
    github-token: ***
Docker info
Buildx version
  /usr/bin/docker buildx version
  github.com/docker/buildx 0.9.0+azure-[1](https://github.com/jkulak/gh-actions-test/runs/7976332899?check_suite_focus=true#step:3:1) 6113[2](https://github.com/jkulak/gh-actions-test/runs/7976332899?check_suite_focus=true#step:3:2)9fc7f1[3](https://github.com/jkulak/gh-actions-test/runs/7976332899?check_suite_focus=true#step:3:3)65556789bff[4](https://github.com/jkulak/gh-actions-test/runs/7976332899?check_suite_focus=true#step:3:4)747f608d40cdc8a9
/usr/bin/docker buildx build --iidfile /tmp/docker-build-push-0pxVKg/iidfile --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-build-push-0pxVKg/tmp-1[5](https://github.com/jkulak/gh-actions-test/runs/7976332899?check_suite_focus=true#step:3:5)35-gtFtbXRZZaTx --tag grabtrack/app:latest --metadata-file /tmp/docker-build-push-0pxVKg/metadata-file --push https://github.com/***/gh-actions-test.git#7915aa2203[6](https://github.com/jkulak/gh-actions-test/runs/7976332899?check_suite_focus=true#step:3:6)b6238[7](https://github.com/jkulak/gh-actions-test/runs/7976332899?check_suite_focus=true#step:3:7)6c4e04eeda5754b72aafaeb:app
#1 [internal] load git source https://github.com/***/gh-actions-test.git#7915aa22036b623[8](https://github.com/jkulak/gh-actions-test/runs/7976332899?check_suite_focus=true#step:3:8)76c4e04eeda5754b72aafaeb:app
#1 ERROR: subdir not supported yet
------
 > [internal] load git source https://github.com/***/gh-actions-test.git#7[9](https://github.com/jkulak/gh-actions-test/runs/7976332899?check_suite_focus=true#step:3:9)15aa22036b623876c4e04eeda5754b72aafaeb:app:
------
ERROR: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: subdir not supported yet
Error: buildx failed with: ERROR: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: subdir not supported yet
```
