### ISSUE TITLE
Conditional platform configuration

### ISSUE THREAD

**Issue by weeco** [docker/build-push-action#679]
**Usecase**

Generally I'd always like to push Docker images for amd64 & arm64 for every new release as well as for every single git push. However building multi-platform images is pretty slow in GitHub actions (~1.5h in our case) where the single platform build is done within ~10minutes.

Therefore I would only like to enable multi platform builds for Git releases and otherwise it should just target one platform.

**Feature request**

Currently we can only provide a comma-separated string array for our target platforms:

```yaml
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
```

Instead it would be nice to have multi-line configurations as an option, similar as we do have in docker/metadata-action:

```yaml
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            name=linux/amd64,enable=true
            name=linux/arm64,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.docker_meta.outputs.tags }}
```

I might be missing an easy workaround for this. If there is one I'd be very curious to know how to achieve that (without using a duplicate build/push block and use the `if` property there).
