### ISSUE TITLE
403 error when trying to push to multiple gcr registries

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [docker/build-push-action#689]
### Behaviour

Trying to adhere to the guide on how to push to multiple registries according to this guide.

#### Steps to reproduce this issue

```yaml

      - name: login to gcr1
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REPOSITORY }}
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_ACCOUNT_1 }}

      - name: login to gcr2
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REPOSITORY }}
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_ACCOUNT_2 }}

      - name: build and push images
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build_args }}
          tags: |
            ${{ steps.set-images.outputs.image-list }}
```

The `${{ steps.set-images.outputs.image-list }}` is something like this

```
gcr.io/gcr-repo1/my-image:mytag
gcr.io/gcr-repo2/my-image:mytag
```

The build starts and finishes with success

Note that **BOTH** logins succeed

#### Expected behaviour

Images gcr.io/gcr-repo1/my-image:mytag and gcr.io/gcr-repo2/my-image:mytag should be pushed to `gcr.io/gcr-repo1` and `gcr.io/gcr-repo2`

#### Actual behaviour

```
#14 [auth] gcr-repo2/my-image:pull,push token for gcr.io
#14 DONE 0.0s

#13 exporting to image
#13 pushing layers 0.3s done
#13 ERROR: failed to authorize: failed to fetch oauth token: unexpected status: 403 Forbidden
------
 > exporting to image:
------
ERROR: failed to solve: failed to fetch oauth token: unexpected status: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: failed to fetch oauth token: unexpected status: 403 Forbidden
```

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
Authentication is scoped to the registry `gcr.io`. You can't login to the same registry with multiple accounts. Therefore only `login to gcr2` will be effective. You should handle permissions of this service account on GCR for both repos.

> The `${{ steps.set-images.outputs.image-list }}` is something like this
> 
> ```
> gcr.io/gcr-repo1/my-image:mytag
> gcr.io/gcr-repo2/my-image:mytag
> ```

Also tags don't seem right looking at your logs:

```
#14 [auth] gcr-repo2/my-image:pull,push token for gcr.io
#14 DONE 0.0s
```

`gcr-repo2/my-image` should be smth like `gcr.io/gcr-repo2/my-image`.

**Comment by pantelis-karamolegkos** [comment]
I assume this is a limitation of `gcr.io`, right? The same example would work if I wanted to push to `dockerhub` and (one) `gcr.io` at the same time? (setting aside the tag format)

**Comment by pantelis-karamolegkos** [comment]
Also, I don't know why the logs spit out the tags like this in the end, but the build command seems right (logs below)

```
Buildx version
  /usr/bin/docker buildx version
  github.com/docker/buildx 0.9.1+azure-1 ed00243a0ce2a0aee75311b06e32d33b44729689
  ::endgroup::
/usr/bin/docker buildx build --iidfile /tmp/docker-build-push-pFUSRo/iidfile --tag gcr.io/gcr-repo1/my-image:mytag --tag gcr.io/gcr-repo2/my-image:mytag --metadata-file /tmp/docker-build-push-pFUSRo/metadata-file --push ./somescript.sh
```

**Comment by crazy-max** [comment]
> `--tag gcr.io/gcr-repo1/my-image:mytag --tag gcr.io/gcr-repo2/my-image:mytag`

Tags look good actually

> And also the `DONE` part perhaps is erroneously reassuring here?
> 
> ```
> #14 [auth] gcr-repo2/my-image:pull,push token for gcr.io
> #14 DONE 0.0s
> ```

Ah ok I get it, so `gcr-repo2/my-image` is right there as it checks "token for gcr.io".

> I assume this is a limitation of `gcr.io`, right?

Not a limitation on `gcr.io`, this would be the same for ECR or ACR. You just need to set correct permissions on GCR console to access both repositories with a single service account.

> The same example would work if I wanted to push to `dockerhub` and (one) `gcr.io` at the same time? (setting aside the tag format)

Yes because registry is not the same (`docker.io` and `ghcr.io`).

**Comment by dzervas** [comment]
To add another solution:

You have to give the `packages: write` permission to the specific workflow as described [here](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs):

```yaml
permissions:
  packages: write

jobs:...
```
