### ISSUE TITLE
Read Only File System

### ISSUE THREAD

**Issue by ideonrandy** [docker/build-push-action#690]
### Troubleshooting

1. Went through the doc - issue not covered
2. Attempted to add `security.insecure` to the `allow` option
3. Attempted a `chmod 755 /etc/`

### Behaviour
I'm building a DHCP docker container which needs to modify the contents to `/etc/hosts` and `/etc/dhcp/dhcpd.conf` - in attempting to write changes, I get an error that states the filesystem is read only. Below is the code needed for the minimally reproducible example which will be outlined in the next section:

**create_docker.yml (uses docker/build-push-action@v3 - not working)**
```
name: Build and Publish DHCP

on:
  # run it on push to the default repository branch
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Docker image name tag'
        required: false
        default: 'dhcp'

jobs:
  push-image-to-docker-hub:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)
    steps:
    - name: Checkout
      uses: actions/checkout@v3 # first action : checkout source code
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: <your registry>
        username: <your username>
        password: <your password>
    - name: Build and Push to DigitalOcean Container Registry
      uses: docker/build-push-action@v3
      with:
        context: .
        file: dhcp.Dockerfile
        platforms: linux/amd64
        push: true
        tags: <your registry>/${{github.event.inputs.TAG}}
```

**create_docker.yml (works but doesn't use docker/build-push-action@v3)**
```
name: Build and Publish DHCP

on:
  # run it on push to the default repository branch
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Docker image name tag'
        required: false
        default: 'dhcp'

jobs:
  push-image-to-docker-hub:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)
    steps:
    - name: Checkout
      uses: actions/checkout@v3 # first action : checkout source code
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: <your registry>
        username: <your username>
        password: <your password>
    - name: Build and Push to DigitalOcean Container Registry
      run: docker build -t ${{github.event.inputs.TAG}} -f dhcp.Dockerfile .
```

**dhcp.Dockerfile**
```
#Adding a dhcpd.conf file to the base image
FROM networkboot/dhcpd

RUN apt-get update && apt-get -y upgrade && \
    echo "dummy" >> /etc/hosts
```

#### Steps to reproduce this issue

1. Create an empty repository `Dummy` with a github actions folder
2. Copy the non-working `create_docker.yml` to the github actions folder
3. Copy the `dhcp.Dockerfile` to `~/Dummy`
4. Push the repo contents to github
5. Run a github action to create the docker image

#### Expected behaviour

The image should create without any issues - this will be evident if the steps above are redone with the working `create_docker.yml` file

#### Actual behaviour
`cannot create /etc/hosts: Read-only file system`

### Configuration

Files needed for a minimally reproducible example are in the **Behaviour** section

### Logs

`cannot create /etc/hosts: Read-only file system` is the error thrown
