### ISSUE TITLE
Unable to COPY artifacts downloaded with download-artifacts

### ISSUE THREAD

**Issue by terjekv** [docker/build-push-action#691]
### Behaviour

I am trying to use upload-artifact to store some artifacts from a pervious part of the workflow and then download-artifact to fetch those in the next stage. This works fine. However, once I try to COPY these artifacts into a Docker, I can't find these artifacts no matter if I use WORKDIR or full paths. 

I have tested that the artifacts are created and uploaded as expected, and they are also shown as downloaded correctly. It is the copying into the docker that I cannot get to work.

#### Steps to reproduce this issue

Good question. Do we have a simplified solution with upload-artifact, download-artifact and copy into a docker that works? I have not been able to find an example that uses this kind of a workflow. :(

The output from a test run can be seen here: 
#### Expected behaviour

Ideally, I would like to be able to copy the artifact into the Docker image :)

#### Actual behaviour

I consistently get, no matter what I do with WORKDIR or pathing for the artifact:

````
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref t8g1qr0vtgpmd3ggljtaq2g1z::d8v6fu372t8i1zbg7k5626zaj: "/github-authorized-keys.amd64": not found
[146](https://github.com/terjekv/github-authorized-keys/actions/runs/3108515551/jobs/5037813725#step:9:149)
Error: buildx failed with: ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref t8g1qr0vtgpmd3ggljtaq2g1z::d8v6fu372t8i1zbg7k5626zaj: "/github-authorized-keys.amd64": not foundERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref t8g1qr0vtgpmd3ggljtaq2g1z::d8v6fu372t8i1zbg7k5626zaj: "/github-authorized-keys.amd64": not found
[146](https://github.com/terjekv/github-authorized-keys/actions/runs/3108515551/jobs/5037813725#step:9:149)
Error: buildx failed with: ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref t8g1qr0vtgpmd3ggljtaq2g1z::d8v6fu372t8i1zbg7k5626zaj: "/github-authorized-keys.amd64": not found

````
### Configuration

* Repository URL (if public): https://github.com/terjekv/github-authorized-keys/
* Build URL (if public): https://github.com/terjekv/github-authorized-keys/actions/runs/3108515551/jobs/5037813725 

```yml
on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.31
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: README.md LICENSE

    - name: Debug build environment
      run: pwd; ls -R

    - name: Copy the artifact itself to isolate it
      run: cp ./build-artifacts-*/github-authorized-keys github-authorized-keys.${{ matrix.goarch }}

    - uses: actions/upload-artifact@v3
      with:
        path: github-authorized-keys.${{ matrix.goarch }}

  # define job to build and publish docker image
  # https://event-driven.io/en/how_to_buid_and_push_docker_image_with_github_actions/
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    needs: releases-matrix

    # steps to perform in job
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: releases
      
      - name: Debug downloads
        run: pwd; ls -R

      - name: Copy downloaded artifacts to . for Dockerfile compatibility
        run: cp -av ./releases/artifact/* .

      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            terjekv/github-authorized-keys:latest 
            ghcr.io/terjekv/github-authorized-keys:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```

 The Dockerfile is simple enough:

````
FROM --platform=$BUILDPLATFORM alpine:3.15.4 as stage
# FROM --platform=linux/arm64 alpine:3.15.4 as stage-arm64

ARG TARGETARCH

# [ lots of irrelevant ENV definitions ]

RUN apk --update --no-cache add libc6-compat ca-certificates shadow && \
    ln -s /lib /lib64

COPY ./github-authorized-keys.${TARGETARCH} /usr/bin/github-authorized-keys
RUN chmod +x /usr/bin/github-authorized-keys

ENTRYPOINT ["github-authorized-keys"]
````

### Logs

[logs_23.zip](https://github.com/docker/build-push-action/files/9629661/logs_23.zip)

**Comment by crazy-max** [comment]
Looking at your workflow, I wonder why you're building your Go app using another action using a matrix in a dedicated job: https://github.com/terjekv/github-authorized-keys/blob/46f2a49350cf6cc1a68ee972c8d1d21694287ddf/.github/workflows/releases.yml#L19-L24

```yaml

**Comment by L1ghtman2k** [comment]
I ran into this issue myself recently. Turns out, this issue is due to:
```
      - name: Checkout code
        uses: actions/checkout@v3
```
being called after artifacts have been downloaded, which ends up cleaning all previously instantiated files in that directory, including the artifact you have downloaded

**Comment by tuxerrante** [comment]
> being called after artifacts have been downloaded

Actually I'm experiencing the same issue even if the steps are in the correct order as suggested by docker plugin templates. 
https://github.com/tuxerrante/kapparmor/commit/00fb10f4fd4f6ba5297857ebfee9901323832eb1

In [this issue](https://github.com/docker/build-push-action/issues/97) they suggest persisting it with the artifact download plugin but it doesn't seem to work in this case.

> Why not building directly the app in the Dockerfile?
@crazy-max  Because I care more about operating my applications than moving a few bytes inside huge platforms like GitHub or Azure pipelines.  Using multiple jobs let me have separation of concerns where every one does one single activity, letting me also to configure different access rights more easily. Is it why jobs are born in first place, right?

Doing it all inside the Dockerfile [seems to work fine](https://github.com/tuxerrante/kapparmor/actions/runs/3893780995/jobs/6646847875) by the way.
Thanks

**Comment by radicand** [comment]
I had a similar issue, and it turned out that the default context is the Git context (clones the repo fresh inside Docker). Adding `context: .` to the `with:` parameters resolved it. I see OP has context already specified so the issue may be different, however wanted to leave this note in case it helps anyone else.

**Comment by crazy-max** [comment]
@tuxerrante 

> In [this issue](https://github.com/docker/build-push-action/issues/97) they suggest persisting it with the artifact download plugin but it doesn't seem to work in this case.

That's a pretty old issue but yes using [upload-artifact](https://github.com/actions/upload-artifact/) action could work like in https://docs.docker.com/build/ci/github-actions/examples/#share-built-image-between-jobs where we share an image between jobs.

> Because I care more about operating my applications than moving a few bytes inside huge platforms like GitHub or Azure pipelines.

But you are tight to the CI so migration to another CI provider will be painful and also by not being sandboxed you can't repro easily locally what fails on CI.

> Using multiple jobs let me have separation of concerns where every one does one single activity, letting me also to configure different access rights more easily. Is it why jobs are born in first place, right?

With a Dockerfile you can have a clear separation concerns by running a specific target so you don't need to specify any of these steps: https://github.com/tuxerrante/kapparmor/blob/00fb10f4fd4f6ba5297857ebfee9901323832eb1/.github/workflows/build-and-push.yml#L28-L38

> Do you think code testing should be run also in containerfiles?

Depends on what you're testing. See for example our [Dockerfile in buildx repo](https://github.com/docker/buildx/blob/master/Dockerfile) and our [Bake definition](https://github.com/docker/buildx/blob/master/docker-bake.hcl) that can runs lint, tests, vendoring, docs validation, building artifacts and releases, building image, checking outdated go modules, ... See also our [workflow](https://github.com/docker/buildx/blob/d2fa4a57244df2d1aae9efc9dfe6f563f72bafc3/.github/workflows/build.yml)

@terjekv

As @L1ghtman2k said, you have to move the `Checkout code` step on top of your job like shown in the README of the action: https://github.com/actions/download-artifact

**Comment by tuxerrante** [comment]
> That's a pretty old issue but yes using [upload-artifact](https://github.com/actions/upload-artifact/) action could work like in https://docs.docker.com/build/ci/github-actions/examples/#share-built-image-between-jobs where we share an image between jobs.

Thanks, in the end I had proceeded exactly like that

> Depends on what you're testing. See for example our [Dockerfile in buildx repo](https://github.com/docker/buildx/blob/master/Dockerfile) and our [Bake definition](https://github.com/docker/buildx/blob/master/docker-bake.hcl) that can runs lint, tests, vendoring, docs validation, building artifacts and releases, building image, checking outdated go modules, ... See also our [workflow](https://github.com/docker/buildx/blob/d2fa4a57244df2d1aae9efc9dfe6f563f72bafc3/.github/workflows/build.yml)

I'm starting unit testing at the end of Dockerfile building, the goal is to trigger the tests and have some coverage result published. I was having issues in saving the results of the tests outside of the docker container, to have them read by the codecov/codecov-action GH action. Something like:
```
RUN go get -d -v .
RUN go build  -v -o /go/bin/app .
RUN go test   -coverprofile=coverage.out  # Need this out of the container 
```
And
```
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          fail_ci_if_error: true
          verbose: true

```
I'm looking in how you use[ --mount in the RUN command](https://github.com/docker/buildx/blob/master/Dockerfile#L42).

I'm not sure I need such a complex bake file rught now, but I'm still new to that.
Thanks again
