### ISSUE TITLE
Git Secrets as enn variables

### ISSUE THREAD

**Issue by alejoGT1202** [docker/build-push-action#698]
### Troubleshooting

Tried to replicate the solution presented in the following issue #390 

### Behaviour

Inside my workflow I'm passing my organization secrets as follows:

```      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          secrets: |
           "CASSANDRA_CLIENT_ID=${{ secrets.CASSANDRA_CLIENT_ID }}"
           "CASSANDRA_CLIENT_SECRET=${{ secrets.CASSANDRA_CLIENT_SECRET }}"
          labels: ${{ steps.meta.outputs.labels }}
``` 

Inside my docker file I'm executing the suggested command from #390 

``` 
RUN --mount=type=secret,id=CASSANDRA_CLIENT_ID \
  --mount=type=secret,id=CASSANDRA_CLIENT_SECRET \
   export CASSANDRA_CLIENT_ID=$(cat /run/secrets/CASSANDRA_CLIENT_ID) && \
   export CASSANDRA_CLIENT_SECRET=$(cat /run/secrets/CASSANDRA_CLIENT_SECRET) && \
   echo $CASSANDRA_CLIENT_ID
  
```

However, when my python script is trying to access to the env variables through   `os.getenv('CASSANDRA_CLIENT_ID')` it returns a `None` value.  
#### Steps to reproduce this issue

1. Pass github secrets through the workflow
2. In the docker file add the `--mount=type=secret` line to access to the variables and export it to the desired variable name.
3. Run the docker container and echo the env variable to see if it's present

#### Expected behaviour

The github secret should be passed to the container as and env variable. 

#### Actual behaviour

The container doesn't have any of the defined secret variables  in the workflow

### Configuration

```
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          secrets: |
           "cassandra_client_id=${{ secrets.CASSANDRA_CLIENT_ID }}"
           "cassandra_client_secret=${{ secrets.CASSANDRA_CLIENT_SECRET }}"
          labels: ${{ steps.meta.outputs.labels }}


```
