### ISSUE TITLE
How to use step/build cache?

### ISSUE THREAD

**Issue by amcsi** [docker/build-push-action#70]
Every time I push changes, it runs all the steps in the Dockerfile, rather than using the cached verion.

Here is my workflow yml:

https://github.com/amcsi/lycee-overture/commit/1b83c4c6a7e1d4385edc44fb05d2bcf59a984e13

Here is my Dockerfile:

https://github.com/amcsi/lycee-overture/blob/ac5c162e2ad314055c44cb89b9d60fba27d6fac5/Dockerfile

How do I get all the possible steps to use the cache?

**Comment by tonistiigi** [comment]
Use `cache_from`, for example with Buildkit inline cache https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources

**Comment by amcsi** [comment]
@tonistiigi I'm not sure if I understand... So I should just repeat what I put as a value for `repository` as a value from `cache_from`, and then caching would work?

So in my case...

```yaml
        ...
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          repository: amcsi/lycee-overture
          cache_from: amcsi/lycee-overture # <- Is this the line I need to add?
```
