### ISSUE TITLE
Secrets not working as expected (mount fails)

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [docker/build-push-action#701]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

A secret mount is not made available to the `Dockerfile` (apparently)

#### Steps to reproduce this issue

1. Create the following `Dockerfile`

```
# syntax = docker/dockerfile:1.3

FROM alpine:3.14

RUN --mount=type=secret,id=JFROG_PASS \
  cat /run/secrets/JFROG_PASS


RUN wget --user ${JFROG_USER} --password ${JFROG_PASS} "https://my/jfrog/binary" 
```

2. Execute the following action

```
      - name: build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          no-cache: ${{ inputs.no_cache }}
          build-args: ${{ inputs.build_args }}
          secrets: |
            "JFROG_PASS=${{ secrets.MY_PASSWORD }}"
          push: true
          tags: ${{ env.LOCAL_IMAGE }}
```

#### Expected behaviour

> Tell us what should happen

The `wget` command inside the `Dockerfile` should have succeeded (the values have been tested)

#### Actual behaviour

> Tell us what happens instead

The process of `mount` fails, check logs

### Logs

```
#9 [stage-0 2/8] RUN --mount=type=secret,id=JFROG_PASS   cat /run/secrets/JFROG_PASS
#0 0.062 cat: can't open '/run/secrets/JFROG_PASS': No such file or directory
#9 ERROR: process "/bin/sh -c cat /run/secrets/JFROG_PASS" did not complete successfully: exit code: 1
------
 > [stage-0 2/8] RUN --mount=type=secret,id=JFROG_PASS   cat /run/secrets/JFROG_PASS:
#0 0.062 cat: can't open '/run/secrets/JFROG_PASS': No such file or directory
------
Dockerfile:5
--------------------
   4 |     
   5 | >>> RUN --mount=type=secret,id=JFROG_PASS \
   6 | >>>   cat /run/secrets/JFROG_PASS
   7 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cat /run/secrets/JFROG_PASS" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c cat /run/secrets/JFROG_PASS" did not complete successfully: exit code: 1
```

**Comment by crazy-max** [comment]
> ```dockerfile
> RUN --mount=type=secret,id=JFROG_PASS \
>   cat /run/secrets/JFROG_PASS
> 
> 
> RUN wget --user ${JFROG_USER} --password ${JFROG_PASS} "https://my/jfrog/binary" 
> ```

Secret mounts are only available for the `RUN` instruction to which they are specified.

This should work:

```dockerfile
RUN --mount=type=secret,id=JFROG_PASS \
  wget --user ${JFROG_USER} --password $(cat /run/secrets/JFROG_PASS) "https://my/jfrog/binary" 
```

**Comment by pantelis-karamolegkos** [comment]
Here is my new `Dockerfile` (did not change anything in the action invocation)

```
FROM alpine:3.14

ARG JFROG_USER

RUN -mount=type=secret,id=JFROG_PASS \
  cat /run/secrets/JFROG_PASS wget --user ${JFROG_USER} --password ${JFROG_PASS} "https://my/jfrog/binary"
```

And here is the new error

```
#14 [7/7] RUN -mount=type=secret,id=JFROG_PASS   cat /run/secrets/JFROG_PASS wget --user dev-robot -*** "https://my/jfrog/binary" 
#0 0.065 errexit         on
#0 0.065 noglob          on
#0 0.065 ignoreeof       on
#0 0.065 monitor         on
#0 0.065 noexec          on
#0 0.065 xtrace          on
#0 0.065 verbose         on
#0 0.065 noclobber       on
#0 0.065 allexport       on
#0 0.065 notify          on
#0 0.065 nounset         on
#0 0.065 vi              on
#0 0.065 pipefail        on
#0 0.065 /bin/sh: illegal option -t
#14 ERROR: process "/bin/sh -c -mount=type=secret,id=JFROG_PASS   cat /run/secrets/JFROG_PASS wget --user $***JFROG_USER*** -*** \"https://my/jfrog/binary\" " did not complete successfully: exit code: 2
------
 > [7/7] RUN -mount=type=secret,id=JFROG_PASS   cat /run/secrets/JFROG_PASS wget --user dev-robot -*** "https://my/jfrog/binary"
#0 0.065 noexec          on
#0 0.065 xtrace          on
#0 0.065 verbose         on
#0 0.065 noclobber       on
#0 0.065 allexport       on
#0 0.065 notify          on
#0 0.065 nounset         on
#0 0.065 vi              on
#0 0.065 pipefail        on
#0 0.065 /bin/sh: illegal option -t
------
Dockerfile:13
--------------------
  12 |       
  13 | >>> RUN -mount=type=secret,id=JFROG_PASS \
  14 | >>>   cat /run/secrets/JFROG_PASS wget --user $***JFROG_USER*** -*** "https://my/jfrog/binary" 
  15 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c -mount=type=secret,id=JFROG_PASS   cat /run/secrets/JFROG_PASS wget --user $***JFROG_USER*** -*** \"https://my/jfrog/binary\" " did not complete successfully: exit code: 2
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c -mount=type=secret,id=JFROG_PASS   cat /run/secrets/JFROG_PASS wget --user $***JFROG_USER*** -*** \"https://my/jfrog/binary\" " did not complete successfully: exit code: 2
```

**Comment by pantelis-karamolegkos** [comment]
Here is the new `Dockerfile` (did not change anything in the action invocation)

```
# syntax = docker/dockerfile:1.3

FROM alpine:3.14

ARG JFROG_USER

RUN --mount=type=secret,id=JFROG_PASS \
  wget --user ${JFROG_USER} --password $(cat /run/secrets/JFROG_PASS) "https://my/jfrog/binary" 
```

and here is the new error

```
#9 [stage-0 2/2] RUN --mount=type=secret,id=JFROG_PASS   wget --user my-jfrog-user -*** /run/secrets/JFROG_PASS) "https://my/jfrog/binary"
#0 0.051 cat: can't open '/run/secrets/JFROG_PASS': No such file or directory
#9 0.052 wget: unrecognized option: password
#9 0.057 BusyBox v1.33.1 () multi-call binary.
```

**Comment by pantelis-karamolegkos** [comment]
do I have to explicitly create the `/run/secrets/JFROG_PASS` myself in a previous step? or does the action take care of this?

**Comment by crazy-max** [comment]
Do you have a link to your repo or logs?

**Comment by pantelis-karamolegkos** [comment]
Hm...I think I have figured it out...

This action is part of a re-usable workflow

```
      - name: build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          no-cache: ${{ inputs.no_cache }}
          build-args: ${{ inputs.build_args }}
          secrets: |
            "JFROG_PASS=${{ secrets.MY_PASSWORD }}"
          push: true
          tags: ${{ env.LOCAL_IMAGE }}
```

so the problem seems to be I have not explicitly declared `MY_PASSWORD` as a secret in the re-usable workflow.

(I am in the process of making this generic since we have the `docker/build-push-action` as a step of a reusable workflow.
