### ISSUE TITLE
Build times out trying to copy files from gha cache

### ISSUE THREAD

**Issue by hgibsonqb** [docker/build-push-action#710]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

We using the build-push-action to build a container image. We're using gha for caching and multi-stage builds. 

We keep getting an intermittent failure where docker buildx will time out trying to copy files from the cache.
```
#37 ERROR: failed to copy: read tcp 172.17.0.2:43996->20.150.90.4:443: read: connection timed out
------
 > [production-assets-compiler 1/2] COPY --chown=indigo:indigo . /indigo/:
------
Dockerfile:139
--------------------
 137 |     LABEL description="Used to compile Indigo production assets"
 138 |     
 139 | >>> COPY --chown=indigo:indigo . $APP_HOME/
 140 |     
 141 |     RUN RAILS_ENV=production \
--------------------
ERROR: failed to solve: failed to compute cache key: failed to copy: read tcp 172.17.0.2:43996->20.150.90.4:443: read: connection timed out
Error: buildx failed with: ERROR: failed to solve: failed to compute cache key: failed to copy: read tcp 172.17.0.2:43996->20.150.90.4:443: read: connection timed out
```

I reached out to github support about this already, and they suspect the steps that's failed is when the client makes a request to Azure Blob Storage to download the cached data. They claim "this is not something that we can help further since the action is not owned by us". But they recommend open a support ticket here also. Do you have any insight into this issue?

#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell us what should happen

The build should succeed and push a new container image

#### Actual behaviour

> Tell us what happens instead

Sometimes the build tries to copy files from the cache but times out, causing the build to fail.

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Generate image tags (indigo)
        id: indigo-tags
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{github.repository}}
          tags: |
            type=raw,enable=${{ github.ref_name == 'main' }},value=latest
            type=sha,format=long,prefix=
      - name: Docker Release (indigo)
        uses: docker/build-push-action@v3
        with:
          build-args: |
             GITHUB_USER=ats-ci
             GITHUB_TOKEN=${{ secrets.ATS_CI_GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: build_docker/Dockerfile
          labels: ${{ steps.indigo-tags.outputs.labels }}
          push: true
          tags: ${{ steps.indigo-tags.outputs.tags }}
          target: indigo-static-assets
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

I'm leaving the log archive out because it has sensitive data, but I've posted the relevant error message. Let me know if you need any more information.

**Comment by crazy-max** [comment]
> Error: buildx failed with: ERROR: failed to solve: failed to compute cache key: failed to copy: read tcp 172.17.0.2:43996->20.150.90.4:443: read: connection timed out

This looks like an intermittent network issue to connect to GitHub Cache backend, don't think we can do much about this.

If you can enable debug and post [BuildKit logs](https://github.com/docker/setup-buildx-action#buildkit-container-logs) if it happens again that would be useful:

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
```

Closing in the meantime.
