### ISSUE TITLE
Multi-platform image is being built without Qemu, with amd64 builder only

### ISSUE THREAD

**Issue by haimgel** [docker/build-push-action#711]
### Behaviour

I'm seeing something strange:
1. I didn't set up Qemu
2. Set up `setup-buildx-action`, even manually specified `linux/amd64` as the sole platform.
3. Specified `linux/arm64,linux/ppc64le` platforms for `build-push-action`

**It builds the multi-platform image**! I don't understand why, and how, according to the docs in this repo it shouldn't (multi-platform build under advanced docs)

#### Steps to reproduce this issue

[Sample repo](https://github.com/haimgel/test-docker-build), my [action run there](https://github.com/haimgel/test-docker-build/actions/runs/3325656947/jobs/5498621913)

#### Expected behaviour

I expect this build not to succeed, due to platforms mismatch.

#### Actual behaviour

It builds successfully.

### Configuration

* Repository URL (if public): https://github.com/haimgel/test-docker-build
* Build URL (if public): https://github.com/haimgel/test-docker-build/actions/runs/3325656947/jobs/5498621913

```yml
name: TEST

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - id: builder-github
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - run: |
          docker buildx ls
          docker buildx inspect --bootstrap
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64,linux/ppc64le
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### Logs

[logs_2.zip](https://github.com/docker/build-push-action/files/9870249/logs_2.zip)
