### ISSUE TITLE
Building and Pushing Docker image with private npm packages on GitHub Actions

### ISSUE THREAD

**Issue by matzar** [docker/build-push-action#712]
I'm using GitHub Actions to build and push my Docker image.

I've got private npm packages in my Dockerfile.

I need to install them when building the image.

To do it securely I'm using `--secret` flag.

This is how I got around building a Docker image with private npm packages with GutHub Actions:

```yml
- name: Build and Push Docker image
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          docker buildx build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }} --secret id=npmrc,src=.npmrc --push
```

It's probably not state of the art so, any idea how could I improve this?

There's obviously other steps before this one, like logging to docker, checking out the branch etc.
