### ISSUE TITLE
Specify repository package README

### ISSUE THREAD

**Issue by brettinternet** [docker/build-push-action#722]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. In a containers monorepo with multiple images where the README is in a subdirectory
2. build and push to GHCR or Docker Hub

#### Expected behaviour

It should README in the context directory or allow users to specify the location of the README.

#### Actual behaviour

Docker Hub does not have any README, and GHCR uses the project's root README.

### Configuration

```yml
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./containers/${{ env.IMAGE_NAME }}
          file: ./containers/${{ env.IMAGE_NAME }}/Dockerfile
          platforms: arm64,amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.name=${{ env.IMAGE_NAME }}
```
