### ISSUE TITLE
build-push-action not copying hidden folder to docker image

### ISSUE THREAD

**Issue by sarahcthekey** [docker/build-push-action#728]
#### Expected behaviour

The Dockerfile has a step to copy `next` folder (containing a hidden folder called `.next` to /opt/auth-service/next):

`COPY   next         /opt/auth-service/next`

The next/.next folder should copy across to the docker image when using the build-push-action, like it does if I run a `docker build -t <image-name> .` command on the github runner manually (when SSH'd in) or on my local machine.

#### Actual behaviour

My issue is that the build-and-push step copies all the contents of the `next` folder to the docker image **apart from** the hidden folder and I can't seem to find out why. 

- I've used tmate (`mxschmitt/action-tmate@v3`) to SSH into the github action runner just before the build/push step and can confirm the folder `next/.next` is present. 
- Whilst on the github runner I can also run `docker build -t <image-name> .` and then when I download that image to my laptop and run it, the `next/.next` folder is there. But not when it's build by the `docker/build-push-action@v3` action.
- There is nothing in `.gitignore` or `.dockerignore` for the `next` or `.next` folders, so they should be included 

```yml
name: Build Docker

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      key_image_name:
        required: false
        type: string
        default: ''
      image_tag:
        required: false
        type: string
        default: ${{ github.sha }}
      build-args:
        required: false
        type: string
      build_arm:
        required: false
        type: boolean
        default: false
    outputs:
      datetime:
        description: "The datetime used in the tag"
        value: ${{ jobs.build-docker.outputs.datetime }}
    secrets:
      build-args:
        required: false
      build-secrets:
        required: false
      PYTHON_GRPC_SSH_KEY:
        required: false

jobs:
  build-docker:
    runs-on: ubuntu-latest
    outputs:
      datetime: ${{ steps.vars.outputs.datetime }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: inputs.build_arm
        with:
          platforms: arm64

      - name: Authenticate to Google Cloud
        id: auth
        uses: **REDACTED**/github-actions/.github/actions/authenticate-gcp@main
        with:
          with_access_token: true
          gcp_project_id:  **REDACTED**
          gcp_workload_identity_provider: **REDACTED**

      - name: Download workspace data containing .next folder
        uses: actions/download-artifact@v3

      - name: Copy nextjs build over and check next folder is there
        run: |
          ls -l
          cp -r workspace next/.next
          ls -l next/.next

      # - name: Setup tmate session for SSH into github runner
      #   uses: mxschmitt/action-tmate@v3

      - name: 'Extract registry'
        uses: **REDACTED**/github-actions/.github/actions/extract-docker-registry@main
        with:
          image: ${{ inputs.image_name }}
        id: extract_registry

      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.extract_registry.outputs.registry }}
          username: **REDACTED**
          password: ${{ steps.auth.outputs.access_token }}

      - name: Setup variables
        id: vars
        uses: **REDACTED**/github-actions/.github/actions/setup-variables@main

      - name: Create tags
        id: tags
        with:
          branch: ${{ steps.vars.outputs.branch }}
          commit: ${{ github.sha }}
          datetime: ${{ steps.vars.outputs.datetime }}
        uses: **REDACTED/github-actions/.github/actions/create-tags@main

      - name: List directories in next directory (with hidden files)
        run: |
          ls -la next

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ inputs.build_arm && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}${{ inputs.key_image_name && format(',{0}:{1}', steps.thekey-image-name.outputs.key_image_name, steps.tags.outputs.tag1) || '' }}
          build-args: |
            ${{secrets.build-args}}
            ${{inputs.build-args}}
          secrets: |
            ${{secrets.build-secrets}}

```

### Logs

Attached logs for build_and_push with sensitive info redacted.

[14_Build and push.txt](https://github.com/docker/build-push-action/files/10083616/14_Build.and.push.txt)

**Comment by sarahcthekey** [comment]
Also attached logs for the step before build push which lists the contents of the directory on the github runner:

` ls -la next`

[13_List directories in next directory (with hidden files).txt](https://github.com/docker/build-push-action/files/10083660/13_List.directories.in.next.directory.with.hidden.files.txt)

**Comment by crazy-max** [comment]
Can you post your Dockerfile please?

**Comment by crazy-max** [comment]
Sorry for the delay, can you replace

```yaml
      - name: List directories in next directory (with hidden files)
        run: |
          ls -la next
```

with:

```yaml
      - name: List directories in next directory (with hidden files)
        run: |
          tree -anhpug next
```

and give me the output?
