### ISSUE TITLE
cache-from doesn't use cache with local aha runners

### ISSUE THREAD

**Issue by navi86** [docker/build-push-action#740]
docker build doesn't use cache from repo

#### Steps to reproduce this issue

1. create docker image and push to registry
2. create another commit

#### Expected behaviour
1. cache is working

#### Actual behaviour
cache is not working

however, if I run `docker build` manually then it uses cache
```
    - name: Create Docker Context for Buildx
      run: |
        docker context create builders
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        endpoint: builders
        buildkitd-flags: --debug
     
   - name: Login to Quay.io docker registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: "${{ steps.secrets.outputs.docker_username }}"
        password: "${{ steps.secrets.outputs.docker_password }}"
   
   - name: Build
      uses: docker/build-push-action@v3
      with:
        cache-from: type=registry,ref=quay.io/${{ steps.vars.outputs.github_repository }}:${{ steps.vars.outputs.branch_name }}
        push: false
        load: true
        tags: |
          quay.io/${{ steps.vars.outputs.github_repository }}:${{ steps.vars.outputs.branch_name }}
```
