### ISSUE TITLE
cache-from doesn't use cache with local gha runners

### ISSUE THREAD

**Issue by navi86** [docker/build-push-action#741]
docker build doesn't use cache from repo

#### Steps to reproduce this issue

1. create docker image and push to registry
2. create another commit

#### Expected behaviour
1. cache is working

#### Actual behaviour
cache is not working

however, if I run `docker build` manually then it uses cache
```
    - name: Create Docker Context for Buildx
      run: |
        docker context create builders
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        endpoint: builders
        buildkitd-flags: --debug
     
   - name: Login to Quay.io docker registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: "${{ steps.secrets.outputs.docker_username }}"
        password: "${{ steps.secrets.outputs.docker_password }}"

    - name: docker_build_manual
      run: |
        docker build -t quay.io/${{ steps.vars.outputs.github_repository }}:${{ steps.vars.outputs.branch_name }} ./ 
   
   - name: Build
      uses: docker/build-push-action@v3
      with:
        cache-from: type=registry,ref=quay.io/${{ steps.vars.outputs.github_repository }}:${{ steps.vars.outputs.branch_name }}
        cache-to: type=local,dest=/tmp/cache # I was also trying to use type=inline
        push: false
        load: true
        tags: |
          quay.io/${{ steps.vars.outputs.github_repository }}:${{ steps.vars.outputs.branch_name }}
```
moreover, I am using the same gha  runner agent, so I literally have docker images of previous runs therefore "docker_build_manual" step is using cache without issue. How to use cache for action "docker/build-push-action" ?
