### ISSUE TITLE
file param can't with double quotation marks

### ISSUE THREAD

**Issue by paomian** [docker/build-push-action#742]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. https://github.com/paomian/code-with-quarkus/blob/main/.github/workflows/build-docker.yml
2. set file parameter by result of github-script
3. https://github.com/paomian/code-with-quarkus/actions/runs/3639732416/jobs/6143488816#step:8:109

#### Expected behaviour

> use file

#### Actual behaviour

> buildx failed with: ERROR: could not find ".: stat ".: no such file or directory
but the file is exist.

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: test-build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


on:
  workflow_dispatch:
    inputs:
      target:
        description: 'build target native or jvm'
        required: true
        default: 'jvm'
        type: choice
        options:
          - jvm
          - native
      branch:
        description: 'which branch to use'
        required: true
        default: 'main'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
      packages: write
      id-token: write

    steps:
      - name: determine which docker file to use
        uses: actions/github-script@v6
        id: determine-docker-file
        with:
          script: |
            if (context.payload.inputs.target == 'native') {
              return './Dockerfile.0'
            } else {
              return './Dockerfile.1'
            }
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: get short sha
        id: short-sha
        run: echo "result=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.short-sha.outputs.result }}-{{date 'YYYYMMDDhhmmssSSS'}}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ steps.determine-docker-file.outputs.result }}
          push: true
          tags: user/app:latest
```

### Logs
[logs_1.zip](https://github.com/docker/build-push-action/files/10176894/logs_1.zip)
> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
Does not look to be an issue with the action but your workflow. What you're passing to the `file` input is effectively a quoted string `"./Dockerfile.1"` and therefore will be interpreted as such: https://github.com/paomian/code-with-quarkus/actions/runs/3639732416/jobs/6143488816#step:8:4

Looking at this step in your workflow:

```yaml
      - name: determine which docker file to use
        uses: actions/github-script@v6
        id: determine-docker-file
        with:
          script: |
            if (context.payload.inputs.target == 'native') {
              return './Dockerfile.0'
            } else {
              return './Dockerfile.1'
            }
```

It seems you forgot to set `result-encoding: string` as explained in https://github.com/actions/github-script#reading-step-results
