### ISSUE TITLE
Labels key does not apply labels to images

### ISSUE THREAD

**Issue by pentago** [docker/build-push-action#747]
#### Steps to reproduce this issue

1. Setup regular, simple image build/tag/push workflow containing `labels` key:

```
- name: Build Docker Image
  id: build_api
  uses: docker/build-push-action@v3.2.0
  with:
    context: .
    file: ./Dockerfile
    labels: |
      "commit=${{ env.SHA_SHORT }}"
      "commit_url=${{ env.COMMIT_URL }}/${{ env.SHA_SHORT }}"
    tags: |
      something:latest
    cache-to: type=gha,mode=max
    cache-from: type=gha
    push: true
```

#### Expected behaviour

Using `docker image inspect` should list above labels in JSON output.

#### Actual behaviour

No labels were shown in the JSON output as they likely aren't applied in the first place.

### Logs

Build logs actually show that propper strings are being used, I just don't see those applied to the image when doing inspect:
![build logs](https://i.imgur.com/DXGxHjA.png)

**Comment by douglassllc** [comment]
I am having the same issue.  My label is missing from my image.

`Docker version 20.10.22, build 3a2c30b`

**Comment by crazy-max** [comment]
I can't repro on my side:

```
name: labels

on:
  workflow_dispatch:

env:
  LOCAL_SLUG: "localhost:5000/name/app"

jobs:
  labels:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            network=host
          buildkitd-flags: --debug
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.LOCAL_SLUG }}:latest
          labels: |
            "commit=${{ github.sha }}"
            org.opencontainers.image.title=foo
            org.opencontainers.image.description=bar
      -
        name: Check manifest
        run: |
          docker buildx imagetools inspect ${{ env.LOCAL_SLUG }}:latest
      -
        name: Inspect image
        run: |
          docker pull ${{ env.LOCAL_SLUG }}:latest
          docker image inspect --format='{{.Config.Labels}}' ${{ env.LOCAL_SLUG }}:latest
```

Output of `Inspect image` step:

```
map[commit:f1929cd3f94533908955097937d061d4c505d4aa org.opencontainers.image.description:bar org.opencontainers.image.title:foo]
```
