### ISSUE TITLE
Corrective action unclear after a publish container image fails

### ISSUE THREAD

**Issue by kvchitrapu** [docker/build-push-action#751]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

PR Workflow fails to push the container image to ghcr.io from a public fork despite setting `package:write` access and Workfllow permission with "read and access" for the GITHUB_TOKEN on the target repo.

#### Steps to reproduce this issue

1. Create a PR from a fork branch
2. PR build triggers on the upstream branch
3. Wait for the build to fail

#### Expected behaviour

The step should push a container image to ghcr.io. 

#### Actual behaviour

The container push step fails with this error:
```
#37 ERROR: denied: installation not allowed to Write organization package
------
 > pushing ghcr.io/kvchitrapu/ambuda:pr-39 with docker:
------
ERROR: denied: installation not allowed to Write organization package
Error: buildx failed with: ERROR: denied: installation not allowed to Write organization package
```

### Configuration

* Repository URL (if public): https://github.com/kvchitrapu/ambuda/blob/main/.github/workflows/pr-open.yml
* Build URL (if public): https://github.com/kvchitrapu/ambuda/actions/runs/3868006836/jobs/6597669282

```
jobs:
  push_to_registries:
    name: Push Ambuda image to GH container registry
    runs-on: ubuntu-22.04
    environment: staging
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: GH container registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,value=v0.1-{{branch}}-{{sha}}
            type=ref,event=pr,value=pr-{{branch}}-{{sha}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,event=push,value=v0.1-{{branch}}-{{sha}}
      
      - name: Build and push Docker images
        id: publish
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: build/containers/Dockerfile.final
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
