### ISSUE TITLE
Feature Request: Add input 'save' has a shorthand for --output=type=docker,dest=

### ISSUE THREAD

**Issue by ricardo-dematos** [docker/build-push-action#753]
This input would allow to more easily create a step to build and save the Docker image to a Docker image specification tarball.

```yaml
  save:
    description: 'Save is a shorthand for `--output=type=docker,dest=`'
    required: false
    default: 'false'
  archive:
    description: 'Docker image specification tarball name (must include `tar.gz` extension)'
    required: false
    default: '${{ github.event.repository.name }}-docker.tar.gz'
```

```yaml
      - name: 'Build and save docker image'
        id: docker
        uses: docker/build-push-action@v3
        with:
          save: true
          archive: '${{ github.event.repository.name }}-docker.tar.gz'
          file: 'Dockerfile'
          labels: |
            version=1.0.0
          tags: |
            ${{ github.repository }}:1.0.0
            ${{ github.repository }}:latest
```
