### ISSUE TITLE
Not able to read passed secrets in the docker file.

### ISSUE THREAD

**Issue by Ganesh-Ponipireddy** [docker/build-push-action#754]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. 
```
name: Build image
      uses: docker/build-push-action@v3.2.0
      with:
        build-args: 
        secrets: |
            "github_token=${{ inputs.token }}"
```
3. In the Docker file: I had tried to consume: 
```
RUN --mount=type=secret,id=github_token \
    cat /run/secrets/github_token

RUN echo ${id}
```

#### Expected behaviour

> need to print *** or the value which we read.

#### Actual behaviour
```
> #18 [build 10/17] RUN --mount=type=secret,id=github_token     cat /run/secrets/github_token
#18 0.422 cat: can't open '/run/secrets/github_token': No such file or directory
#18 ERROR: process "/bin/sh -c cat /run/secrets/github_token" did not complete successfully: exit code: 1
------
 > [build 10/17] RUN --mount=type=secret,id=github_token     cat /run/secrets/github_token:
#18 0.422 cat: can't open '/run/secrets/github_token': No such file or directory
------
Dockerfile.prod:21
--------------------
  20 |     
  21 | >>> RUN --mount=type=secret,id=github_token \
  22 | >>>     cat /run/secrets/github_token
  23 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cat /run/secrets/github_token" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c cat /run/secrets/github_token" did not complete successfully: exit code: 1
```

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by Ganesh-Ponipireddy** [comment]
I'm able to get the data after some changes, but not able to get the value into the `id` field. How to read the values of multiple secret keys?
<img width="777" alt="image" src="https://user-images.githubusercontent.com/48117290/211496583-4080e8f2-659a-4d5b-8c35-f05cf77fbc18.png">

**Comment by crazy-max** [comment]
> read the values of multiple secret keys?

What do you mean? Can you show your complete workflow and also buildx command in the logs please?

**Comment by Ganesh-Ponipireddy** [comment]
```
name: Build image
      uses: docker/build-push-action@v3.2.0
      with:
        build-args: 
        secrets: |
            "github_token=${{ inputs.token }}"
            "uname=${{ github.actor }}"
```
```
RUN --mount=type=secret,id=github_token \
    cat /run/secrets/github_token

RUN echo ${id}
```
I want to consume the github_token and uname in my docker file.
I had tried below `RUN` cmds in my docker file no luck.
RUN echo ${id}
RUN echo ${github_token}

I wnat to pass the github_token and uname in nuget add source
```
RUN dotnet nuget add source "https://nuget.pkg.github.com/xxxx/index.json" -n "githubfeed" -u ${uname} -p ${github_token} --store-password-in-clear-text
```
 no value is getting printed...

**Comment by enpatrik** [comment]
@Ganesh-Ponipireddy not sure if it's the best solution - but you can use [progress=plain](https://docs.docker.com/engine/reference/commandline/buildx_build/#progress) to see echo output.
i.e.
```yaml
        with:
          build-args: |
            BUILDKIT_PROGRESS=plain
```
