### ISSUE TITLE
Action started to push manifest indexes instead of images for a single platform

### ISSUE THREAD

**Issue by bubenkoff** [docker/build-push-action#755]
#### Steps to reproduce this issue

1. Set up build and push action with a single platform (non-multiarch build) 

#### Expected behaviour

> Image is pushed to the repository as an image, not manifest index

#### Actual behaviour

> Image is pushed as a manifest index

**Comment by 0xF4D3C0D3** [comment]
I bumped this issue too

**Comment by 0xF4D3C0D3** [comment]
![image](https://user-images.githubusercontent.com/19762154/211725358-67d72ffd-9729-48a5-beb7-e208d831c5bc.png)

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/19762154/211725400-cf80f768-32d6-4e3e-90d5-5fd502214a8b.png">

the first one works fine though the second one pushes wrong manifest indexes. it seems that buildkit version is culprit?

**Comment by 0xF4D3C0D3** [comment]
I solved this by setting driver-opts in setup-buildx-action step

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders
          driver-opts: 'image=moby/buildkit:v0.10.5'
```

**Comment by jedevc** [comment]
See my comment [here](https://github.com/docker/buildx/issues/1507#issuecomment-1378487020):

> This is the new provenance feature, which is enabled by default - you can get the contents using `buildx imagetools`:
> 
> ```bash
> $ docker buildx imagetools inspect <your-image> --format '{{ json .Provenance }}'
> ```
> 
> To disable it on build, you can explicitly set `--provenance=false`. You can find out more in the docs [here](https://docs.docker.com/build/attestations/slsa-provenance/).

Is there an issue with the single platform being uploaded as an index instead of a manifest? Is there a specific tool you're using that's giving issues?

**Comment by martadinata666** [comment]
so in simple terms add `--provenance=false` to every `docker buildx build` in CI? 🤔

**Comment by jedevc** [comment]
@martadinata666 that's definitely a solution you can try :tada:

But yeah, not ideal - the idea for enabling provenance by default is to enable better introspection of built images, where they come from, how they were built, etc. We want to make it easier by default to understand where an image has come from, to make it easier to decide how and whether to trust random images on the internet. :crossed_fingers: 

Is there a reason that it matters whether buildkit outputs an index instead of an image here? I'm not able to think of a use case where this should matter, except maybe for the known bug with `docker manifest`: https://github.com/docker/buildx/issues/1509. Ideally, how the image is stored in the registry shouldn't be a detail that end-users need to be aware of - if you are, I'm interested in why!

In https://github.com/docker/buildx/issues/1509#issuecomment-1378538197, I give some workarounds for the `docker manifest` issue - using `imagetools` should be a drop-in replacement for `docker manifest` that properly handles OCI indexes. If that's not an acceptable workaround, is there a reason why, so we can work on that?

**Comment by Legomegger** [comment]
> I solved this by setting driver-opts in setup-buildx-action step
> 
> ```yaml
>       - name: Set up Docker Buildx
>         uses: docker/setup-buildx-action@v2
>         with:
>           version: latest
>           endpoint: builders
>           driver-opts: 'image=moby/buildkit:v0.10.5'
> ```

tried this and got
`ERROR: failed to initialize builder builder-416a51ae-43b3-43a2-b551-c9b764437ef9 (builder-416a51ae-43b3-43a2-b551-c9b764437ef90): error during connect: Get "http://builders:2375/v1.24/containers/buildx_buildkit_builder-416a51ae-43b3-43a2-b551-c9b764437ef90/json": dial tcp: lookup builders on 127.0.0.53:53: server misbehaving`

**Comment by bubenkoff** [comment]
@jedevc thanks a lot for solving this mystery!
so is there a away to set --provenance=false, do you have an example?
pinning driver-opts: 'image=moby/buildkit:v0.10.5' seem to be quite extreme as it's exact version and might break again later on?

**Comment by nanake** [comment]
> @jedevc thanks a lot for solving this mystery! so is there a away to set --provenance=false, do you have an example? pinning driver-opts: 'image=moby/buildkit:v0.10.5' seem to be quite extreme as it's exact version and might break again later on?

Not now, just wait for #746 to land to use `provenance: false`.

**Comment by bubenkoff** [comment]
@jedevc 
and on the reasons why this is important so that the previous behavior stays: building multiarch images using build is very slow due to virtualization, hence the need of parallel build using different arch runners that push separate images, then use ahttps://github.com/Noelware/docker-manifest-action to push the manifest index using those separate images. This way it's like 10x faster.

**Comment by martadinata666** [comment]
docker actions wise, i personally set to specific version right now.
```
  - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
```

**Comment by jedevc** [comment]
@bubenkoff yup, buildx actually can do parallel native builds without needing to do manual manifest manipulation - however, it's definitely not as well presented as it could be. We're tracking that here: https://github.com/docker/buildx/issues/1510. If there's something you think we should cover in relation to the topic, please do mention it in that thread :tada:

**Comment by Vaub** [comment]
> Is there a reason that it matters whether buildkit outputs an index instead of an image manifest here? I'm not able to think of a use case where this should matter, except maybe for the known bug with `docker manifest`: [docker/buildx#1509](https://github.com/docker/buildx/issues/1509). Ideally, how the image is stored in the registry shouldn't be a detail that end-users need to be aware of - if you are, I'm interested in why!

If it helps, it broke our Google Cloud Run deployments, they don't seem to support this new format under-the-hood (at least in our region it causes an `image X not found` error). There isn't a lot of documentation from how they manage images, but I feel it is related to this bug. In any case, we reverted to v0.9.1 for now.

**Comment by bekriebel** [comment]
> > Is there a reason that it matters whether buildkit outputs an index instead of an image manifest here? I'm not able to think of a use case where this should matter, except maybe for the known bug with `docker manifest`: [docker/buildx#1509](https://github.com/docker/buildx/issues/1509). Ideally, how the image is stored in the registry shouldn't be a detail that end-users need to be aware of - if you are, I'm interested in why!
> 
> If it helps, it broke our Google Cloud Run deployments, they don't seem to support this new format under-the-hood (at least in our region it causes an `image X not found` error). There isn't a lot of documentation from how they manage images, but I feel it is related to this bug. In any case, we reverted to v0.9.1 for now.

This also broke our Cloud Run deployments that are pulling from Artifact Registry. It manifests as Cloud Run saying "Image '<REDACTED>' not found". It is fixed by adding `provenance: false` to my `docker/build-push-action@v3` with values.

**Comment by jakeonfire** [comment]
with the update to v0.10.0 it started using manifest v1?!

from the Manifest output:
```
    "containerimage.descriptor": {
      "mediaType": "application/vnd.oci.image.index.v1+json",
      "digest": "sha256:3a1b902d20d975b7a38a36ccc8cbeba629599501fd2bbd6a0414678580a601c5",
      "size": 856
    },
```
and that causes issues later on (during `docker pull` which doesn't support v1).

**Comment by joestringer** [comment]
I've also hit issues with this, however setting `provenance: false` is not working for me (see https://github.com/cilium/cilium/pull/23206#issuecomment-1397777488). However, pinning the version does appear to work correctly, so I've hardcoded the v0.9.1 buildx version for now in order to mitigate this issue.

**Comment by jakeonfire** [comment]
@joestringer you're not the only one with that issue: https://github.com/docker/build-push-action/pull/746#issuecomment-1381226322

**Comment by mgmarino** [comment]
Just adding that this also broke deployments to AWS lambda, which currently *does not* support multi-architecture containers.  We were confronted with the following error:

```
Resource handler returned message: "The image manifest or layer media type for the source image xxxxxx.dkr.ecr.eu-west-1.amazonaws.com/lambda/container:vXXX is not supported
```

We noticed that the new builds (with buildx 0.10.0 instead of 0.9) added the following flags by default:

```
--provenance mode=min,inline-only=true,builder-id=https://github.com/org/repo/actions/runs/xxxxxx
```

We were able to solve this by setting `provenance: false`.

IMHO it was not ideal to have this breaking change introduced without e.g. a major version bump.  Going forward, should we expect breaking changes like this, i.e. should we rather pin to minor versions?  

Thanks!

**Comment by jedevc** [comment]
@Vaub @bekriebel @mgmarino I've done some investigation and opened a separate tracking issue for the GCR/Lambda failures: https://github.com/docker/buildx/issues/1533. This is related to those platforms lack of support for multi-platform images - I've also given some other temporary workarounds in that thread.

---

@jakeonfire the update to buildx causes the format of the output to upgrade from docker manifest v2 to oci v1. See the mediatypes:
- On Buildx v0.9 : `application/vnd.docker.distribution.manifest.v2+json`
- On Buildx v0.10: `application/vnd.oci.image.index.v1+json`

See https://github.com/opencontainers/image-spec for more info.

**Comment by jakeonfire** [comment]
@jedevc ah i didn't look closely enough, thanks. but do you know why `docker pull` would fail with the message
```
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'
```
? we are using Amazon ECR if that matters...

**Comment by bekriebel** [comment]
> @Vaub @bekriebel @mgmarino I've done some investigation and opened a separate tracking issue for the GCR/Lambda failures: [docker/buildx#1533](https://github.com/docker/buildx/issues/1533). This is related to those platforms lack of support for multi-platform images - I've also given some other temporary workarounds in that thread.

There's lack of support on the runners, but also a seeming lack of support on the container registries. In both Google Artifact Registry and GitHub Container registry, an image pushed without `provenance: false` is appearing as three separate images. One of them can be pulled properly if you point to it, but the one that gets tagged appears to be just a manifest entry and can't be pulled by the services. Personally, I'll just be keeping provenance disabled until this format is better supported by existing cloud infrastructures.

**Comment by devunt** [comment]
This also causing ArgoCD Image Updater to fails with Amazon ECR registry. It seems they're not supporting the new format.

**Comment by tianon** [comment]
That's an interesting one that seems like it's slightly different from the others reported here -- ECR (Public, at least, but Private should be similar since AFAIK they share the underlying registry implementation) _does_ support OCI images (and indexes) for sure: https://explore.ggcr.dev/?image=public.ecr.aws/debian/debian@sha256:f7ec091514b5fc3c6977030d2d0fd85cf0857ef3f89a791c091395c3d5614979&mt=application%2Fvnd.oci.image.index.v1%2Bjson&size=2560

However, historically their validation of pushed objects has been more strict than some other registries, so I wonder if the provenance objects themselves are what's getting rejected?  (Not sure how to get some more detailed debug logs from the push attempt to know for sure but perhaps a buildx/buildkit maintainer has some ideas :innocent:)

**Comment by sbe-arg** [comment]
#773 lock to v3.3.0 or sha and set the provenance false.

advice don't run as @v3 in critical workflows where breaking changes are introduced in minor bumps

**Comment by mmatl** [comment]
This broke all of our builds that were tagged as `@v3` -- these sorts of changes should _probably_ be major revisions, as they break many common workflows.

**Comment by jedevc** [comment]
Closing, this is a duplicate of several other issues, and should be resolved by https://github.com/docker/build-push-action/pull/781 to ensure that v3 does not enable provenance by default.

Upgrading to v4 will enable provenance by default.

**Comment by alexellis** [comment]
@jedevc it seems like this breaks our tutorial for building two native images and compiling them into a manifest.

https://actuated.dev/blog/how-to-run-multi-arch-builds-natively

We can tell users to set `provenance: false` when using the v4 action, but is there a way to use these new provenance-enabled manifests to create a multi-arch image / manifest as per the blog post?

Or is that no-longer going to be possible going forward if using provenance?

**Comment by jedevc** [comment]
@alexellis `docker manifest` unfortunately doesn't work with multi-platform indexes as inputs. In an above message, I link to a list of workarounds: https://github.com/docker/buildx/issues/1509#issuecomment-1378538197.

I'd personally recommend using `buildx imagetools` which supports OCI/docker media types, merging manifest lists, and all of that.

**Comment by mqasimsarfraz** [comment]
> I'd personally recommend using buildx imagetools which supports OCI/docker media types, merging manifest lists, and all of that.

@jedevc I have been [using](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/.github/workflows/inspektor-gadget.yml#L507) `buildx imagetools` to create a manifest lists with OCI media types but struggling to find a way to add [OCI annotations](https://github.com/opencontainers/image-spec/blob/main/image-index.md#image-index-property-descriptions) to make GitHub happy with descriptions and all ? I am wondering if that is something imagetool even supports (or should support)?

**Comment by seebeen** [comment]
> @jedevc it seems like this breaks our tutorial for building two native images and compiling them into a manifest.
> 
> https://actuated.dev/blog/how-to-run-multi-arch-builds-natively
> 
> We can tell users to set `provenance: false` when using the v4 action, but is there a way to use these new provenance-enabled manifests to create a multi-arch image / manifest as per the blog post?
> 
> Or is that no-longer going to be possible going forward if using provenance?

Did you get an answer?

**Comment by mqasimsarfraz** [comment]
> > @jedevc it seems like this breaks our tutorial for building two native images and compiling them into a manifest.
> > https://actuated.dev/blog/how-to-run-multi-arch-builds-natively
> > We can tell users to set `provenance: false` when using the v4 action, but is there a way to use these new provenance-enabled manifests to create a multi-arch image / manifest as per the blog post?
> > Or is that no-longer going to be possible going forward if using provenance?
> 
> Did you get an answer?

@seebeen As mentioned in the comment [here](https://github.com/docker/build-push-action/issues/755#issuecomment-1619781552) using `buildx imagetools` should do the trick. The complete steps are listed in ["Distribute build across multiple runners"](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners). More examples ([index pushing](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/.github/workflows/inspektor-gadget.yml#L441), [index merging](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/.github/workflows/inspektor-gadget.yml#L542))

**Comment by seebeen** [comment]
That doesnt work. No annotations get applied. It doesn't matter where you add them.
I've compiled a custom manifest file myself, using sha's from previous release, and I'm overwriting the manifest -> no show 😢

**Comment by mqasimsarfraz** [comment]
Can you please share the steps you are trying so I can get an idea? Also, in case of annotations if you want to add them to final index then you must use `buildx imagetools create --annotation ...`. The support for `--annotation` flag was recently merged so be sure to use update to date version:

```
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2
    with:
    # TODO: Remove once buildx v0.12.0 is released with https://github.com/docker/buildx/pull/1965
    version: https://github.com/docker/buildx.git#e5cee892ed4fa2e0af53c54c09131c96c68383ff
```

We are using them [here](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/.github/workflows/inspektor-gadget.yml#L542) and works fine.

**Comment by seebeen** [comment]
Here is the entire workflow file
```yaml
name: Docker builds
on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

env:
  REGISTRY_IMAGE: ghcr.io/oblakstudio/woosync
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  build:
    name: Build image
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            runner: amd64-builder
          - platform: linux/arm64
            runner: arm64-builder

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: oblakbot
          password: ${{ secrets.OBLAK_BOT_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Build Docker Image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: ./
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true,annotation.org.opencontainers.image.title=WooCommerce Sync Service v2,annotation.org.opencontainers.image.authors=Oblak Studio <support@oblak.studio>,annotation.org.opencontainers.image.source=https://github.com/oblakstudio/wcs,annotation.org.opencontainers.image.description=Docker Optimized WooSync v2,annotation.org.opencontainers.image.licenses=MIT
          provenance: false

      - name: Export Image Digest
        run: |
          mkdir -p /tmp/build-digest
          digest="${{ steps.build.outputs.digest }}"
          digest="${digest#sha256:}"
          touch "/tmp/build-digest/$digest"
        shell: bash

      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/build-digest/*
          if-no-files-found: error
          retention-days: 1

      - name: Clear temporary directory
        run: |
          rm -rf /tmp/build-digest/*
        shell: bash

  merge:
    name: Merge manifest
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: /tmp/build-digest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.source="https://github.com/oblakstudio/wcs"
            org.opencontainers.image.authors="Oblak Studio <support@oblak.studio>"
            org.opencontainers.image.title="WooCommerce Sync Service v2"
            org.opencontainers.image.description="Docker Optimized WooSync v2"
            org.opencontainers.image.licenses="MIT"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: oblakbot
          password: ${{ secrets.OBLAK_BOT_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/build-digest
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: my-artifact
          failOnError: false
          ```
