### ISSUE TITLE
Provide better definition of `no-cache-filters`

### ISSUE THREAD

**Issue by ReenigneArcher** [docker/build-push-action#757]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. Build many multiple images with cache enabled

#### Expected behaviour

> Tell us what should happen

Please provide more context or examples on how to use the `no-cache-filters`. Readme is not clear.

#### Actual behaviour

> Tell us what happens instead

Cache fills quickly and hits 10GB limit.
![image](https://user-images.githubusercontent.com/42013603/212233602-d429a49d-7fb8-4491-b8cc-01594d81acb0.png)

### Configuration

* Repository URL (if public): https://github.com/LizardByte/Sunshine
* Build URL (if public): https://github.com/LizardByte/Sunshine/actions/runs/3908197569

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
Let's say you have this Dockerfile:

```dockerfile
FROM alpine AS base
RUN apk add nano

FROM base as prod
RUN apk add vim

FROM prod as test
RUN apk add python3
```

Building with:

```yaml
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: user/app:latest
          no-cache-filters: test
```

`test` stage will not be cached.

> Cache fills quickly and hits 10GB limit.

Looking at your workflow: https://github.com/LizardByte/Sunshine/blob/0dfbcfdbc4a996fc6431387fd227525e7ec57684/.github/workflows/ci-docker.yml#L350-L351

```yaml
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
```

I would suggest to switch to `gha` cache exporter: https://docs.docker.com/build/ci/github-actions/cache/#github-cache

```yaml
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
```

Also the scope you're using is too wide and will filling up the cache very quickly: https://github.com/LizardByte/Sunshine/blob/0dfbcfdbc4a996fc6431387fd227525e7ec57684/.github/workflows/ci-docker.yml#L308-L314

```yaml
      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: Docker-buildx${{ matrix.tag }}-${{ github.sha }}
          restore-keys: |
            Docker-buildx${{ matrix.tag }}-
```

I think it should just scope to the Dockerfile you're using in your matrix. With `gha` exporter:

```yaml
          cache-from: type=gha,scope=${{ matrix.dockerfile }}
          cache-to: type=gha,scope=${{ matrix.dockerfile }},mode=max
```
