### ISSUE TITLE
Feature Request: build and push multiple images

### ISSUE THREAD

**Issue by Loudsi** [docker/build-push-action#76]
Could it be possible to specify multiple path to build and push multiple images in one go ?

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

About your issue, you can use this workflow to build multiple images:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image1
        uses: docker/build-push-action@v2
        with:
          context: ./image1
          file: ./image1/Dockerfile
          push: true
          tags: user/image1:latest
      -
        name: Build image2
        uses: docker/build-push-action@v2
        with:
          context: ./image2
          file: ./image2/Dockerfile
          push: true
          tags: user/image2:latest
```

Don't hesitate if you have any questions.
