### ISSUE TITLE
Github Actions cache does not work every time

### ISSUE THREAD

**Issue by orkenstein** [docker/build-push-action#763]
### Behaviour

Github Actions cache works unstable. I cannot find any pattern. Sometimes it works on every commit, sometimes builds from scratch every time. I use the following step setup:

```yaml
    - name: Build
      uses: docker/build-push-action@v3.3.0
      with:
        context: ${{inputs.BUILD_CONTEXT}}
        tags: gcr.io/${{inputs.PROJECT_ID}}/${{inputs.IMAGE_NAME}}:${{github.sha}}
        build-args: ${{inputs.BUILD_ARGS}}
        outputs: type=docker,dest=/tmp/myimage.tar
        cache-from: type=gha,scope=${{inputs.IMAGE_NAME}}
        cache-to: type=gha,mode=max,scope=${{inputs.IMAGE_NAME}}
```
`IMAGE_NAME` is basically the repo name. I want to share cache across all possible branches (taking in account GitHub cache limitations). So it's very confusing, that docker build starts from scratch almost every time.

#### Steps to reproduce this issue

1. Trigger action with anything not affecting Dockerfile
2. Watch build step
3. Get success rate around 5/10

#### Expected behaviour

Cache should be utilised every time

#### Actual behaviour

Cache works about 5/10 times

### Configuration

```yml
jobs:
  setup-build:
    name: Setup and Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Build
      uses: docker/build-push-action@v3.3.0
      with:
        context: ${{inputs.BUILD_CONTEXT}}
        tags: gcr.io/${{inputs.PROJECT_ID}}/${{inputs.IMAGE_NAME}}:${{github.sha}}
        build-args: ${{inputs.BUILD_ARGS}}
        outputs: type=docker,dest=/tmp/myimage.tar
        cache-from: type=gha,scope=${{inputs.IMAGE_NAME}}
        cache-to: type=gha,mode=max,scope=${{inputs.IMAGE_NAME}}
```

### Logs

Buildx command:
```
2023-01-17T12:45:17.0685645Z ##[endgroup]
2023-01-17T12:45:17.0770144Z [command]/usr/bin/docker buildx build --build-arg GITHUB_SHA=a543c69a903d86581d4071ba60b5f5b4c94fb940 --cache-from type=gha,scope=frontend --cache-to type=gha,mode=max,scope=frontend --iidfile /tmp/docker-build-push-c8hUCl/iidfile --output type=docker,dest=/tmp/myimage.tar --tag gcr.io/filmustage/frontend:a543c69a903d86581d4071ba60b5f5b4c94fb940 --metadata-file /tmp/docker-build-push-c8hUCl/metadata-file .
```
