### ISSUE TITLE
[Question] Specify Region for Pushing to Google Cloud Registry

### ISSUE THREAD

**Issue by Hyperclaw79** [docker/build-push-action#765]
First of all, this action works like a charm and really makes my life easy by abstracting away the nitty gritty details.
However, I'm unable to find a way to push to a specific region of GCR. By default, when we push to there, it defaults to a multi-region bucket. I want to avoid that and specify a region like us-central1-c which is where my GKE cluster is running.
How can I achieve this?

Here's my build step:
```yaml
 - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: |
            ghcr.io/hyperclaw79/pokegambler:${{ env.TAG }}
            gcr.io/pokegambler/pokegambler:${{ env.TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
```

If the multi-container push is a challenge as well, I can focus on GCR only.

*P.S. Please excuse me for not following the Issue format, as this is more of a question than a bug.*

**Comment by Hyperclaw79** [comment]
@crazy-max 

I am actually authenticating to GCP in the previous step, (it's an old version which I am planning to update)

```yml
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker
```

I am able to successfully push to the default bucket in GCR, so I'm not really sure if it's an auth issue...
