### ISSUE TITLE
Strange cache misshit when using `gha` cache.

### ISSUE THREAD

**Issue by maxisme** [docker/build-push-action#766]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. Setup an action like (see below)
2. Create a go Dockerfile like:
```
...

COPY src/go.mod ./
COPY src/go.sum ./
RUN go mod download


COPY src ./
RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -tags=static -o /cli && ls -al /cli
...
```
3. Run the action

#### Expected behaviour

The `RUN go mod download` cache should **not** be invalidated

#### Actual behaviour
When editing a file inside `src` `RUN go mod download` is invalidated. Well at least I think it is:
```
#20 [base 22/26] COPY src/go.sum ./
#20 CACHED
#30 [base 23/26] RUN go mod download
#30 sha256:fccecca06c0e928afeb80a372e92178cfe09778a2d41c53d690328cd9350920f 43.01kB / 43.01kB 0.1s done
#30 sha256:46e25f3fb1d9354adea3ee0ec11523a2d4bdb24c795548575f2a8a180f8ef285 2.53kB / 2.53kB 0.1s done
...
#30 DONE 24.2s
```

I am not quite sure what these sha256 lines actually mean (is it pulling from cache)?

However, when I do not edit a file inside `src` (e.g .github/...) all lines are marked as CACHED.

### Configuration

```yml
      - uses: docker/setup-buildx-action@v1
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha,scope=${{ matrix.ecr_repo }}
          cache-to: type=gha,mode=max,scope=${{ matrix.ecr_repo }}
          push: true
          tags: "${{ env.tags }}"
```

I have [cross posted on stackoverflow](https://stackoverflow.com/questions/75172887/github-actions-docker-cache-invalidation).
