### ISSUE TITLE
Creates 3 Google Container Registry images instead of the one

### ISSUE THREAD

**Issue by murphman300** [docker/build-push-action#767]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

On pretty out of the box setup, the action creates 3 GCR images, and applies a Created timestamp dating back to 1969.

#### Steps to reproduce this issue

The result on GCR was this:
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/21324779/213806079-3948c269-698f-4613-afe1-6a065b09353f.png">

Now the result is this:

<img width="995" alt="image" src="https://user-images.githubusercontent.com/21324779/213807089-b6b4d546-6c45-42ac-9ad4-57703a08340f.png">

#### Expected behaviour

The action deploys 1 image and tags that one as latest

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/21324779/213806079-3948c269-698f-4613-afe1-6a065b09353f.png">

#### Actual behaviour

The action deploys 3 images, instead of 1, the first one being uploaded being the right one

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/21324779/213809290-6e1bf267-7717-4887-aa70-536c3758cec9.png">

### Configuration

This file has had no commits this week and was working up until 24h ago
```yml
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./apps/<project-name>/Dockerfile
          push: true
          tags: |
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/<project-name>-ssr:${{ github.sha }}
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/<project-name>-ssr:latest
          build-args: |
            some args here..
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

Logs don't indicate anything job side - however, when i pull one of those images of 0 or ~1.4KB in size i get this error from docker:

`unsupported media type application/vnd.in-toto+json`
