### ISSUE TITLE
Image not found after push 

### ISSUE THREAD

**Issue by andreyluchianic** [docker/build-push-action#768]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour
Nothing was changed in configurations but now so weird files are creating in registry together with image itself
#### Steps to reproduce this issue

1. 
2.
3.

#### Expected behaviour

should pushes image with tag `latest`

#### Actual behaviour

pushes image together with 2 weird files with weird date and time 
<img width="1163" alt="Screenshot 2023-01-23 at 12 05 52" src="https://user-images.githubusercontent.com/88837148/214013942-0ba167c8-6290-45e3-b739-58acbd1fe312.png">

<img width="1158" alt="Screenshot 2023-01-23 at 12 04 03" src="https://user-images.githubusercontent.com/88837148/214013934-85537670-dd85-4b72-b37c-5f225c1fed33.png">
<img width="935" alt="Screenshot 2023-01-23 at 12 04 44" src="https://user-images.githubusercontent.com/88837148/214013939-73308861-2dc9-479b-bfea-4a3a78b126df.png">

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: ${{ matrix.os }}
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      env:
       TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
       TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      strategy:
        matrix:
          os: [ubuntu-latest]         # , macos-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: yarn
        - name: Install dependencies
          run: yarn install
    #  *****|*****|*****| Strapi |*****|*****|***** 
        - name: Verify Strapi changed
          id: strapi_changed
          uses: tj-actions/changed-files@v35
          with:
            files: |
              apps/strapi-v4/**
        
        - name: Login to GCR
          if: steps.strapi_changed.outputs.any_changed == 'true'
          uses: docker/login-action@v2
          with:
            registry: gcr.io
            username: _json_key
            password: ${{ secrets.GCR_JSON_KEY }}

        - name: Docker - Set up QEMU
          if: steps.strapi_changed.outputs.any_changed == 'true'
          uses: docker/setup-qemu-action@v2

        - name: Docker - Set up Buildx
          if: steps.strapi_changed.outputs.any_changed == 'true'
          uses: docker/setup-buildx-action@v2
 
        - name: Strapi Backend - Build and push
          if: steps.strapi_changed.outputs.any_changed == 'true'
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./apps/strapi-v4/Dockerfile
            push: true
```

### Logs
No error. CI/CD runs ok 
> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
