### ISSUE TITLE
Digest from `docker/build-push-action` doesn't match the `docker inspect` digest

### ISSUE THREAD

**Issue by ruzickap** [docker/build-push-action#770]
### Troubleshooting

It looks like digest generated by the `docker/build-push-action` doesn't match the `docker inspect` one.

#### Steps to reproduce this issue

I wrote a simple docker build pipeline which is using `docker/build-push-action` to build container image from Dockerfile and then using `docker push` to push it to registry.

My use case is to build container image first, then scan it by [trivy](https://trivy.dev/), [grype](https://github.com/anchore/grype) and then push it:

```yaml
name: docker-digest-test

on:
  workflow_dispatch:

jobs:
  container-build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: localhost:5000/name/app
          tags: type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build
        uses: docker/build-push-action@v3
        id: build-push-action-load
        with:
          file: Dockerfile
          context: src/app
          push: false       # I do not want to use push which is part of docker/build-push-action
          load: true
          tags: ${{ steps.docker_meta.outputs.tags }}

# Container scanning (trivy, grype)

      - name: Docker push
        run: |
          set -euxo pipefail
          docker push ${{ steps.docker_meta.outputs.tags }}

      - name: Test123
        run: |
          set -euxo pipefail
          echo "${{ steps.build-push-action-load.outputs.imageid }}"
          echo "${{ steps.build-push-action-load.outputs.digest }}"
          echo "***********************************************************"
          docker inspect ${{ steps.docker_meta.outputs.tags }} | jq '.[].RepoDigests'
          docker inspect ${{ steps.docker_meta.outputs.tags }}
```

What is surprising is that digest generated by `docker/build-push-action` doesn't match the one which I can get using `docker inspect`:

![image](https://user-images.githubusercontent.com/1434387/214032608-39df2f52-89fe-4640-b79f-04a83c8be630.png)

#### Expected behaviour

Digest of the container image should be "everywhere" the same.

#### Actual behaviour

The digest generate by `docker/build-push-action` doesn't match the one in `docker inspect`.

### Logs

Screenshot above or (https://github.com/ruzickap/action-test2/actions/runs/3985748207/jobs/6833500130#step:7:25):

```
#7 exporting to docker image format
#7 exporting layers 0.1s done
#7 exporting manifest sha256:8cedab3c2c83ab380b175796dd52a82c3b3fa1cd0e708202e236478aaa827915 done
#7 exporting config sha256:51c13268effeb8a9a7cf2f2751e92e4a59d44909056f6f[159](https://github.com/ruzickap/action-test2/actions/runs/3985748207/jobs/6833500130#step:6:163)ead178c78a499d0 done
#7 sending tarball
#7 ...

#8 importing to docker
#8 DONE 0.3s

#7 exporting to docker image format
#7 sending tarball 0.4s done
#7 DONE 0.5s
ImageID
  sha256:51c13268effeb8a9a7cf2f2751e92e4a59d44909056f6f159ead178c78a499d0
Digest
  sha256:8cedab3c2c83ab380b175796dd52a82c3b3fa1cd0e708202e236478aaa827915
Metadata

...
...
...

+ docker push localhost:5000/name/app:latest
The push refers to repository [localhost:5000/name/app]
29ee6a1728bc: Preparing
2f7048230bc7: Preparing
29ee6a1728bc: Pushed
2f7048230bc7: Pushed
latest: digest: sha256:97f47604ba63a1aa93[22](https://github.com/ruzickap/action-test2/actions/runs/3985748207/jobs/6833500130#step:7:23)41e72f1f2518849f870501b57d2f7660708ebb03e07f size: 739

...
...
...

 docker inspect localhost:5000/name/app:latest
[
  "localhost:5000/name/app@sha256:97f47604ba63a1aa932241e72f1f2518849f870501b57d2f7660708ebb03e07f"
]
+ docker inspect localhost:5000/name/app:latest
[
    {
        "Id": "sha256:51c13268effeb8a9a7cf2f2751e92e4a59d44909056f6f159ead178c78a499d0",
        "RepoTags": [
            "localhost:5000/name/app:latest"
        ],
        "RepoDigests": [
            "localhost:5000/name/app@sha256:97f47604ba63a1aa932241e72f1f2518849f870501b57d2f7660708ebb03e07f"
        ],
```

Probably - I am missing something here.

Thank you...
