### ISSUE TITLE
Docker push creates multiple images on GCR, some with creation timestamp equal to 0 epoch

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [docker/build-push-action#771]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1.

Build an image and push to local registry

```
      - name: build and push to local registry
        uses: docker/build-push-action@v3.3.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          no-cache: ${{ inputs.no_cache }}
          build-args: ${{ inputs.build_args }}
          push: true
          tags: ${{ env.LOCAL_IMAGE }}
          cache-to: type=inline
          provenance: false
```

2.

Use `buildx` to copy the image to a GCR registry

```
      - name: copy tagged image to sre gcr
        if: inputs.image_build == true
        shell: bash
        run: |
          docker buildx imagetools create \
            --tag "${{ steps.set-images.outputs.base }}:${{ inputs.image_tag }}" \
            ${{ env.LOCAL_IMAGE }}
```

#### Expected behaviour

> Tell us what should happen

One image should be created

#### Actual behaviour

Instead, I am seeing this weird behaviour

> Tell us what happens instead

![Screenshot 2023-01-23 at 9 05 51 PM](https://user-images.githubusercontent.com/50835081/214127447-b01418b1-d4f7-4762-9f2f-47ab1102d169.png)

### Configuration

My workflow uses the local registry service

```
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
```

FWIW

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by mountain-hiker** [comment]
I am also seeing 3 images built and pushed, expecting one

**Comment by tonistiigi** [comment]
It is the GCR web UI that is interpreting the OCI image incorrectly and showing it as 3 separate images. See https://github.com/docker/buildx/issues/1533 for details.

**Comment by pantelis-karamolegkos** [comment]
Despite the fact that I have `provenance: false` ?

**Comment by pantelis-karamolegkos** [comment]
Is there a way around it for the moment?

**Comment by mountain-hiker** [comment]
Per the link to this issue this worked for me:
```
name: Build and push
  uses: docker/build-push-action@v3
    with:
      push: true
      tags: [MY REGISTRY HERE]
      provenance: false
```

**Comment by tonistiigi** [comment]
@pantelis-karamolegkos Do you have logs to show for that build that uses `provenance: false` ?

**Comment by pantelis-karamolegkos** [comment]
Yes, here they are

```
Run docker/build-push-action@v3.3.0
  with:
    context: ./test_image_creation
    file: ./test_image_creation/Dockerfile
    no-cache: false
    push: true
    tags: localhost:5000/name/app:latest
    provenance: false
    load: false
    pull: false
    github-token: ***
```

**Comment by pantelis-karamolegkos** [comment]
@tonistiigi I assume I could switch to the `docker` format as well, but I am stumbling upon [this](https://github.com/docker/build-push-action/issues/772)

**Comment by tonistiigi** [comment]
@pantelis-karamolegkos The logs. https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs#downloading-logs 

The config in your other issue is not correct. You might be looking for `type=image,oci-mediatypes=false`

**Comment by jedevc** [comment]
@pantelis-karamolegkos could you share the *full* logs of your github ci run? If there's something confidential in there, then feel free to just include the buildx command invoked, and the final push part of the log: e.g.:

```
=> exporting to image                                                                                                                                                     4.1s
 => => exporting layers                                                                                                                                                    0.0s
 => => exporting manifest sha256:fcaad12161b2745bcca40e953e1e7a9cfb66b9b48c17cee2c079899eebd6fdb5                                                                          0.0s
 => => exporting config sha256:0ba2b9314db6130620130d7f7c6361d86a13573a4551a7c55a6aeda890424136                                                                            0.0s
 => => exporting attestation manifest sha256:4646f10822117652f073b326c6349e22d23f65de67c8f47a088d6e0d6984a353                                                              0.0s
 => => exporting manifest list sha256:98fffba4640144a71473fc4edd811b1d9d276f2654a98cbd420288c3a1fd2bd0                                                                     0.0s
 => => pushing layers                                                                                                                                                      2.8s
 => => pushing manifest for docker.io/test/test:latest@sha256:98fffba4640144a71473fc4edd811b1d9d276f2654a98cbd420288c3a1fd2bd0                         1.2s
```

**Comment by pantelis-karamolegkos** [comment]
My setup is the following

- build and push to local registry

```yaml
      - name: build and push to local registry
        uses: docker/build-push-action@v3.3.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          no-cache: ${{ inputs.no_cache }}
          build-args: ${{ inputs.build_args }}
          push: true
          tags: ${{ env.LOCAL_IMAGE }}
          builder: ${{ steps.setup-buildx.outputs.name }}
          provenance: false
```

copy image to gcr

```
      - name: copy tagged image to gcr
        if: inputs.image_build == true
        shell: bash
        run: |
          docker buildx imagetools create \
            --tag "${{ steps.set-images.outputs.sre_base }}:${{ inputs.image_tag }}" \
            ${{ env.LOCAL_IMAGE }}
```

![Screenshot 2023-01-24 at 5 57 43 PM](https://user-images.githubusercontent.com/50835081/214343117-2101a42e-e47c-442a-ab54-a61d9f8fe198.png)

![Screenshot 2023-01-24 at 5 58 06 PM](https://user-images.githubusercontent.com/50835081/214343231-c6e7b715-c051-415c-9323-9859c48353fe.png)

![Screenshot 2023-01-24 at 5 58 48 PM](https://user-images.githubusercontent.com/50835081/214343434-4f35dee0-9a9c-41b5-9d7f-09a8ec11153f.png)

**Comment by crazy-max** [comment]
@pantelis-karamolegkos Output of `Dcoker info` too please:

![image](https://user-images.githubusercontent.com/1951866/214344522-ee38730b-cfc5-4f95-be33-86f5e54d6c16.png)

**Comment by jedevc** [comment]
Provenance is disabled - there's no messages about it in the log output that would definitely appear if provenance was enabled.

Your logs indicate that you're pushing a single manifest - I'm not sure why you're seeing the weird result in GCR. Could one of them be the result of a previous run? Could you try with a different tag, to ensure they're separate?

If still the same, could you share the contents in the `Manifest` tab in GCR?

**Comment by pantelis-karamolegkos** [comment]
Let me delete both ghost images, use another tag and re-run the experiment. I will then share the manifest contents

**Comment by pantelis-karamolegkos** [comment]
btw I noticed (FWIF) that no matter the action version used, buildkit is **always**

```
moby/buildkit:buildx-stable-1 => buildkitd github.com/moby/buildkit v0.11.0 830288a71f447b46ad44ad5f7bd45148ec450d44
```

**Comment by jedevc** [comment]
> btw I noticed (FWIF) that no matter the action version used, buildkit is always

Yes. This is intentional. If you want to pin the buildkit version, you can use the `version` field of the action to pin the version.

**Comment by pantelis-karamolegkos** [comment]
Same result 

<img width="1046" alt="Screenshot 2023-01-24 at 6 10 59 PM" src="https://user-images.githubusercontent.com/50835081/214346330-23fa9ba5-66b9-4247-beeb-b2045def5617.png">

Manifest of the first image in the list (the one tagged `2.2.2`

```json
{
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "schemaVersion": 2,
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:29de78dbd7dfdb97af5ee4a0e840e91e9337a9e74ec45c00c8c4c53fd35ba3f5",
         "size": 696,
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```

Manifest of the 2nd image

```json
{
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "schemaVersion": 2,
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "digest": "sha256:f623c026bf51ce59c501d428786e33290f80477c63259cb114b8d8326035d67b",
      "size": 1082
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "digest": "sha256:8921db27df2831fa6eaa85321205a2470c669b855f3ec95d5a3c2b46de0442c9",
         "size": 3370628
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "digest": "sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1",
         "size": 32
      }
   ]
}
```

**Comment by pantelis-karamolegkos** [comment]
Here comes the coolest part...Whenever I delete these 2 images, a 3rd one appears (!!!)

<img width="1074" alt="Screenshot 2023-01-24 at 6 16 38 PM" src="https://user-images.githubusercontent.com/50835081/214347649-d4a4efce-432d-4a33-a276-b76c9610c9d5.png">


Manifest

```json
{
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "schemaVersion": 2,
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "digest": "sha256:f623c026bf51ce59c501d428786e33290f80477c63259cb114b8d8326035d67b",
      "size": 1082
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "digest": "sha256:8921db27df2831fa6eaa85321205a2470c669b855f3ec95d5a3c2b46de0442c9",
         "size": 3370628
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "digest": "sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1",
         "size": 32
      }
   ]
}
```

**Comment by pantelis-karamolegkos** [comment]
Everything started about a week ago.

**Comment by pantelis-karamolegkos** [comment]
@jedevc I tried to change the `buildkit` version by using another `buildx` version

```
      - name: set up docker buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          version: v0.9.1
          driver-opts: network=host
```

but still...

```
BuildKit version
builder-4fcd40b5-ef91-4e1d-9ab5-3c72b1b8a1490: moby/buildkit:buildx-stable-1 => buildkitd github.com/moby/buildkit v0.11.0 830288a71f447b46ad44ad5f7bd45148ec450d44
```

does this make sense?

**Comment by jedevc** [comment]
to pin the buildkit version you need:

```
      - name: set up docker buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          version: v0.9.1
          driver-opts: network=host,image=moby/buildkit:v0.10.6
```
