### ISSUE TITLE
ERROR: push and "local" output can't be used together

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [docker/build-push-action#772]
#### Steps to reproduce this issue

1.

Include the following step

```yaml
      - name: build and push to local registry
        uses: docker/build-push-action@v3.3.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          no-cache: ${{ inputs.no_cache }}
          build-args: ${{ inputs.build_args }}
          push: true
          tags: ${{ env.LOCAL_IMAGE }}
          provenance: false
          outputs: docker
```

where:

```
env:
  LOCAL_IMAGE: localhost:5000/name/app:latest
```

and I am using the `registry` service

```yaml
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

```
#### Expected behaviour

> Tell us what should happen

The image should have been build/pushed using the `docker` format (instead of the default, i.e. `oci`)

#### Actual behaviour

> Tell us what happens instead

```
--
buildx failed with: ERROR: push and "local" output can't be used together
```
I am not using the `local` output, why is this happening?
