### ISSUE TITLE
in v3.3.0 provenance should have been default false is a breaking change

### ISSUE THREAD

**Issue by sbe-arg** [docker/build-push-action#773]
if you are building multi images using manifest outside the build step it will break the digests with an unknown arch type hence you cannot amend and push multi arch manifests in a separated job.

**Comment by tonistiigi** [comment]
> it will break the digests with an unknown arch

What breaks? We only push valid OCI images.

> building multi images using manifest outside the build step

If you don't build multi-arch with `buildx build --platform` and need to combine images together later, then use `docker buildx imagetools create -t yourimage:combined yourimage-amd64 yourimage-arm64` . Add `--dry-run` if you want to test it before pushing.

**Comment by Naltharial** [comment]
For one example, it breaks AWS Lambda deployments, which can't parse multi-arch images.

`An error occurred (InvalidParameterValueException) when calling the UpdateFunctionCode operation: The image manifest or layer media type for the source image ***.dkr.ecr.***.amazonaws.com/**********:develop is not supported.`

We have to redo every single workflow that uses this action.

**Comment by tonistiigi** [comment]
https://github.com/docker/buildx/issues/1533

**Comment by sbe-arg** [comment]
When building in githun actions to push ghrc it pushes a the correct architecture lets say amd64 but also adds an uknown/uknown double architecture breaking the digest.

**Comment by tonistiigi** [comment]
> architecture breaking the digest.

Breaking what digest? It pushes a single multi-platform image to the tag that you specified.

**Comment by sbe-arg** [comment]
![image](https://user-images.githubusercontent.com/23391642/214709876-1aba2345-d3f5-4105-8d33-d23af6ace8ca.png)

breaks image if inspect a digest with unknown returns an error
```
      - name: Build and push Docker image [ARM]
        uses: docker/build-push-action@v3.3.0
        id: docker_build_arm
        with:
          provenance: true
          builder: ${{ steps.buildx_arm.outputs.name }}
          context: .
          file: dockerfiles/orbit.Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY_GITHUB_DOMAIN }}/kry10-nz/orbit:buildcache-arm
          cache-to: type=registry,ref=${{ env.REGISTRY_GITHUB_DOMAIN }}/kry10-nz/orbit:buildcache-arm,mode=max
```

with provenance false leads to the following successful build

![image](https://user-images.githubusercontent.com/23391642/214710663-34f8f4d6-d4cc-4f59-8db7-b645977e1a7f.png)
