### ISSUE TITLE
Multiple images getting uploaded with newer buildx version 0.10.0

### ISSUE THREAD

**Issue by cakoose** [docker/build-push-action#774]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

We're using build-push-action to upload to the GCP Artifact Registry. With buildx v0.9.1, a single image was uploaded with media type: "application/vnd.docker.distribution.manifest.v2+json"

With buildx v0.10.0, three images are uploaded with media types:
- "application/vnd.oci.image.index.v1+json"
- "application/vnd.oci.image.manifest.v1+json"
- "application/vnd.oci.image.manifest.v1+json"

I'm not sure if this is the expected behavior with buildx v0.10.0 or if maybe build-push-action is uploading too many things? I thought I'd check here first before going to the buildx project.

#### Steps to reproduce this issue

```yaml
- uses: docker/setup-buildx-action@v2.2.1
  with:
    version: v0.10.0

- uses: google-github-actions/setup-gcloud@v0.6.2

- run: gcloud auth configure-docker us-central1-docker.pkg.dev

- name: Build container image
  id: container-build
  uses: docker/build-push-action@v3.2.0
  with:
    build-args: 'NODE_VERSION=${{steps.versions.outputs.node}}'
    cache-from: type=gha
    cache-to: type=gha,mode=max
    context: .
    push: true
    tags: ${{ steps.tags.outputs.tags }}
```

#### Expected behaviour

See above.

#### Actual behaviour

See above.

### Configuration

See above.

### Logs

[0.9.1.log](https://github.com/docker/build-push-action/files/10486514/0.9.1.log)
[0.10.0.log](https://github.com/docker/build-push-action/files/10486515/0.10.0.log)
