### ISSUE TITLE
Unable to set buildx version in builder input

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [docker/build-push-action#776]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

According to the [docs](https://github.com/docker/setup-buildx-action#inputs) for the `builder` input:

![Screenshot 2023-01-24 at 12 27 44 PM](https://user-images.githubusercontent.com/50835081/214268289-176f0bd2-412c-4d6b-9727-990bd9d1fc7b.png)

However when setting a valid `buildx` [release](https://github.com/docker/buildx/releases) there:

```yaml
      - name: build and push to local registry
        uses: docker/build-push-action@v3.3.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          no-cache: ${{ inputs.no_cache }}
          build-args: ${{ inputs.build_args }}
          push: true
          tags: ${{ env.LOCAL_IMAGE }}
          builder: v0.9.1
          outputs: type=image,oci-mediatypes=false
```

> Error: ERROR: no builder "v0.9.1" found

I have also tried with plain ` builder: 0.9.1`, doesn't work either.

This step doesn't seem to have an issue however

```yaml
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          version: v0.9.1
          driver-opts: network=host
```

**Comment by crazy-max** [comment]
`builder` is not the buildx version but the builder instance (or builder name) like:

```yaml
name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: mybuilder
      -
        name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.mybuilder.outputs.name }}
          context: .
```

Typical usage of this input is for isolated builders: https://docs.docker.com/build/ci/github-actions/configure-builder/#isolated-builders

See also https://docs.docker.com/engine/reference/commandline/buildx/#options
