### ISSUE TITLE
Two empty or almost empty images pushed to the registry besides the actual image which is missing its tag

### ISSUE THREAD

**Issue by m3h0w** [docker/build-push-action#777]
#### Steps to reproduce this issue

I don't know how to reproduce the issue.

#### Expected behaviour

1 large image should be pushed to the registry with the appropriate tag.

#### Actual behaviour

The expected large image is pushed but without a tag and 2 other empty or almost empty "shadow" images are pushed with a created date of 1 Jan 1970 from which 1 has the tag that the large image was supposed to have.

![image](https://user-images.githubusercontent.com/25684390/214301173-29fa802b-8a99-46fd-9518-09393b971160.png)

### Configuration

```yml
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                install: true

            - name: Build base image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: false
                cache-from: |
                  type=gha,scope=base
                cache-to: |
                  type=gha,scope=base,mode=max
                target: base

            - name: Build production image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                load: false
                tags: eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
                cache-from: |
                  type=gha,scope=production
                  type=gha,scope=base
                cache-to: |
                  type=gha,scope=production,mode=max
                target: production
```

### Logs

[8_Build production image.txt](https://github.com/docker/build-push-action/files/10490002/8_Build.production.image.txt)
