### ISSUE TITLE
Breaking change included in subversion release

### ISSUE THREAD

**Issue by zymotik** [docker/build-push-action#778]
Many thanks for your action, we appreciate your hard work. However:

### Behaviour

[v3.3](https://github.com/docker/build-push-action/releases/tag/v3.3.0) included a warning message `This may introduce issues with registry and runtime support (e.g. GCR and Lambda)`. May I suggest that in future, known breaking changes are left for major version changes. It would have saved some headache troubleshooting why we were getting `Image 'eu.gcr.io/{project-id}/image-name' not found` errors in our Cloud Run deployments.

#### Expected behaviour

Action conforms to [Semantic Versioning](https://semver.org/)

#### Actual behaviour

Minor version release impacted publish to [GCR](https://cloud.google.com/container-registry)

### Configuration

```yml
      - name: Build and Push to the Google Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: ${{ github.actor == 'dependabot[bot]' && 'false' || 'true' }}
          tags: ${{ env.image_tags }}
 ```

### Fix

```yml
      - name: Build and Push to the Google Container Registry
        uses: docker/build-push-action@v3
        with:
          ...
          provenance: false
 ```
