### ISSUE TITLE
Warning: The `save-state` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by spkane** [docker/build-push-action#779]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. use the GitHub action (likely for anything at all)

#### Expected behaviour

There should be no warnings under normal circumstances.

#### Actual behaviour

I get this warning in the output:

```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

<img width="801" alt="CleanShot 2023-01-24 at 13 33 03@2x" src="https://user-images.githubusercontent.com/129629/214425417-5094a5b4-9335-4200-b43c-5387b3bfe5c6.png">

### Configuration

* Repository URL (if public):  **private**
* Build URL (if public):  **private**

```yml
name: Build Container Image

on:
  push:
    branches:
      - 'main'

jobs:
  buildx:
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./_containers/runner/
          file: ./_containers/runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: me/runner:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```

### Logs

N/A
