### ISSUE TITLE
Fail to push image to registry

### ISSUE THREAD

**Issue by can019** [docker/build-push-action#780]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. `2023.01.16` was the last success and had not failed before.
2. Nothing was changed in my `action.yml` but suddenly started to fail after `2022.01.21`
3. Pushing images to registry by manual cli has been successed

#### Expected behaviour

> Success to push images to registry

#### Actual behaviour

> Success to build image but failed to push images to registry

### Configuration

* Repository URL (if public): private
* Build URL (if public): private

**Not work after 2023.01.21**
```yml
   - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.***
          username: ${{ secrets.HARBOR_USER_NAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
        
      - name: Build image
        run: docker build --tag registry.***/***/node:latest --target production .

      - name: Push image to harbor
        run: docker push registry.***/***/node:latest
```

**This yml success**
```yml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.***
          username: ${{ secrets.HARBOR_USER_NAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
        
      - name: Build image manualy
        run: docker build --tag registry.***/***/node:latest --target production .

      - name: Check docker image
        run: docker image ls
      
      - name: Push to harbor manualy
        run: docker push registry.***/***/node:latest
``` 
### Logs
<img width="1023" alt="스크린샷 2023-01-27 오후 4 49 42" src="https://user-images.githubusercontent.com/26926966/215036603-228634d2-a51f-4081-8cf1-abe02fbd2dd3.png">

```shell
buildx failed with: ERROR: failed to solve: failed to push registry.***/***/node:latest: failed commit on ref
 "manifest-sha256:3dd1ff***": unexpected status: 500 Internal Server Error
```

**Comment by jedevc** [comment]
Do you have harbor-side logs? The 500 error indicates this is a registry issue - something there is likely failing.

I imagine this is the newest release of buildx/buildkit - you can try disable provenance attestations, with `provenance: false` to see if that helps to resolve your issue.

**Comment by crazy-max** [comment]
Also what kind of registry is this?

**Comment by jedevc** [comment]
@crazy-max I assume harbor:

```
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.***
          username: ${{ secrets.HARBOR_USER_NAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
```

**Comment by koljamaier** [comment]
same issue, also fixed via `provenance: false`. Thx for the support!

**Comment by can019** [comment]
> Do you have harbor-side logs? The 500 error indicates this is a registry issue - something there is likely failing.
> 
> I imagine this is the newest release of buildx/buildkit - you can try disable provenance attestations, with `provenance: false` to see if that helps to resolve your issue.

```shell
Jan 21 11:39:28 ip-172-19-0-1.ap-northeast-2.compute.internal core[3877]: 
2023-01-21T11:39:28Z [WARNING] [/core/middlewares/sizequota/handler.go:48]: 
Error occurred when to handle request in size quota handler: unsupported content type for manifest: application/vnd.oci.image.manifest.v1+json
```

**Comment by can019** [comment]
> Do you have harbor-side logs? The 500 error indicates this is a registry issue - something there is likely failing.
> 
> I imagine this is the newest release of buildx/buildkit - you can try disable provenance attestations, with `provenance: false` to see if that helps to resolve your issue.

@crazy-max 
@jedevc 
Fixed via `provenance:false` thanx

```shell
#23 exporting to image
[330](https://github.com/***/***/actions/runs/4042086994/jobs/6949372253#step:6:334)
#23 pushing layers 33.1s done
[331](https://github.com/***/***/actions/runs/4042086994/jobs/6949372253#step:6:335)
#23 pushing manifest for registry***/***/node:latest@sha256:5925***
[332](https://github.com/***/***/actions/runs/4042086994/jobs/6949372253#step:6:336)
#23 pushing manifest for registry***/***/node:latest@sha256:5925*** 0.7s done
[333](https://github.com/***/***/actions/runs/4042086994/jobs/6949372253#step:6:337)
#23 DONE 48.2s
```

I won't close the issue.

**Comment by jacek-jablonski** [comment]
Action v3.3.0 also broke my GCP Cloud Run jobs. GH Actions can successfully push docker image to Artifact Registry, but then Cloud Run is unable to load these images with error:
```yaml
  - type: Started
    status: 'False'
    reason: ContainerMissing
    message: Image 'europe-west4-docker.pkg.dev/xxx' not found.
```

Setting `provenance` to false fixed this problem.
