### ISSUE TITLE
error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.

### ISSUE THREAD

**Issue by bluekms** [docker/build-push-action#783]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. upgrade my project dotnet core 7.x
2.
3.

#### Expected behaviour

> upload success

#### Actual behaviour

> Error: #16 1.225 /usr/share/dotnet/sdk/6.0.405/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [MyProject's csproj]

### Configuration

* Repository URL (if public): https://github.com/bluekms/Playground
* Build URL (if public): https://hub.docker.com/repository/docker/bluekms/playground-auth-server/general

```yml
name: Deploy Auth Server

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      UseSpecificTag:
        type: boolean
        default: false
        description: latest와 특정 tag를 같이 업로드
    
jobs:
  docker:
    name: AuthServer
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Split Github Sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          
      - name: Build and tag:${{ steps.vars.outputs.sha_short }} push
        if: ${{ inputs.UseSpecificTag }}
        uses: docker/build-push-action@v3
        with:
          file: Servers/AuthServer/Dockerfile
          context: .
          push: true
          tags: bluekms/playground-auth-server:${{ steps.vars.outputs.sha_short }}
          
      - name: Build and tag:latest push
        uses: docker/build-push-action@v3
        with:
          file: Servers/AuthServer/Dockerfile
          context: .
          push: true
          tags: bluekms/playground-auth-server:latest
```

### Logs

[logs_255.zip](https://github.com/docker/build-push-action/files/10534155/logs_255.zip)
