### ISSUE TITLE
Quesion regarding default environment variables

### ISSUE THREAD

**Issue by aduzsardi** [docker/build-push-action#786]
Hi,
I just started using GH Actions i'm confused as to why the `GITHUB_RUN_NUMBER` is not working in this action withing a workflow
For example
```yaml
name: CI
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.3.0

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:$GITHUB_RUN_NUMBER
      # or
            ghcr.io/${{ github.repository }}:${ GITHUB_RUN_NUMBER }
      # or
            ghcr.io/${{ github.repository }}:${{ env.GITHUB_RUN_NUMBER }}
```
