### ISSUE TITLE
`4.0.0` + `--provenance false` fails with `ERROR: attestations are not supported by the current buildkitd`

### ISSUE THREAD

**Issue by polarathene** [docker/build-push-action#795]
### Behaviour

- Updated to `4.0.0` and explicitly opted out of `provenance`.
- A workflow with a matrix run has 3 out of 4 runners failing with the only difference seeming to be buildx version `0.10.0`, while the passing runner had buildx version `0.10.2`.

Presumably this is a transient issue with Github. I've re-run the failed jobs twice but they continue to use the older buildx version and failing:

```
Docker Engine: 20.10.22
Buildx: 0.10.0

/usr/bin/docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --iidfile /tmp/docker-build-push-AubJbU/iidfile --platform linux/amd64 --provenance false --tag mailserver-testing:ci --load --metadata-file /tmp/docker-build-push-AubJbU/metadata-file .

ERROR: attestations are not supported by the current buildkitd
Error: buildx failed with: ERROR: attestations are not supported by the current buildkitd
```

This is bizarre since we've clearly opted out of provenance with the CLI option from this action?

#### Steps to reproduce this issue

Probably not easy to reproduce, but [here is our affected workflow](https://github.com/docker-mailserver/docker-mailserver/blob/9e9f8026d9260db89da37b555b16975fb8cb2ae7/.github/workflows/generic_test.yml#L13-L51):

```yaml
jobs:
  run-tests:
    name: 'Test'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        part: [serial, parallel/set1, parallel/set2, parallel/set3]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Required to retrieve bats (core + extras):
          submodules: recursive

      # Get the cached build layers from the build job:
      # This should always be a cache-hit, thus `restore-keys` fallback is not used.
      # No new cache uploads should ever happen for this job.
      - name: 'Retrieve image built from build cache'
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: cache-buildx-${{ inputs.cache-key }}

      # Importing from the cache should create the image within approx 30 seconds:
      # Earlier `buildx` + `qemu` steps are not needed as no cache is exported,
      # and only a single platform (AMD64) is loaded:
      - name: 'Build AMD64 image from cache'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          tags: mailserver-testing:ci
          # Export the built image to the Docker host for use with BATS:
          load: true
          # Rebuilds the AMD64 image from the cache:
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          # Disable provenance attestation: https://docs.docker.com/build/attestations/slsa-provenance/
          provenance: false
```

In the past we have not needed the buildx action for this workflow (_a previous workflow it is dependent on provides a build and exports / uploads the image as a cache_). Both the passing workflow (buildx 0.10.2) and failing workflows (buildx 0.10.0) successfully import the same cache. Nothing else appears to be different in the action logs.

#### Expected behaviour

Workflow completes without error about missing attestations support.

#### Actual behaviour

Workflow fails, despite opting out of attestations with `provenance: false`.

### Configuration

- See "Steps to reproduce this issue" section above.
- Build URL / logs are linked to in the [affected PR](https://github.com/docker-mailserver/docker-mailserver/pull/3060#issuecomment-1421662676).

### Logs

[logs_8988.zip](https://github.com/docker/build-push-action/files/10680498/logs_8988.zip)
