### ISSUE TITLE
Running a build with empty build args builds and pushes an image with no name

### ISSUE THREAD

**Issue by br3ndonland** [docker/build-push-action#80]
## Description

I recently ran this action in a workflow, with my repo name nicely lowercased (docker/build-push-action#37), but had one of my build args configured incorrectly. Note the environment variable `BUILD_env=test`, which should have been `BUILD_ENV=test`. My Dockerfile has default build args set (like `ARG BUILD_ENV=development`), but the build arg here was probably overwriting that. My bad.

However, the action actually sets the image name to `[]`, kicks off a Docker build, completes the build, and attempts to push an image named `[]`.

Specific image name below replaced with `org/repo/image`.

```
Run docker/build-push-action@v1
  with:
    username: br3ndonland
    password: ***
    build_args: BUILD_ENV=
    registry: docker.pkg.github.com
    repository: org/repo/image
    tag_with_ref: false
    tag_with_sha: false
    path: .
    always_pull: false
    add_git_labels: false
    push: true
  env:
    DOCKER_REPO: org/repo
    BUILD_env: test

...

Logging in to registry docker.pkg.github.com

Login Succeeded
Building image []
Sending build context to Docker daemon  301.6kB

...

Removing intermediate container c6704dceaa3b
---> 2a565e64a9ba
Successfully built 2a565e64a9ba
Pushing image []
```

## Suggestions

- **The action should correctly read image names.**
- **If the action doesn't receive a name, it should stop and throw an error, rather than going through the entire build and push process.**

## Related

docker/build-push-action#37
docker/build-push-action#41

**Comment by mattwelke** [comment]
I'm having this issue too. I started from the Cloud Run example maintained by GCP (https://github.com/GoogleCloudPlatform/github-actions/tree/master/example-workflows/cloud-run). It worked perfectly, but I figured it was a waste to use my Cloud Build minutes to build the image, since GitHub Actions was just waiting for Cloud Build to build the image. I figured I'd swap out the Cloud Build part of that workflow for a generic "build and push" step that would push to GCR. That led me to this action.

My workflow step follows the style in the README in this repo:

```yaml
- name: Build and push Docker image to Google Container Registry
  uses: docker/build-push-action@v1.1.0
  with:
    username: _json_key
    password: ${{ secrets.RUN_SA_KEY }}
    registry: gcr.io
    repository: ${{ secrets.RUN_PROJECT }}/${{ env.SERVICE_NAME }}
    tags: ${{ env.GITHUB_SHA }}
```

(note that I added the "Cloud Storage Admin" role to the service account created when following the Cloud Run example README, so that my service account could be used to push the image to GCR too)

But, when it runs, it does the build but finishes with this in the logs:

```
Successfully built f8a13f5fd208
Pushing image []
```

And when I check GCR, I don't see a repository for the repository name I chose in this workflow.
