### ISSUE TITLE
why [permission_denied: write_package] after recreate a repo with same name

### ISSUE THREAD

**Issue by yxgms** [docker/build-push-action#806]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. create a repo, run action, push image to registry (ghcr.io)
2. delete repo, create a new one with same name same content
3. run action again, failed
    `buildx failed with: ERROR: denied: permission_denied: write_package` 

#### Expected behaviour

> after recreate repo, i can push image to registry

#### Actual behaviour

> i can't push image to registry

### Configuration

* Repository URL (if public): https://github.com/yxgms/helloworld
* Build URL (if public): https://github.com/yxgms/helloworld/actions/runs/4191987824

```yml
# paste your YAML workflow file here and remove sensitive data
name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{branch}}-{{date 'YYYYMMDD'}}-{{sha}}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### Logs
![image](https://user-images.githubusercontent.com/104618784/219309151-1c250d48-5e98-45a5-9dd0-7964f432ddc6.png)
> [logs_1.zip](https://github.com/docker/build-push-action/files/10753616/logs_1.zip) to this issue.
