### ISSUE TITLE
How to make buildx search locally for temporary images? 

### ISSUE THREAD

**Issue by daixtrose** [docker/build-push-action#807]
#### Steps to reproduce this issue

Consider [a Github Action that writes an image to a temporary file](https://github.com/daixtrose/how-to-use-docker-for-copperspice/blob/6236834616c4151875c260fe5c9c10881a6cbc10/.github/workflows/docker-build-images.yml#L51). 

```yaml
- 
        name: Build Debian base image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            VERSION=11
          context: .
          file: ./debian/Dockerfile 
          tags: 
            debian-base-11:latest
          outputs: type=docker,dest=/tmp/debian-base-11.tar
          load: true
```

The image [is available](https://github.com/daixtrose/how-to-use-docker-for-copperspice/actions/runs/4193919779/jobs/7271414128#step:10:1), since the commands

```yaml
-
        name: Load Debian image
        run: |
          docker load --input /tmp/debian-base-11.tar
          docker images -a
          docker inspect --format='{{.Os}}/{{.Architecture}}' debian-base-11:latest
```

yield 

```
Run docker load --input /tmp/debian-base-11.tar
  docker load --input /tmp/debian-base-11.tar
  docker images -a
  docker inspect --format='{{.Os}}/{{.Architecture}}' debian-base-11:latest
  shell: /usr/bin/bash -e {0}
Loaded image: debian-base-11:latest
REPOSITORY       TAG               IMAGE ID       CREATED          SIZE
debian-base-11   latest            3[2](https://github.com/daixtrose/how-to-use-docker-for-copperspice/actions/runs/4193919779/jobs/7271414128#step:10:2)799565bdaf   26 seconds ago   497MB
...
```

In a subsequent step I want to [use this image as base image for another build step](https://github.com/daixtrose/how-to-use-docker-for-copperspice/blob/6236834616c4151875c260fe5c9c10881a6cbc10/.github/workflows/docker-build-images.yml#L51).

```yaml
      -
        name: Add Git
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BASE_IMAGE=debian-base-11:latest
            VERSION=2.30.2
          file: ./git/Dockerfile 
          tags: debian-base-11-git-2.30.2:latest
          outputs: type=docker,dest=/tmp/debian-base-11-git-2.30.2.tar
          load: true
          pull: false
```

Despite the [hints in this issue](https://github.com/docker/buildx/issues/795#issuecomment-943593444) the `local/<image_name>` thing did not work for me, but maybe I just got that one wrong, too.

#### Expected behaviour

The build step should use the locally loaded image as base image.

#### Actual behaviour

The build step tries to login to `docker.io` to download `docker.io/library/debian-base-11:latest` which is locally available.

### Configuration

* Repository URL: https://github.com/daixtrose/how-to-use-docker-for-copperspice 
* Build URL: https://github.com/daixtrose/how-to-use-docker-for-copperspice/actions/runs/4193919779/jobs/7271414128#step:10:1

```yml
name: "Build Docker image cascade"

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-image_build
      - 
        name: Prepare binftms 
        run: |
          sudo apt-get install -y \
          qemu \
          binfmt-support \
          qemu-user-static 
      - 
        name: Add armhf architecture to multiarch configuration
        run: |
          sudo dpkg --add-architecture armhf 
          sudo update-binfmts --enable         
      - 
        name: Add aarch64 architecture to multiarch configuration
        run: |
          sudo dpkg --add-architecture aarch64 
          sudo update-binfmts --enable         
      - 
        name: Build Debian base image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            VERSION=11
          context: .
          file: ./debian/Dockerfile 
          tags: 
            debian-base-11:latest
          outputs: type=docker,dest=/tmp/debian-base-11.tar
          load: true
      -
        name: Load Debian image
        run: |
          docker load --input /tmp/debian-base-11.tar
          docker images -a
          docker inspect --format='{{.Os}}/{{.Architecture}}' debian-base-11:latest
      -
        name: Add Git
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BASE_IMAGE=debian-base-11:latest
            VERSION=2.30.2
          file: ./git/Dockerfile 
          tags: debian-base-11-git-2.30.2:latest
          outputs: type=docker,dest=/tmp/debian-base-11-git-2.30.2.tar
          load: true
          pull: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        [ ... cut off rest of file ...]
```

### Logs

[logs_60.zip](https://github.com/docker/build-push-action/files/10756261/logs_60.zip)

**Comment by daixtrose** [comment]
@crazy-max I probably misread the docs, but this still [does not work](https://github.com/daixtrose/how-to-use-docker-for-copperspice/actions/runs/4194534099/jobs/7272826529#step:10:130) for me. 

```yaml
- 
        name: Build Debian base image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          build-args: |
            VERSION=11
          file: ./debian/Dockerfile 
          tags: 
            debian-base-11:latest
      -
        name: Add Git
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BASE_IMAGE=debian-base-11:latest
            VERSION=2.30.2
          file: ./git/Dockerfile 
          context: .
          build-contexts: |
            debian-base-11:latest=docker-image://debian-base-11:latest
          tags: debian-base-11-git-2.30.2:latest
          load: true
```

**Comment by crazy-max** [comment]
@daixtrose Can you show your Dockerfile?

**Comment by daixtrose** [comment]
[Yes](https://github.com/daixtrose/how-to-use-docker-for-copperspice/actions/runs/4194534099/workflow)

**Comment by crazy-max** [comment]
> [Yes](https://github.com/daixtrose/how-to-use-docker-for-copperspice/actions/runs/4194534099/workflow)

Link looks to be your workflow, not the Dockerfile.

**Comment by daixtrose** [comment]
So sorry. Dockerfile is [here](https://github.com/daixtrose/how-to-use-docker-for-copperspice/blob/add-aarch64/git/Dockerfile).

**Comment by daixtrose** [comment]
Note that I also tried `local_debian` to avoid the parser running the wrong way.

```yaml
      -
        name: Add Git
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BASE_IMAGE=local_debian
            VERSION=2.30.2
          file: ./git/Dockerfile 
          context: .
          build-contexts: |
            local_debian=docker-image://debian-base-11:latest
          tags: debian-base-11-git-2.30.2:latest
          load: true
```
