### ISSUE TITLE
Local file is not copied into container 

### ISSUE THREAD

**Issue by Ludea** [docker/build-push-action#810]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. create a simple txt file 
2. Create a dockerfile with COPY . . 
3.RUN ls command to check if local file is copied

#### Expected behaviour
> Tell us what should happen

Local file move from host to container  

#### Actual behaviour
> Tell us what happens instead

Local file is not copies from local filesystem  

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v3
    - run: echo foo >> bar.txt
    - run: touch foo.txt
    - run: ls -l
    - name: Build container 
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: foo:latest
        platforms: linux/amd64
```
 
Dockerfile:        
```yml
FROM debian:bullseye-slim

WORKDIR /opt/foo
COPY . . 
RUN ls

CMD ["/bin/bash"] 
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
