### ISSUE TITLE
Lack of documentation about pushing to github packages

### ISSUE THREAD

**Issue by mercuriete** [docker/build-push-action#82]
in this doc: https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages#authenticating-to-github-packages

I can infer that the password is ```password: ${{ secrets.GITHUB_TOKEN }}```
but I dont know what is the username.

Can you put in the README.md an example of usage to push to github packages?
thanks

**Comment by mercuriete** [comment]
Sorry already there is a PR #14 

you can close this when that PR is merged.

**Comment by crazy-max** [comment]
@mercuriete This will be available through [build-push-action v2](https://github.com/docker/build-push-action/tree/v2-build-push) (#92). You can already try it with the [login-action](https://github.com/docker/login-action). See also #99

**Comment by mercuriete** [comment]
I already did it with this snippet:

```yaml
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: AAAAAA/BBBBB/CCCCC
          tags: ${{ steps.vars.outputs.short_ref }}
```

the problem is the lack of documentation.
