### ISSUE TITLE
GitHub Action produces unknown architecture and OS

### ISSUE THREAD

**Issue by mu88** [docker/build-push-action#820]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. Run [this GitHub Action](https://github.com/mu88/ThisIsYourLife/blob/main/.github/workflows/Release.yml)
2. Pull the created Docker image onto a Raspberry Pi via `docker pull mu88/thisisyourlife:latest`

#### Expected behaviour

The image can be pulled.

#### Actual behaviour

```
latest: Pulling from mu88/shopandeat
no matching manifest for linux/arm64/v8 in the manifest list entries
```

When running `hub-tool tag ls mu88/thisisyourlife --format json` on my Win11 machine, it shows this:
```json
[
  {
    "Name": "mu88/thisisyourlife:latest",
    "FullSize": 102816471,
    "LastUpdated": "2023-02-12T09:48:05.871245Z",
    "LastUpdaterUserName": "mu88",
    "Images": [
      {
        "Digest": "sha256:a372572eb3b089293ff8334f4f9d70e6dd6900f48314c372d86a83f4ba9f0c5f",
        "Architecture": "arm64",
        "Os": "linux",
        "Variant": "v8",
        "Size": 102816471,
        "LastPulled": "2023-02-12T09:48:06.485083Z",
        "LastPushed": "2023-02-12T09:48:05.470786Z",
        "Status": "active"
      },
      {
        "Digest": "sha256:85ebb19d1ec6022c5d0999c80dd58d847497a4afc35bcecacf854f91e7226560",
        "Architecture": "unknown",
        "Os": "unknown",
        "Variant": "",
        "Size": 19940,
        "LastPulled": "2023-02-12T09:48:06.520255Z",
        "LastPushed": "2023-02-12T09:48:05.636699Z",
        "Status": "active"
      }
    ],
    "LastPulled": "2023-02-12T09:49:00.217342Z",
    "LastPushed": "2023-02-12T09:48:05.871245Z",
    "Status": "active"
  },
  {
    "Name": "mu88/thisisyourlife:2.2",
    "FullSize": 102816471,
    "LastUpdated": "2023-02-12T09:48:06.748996Z",
    "LastUpdaterUserName": "mu88",
    "Images": [
      {
        "Digest": "sha256:a372572eb3b089293ff8334f4f9d70e6dd6900f48314c372d86a83f4ba9f0c5f",
        "Architecture": "arm64",
        "Os": "linux",
        "Variant": "v8",
        "Size": 102816471,
        "LastPulled": "2023-02-12T09:48:06.485083Z",
        "LastPushed": "2023-02-12T09:48:05.470786Z",
        "Status": "active"
      },
      {
        "Digest": "sha256:85ebb19d1ec6022c5d0999c80dd58d847497a4afc35bcecacf854f91e7226560",
        "Architecture": "unknown",
        "Os": "unknown",
        "Variant": "",
        "Size": 19940,
        "LastPulled": "2023-02-12T09:48:06.520255Z",
        "LastPushed": "2023-02-12T09:48:05.636699Z",
        "Status": "active"
      }
    ],
    "LastPulled": "2023-02-12T09:49:00.217342Z",
    "LastPushed": "2023-02-12T09:48:06.748996Z",
    "Status": "active"
  },
...
```

I've already created [this issue](https://forums.docker.com/t/cannot-pull-latest-image-on-raspberry-pi-4/134188) in a Docker forum. I first had the problem with [this repo](https://github.com/mu88/ShopAndEat/) resp. the Docker image `mu88/shopandeat:latest`. Then I thought that I can resolve it by deleting all tags from the Docker Hub and building the image again, but now the problem is back for another repo and deleting the tags doesn't solve it.

Since I cannot reproduce this issue when running the GitHub Action locally (via [`act`](https://github.com/nektos/act)) or simply via `docker build`, I assume it's a problem of this GitHub Action step `docker/build-push-action@v4`.

### Configuration

* Repository URL (if public): https://github.com/mu88/ThisIsYourLife
* Build URL (if public): 

```yml
name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching everything, e. g. "v1" or "2021.2.2.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'
    - name: Restore dependencies
      run: dotnet restore ThisIsYourLife.sln
    - name: Build
      run: dotnet build --no-restore ThisIsYourLife.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ThisIsYourLife.sln
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image for Raspberry Pi
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          mu88/thisisyourlife:latest
          mu88/thisisyourlife:${{ github.ref_name }}
        file: src/WebApp/Dockerfile
    - name: Build single-file EXE
      run: dotnet publish src/WebApp/WebApp.csproj -r win-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
    - name: Create ZIP for release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: ThisIsYourLife.${{ github.ref_name }}.zip
        directory: 'src/WebApp/bin/Release/net7.0/win-x64/publish'
    - name: Create CHANGELOG
      id: changelog
      uses: Requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        tag: ${{ github.ref_name }}
        excludeTypes: build,docs,other,style,chore(deps)
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: src/WebApp/bin/Release/net7.0/win-x64/publish/ThisIsYourLife*.zip
        tag_name: ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.changes }}
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by jedevc** [comment]
What version of Docker is running on the raspberry pi? You can get this information from `docker info`. I think the version of Docker is probably quite an old version, and isn't able to pull OCI images - which is the default in the latest versions of buildx (which the build-push-action uses to build images).

The extra manifest is attached as part of the new `provenance` feature - see the release notes for v4.0.0 for more information: https://github.com/docker/build-push-action/releases/tag/v4.0.0

**Comment by mu88** [comment]
Here's the output of `dotnet info`:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.84-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.705GiB
 Name: <<name of my Raspi>>
 ID: IDOS:QQKL:UAX6:G6LD:FEEG:QVRA:HKCA:W5RD:3VOW:EV4N:XJJJ:O2E6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: mu88
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

Doesn't seem that old to me, doesn't it :)

**Comment by crazy-max** [comment]
Doesn't seem you're building for your platform in your workflow. Looks like you're missing the `platforms` input with `linux/arm64`:

```yaml
    - name: Build and push Docker image for Raspberry Pi
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          mu88/thisisyourlife:latest
          mu88/thisisyourlife:${{ github.ref_name }}
        file: src/WebApp/Dockerfile
```

More info: https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by mu88** [comment]
Specifying the `platforms` parameter results in further issues with building the .NET code ([see this issue](https://github.com/dotnet/aspnetcore/issues/46306)).

AFAIK specifying `mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim-arm64v8` as  base image ([see here](https://github.com/mu88/ThisIsYourLife/blob/main/src/WebApp/Dockerfile#L1)) should be sufficient - at least it has been working this way for years.

**Comment by mu88** [comment]
@crazy-max what would be the syntax for setting `--provenance=false` in my GitHub Action? Like this:
```yaml
    - name: Build and push Docker image for Raspberry Pi
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        provenance: false
        tags: |
          mu88/thisisyourlife:latest
          mu88/thisisyourlife:${{ github.ref_name }}
```
