### ISSUE TITLE
Test before push error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: read /tmp/buildkit-mount1790184381: is a directory

### ISSUE THREAD

**Issue by AdrianPaulCarrieres** [docker/build-push-action#824]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. See workflow/action .yml

#### Expected behaviour
I should be able to build the image in a first step, then test/scan it (if needed) and then push it in a 3rd step

#### Actual behaviour

The first step builds the action, the 2nd one scan it, but the 3rd fails

### Configuration

```yml
name: "Build the docker image, scan it and push it"
description:  build docker image, scan it and push it

inputs:
  # -- Run steps -- #
  run-scan:
    description: Run scan
    default: "true"
  # -- Docker image -- #
  image:
    description: "Name of the image"
    required: true
  version:
    description: "How to tag the image"
    required: true
  # -- SSH key -- #
  ssh-key:
    description: SSH key to use for the CI
    required: true
  # -- Docker registry -- #
  dockerhub-username:
    description: Docker Hub username
    required: true
  dockerhub-token:
    description: Docker Hub token
    required: true

runs:
  using: "composite"

  steps:
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-key }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
        tags: ${{ inputs.dockerhub-username }}/${{ inputs.image }}:${{ inputs.version }}
        context: .
        load: true # toggled it on and off to see but not results

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.dockerhub-username }}/${{ inputs.image }}:${{ inputs.version }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
      if: inputs.run-scan != 'false'

    - name: Push image
      uses: docker/build-push-action@v2
      with:
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
        tags: ${{ inputs.dockerhub-username }}/${{ inputs.image }}:${{ inputs.version }}
        push: true
```

### Logs

I had the scan step disabled so there is the first build and then the build + push

```
#32 [stage-1 6/6] COPY --from=builder --chown=nobody:root /app/_build/prod/rel/covid ./
#32 DONE 0.2s

#33 exporting to docker image format
#33 exporting layers
#33 exporting layers 1.2s done
#33 exporting manifest sha256:8de2cb1247b5f81e44306ee03fabc8d67c9963cee1423a3ce7b6d1e511d90e94 done
#33 exporting config sha256:928ce73fc2dac997d9a1cdca5a232e9ca5f6f55090c007ed59ae37c8246d05f9
#33 exporting config sha256:928ce73fc2dac997d9a1cdca5a232e9ca5f6f55090c007ed59ae37c8246d05f9 done
#33 sending tarball
#33 sending tarball 3.7s done
#33 DONE 4.9s

#34 importing to docker
#34 DONE 2.7s
ImageID
Digest
Metadata
Run docker/build-push-action@v4
GitHub Actions runtime token access controls
Docker info
Buildx version
/usr/bin/docker buildx build --file . --iidfile /tmp/docker-build-push-tn8stB/iidfile --provenance mode=min,inline-only=true,builder-id=https://github.com/myriad-sas/hub-covid/actions/runs/4302922167 --ssh default=/tmp/ssh-XXXXXXCu1zld/agent.1998 --tag ***/hub-covid:1.0 --metadata-file /tmp/docker-build-push-tn8stB/metadata-file --push .
#1 [internal] load .dockerignore
#1 transferring context: 1.36kB 0.0s done
#1 DONE 0.0s

#2 [internal] load build definition from .
#2 transferring dockerfile: 956.08kB 0.0s done
#2 DONE 0.1s
ERROR: failed to solve: failed to read dockerfile: read /tmp/buildkit-mount1790184381: is a directory
Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: read /tmp/buildkit-mount1790184381: is a directory
```
