### ISSUE TITLE
Is there a way to use env file?

### ISSUE THREAD

**Issue by Alejandroacho** [docker/build-push-action#827]
### Troubleshooting

Hi,

I would like to know if there is a way to use an env file such like this:

```
    - name: 🏗️ Create ENV file for master
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: echo "${{ secrets.PRODUCTION_ENV_FILE }}" > .env
    - name: 🏗️ Build and push dev
      if: ${{ github.ref == 'refs/heads/dev' }}
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Envs/Dev/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:dev-latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:${{ github.sha }}
        build-args: cat .env
```
