### ISSUE TITLE
Getting remote error: tls: handshake failure when I try to push the images to ghcr.io

### ISSUE THREAD

**Issue by thibaultserti** [docker/build-push-action#836]
#### Expected behaviour

Push should succed

#### Actual behaviour

I get a TLS handshake failure when I push.
It happens at a random time. Sometimes after on minute, and sometimes afeter 10 minutes

### Configuration

* Repository URL (if public): https://github.com/thibaultserti/bootstrap-golang
* Build URL (if public): https://github.com/thibaultserti/bootstrap-golang/actions/runs/4396883330/jobs/7699651608

```yml
- name: Log in to the Container registry
  uses: docker/login-action@v2
  with:
    registry: ${{ vars.REGISTRY }}
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}

- name: Build and push Docker image
  uses: docker/build-push-action@v4
  with:
    context: .
    push: true
    tags: gchr.io/${{ github.actor }}/${{ vars.NAME }}:v${{ inputs.release }}
    labels: ${{ steps.meta.outputs.labels }}
    platforms: ${{ inputs.platforms }}

```

### Logs

```
 #18 exporting to image
#18 exporting layers
#18 exporting layers 0.3s done
#18 exporting manifest sha256:02c2a450d75753cdc057562822f9e588450392db8fbb450f888efd1c0d029502 done
#18 exporting config sha256:6ccc997489a7f687fa3b57d9ef5d39ab4fbbbaad719f32f45b3506c6a2e57fe4 done
#18 exporting attestation manifest sha256:ffda9858c32cd68613b53dd9e45661b82faf77ddda08caba63f07dfa2eaa4578 done
#18 exporting manifest list sha256:37544c0cb93651c540bc7850d8bb8b20bf01f974ecba48963fda9026d51e1821 done
#18 pushing layers
#18 pushing layers 0.2s done
#18 ERROR: failed to push gchr.io/thibaultserti/hello:v1.1.8: failed to do request: Head "https://gchr.io/v2/thibaultserti/hello/blobs/sha256:8e197d40ce10b5ad7663fa52c6a27f8b26443cd7af2e8412afeaa6b7271b4f8d": remote error: tls: handshake failure
------
 > exporting to image:
------
ERROR: failed to solve: failed to push gchr.io/thibaultserti/hello:v1.1.8: failed to do request: Head "https://gchr.io/v2/thibaultserti/hello/blobs/sha256:8e197d40ce10b5ad7663fa52c6a27f8b26443cd7af2e8412afeaa6b7271b4f8d": remote error: tls: handshake failure
Error: buildx failed with: ERROR: failed to solve: failed to push gchr.io/thibaultserti/hello:v1.1.8: failed to do request: Head "https://gchr.io/v2/thibaultserti/hello/blobs/sha256:8e197d40ce10b5ad7663fa52c6a27f8b26443cd7af2e8412afeaa6b7271b4f8d": remote error: tls: handshake failure
```
