### ISSUE TITLE
Docker Push Publishes Empty Image (twice) and then a 255mb Image Index

### ISSUE THREAD

**Issue by jsrice7391** [docker/build-push-action#840]
# Introduction

I want to implement this step in my GitHub actions to build and push a Docker image using GHA caching and ECR as the repository. Is there anything fundamentally wrong with this approach to using caches?

I ask because the following configuration pushed two empty images and a 255 megabyte Index file:

```yaml
      # Github actions for docker build and push using cache:
      # https://github.com/docker/build-push-action
      - name: Build, tag, and push image to ECR
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: ./application_funnel
          builder: ${{ steps.buildx.outputs.nodes[0].name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.login-ecr.outputs.registry }}/upsmith:${{ github.sha }}
          target: prod
          push: true
```

## Expected Behavior

According to the documentation, I should get a Docker image that gets pushed to ECR, but when I go to check my ECR list, there are three artifacts pushed:

<img width="800" alt="Screenshot 2023-03-15 at 10 21 16 PM" src="https://user-images.githubusercontent.com/10286181/225495477-44aeeec7-79b8-4210-aba3-5d3f79845500.png">

## Question

Is there a better way to configure the step to push the image to ECR and tag? Should I not use the two different services and their caches.

**Comment by gilad-embryonics** [comment]
The same thing happens to me. We have a project which was successfully built and pushed a few months ago, and now after just a minor change in the internal python code, the results are similar to those described by @jsrice7391.

      - name: Build and push
        id: docker_build
        env:
          IMAGE_TAG_V: ${{ inputs.IMAGE_TAG }}_${{ github.run_number }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.LOCAL_PATH }}
          push: true
          tags: ${{ secrets.REPO_DOMAIN }}/${{ secrets.REPO_NAME }}:${{ env.IMAGE_TAG_V }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          
I tried disabling the cache, and updating the actions to their latest version, but the same thing happens.

**Comment by AmitNativ1984** [comment]
Any update on this? I suffer from the same issue

**Comment by INRIX-Iurii-Okhmat** [comment]
Same deal here:

![image](https://user-images.githubusercontent.com/2250038/227347961-9523afff-57af-41f3-aea2-65d47cceae66.png)

Action configuration:
```yaml
- name: Login to ECR
  uses: docker/login-action@v2
  with:
    registry: ${{ steps.ecr-login.outputs.registry }}

- name: Get Tags for Image
  id: metadata
  uses: docker/metadata-action@v4
  with:
    images: ${{ steps.ecr-login.outputs.registry }}/${{ vars.ECR_REPOSITORY_NAME }}
    tags: |
      type=raw,value=${{ steps.tag.outputs.image-tag }}

- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2
  with:
    buildkitd-flags: --debug

- name: Build and push
  uses: docker/build-push-action@v4
  with:
    context: .
    platforms: linux/amd64
    push: true
    tags: ${{ steps.metadata.outputs.tags }}
    labels: ${{ steps.metadata.outputs.labels }}
    cache-from: type=gha
    cache-to: type=gha,mode=max
```

There's nothing in the output logs that would suggest multiple images being pushed:
```text
#16 exporting to image
#16 pushing layers 1.1s done
#16 pushing manifest for ***.dkr.ecr.***.amazonaws.com/app:v1.6.0-210bc18@sha256:...
#16 pushing manifest for ***.dkr.ecr.***.amazonaws.com/app:v1.6.0-210bc18@sha256:... 1.0s done
#16 DONE 2.0s
```

Unrelated, but unexpected, none of them have [platform details](https://aws.amazon.com/blogs/containers/introducing-multi-architecture-container-images-for-amazon-ecr/):
```json
{
    "imageDetails": [
        {
            "registryId": "***",
            "repositoryName": "app",
            "imageDigest": "sha256:...",
            "imageSizeInBytes": 325874129,
            "imagePushedAt": "2023-03-23T13:29:50-07:00",
            "imageManifestMediaType": "application/vnd.oci.image.manifest.v1+json",
            "artifactMediaType": "application/vnd.oci.image.config.v1+json",
            "lastRecordedPullTime": "2023-03-23T13:30:15.904000-07:00"
        },
        {
            "registryId": "***",
            "repositoryName": "app",
            "imageDigest": "sha256:...",
            "imageTags": [
                "v1.6.0-210bc18"
            ],
            "imageSizeInBytes": 325874129,
            "imagePushedAt": "2023-03-23T13:29:50-07:00",
            "imageManifestMediaType": "application/vnd.oci.image.index.v1+json",
            "lastRecordedPullTime": "2023-03-23T13:30:15.741000-07:00"
        },
        {
            "registryId": "***",
            "repositoryName": "app",
            "imageDigest": "sha256:...",
            "imageSizeInBytes": 1425,
            "imagePushedAt": "2023-03-23T13:29:50-07:00",
            "imageManifestMediaType": "application/vnd.oci.image.manifest.v1+json",
            "artifactMediaType": "application/vnd.oci.image.config.v1+json"
        }
    ]
}
```

**Comment by INRIX-Iurii-Okhmat** [comment]
So, it seems like disabling provenance fixes this, at least in my usecase, YMMV

```yaml
- name: Build and push
  uses: docker/build-push-action@v4
  with:
    provenance: false
    ... other args
```
