### ISSUE TITLE
Action created image has different behavior/contents compared to locally created version

### ISSUE THREAD

**Issue by Amndeep7** [docker/build-push-action#844]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

Read the doc; the advice there is not applicable.

#### Steps to reproduce this issue

Run the workflow to generate images from (human) commits into master.

#### Expected behaviour

The generated image should contain a build of the product with all of its dependencies bundled properly.  Specifically, the bundled lodash dependency should function properly resulting in the application displaying its login modal properly when the application is spun up via `docker compose`.

<img width="429" alt="image" src="https://user-images.githubusercontent.com/2015821/226814420-8432ac08-cca4-46d9-9f42-6fb8d0f7dcf3.png">

#### Actual behaviour

The generated image does not contain a build of the product with all of its dependencies bundled properly.  When run via `docker compose`, the application does not work properly due to the lodash dependency not functioning properly.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/2015821/226815428-85ea8e0f-9793-4377-abaa-73e2dfb2eb90.png">

<img width="370" alt="image" src="https://user-images.githubusercontent.com/2015821/226815488-ce8c51cc-bdba-4fa5-98d5-a54fc494f6da.png">

<img width="412" alt="image" src="https://user-images.githubusercontent.com/2015821/226815619-5da1a64c-ff24-4eba-9007-2eef6fbabdf6.png">

### Configuration

The latest commit which had an image created: https://github.com/mitre/heimdall2/commit/2278a5b2d45eed8d22128a27108a2ef2697d0b40

The workflow run that created the image: https://github.com/mitre/heimdall2/actions/runs/4484860787

The dockerfile: https://github.com/mitre/heimdall2/blob/9b5771195539aa6f85f4c065cab993f6753db01f/Dockerfile

```yml
name: Push Heimdall Server to Docker Hub on every merge to master and tag as latest

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout the Heimdall Repository
        uses: actions/checkout@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: mitre/heimdall2:latest
```

### Logs

When comparing the generated images using [container-diff](https://github.com/GoogleContainerTools/container-diff), there are differences in size of the files in the 'dist' directory that I was not expecting.  The size differences could explain why certain packages, like lodash, are not being bundled properly.

```
$ container-diff diff daemon://heimdall2:local remote://mitre/heimdall2:latest --type=file --type=size --type=history --type=apt --type=node
-----Apt-----
Packages found only in heimdall2:local: None
Packages found only in mitre/heimdall2:latest: None
Version differences: None
-----File-----
These entries have been added to heimdall2:local:
FILE                                                       SIZE
/app/dist/frontend/js/app.866db2b2.js                      1.4M
/app/dist/frontend/js/app.866db2b2.js.map                  2.8M
/app/dist/frontend/js/chunk-vendors.1dfb3fb8.js            11.5M
/app/dist/frontend/js/chunk-vendors.1dfb3fb8.js.map        21.8M
These entries have been deleted from heimdall2:local:
FILE                                                       SIZE
/app/dist/frontend/js/app.b25d3868.js                      1.5M
/app/dist/frontend/js/app.b25d3868.js.map                  2.8M
/app/dist/frontend/js/chunk-vendors.026f912f.js            11.4M
/app/dist/frontend/js/chunk-vendors.026f912f.js.map        21.6M
These entries have been changed between heimdall2:local and mitre/heimdall2:latest:
FILE                                 SIZE1        SIZE2
/app/dist/frontend/index.html        1.3K         1.3K
-----History-----
Docker history lines found only in heimdall2:local: None
Docker history lines found only in mitre/heimdall2:latest: None
-----Node-----
Packages found only in heimdall2:local: None
Packages found only in mitre/heimdall2:latest: None
Version differences: None
-----Size-----
Image size difference between heimdall2:local and mitre/heimdall2:latest:
SIZE1         SIZE2
545.8M        545.8M
```

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

[logs_241510.zip](https://github.com/docker/build-push-action/files/11037021/logs_241510.zip)
