### ISSUE TITLE
Manifest unknown errors assumingly related to provenance

### ISSUE THREAD

**Issue by loshz** [docker/build-push-action#851]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

_Apologies in advance if this is a configuration error on my end._

When using the current `v4.0.0` version of this action, as well as buildx `v0.10.4`, I see the following error _after_ the action successfully builds and pushes to a private repo in Docker Hub:

```
Error: buildx failed with: ERROR: Error response from daemon: manifest unknown: manifest unknown
```

The exact same action using identical config and Dockerfile runs without error when the Docker Hub repo is public.

After reading through some of the buildx release notes, I noticed [this](https://github.com/docker/buildx/pull/1645) change related to attestation. So I downgraded to using buildx v0.10.3 and the above error is not thrown, with the action finishing successfully.

#### Steps to reproduce this issue

1. Create a private repo in Docker Hub.
2. Use the latest build-push-action v4.0.0 in a GitHub actions to build and push an image.

#### Expected behaviour

I expect there to be no error.

#### Actual behaviour

I see the above error, even though I can see the new image in Docker Hub.

### Configuration

* Repository URL (if public): N/A - private.
* Build URL (if public):  N/A - private.

Not working:
```yml
jobs:
  docker-build-push:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0

    - name: Login to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # pin@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # pin@v4.0.0
      with:
        push: true
        tags: my_org/my_repo:latest
```

Working:
```yml
jobs:
  docker-build-push:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # pin@v2.4.1
      with:
        version: v0.10.3 # specify buildx version < v0.10.4

    - name: Login to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # pin@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # pin@v4.0.0
      with:
        push: true
        tags: my_org/my_repo:latest
```

Also working:
```yml
jobs:
  docker-build-push:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # pin@v2.4.1

    - name: Login to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # pin@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # pin@v4.0.0
      with:
        provenance: false
        push: true
        tags: my_org/my_repo:latest
```
### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

N/A - private.
