### ISSUE TITLE
github actions push fails with error: denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by nfancy** [docker/build-push-action#853]
Hi, I have two dockerfile to push images to dockerhub. They are virtually the same .yml file except for the image name. However, one pushes successfully and the other one fails. I figured it is down to the docker.io path. For example, the failed one:

```
Run docker push nfancy/omix:1.0.0
The push refers to repository [docker.io/nfancy/omix]
```

and the successful one:

```
Run docker push ***/scflow:0.7.2
The push refers to repository [docker.io/***/scflow]
```

I think the first one fails due to the missing asterisk. Any pointer how to solve that in the gh action file. 

failed.yml
```
name: R GitHub Actions dev-nf

on:
  push:
    branches:
      - dev-nf

jobs:
  R-CMD-check:
    name: R-CMD-check
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RGL_USE_NULL: TRUE

    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: false

      - name: Get R package version
        run: |
          version=$(grep Version DESCRIPTION | grep -o "[0-9.]\+")
          echo "packageVersion=${version}" >> $GITHUB_ENV
        shell: bash {0}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          load: true
          file: ./Dockerfile
          tags: |
            nfancy/omix:${{ env.packageVersion }}
            nfancy/omix:latest
            nfancy/omix:dev
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push service
        run: |
          docker push nfancy/omix:${{ env.packageVersion }}
          docker push nfancy/omix:latest
          docker push nfancy/omix:dev
```

successful.yml
```
name: R GitHub Actions dev-nf

on:
  push:
    branches:
      - dev-nf

jobs:
  R-CMD-check:
    name: R-CMD-check
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RGL_USE_NULL: TRUE

    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: false

      - name: Get R package version
        run: |
          version=$(grep Version DESCRIPTION | grep -o "[0-9.]\+")
          echo "packageVersion=${version}" >> $GITHUB_ENV
        shell: bash {0}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          load: true
          file: ./Dockerfile
          tags: |
            nfancy/scflow:${{ env.packageVersion }}
            nfancy/scflow:latest
            nfancy/scflow:dev
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push service
        run: |
          docker push nfancy/scflow:${{ env.packageVersion }}
          docker push nfancy/scflow:latest
          docker push nfancy/scflow:dev
```
