### ISSUE TITLE
Push image that was downloaded from artifact

### ISSUE THREAD

**Issue by dorsegal** [docker/build-push-action#856]
Is there way to push an image that was download?
something like this

```
jobs:
   build:
     - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: false
     - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar

   push:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

      - name: Docker push
        uses: docker/build-push-action@v4
        tags: some-tags
        with:
          cache-from: /tmp
          push: true
```

**Comment by dorsegal** [comment]
> I'm not sure of your use case, that seems odd to build from a job and push from another one but anyway you can look at https://docs.docker.com/build/ci/github-actions/share-image-jobs/ and do smth like:
> 

I want to to be able to test my image in a different job and only if that job finished I want to finally push the image.
In this example https://docs.docker.com/build/ci/github-actions/test-before-push/ the workflow will be flat and does not allow you to run complex test (perhaps on different hosts)

I know I can do it with docker push but I will loose 
```
with:
    tags:
```
option and have to do it one by one

**Comment by crazy-max** [comment]
> I know I can do it with docker push but I will loose
> 
> ```
> with:
>     tags:
> ```
> 
> option and have to do it one by one

It should keep the tags when the image is loaded so if you have the first job with:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: |
            myimage:latest
            myimage:v1.0.0
          outputs: type=docker,dest=/tmp/myimage.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar
```

And in the second one pushing with:

```yaml
  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      -
        name: Load and push image
        run: |
          docker load --input /tmp/myimage.tar
          docker push myimage
```

It should push both tags.
