### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by spirit-team** [docker/build-push-action#857]
### Behaviour
Trying to use docker/build-push-action action inside a workflow and fails with an exit code 1

#### Steps to reproduce this issue

1. Manually dispatch workflow using default input values (workflow yml provided below)

#### Expected behaviour

Image gets built and pushed to the internal registry

#### Actual behaviour

I get the same error with all 3 of these actions provided by docker.
Actions:
 * docker/setup-qemu-action@v2
 * docker/setup-buildx-action@v2
 * docker/build-push-action@v4

I tried multiple versions for each of them and always get the same error. If I remove docker/setup-qemu-action from the yml, then docker/setup-buildx-action will fail with the same error and if I remove that, then docker/build-push-action will fail with that same error.

> Run docker/setup-qemu-action@v2
  with:
    image: tonistiigi/binfmt:latest
    platforms: all
  env:
    ARM_CLIENT_ID: ***
    ARM_CLIENT_SECRET: ***
    ARM_TENANT_ID: ***
    ACR_ENDPOINT: ***
Docker info
  /usr/bin/docker version
  Client: Docker Engine - Community
   Version:           20.[1](https://***/***/runs/340131?check_suite_focus=true#step:4:1)0.[2](https://***/***/runs/340131?check_suite_focus=true#step:4:2)1
   API version:       1.[4](https://***/***/runs/340131?check_suite_focus=true#step:4:4)1
   Go version:        go1.18.7
   Git commit:        baeda1f
   Built:             Tue Oct 2[5](https://***/***/runs/340131?check_suite_focus=true#step:4:5) 18:02:21 2022
   OS/Arch:           linux/amd[6](https://***/***/runs/340131?check_suite_focus=true#step:4:6)4
   Context:           default
   Experimental:      true
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: The process '/usr/bin/docker' failed with exit code 1

### Configuration

* Internal Repo 
* Internal Registry

```yml
name: AZ GH Runner Image

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Repository environment where secrets are stored.'
        type: string
        default: 'non-prod'
      RUNNER:
        description: 'The name of the Actions Runner that will be used to execute this Workflow'
        type: string
        default: 'Linux'
      IMAGE_NAME:
        description: 'Image name'
        type: string
        default: 'github-runner-test'
      IMAGE_TAG:
        description: 'Image Tag'
        type: string
        default: 'bidon'
    secrets:
      ARM_CLIENT_ID:
        description: 'Service Principal which will have permissions to manage resources in the specified Subscription.'
        required: true
      ARM_CLIENT_SECRET:
        description: 'Password (secret) of the Service Principal.'
        required: true
      ARM_TENANT_ID:
        description: 'Tenand ID where of the Service Principal.'
        required: true
      ACR_ENDPOINT:
        description: 'Azure Container Registry that will store the image'
        required: true

jobs:
  docker:
    runs-on: ${{ inputs.RUNNER }}
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ACR_ENDPOINT: ${{ secrets.ACR_ENDPOINT }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ARM_CLIENT_ID }}
          password: ${{ secrets.ARM_CLIENT_SECRET }}

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
```

### Logs

> 2023-04-13T20:07:07.9361692Z Requested labels: ***
2023-04-13T20:07:07.9361870Z Job defined at: ***/.github/workflows/build-push-runner-image.yml@refs/heads/main
2023-04-13T20:07:07.9361957Z Waiting for a runner to pick up this job...
2023-04-13T20:07:08.0861659Z Job is about to start running on the runner: *** (organization)
2023-04-13T20:07:11.2866633Z Current runner version: '2.299.0'
2023-04-13T20:07:11.2872839Z Runner name: '***'
2023-04-13T20:07:11.2873258Z Runner group name: 'Default'
2023-04-13T20:07:11.2873902Z Machine name: '***'
2023-04-13T20:07:11.2875583Z ##[group]GITHUB_TOKEN Permissions
2023-04-13T20:07:11.2876873Z Actions: write
2023-04-13T20:07:11.2877130Z Checks: write
2023-04-13T20:07:11.2877419Z Contents: write
2023-04-13T20:07:11.2877658Z Deployments: write
2023-04-13T20:07:11.2877930Z Discussions: write
2023-04-13T20:07:11.2878162Z Issues: write
2023-04-13T20:07:11.2878399Z Metadata: read
2023-04-13T20:07:11.2879130Z Packages: write
2023-04-13T20:07:11.2879423Z Pages: write
2023-04-13T20:07:11.2879674Z PullRequests: write
2023-04-13T20:07:11.2880239Z RepositoryProjects: write
2023-04-13T20:07:11.2880487Z SecurityEvents: write
2023-04-13T20:07:11.2880834Z Statuses: write
2023-04-13T20:07:11.2881115Z ##[endgroup]
2023-04-13T20:07:11.2884914Z Secret source: Actions
2023-04-13T20:07:11.2885475Z Prepare workflow directory
2023-04-13T20:07:11.4624283Z Prepare all required actions
2023-04-13T20:07:11.4850674Z Getting action download info
2023-04-13T20:07:12.0891628Z Download action repository 'actions/checkout@v3' (SHA:ac593985615ec2ede58e132d2e21d2b1cbd6127c)
2023-04-13T20:07:12.5203556Z Download action repository 'docker/setup-qemu-action@v2' (SHA:e81a89b1732b9c48d79cd809d8d81d79c4647a18)
2023-04-13T20:07:12.8090437Z Download action repository 'docker/setup-buildx-action@v2' (SHA:4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c)
2023-04-13T20:07:13.1575746Z Download action repository 'docker/login-action@v2' (SHA:f4ef78c080cd8ba55a85445d5b36e214a81df20a)
2023-04-13T20:07:13.5146467Z Download action repository 'docker/build-push-action@v4' (SHA:3b5e8027fcad23fda98b2e3ac259d8d67585f671)
2023-04-13T20:07:14.1227086Z A job started hook has been configured by the self-hosted runner administrator
2023-04-13T20:07:14.1396274Z ##[group]Run '/cleanup_script.sh'
2023-04-13T20:07:14.1409252Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2023-04-13T20:07:14.1410546Z ##[endgroup]
2023-04-13T20:07:14.1861249Z Cleaning up Workspace directory.
2023-04-13T20:07:14.1878008Z Cleaning up home directory.
2023-04-13T20:07:14.1886287Z Cleaning up event.json.
2023-04-13T20:07:14.1895452Z Post job cleanup complete.
2023-04-13T20:07:14.2655070Z ##[group]Run actions/checkout@v3
2023-04-13T20:07:14.2655551Z with:
2023-04-13T20:07:14.2656511Z   repository: ***
2023-04-13T20:07:14.2657357Z   token: ***
2023-04-13T20:07:14.2657690Z   ssh-strict: true
2023-04-13T20:07:14.2658033Z   persist-credentials: true
2023-04-13T20:07:14.2658367Z   clean: true
2023-04-13T20:07:14.2658658Z   fetch-depth: 1
2023-04-13T20:07:14.2658928Z   lfs: false
2023-04-13T20:07:14.2659245Z   submodules: false
2023-04-13T20:07:14.2659595Z   set-safe-directory: true
2023-04-13T20:07:14.2660219Z env:
2023-04-13T20:07:14.2660637Z   ARM_CLIENT_ID: ***
2023-04-13T20:07:14.2661037Z   ARM_CLIENT_SECRET: ***
2023-04-13T20:07:14.2662083Z   ARM_TENANT_ID: ***
2023-04-13T20:07:14.2662556Z   ACR_ENDPOINT: ***
2023-04-13T20:07:14.2662870Z ##[endgroup]
2023-04-13T20:07:14.5118216Z Syncing repository: ***
2023-04-13T20:07:14.5130760Z ##[group]Getting Git version info
2023-04-13T20:07:14.5131662Z Working directory is '/opt/github-runner/***'
2023-04-13T20:07:14.5132629Z [command]/usr/bin/git version
2023-04-13T20:07:14.5132975Z git version 2.39.0
2023-04-13T20:07:14.5134331Z ##[endgroup]
2023-04-13T20:07:14.5149012Z Temporarily overriding HOME='/opt/github-runner/_temp/1009a031-f24a-4388-8b82-dcc3a90b813d' before making global git config changes
2023-04-13T20:07:14.5149651Z Adding repository directory to the temporary git global config as a safe directory
2023-04-13T20:07:14.5150942Z [command]/usr/bin/git config --global --add safe.directory /opt/github-runner/***
2023-04-13T20:07:14.5186003Z Deleting the contents of '/opt/github-runner/***'
2023-04-13T20:07:14.5192508Z ##[group]Initializing the repository
2023-04-13T20:07:14.5198864Z [command]/usr/bin/git init /opt/github-runner/***
2023-04-13T20:07:14.5228440Z hint: Using 'master' as the name for the initial branch. This default branch name
2023-04-13T20:07:14.5233941Z hint: is subject to change. To configure the initial branch name to use in all
2023-04-13T20:07:14.5238475Z hint: of your new repositories, which will suppress this warning, call:
2023-04-13T20:07:14.5243104Z hint: 
2023-04-13T20:07:14.5246707Z hint: 	git config --global init.defaultBranch <name>
2023-04-13T20:07:14.5250374Z hint: 
2023-04-13T20:07:14.5254765Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2023-04-13T20:07:14.5259342Z hint: 'development'. The just-created branch can be renamed via this command:
2023-04-13T20:07:14.5263315Z hint: 
2023-04-13T20:07:14.5266927Z hint: 	git branch -m <name>
2023-04-13T20:07:14.5337565Z Initialized empty Git repository in /opt/github-runner/***/.git/
2023-04-13T20:07:14.5356331Z [command]/usr/bin/git remote add origin ***
2023-04-13T20:07:14.5431554Z ##[endgroup]
2023-04-13T20:07:14.5432252Z ##[group]Disabling automatic garbage collection
2023-04-13T20:07:14.5440451Z [command]/usr/bin/git config --local gc.auto 0
2023-04-13T20:07:14.5471631Z ##[endgroup]
2023-04-13T20:07:14.5472245Z ##[group]Setting up auth
2023-04-13T20:07:14.5472927Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-04-13T20:07:14.5501824Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-04-13T20:07:14.5712331Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/*\/\.extraheader
2023-04-13T20:07:14.5742090Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/***\/\.extraheader' && git config --local --unset-all 'http.https://***/.extraheader' || :"
2023-04-13T20:07:14.5902143Z [command]/usr/bin/git config --local http.https://***/.extraheader AUTHORIZATION: basic ***
2023-04-13T20:07:14.6001006Z ##[endgroup]
2023-04-13T20:07:14.6001706Z ##[group]Fetching the repository
2023-04-13T20:07:14.6006421Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +d2bf3e421db2d75ac56d03083932db6d50c4191d:refs/remotes/origin/main
2023-04-13T20:07:14.9482530Z remote: Enumerating objects: 20, done.        
2023-04-13T20:07:14.9629117Z remote: Counting objects:   5% (1/20)        
2023-04-13T20:07:14.9630042Z remote: Counting objects:  10% (2/20)        
2023-04-13T20:07:14.9630508Z remote: Counting objects:  15% (3/20)        
2023-04-13T20:07:14.9630853Z remote: Counting objects:  20% (4/20)        
2023-04-13T20:07:14.9631243Z remote: Counting objects:  25% (5/20)        
2023-04-13T20:07:14.9631608Z remote: Counting objects:  30% (6/20)        
2023-04-13T20:07:14.9631936Z remote: Counting objects:  35% (7/20)        
2023-04-13T20:07:14.9632304Z remote: Counting objects:  40% (8/20)        
2023-04-13T20:07:14.9632667Z remote: Counting objects:  45% (9/20)        
2023-04-13T20:07:14.9633004Z remote: Counting objects:  50% (10/20)        
2023-04-13T20:07:14.9633381Z remote: Counting objects:  55% (11/20)        
2023-04-13T20:07:14.9633748Z remote: Counting objects:  60% (12/20)        
2023-04-13T20:07:14.9634217Z remote: Counting objects:  65% (13/20)        
2023-04-13T20:07:14.9634610Z remote: Counting objects:  70% (14/20)        
2023-04-13T20:07:14.9634951Z remote: Counting objects:  75% (15/20)        
2023-04-13T20:07:14.9635683Z remote: Counting objects:  80% (16/20)        
2023-04-13T20:07:14.9637399Z remote: Counting objects:  85% (17/20)        
2023-04-13T20:07:14.9637807Z remote: Counting objects:  90% (18/20)        
2023-04-13T20:07:14.9638171Z remote: Counting objects:  95% (19/20)        
2023-04-13T20:07:14.9638558Z remote: Counting objects: 100% (20/20)        
2023-04-13T20:07:14.9638911Z remote: Counting objects: 100% (20/20), done.        
2023-04-13T20:07:14.9639296Z remote: Compressing objects:   5% (1/17)        
2023-04-13T20:07:14.9639699Z remote: Compressing objects:  11% (2/17)        
2023-04-13T20:07:14.9640312Z remote: Compressing objects:  17% (3/17)        
2023-04-13T20:07:14.9640685Z remote: Compressing objects:  23% (4/17)        
2023-04-13T20:07:14.9641133Z remote: Compressing objects:  29% (5/17)        
2023-04-13T20:07:14.9641484Z remote: Compressing objects:  35% (6/17)        
2023-04-13T20:07:14.9641857Z remote: Compressing objects:  41% (7/17)        
2023-04-13T20:07:14.9642619Z remote: Compressing objects:  47% (8/17)        
2023-04-13T20:07:14.9643260Z remote: Compressing objects:  52% (9/17)        
2023-04-13T20:07:14.9643905Z remote: Compressing objects:  58% (10/17)        
2023-04-13T20:07:14.9644313Z remote: Compressing objects:  64% (11/17)        
2023-04-13T20:07:14.9644658Z remote: Compressing objects:  70% (12/17)        
2023-04-13T20:07:14.9645035Z remote: Compressing objects:  76% (13/17)        
2023-04-13T20:07:14.9645372Z remote: Compressing objects:  82% (14/17)        
2023-04-13T20:07:14.9645747Z remote: Compressing objects:  88% (15/17)        
2023-04-13T20:07:14.9646122Z remote: Compressing objects:  94% (16/17)        
2023-04-13T20:07:14.9646459Z remote: Compressing objects: 100% (17/17)        
2023-04-13T20:07:14.9646869Z remote: Compressing objects: 100% (17/17), done.        
2023-04-13T20:07:14.9647609Z remote: Total 20 (delta 0), reused 16 (delta 0), pack-reused 0        
2023-04-13T20:07:14.9650777Z From https://***
2023-04-13T20:07:14.9651829Z  * [new ref]         d2bf3e421db2d75ac56d03083932db6d50c4191d -> origin/main
2023-04-13T20:07:14.9653156Z ##[endgroup]
2023-04-13T20:07:14.9653737Z ##[group]Determining the checkout info
2023-04-13T20:07:14.9654300Z ##[endgroup]
2023-04-13T20:07:14.9654805Z ##[group]Checking out the ref
2023-04-13T20:07:14.9655315Z [command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
2023-04-13T20:07:14.9655835Z Switched to a new branch 'main'
2023-04-13T20:07:14.9656617Z branch 'main' set up to track 'origin/main'.
2023-04-13T20:07:14.9658083Z ##[endgroup]
2023-04-13T20:07:14.9659651Z [command]/usr/bin/git log -1 --format='%H'
2023-04-13T20:07:14.9660394Z 'd2bf3e421db2d75ac56d03083932db6d50c4191d'
2023-04-13T20:07:14.9761187Z ##[group]Run docker/setup-qemu-action@v2
2023-04-13T20:07:14.9761574Z with:
2023-04-13T20:07:14.9761889Z   image: tonistiigi/binfmt:latest
2023-04-13T20:07:14.9762857Z   platforms: all
2023-04-13T20:07:14.9763184Z env:
2023-04-13T20:07:14.9763628Z   ARM_CLIENT_ID: ***
2023-04-13T20:07:14.9764090Z   ARM_CLIENT_SECRET: ***
2023-04-13T20:07:14.9764486Z   ARM_TENANT_ID: ***
2023-04-13T20:07:14.9764849Z   ACR_ENDPOINT: ***
2023-04-13T20:07:14.9765164Z ##[endgroup]
2023-04-13T20:07:15.0726828Z ##[group]Docker info
2023-04-13T20:07:15.0727218Z [command]/usr/bin/docker version
2023-04-13T20:07:15.0893813Z Client: Docker Engine - Community
2023-04-13T20:07:15.1004715Z  Version:           20.10.21
2023-04-13T20:07:15.1005658Z  API version:       1.41
2023-04-13T20:07:15.1006233Z  Go version:        go1.18.7
2023-04-13T20:07:15.1006765Z  Git commit:        baeda1f
2023-04-13T20:07:15.1007296Z  Built:             Tue Oct 25 18:02:21 2022
2023-04-13T20:07:15.1007825Z  OS/Arch:           linux/amd64
2023-04-13T20:07:15.1009578Z  Context:           default
2023-04-13T20:07:15.1010542Z  Experimental:      true
2023-04-13T20:07:15.1011171Z Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2023-04-13T20:07:15.1012106Z ##[endgroup]
2023-04-13T20:07:15.1046426Z ##[error]The process '/usr/bin/docker' failed with exit code 1
2023-04-13T20:07:15.1126261Z Post job cleanup.
2023-04-13T20:07:15.3122743Z [command]/usr/bin/git version
2023-04-13T20:07:15.4246011Z git version 2.39.0
2023-04-13T20:07:15.4254685Z Temporarily overriding HOME='/opt/github-runner/_temp/ae9bf649-541b-4e98-8cf4-27cff326ca8a' before making global git config changes
2023-04-13T20:07:15.4255327Z Adding repository directory to the temporary git global config as a safe directory
2023-04-13T20:07:15.4258691Z [command]/usr/bin/git config --global --add safe.directory /opt/github-runner/***
2023-04-13T20:07:15.4262111Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-04-13T20:07:15.4264838Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-04-13T20:07:15.4270065Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/***\/\.extraheader
2023-04-13T20:07:15.4270805Z http.https://***/.extraheader
2023-04-13T20:07:15.4273124Z [command]/usr/bin/git config --local --unset-all http.https://***/.extraheader
2023-04-13T20:07:15.4276244Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/***\/\.extraheader' && git config --local --unset-all 'http.https://***/.extraheader' || :"
2023-04-13T20:07:15.4597475Z Cleaning up orphan processes
