### ISSUE TITLE
400 error when exporting cache to DockerHub registry

### ISSUE THREAD

**Issue by Drew-Kimberly** [docker/build-push-action#858]
### Troubleshooting

This action started failing today (4/17/23 CST AM) when using the `cache-to` input to export build cache to a DockerHub registry.

### Behaviour

The action fails when using the `cache-to` input to export build cache to DockerHub registry. A 400 error is returned from DockerHub when exporting the cache.

#### Steps to reproduce this issue

1. Configure this action with the `cache-to` input set to `type=registry`
2. Run the workflow in GH Actions

#### Expected behaviour

The action should successfully export the cache.

#### Actual behaviour

A 400 response is received from the DockerHub API.

### Configuration

* Repository URL: https://github.com/Drew-Kimberly/docker-cache-export-repro
* Build URL (if public): https://github.com/Drew-Kimberly/docker-cache-export-repro/actions/runs/4723728068/jobs/8380065758?pr=1

```yml
name: CI
on:
  pull_request: {}
jobs:
  docker-build-push:
    name: Docker Build/Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Log in to Dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          install: true
      - name: Docker build
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          cache-from: type=registry,ref=uncledrewbie/docker-cache-export-repro:buildcache
          cache-to: type=registry,ref=uncledrewbie/docker-cache-export-repro:buildcache,mode=max
          tags: |
            uncledrewbie/docker-cache-export-repro:latest

```

### Logs

```
#13 exporting content cache
#13 preparing build cache for export
#13 writing layer sha256:0336c50c9f6942b660e433b1086238eec37057c34b14c4e3b28bd7bf05bd84ba 0.1s done
#13 writing layer sha256:093c82e9664e233bfad74e0241b1c7db19d688f8d2066bc3cc80d201ccb95709
#13 writing layer sha256:093c82e9664e[233](https://github.com/Drew-Kimberly/docker-cache-export-repro/actions/runs/4723728068/jobs/8380065758?pr=1#step:5:237)bfad74e0241b1c7db19d688f8d2066bc3cc80d201ccb95709 0.1s done
#13 writing layer sha256:0a7c7293f3cbaf53c689ef5d475495fb726e66e82264fbcca26298e1fec8d985
#13 writing layer sha256:0a7c7293f3cbaf53c689ef5d475495fb726e66e82264fbcca26298e1fec8d985 0.1s done
#13 writing layer sha256:0cf4be7fb878e046189ece0932e06fae48190c840e5a1aa02b0d451618487f7c
#13 writing layer sha256:0cf4be7fb878e046189ece0932e06fae48190c840e5a1aa02b0d451618487f7c 0.2s done
#13 writing layer sha256:127e97b4daf784e08840a21765f0d4f251192ef2994d0e4a253490f81e63955b
#13 writing layer sha256:127e97b4daf784e08840a21765f0d4f251192ef2994d0e4a253490f81e63955b 0.1s done
#13 writing layer sha256:1b89f3c7f7da8adf032a33a75d1b659cee33179ecb88ea0ba75e4fc58ebe63a6 0.1s done
#13 writing layer sha256:2d62772179761f8fddfaed03ed2bdf7078b103b193d18d79a9b49364830d56cf
#13 writing layer sha256:2d62772179761f8fddfaed03ed2bdf7078b103b193d18d79a9b49364830d56cf 0.1s done
#13 writing layer sha256:7891ab7e431e0092e86529a9945ddeae3a2a1dfd1d4c35c3c9d725655e1eaf3f 0.1s done
#13 writing layer sha256:9b293df1e1ca6c5d4ff93529fafef12b0f636ab6a7b739145e9193a6e4af0521
#13 writing layer sha256:9b293df1e1ca6c5d4ff93529fafef12b0f636ab6a7b739145e9193a6e4af0521 0.1s done
#13 writing layer sha256:ae2511c378ef2f48d84a0b488ca921afd537d0d7cc6aa9c89491905e65ea7be0
#13 writing layer sha256:ae2511c378ef2f48d84a0b488ca921afd537d0d7cc6aa9c89491905e65ea7be0 0.3s done
#13 writing layer sha256:b0[248](https://github.com/Drew-Kimberly/docker-cache-export-repro/actions/runs/4723728068/jobs/8380065758?pr=1#step:5:252)cf3e63c73d0e496a67807d056ca41d5e968b61087e8eca2cf4b9b4d7b99
#13 writing layer sha256:b0248cf3e63c73d0e496a67807d056ca41d5e968b61087e8eca2cf4b9b4d7b99 0.1s done
#13 writing config sha256:c31dbf99cf4c436c41de859995f61830d8c71b8cec7778694fcaa2fa9b2263cc
#13 writing config sha256:c31dbf99cf4c436c41de859995f61830d8c71b8cec7778694fcaa2fa9b2263cc 0.7s done
#13 writing manifest sha256:f0f5b942d4803569b43766d6297533d1bc901991199e56c78d64d9a52f786d72
#13 preparing build cache for export 2.3s done
#13 writing manifest sha256:f0f5b942d4803569b43766d6297533d1bc901991199e56c78d64d9a52f786d72 0.3s done
#13 ERROR: error writing manifest blob: failed commit on ref "sha256:f0f5b942d4803569b43766d6297533d1bc901991199e56c78d64d9a52f786d72": unexpected status: 400 Bad Request
------
 > importing cache manifest from ***/docker-cache-export-repro:buildcache:
------
------
 > exporting content cache:
------
ERROR: failed to solve: error writing manifest blob: failed commit on ref "sha[256](https://github.com/Drew-Kimberly/docker-cache-export-repro/actions/runs/4723728068/jobs/8380065758?pr=1#step:5:260):f0f5b942d4803569b43766d6297533d1bc901991199e56c78d64d9a52f786d72": unexpected status: 400 Bad Request
Error: buildx failed with: ERROR: failed to solve: error writing manifest blob: failed commit on ref "sha256:f0f5b942d4803569b43766d6297533d1bc901991199e56c78d64d9a52f786d72": unexpected status: 400 Bad Request
```

**Comment by orensbruli** [comment]
Same problem here. We have been looking for the solution on our side for hours. Can't guess what's the problem.

**Comment by eholum** [comment]
We can report running into this same issue in our workflows and have not identified a fix. We have tried disabling provenance, bumping versions, etc but have not identified a fix.

**Comment by jedevc** [comment]
The issue is resolved now, so I'll close this issue.

**Comment by Mehdi-Verfaillie** [comment]
I'm experiencing the same issue with AWS ECR. 

```sh
ERROR: failed to solve: error writing manifest blob: failed commit on ref "sha256:4687663fb448331fc11fb478d2ac366ad4c598483b2039aac67392a710e2db47": unexpected status: 400 Bad Request
Error: buildx failed with: ERROR: failed to solve: error writing manifest blob: failed commit on ref "sha256:4687663fb448331fc11fb478d2ac366ad4c598483b2039aac67392a710e2db47": unexpected status: 400 Bad Request
```

The only solution I've found is to comment out the cache section.

Here is an exemple:

```yml
name: "Build to AWS"
description: "Push a specific app to AWS"

inputs:
 ...

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push to AWS Container Registry
      uses: docker/build-push-action@v4
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      with:
        context: ${{inputs.context-path}}
        file: ${{inputs.context-path}}/${{inputs.docker-file}}
        platforms: linux/amd64
        push: true
        # cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ inputs.repository }}:buildcache
        # cache-to: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ inputs.repository }}:buildcache,mode=${{ inputs.cache-size }}
        tags: |
          ${{ env.ECR_REGISTRY }}/${{ inputs.repository }}:${{ inputs.version-tag }}
          ${{ env.ECR_REGISTRY }}/${{ inputs.repository }}:latest
        build-args: ${{ inputs.build-args }}
        provenance: false
```
