### ISSUE TITLE
The `labels:` property doesn't work for me with docker/build-push-action@v4

### ISSUE THREAD

**Issue by erikmd** [docker/build-push-action#863]
### Behaviour

I recently migrated from the very-old version v1 (with [`add_git_labels: true`](https://github.com/ocaml-sf/learn-ocaml/blob/6cb8165e871ce182851302ab7ccc8098dcbbb394/.github/workflows/deploy-master.yml#L22)) to v4 (with [these labels](https://github.com/ocaml-sf/learn-ocaml/blob/046087d596c35a8918e7d6a51b54c6c64b5a2397/.github/workflows/deploy-master.yml#L41-L45)).

However, none of these 4 labels is added in the image:

* https://hub.docker.com/r/ocamlsf/learn-ocaml/tags?page=1&name=master

![2023-05-01_22-19-24_Screenshot_missing_labels](https://user-images.githubusercontent.com/10367254/235523974-c91e97cc-3fe6-431a-9562-79129e7750dd.png)

See also our downstream issue:

* https://github.com/ocaml-sf/learn-ocaml/issues/545

### Configuration

* Repository URL (if public): https://github.com/ocaml-sf/learn-ocaml
* Build URL (if public): https://github.com/ocaml-sf/learn-ocaml/actions/runs/4852892261/jobs/8648443649 (see log at the bottom of this description)

```yml
# Note: you may want to update this file and deploy-tags.yml at once
name: Publish dev (Docker image of master)
on:
  push:
    branches:
      - master
  schedule:
    # deploy master every Saturday at 08:00 UTC
    - cron: '0 8 * * 6'
jobs:
  push_server:
    name: Push learn-ocaml image to Docker Hub
    if: ${{ github.repository == 'ocaml-sf/learn-ocaml' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        # cf. https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#image
        # and https://docs.docker.com/engine/reference/commandline/buildx_create/#driver
        uses: docker/setup-buildx-action@v2
        with:
          driver: "docker"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare
        id: prep
        run: |
          echo "::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Push to Docker Hub
        # cf. https://github.com/docker/build-push-action#customizing
        # and https://github.com/docker/build-push-action/pull/119
        uses: docker/build-push-action@v4
        with:
          pull: true
          push: true
          tags: "ocamlsf/learn-ocaml:master"
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=master
            org.opencontainers.image.revision=${{ github.sha }}
  push_client:
    name: Push learn-ocaml-client image to Docker Hub
    if: ${{ github.repository == 'ocaml-sf/learn-ocaml' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        # cf. https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#image
        # and https://docs.docker.com/engine/reference/commandline/buildx_create/#driver
        uses: docker/setup-buildx-action@v2
        with:
          driver: "docker"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare
        id: prep
        run: |
          echo "::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Push to Docker Hub
        # cf. https://github.com/docker/build-push-action#customizing
        # and https://github.com/docker/build-push-action/pull/119
        uses: docker/build-push-action@v4
        with:
          pull: true
          # load: true # implied by "driver: docker"
          push: true
          target: client
          tags: "ocamlsf/learn-ocaml-client:master"
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=master
            org.opencontainers.image.revision=${{ github.sha }}
  push_emacs_client:
    name: Push emacs-learn-ocaml-client image to Docker Hub
    if: ${{ github.repository == 'ocaml-sf/learn-ocaml' }}
    needs: push_client
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        # cf. https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#image
        # and https://docs.docker.com/engine/reference/commandline/buildx_create/#driver
        uses: docker/setup-buildx-action@v2
        with:
          driver: "docker"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare
        id: prep
        run: |
          echo "::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Push to Docker Hub
        # cf. https://github.com/docker/build-push-action#customizing
        # and https://github.com/docker/build-push-action/pull/119
        uses: docker/build-push-action@v4
        with:
          pull: false # because of the previous "load: true"
          push: true
          context: ci/docker-emacs-learn-ocaml-client
          build-args: |
            base=ocamlsf/learn-ocaml-client
            version=master
          tags: "ocamlsf/emacs-learn-ocaml-client:master"
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=master
            org.opencontainers.image.revision=${{ github.sha }}
```

### Logs

[logs_2143.zip](https://github.com/docker/build-push-action/files/11367827/logs_2143.zip)
