### ISSUE TITLE
Cannot push to open source repo using community user bot

### ISSUE THREAD

**Issue by jaronoff97** [docker/build-push-action#864]
#### Steps to reproduce this issue

1. Create a community organization in docker hub
2. Add a community user
3. create PAT for community user
4. use example [here](https://docs.docker.com/build/ci/github-actions/manage-tags-labels/) to push image to both ghcr and docker hub 
5. Let action run on PR merge

#### Expected behaviour

Image should be pushed successfully to both repositories

#### Actual behaviour

ERROR: failed to solve: failed to push otel/autoinstrumentation-java:1.25.1: server message: insufficient_scope: authorization failed
Error: buildx failed with: ERROR: failed to solve: failed to push otel/autoinstrumentation-java:1.25.1: server message: insufficient_scope: authorization failed

### Configuration

* Repository URL (if public): https://github.com/open-telemetry/opentelemetry-operator
* Build URL (if public): https://github.com/open-telemetry/opentelemetry-operator/actions/runs/4927603791/jobs/8807178362

```yml
name: "Publish Java Auto-Instrumentation"

on:
  push:
    paths:
      - 'autoinstrumentation/java/**'
      - '.github/workflows/publish-autoinstrumentation-java.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'autoinstrumentation/java/**'
      - '.github/workflows/publish-autoinstrumentation-java.yaml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Read version
        run: echo "VERSION=$(cat autoinstrumentation/java/version.txt)" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            otel/autoinstrumentation-java
            ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java
          tags: |
            type=match,pattern=v(.*),group=1,value=v${{ env.VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log into Docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: autoinstrumentation/java
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          build-args: version=${{ env.VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
```

### Logs

[logs.txt](https://github.com/docker/build-push-action/files/11435352/1_publish.txt)
