### ISSUE TITLE
GHA cache gets overridden when building multiple images in a single workflow

### ISSUE THREAD

**Issue by MartyWind** [docker/build-push-action#867]
### Behaviour

I build multiple parts of my application in separate jobs in a github action workflow.
They all look like this, one for `frontend` one for `worker` and `backend` respectively:
```
  frontend:
    runs-on: ubuntu-latest
      [...]
      - uses: docker/build-push-action@v4.0.0
        with:
          context: frontend/
          file: frontend/.docker/Dockerfile
          push: ${{ inputs.push }}
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}:latest
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```
The problem is, that only the job that finished last in the previous run gets a cache hit.
All other images are getting built fully.
On the next run this changes obviously, as the freshly build image finished last.

I tried to specify a `ref` like this (different for all images):
```
          cache-from: type=gha,ref=frontend-${{ github.ref_name }}
          cache-to: type=gha,mode=max,ref=frontend-${{ github.ref_name }}
```
But this seems to get ignored, as the behavior is unchanged.

#### Steps to reproduce this issue

1. Build multiple images in a single workflow
2. Cache them (`cache-from` and `cache-to`) with `type=gha`

#### Expected behaviour

> All images should hit their respective caches.

#### Actual behaviour

> Only the lastly built image will get a cache hit.

### Attachments
Nothing changed between these runs:
1.
![grafik](https://github.com/docker/build-push-action/assets/121865041/0feb3878-a342-48fa-9c42-68da5a399fd2)

2.
![grafik](https://github.com/docker/build-push-action/assets/121865041/fd8c1935-95ed-46fa-b243-f902cd8d6ee8)

3.
![grafik](https://github.com/docker/build-push-action/assets/121865041/f9f978c5-6e89-441f-b0a3-621873b03120)
