### ISSUE TITLE
`cache-from: type=gha` does not find image in `COPY --from` directive

### ISSUE THREAD

**Issue by lgrosz** [docker/build-push-action#868]
### Behaviour

When building a dependent image in a second job, where the first job should cache a built image, the second build fails to find first job's image. I also attempted this [like this](https://docs.docker.com/build/ci/github-actions/share-image-jobs/), but it seems buildx cannot be used, in particular the build-push-action, with the same results.

The goal is to build a tools image in the first job and (eventually) several images which depend on the tools in the first image in the second job. The tools image should not be pushed to a public repository.

#### Steps to reproduce this issue

```
.                                    
├── tools                                                                                                       
│   └── Dockerfile                                                                                              
└── uses-tools                                                                                                  
    └── Dockerfile
```

- tools/Dockerfile

```Dockerfile
FROM ubuntu:22.04
RUN touch /tools
```

- uses-tools/Dockerfile

```
FROM ubuntu:22.04
COPY --from=tools:latest /tools /
```

#### Expected behaviour

Dockerfile under `uses-tools` context should successfully build.

#### Actual behaviour

Second job fails as it cannot find the (should be) previously cached image to copy from.

### Configuration

* [Repository URL](https://github.com/lgrosz/my-yocto-dockerfiles/tree/failure-mwe)
* [Build URL](https://github.com/lgrosz/my-yocto-dockerfiles/actions/runs/5052935826)

```yml
name: Build images
on:
  workflow_dispatch:

jobs:
  build-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build tools image
        uses: docker/build-push-action@v4
        with:
          tags: tools:latest
          context: tools
          push: false
          load: true
          cache-to: type=gha,mode=max

  build-uses-tools:
    needs: build-tools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build uses tools image
        uses: docker/build-push-action@v4
        with:
          context: uses-tools
          push: false
          load: true
          cache-from: type=gha
```

### Logs

[logs_41.zip](https://github.com/docker/build-push-action/files/11539238/logs_41.zip)
