### ISSUE TITLE
Order of tags when pushing and registry_package event.

### ISSUE THREAD

**Issue by brpaz** [docker/build-push-action#877]
Hello.

I have a GitHub workflow that push a docker image to the GitHub Package registry using `build-push-action`

```yaml
     -  name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.RELEASE_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=

          labels: |
            maintainer=Bruno Paz
            org.opencontainers.image.title=Express Typescript Starter
            org.opencontainers.image.description=An example application using Express and Typescript

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          build-args: |
            BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          tags: ${{ env.TEST_IMAGE_NAME}}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Push image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels}}

          # use a different to make sure it triggers the deployment workflow.
          # The token must have the `packages:write` permission
          github-token: ${{ secrets.GH_PAT }}
```

Then I have another workflow that is listening to the `registry_package.published` event to trigger a deploy of the application.

The problem is that the tag reference in the `registry_package` event payload always contain the `latest` when releasing from a tag, or the `sha` representation when releasing from main branch.

Example: 
```json
     "container_metadata": {
          "labels": {
            "all_labels": {
              "github.internal.platforms": "[{\"digest\":\"sha256:2b85d0e01f9b0893c602c30a149f8a09f123d8878ce0b595d611065eeedf6e2f\",\"architecture\":\"amd64\",\"os\":\"linux\"},{\"digest\":\"sha256:c25562283d8ad009ea05c8dab9e1cc24b7a00d18df3d6fe3ca73859115920bd0\",\"architecture\":\"unknown\",\"os\":\"unknown\"}]"
            },
            "description": "",
            "image_url": "",
            "licenses": "",
            "revision": "",
            "source": ""
          },
          "manifest": {
            "config": {
              "digest": "",
              "media_type": "",
              "size": 0
            },
            "digest": "sha256:5ba041a0ac626a8240c8e2571d323320d2a4de35f8b5814af1b12df0348a7e96",
            "layers": [],
            "media_type": "application/vnd.oci.image.index.v1+json",
            "size": 856,
            "uri": "repositories/brpaz/express-ts-starter/manifests/sha256:5ba041a0ac626a8240c8e2571d323320d2a4de35f8b5814af1b12df0348a7e96"
          },
          "tag": {
            "digest": "sha256:5ba041a0ac626a8240c8e2571d323320d2a4de35f8b5814af1b12df0348a7e96",
            "name": "latest"
          }
```

I want always to receive the tag `Ex v1.0.0` or the commit sha and never `latest`, while I still want the "latest" tag to be pushed to the repository.

It seems that the event always contains the latest tag that is pushed. Is there any way I can control that order and make sure it always pushes the release tag last?
