### ISSUE TITLE
push to hub.docker.com fails with `denied: requested access to the resource is denied`

### ISSUE THREAD

**Issue by bastelfreak** [docker/build-push-action#88]
Hi!
thanks for the awesome action! I added it to my workflow on https://github.com/voxpupuli/vox-pupuli-tasks

```yaml
name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.7
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        bundle config set path vendor/bundle
        bundle config set jobs $(nproc)
        bundle config set without development
        bundle install
    - name: Run tests
      run: bundle exec rake rubocop
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: voxpupuli/vox-pupuli-tasks
        add_git_labels: true
        tags: latest
        tag_with_ref: true
        tag_with_sha: true
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: voxpupuli/vox-pupuli-tasks
        add_git_labels: true
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
```

I also published a few docker modules with this. Since a few days I get the following errormessage:

```
Successfully built 65ffb4a2ea6a
Successfully tagged voxpupuli/vox-pupuli-tasks:latest
Successfully tagged voxpupuli/vox-pupuli-tasks:pr-217-merge
Successfully tagged voxpupuli/vox-pupuli-tasks:sha-0612700
Pushing image [voxpupuli/vox-pupuli-tasks:latest voxpupuli/vox-pupuli-tasks:pr-217-merge voxpupuli/vox-pupuli-tasks:sha-0612700]
The push refers to repository [docker.io/voxpupuli/vox-pupuli-tasks]
d0d252682376: Preparing
cb1d850665a1: Preparing
3da0bf188cbd: Preparing
97f83abe5a46: Preparing
91cd5a8e58ae: Preparing
fd74c6bcef3b: Preparing
9c6bf071bef9: Preparing
b84c9316c1db: Preparing
1620e857daea: Preparing
93a2bfafa84f: Preparing
54f362ba164c: Preparing
c4b1ff92c516: Preparing
446d8e2016ac: Preparing
50644c29ef5a: Preparing
fd74c6bcef3b: Waiting
9c6bf071bef9: Waiting
b84c9316c1db: Waiting
1fa5cdcb4f03: Waiting
0262166ecd22: Waiting
1bb9a3658531: Waiting
1620e857daea: Waiting
93a2bfafa84f: Waiting
54f362ba164c: Waiting
c4b1ff92c516: Waiting
446d8e2016ac: Waiting
50644c29ef5a: Waiting
denied: requested access to the resource is denied
exit status 1
Error: exit status 1
Usage:
  github-actions build-push [flags]

Flags:
  -h, --help   help for build-push
```

I'm not 100% sure what it means. Are the credentials wrong? I built a docker image locally and pushed it with my credentials and that worked. I set the same as github secrets for `DOCKER_USERNAME` and `DOCKER_PASSWORD`.
