### ISSUE TITLE
Enable Buildx progress=plain

### ISSUE THREAD

**Issue by josherickson** [docker/build-push-action#885]
Hi there, wondering if it's possible to enable the `progress=plain` build setting. It's described [here](https://docs.docker.com/engine/reference/commandline/buildx_build/#progress) and looks like it can either be set with an argument `--progress=plain` in the build command, or as an environment variable `BUILDKIT_PROGRESS=plain`.

Have tried setting this an environment variable on the action but it didn't seem to have any effect.

```
- name: Build and push Docker image
  uses: docker/build-push-action@v4
  env:
    BUILDKIT_PROGRESS: plain
  with:
    build-args: ${{ inputs.docker-build-args }}
    context: ${{ inputs.docker-context }}
    file: ${{ inputs.docker-context }}/${{ inputs.dockerfile }}
    push: true
    tags: latest
```

Thanks!
