### ISSUE TITLE
.Config.Labels vs .ContainerConfig.Labels

### ISSUE THREAD

**Issue by alex-old-user** [docker/build-push-action#887]
Hello, I'm not sure whether it's a bug or by design. When I do sth simple as 
```yaml
      - uses: docker/build-push-action@v4
        with:
          push: true
          labels: |
            foo=bar
```

and then check the image with `docker inspect`, `.Config.Labels` is populated with the label, but `.ContainerConfig.Labels` is set to `null`. Setting the label in Dockerfile has the same result. Is this the expected behavior for the action? Is there a way to set `.ContainerConfig.Labels`?

thanks
