### ISSUE TITLE
Force to use action/checkout with specific context

### ISSUE THREAD

**Issue by headyj** [docker/build-push-action#888]
Hello,

in the documentation, it's written the following:
 
```
By default, this action uses the [Git context](https://docs.docker.com/engine/reference/commandline/build/#git-repositories), so you don't need to use the [actions/checkout](https://github.com/actions/checkout/) action to check out the repository as this will be done directly by [BuildKit](https://github.com/moby/buildkit).
```
This seems not true, as I if I don't do an action/checkout before my docker build, sources are not even found:

`buildx failed with: ERROR: could not find docker: stat docker: no such file or directory`

my Dockerfile is in fact in a subfolder named "docker" on my git repo. The dockerfile will only be found if I do an action/checkout before my build-push-action:

```
      - name: Checkout
        uses: actions/checkout@v2
[...]
     - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: registry/image:latest
          file: docker/Dockerfile
          context: "/home/runner/work/git-repo/git-repo"
```

moreover, if I don't setup the context, git sources are not found at all
