### ISSUE TITLE
Untagged images produced for multi platform builds

### ISSUE THREAD

**Issue by daltonv** [docker/build-push-action#894]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

Multiplatform images produce untagged images for each platform built for

#### Steps to reproduce this issue

1. Build a multiplatform image & push to ghcr
2. Observe multiple images being posted like so 
![image](https://github.com/docker/build-push-action/assets/8504933/6f12721b-0ad0-4b0c-82f0-19e0ea650593)
![image](https://github.com/docker/build-push-action/assets/8504933/9b282961-74d3-4611-b741-5eba1d5e8d4d)

#### Expected behaviour

I would hope there is at least an option to tag each platforms image with special tag. In the example above perhaps pr-5-arm64 and pr-5-amd64

#### Actual behaviour

Multiple untagged images

### Configuration

```yml
name: CI

on:
  push:
    tags:
        - 'v*.*.*'

  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
          include:
            - image_name: ${{ github.repository }}-ci
              docker_target: ci
            - image_name: ${{ github.repository }}
              docker_target: developer

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ matrix.image_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=pr
            type=sha

      # Crazy thing needed to for the cache to work in the next step, as the
      # cache must be sent in lower case
      - name: downcase REPO
        run: |
          echo "REPO=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.docker_target }}
          provenance: false
          build-args: |
            JFROG_USER=${{ secrets.JFROG_USER }}
            JFROG_KEY=${{ secrets.JFROG_KEY }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO }}:latest
          cache-to: type=inline
          platforms: |
            linux/amd64
            linux/arm64
```

**Comment by saadbahir** [comment]
I have the same problem without using multi-platforms

I am pushing images to two separate registries, including Github registry
```
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ needs.prepare.outputs.image_fly }}${{ env.IMAGE_SUFFIX }}
            ${{ needs.prepare.outputs.image_github }}${{ env.IMAGE_SUFFIX }}
```

In github registry, I end up with the correct version for example `image-repo-name:1.0.0` and two untagged versions

```
#12 exporting to image
#12 exporting layers
#12 exporting layers 17.8s done
#12 exporting manifest sha256:b1ee819a2e3d5896b86d8d87e242cee35566f20afbb527441c46f7b0d1480a06 0.0s done
#12 exporting config sha256:9d265a628e53ff77b40026a825fb59758f08eb9935ad42ab9bb95170fbdbf3a3
#12 exporting config sha256:9d265a628e53ff77b40026a825fb59758f08eb9935ad42ab9bb95170fbdbf3a3 done
#12 exporting attestation manifest sha256:8f6eb2770bfada4f266d37985611558f866d281d366cc659486975817d602296 done
#12 exporting manifest list sha256:7264527bd66a26218825ead8b63be68931267f02b45d2bc76a7a2c2943b0d4a1 done
#12 pushing layers
#12 ...

```

In this case for example, I get two other images with tags
```
b1ee819a2e3d5896b86d8d87e242cee35566f20afbb527441c46f7b0d1480a06
```

and 
```
8f6eb2770bfada4f266d37985611558f866d281d366cc659486975817d602296
```

Does anyone know what triggers this behavior?
