### ISSUE TITLE
Is there a way to share an OCI image between jobs?

### ISSUE THREAD

**Issue by LeviPesin** [docker/build-push-action#897]
Is there any way to share an image built with `type=oci` (so that it can contain provenance, for example) between jobs? Using `docker load` results in an error like `open /var/lib/docker/tmp/docker-import-2995601243/blobs/json: no such file or directory` -- it seems it works only with `type=docker`?

**Comment by crazy-max** [comment]
It works fine on my side:

```yaml
name: oci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          outputs: type=oci,dest=/tmp/build.tar
          tags: |
            name/app:latest
            name/app:1.0.0
      -
        name: Load
        run: docker load -i /tmp/build.tar
```

Can you share a full repro please?
