### ISSUE TITLE
Path option not working as expected

### ISSUE THREAD

**Issue by Zethson** [docker/build-push-action#90]
Hi,

```
      - name: debug
        run: |
          pwd
```
results in `/home/runner/work/mlf-core/mlf-core`

My Dockerfile is in `/home/runner/work/mlf-core/exploding_springfield`. 
It's called `Dockerfile`.
I verified this in the Workflow!

```
 cd ../exploding_springfield
  pwd
  ls -la

-rw-r--r-- 1 runner docker  528 Aug 14 16:58 Dockerfile
```

Hence, I expect 

```
- name: Build Docker container
        uses: docker/build-push-action@v1
        with:
          repository: mlfcore/exploding_springfield
          tags: 0.1.0-SNAPSHOT
          push: false
          path: ../exploding_springfield
```

or 

```
      - name: Build Docker container
        uses: docker/build-push-action@v1
        with:
          dockerfile: ../exploding_springfield/Dockerfile
          repository: mlfcore/exploding_springfield
          tags: 0.1.0-SNAPSHOT
          push: false
          path: ../exploding_springfield
```

To find the Dockerfile.
However, even with the absolute path I always run into: 
`unable to prepare context: path "../exploding_springfield" not found`
or
`unable to prepare context: path "/home/runner/work/mlf-core/exploding_springfield" not found`

What am I doing wrong?

Thank you very much!
Cheers

**Comment by lewislbr** [comment]
Adding to this, the `path` doesn't seem to be passed to `dockerfile`, having to rewrite the path (in this case `folder1`) like:

```yml
- name: Build and push Docker images
        uses: docker/build-push-action@master
        with:
          path: folder1
          dockerfile: folder1/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lewislbr/random
```

to make it work.
