### ISSUE TITLE
GHCR "breaks" on images built not with `output: type=docker`

### ISSUE THREAD

**Issue by LeviPesin** [docker/build-push-action#900]
There is no problem with this:

#### No problem

```yaml
- name: Push Docker image
  uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
  with:
    context: src
    tags: ${{ needs.metadata.outputs.tags }}
    labels: ${{ needs.metadata.outputs.labels }}
    cache-from: type=gha
    cache-to: type=gha,mode=max
    load: true
- name: Push Docker image to GHCR
    run: docker push -a ghcr.io/${{ inputs.image-name }}
```

But a problem with this:

#### Breaks

```yaml
- name: Push Docker image
  uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
  with:
    context: src
    tags: ${{ needs.metadata.outputs.tags }}
    labels: ${{ needs.metadata.outputs.labels }}
    cache-from: type=gha
    cache-to: type=gha,mode=max
    push: true
```

Is this a GHCR problem or a problem with the action?

#### Expected behaviour (First code snippet)

![image](https://github.com/docker/build-push-action/assets/35454228/29fa47c2-87f9-4c30-b17c-8ad745ad6f66)

#### Actual behaviour (Second code snippet)

![image](https://github.com/docker/build-push-action/assets/35454228/6cd04a51-725d-4a42-8f89-ac1c6c332466)

As you can see some weird `unknown/unknown` architecture appears and GHCR can no longer read labels including license and description.

### Logs

First log: https://pastebin.com/xVnafXKJ
Second log: https://pastebin.com/X4yyB9gx

**Comment by crazy-max** [comment]
Seems an issue with GHCR not being able to parse an OCI index or it tries to parse manifest attestations but fails to display infos from labels. Pure speculation but I think GitHub does not check the mime-type of the manifest on their side so it fails.

Can you try disabling provenance?:

```
- name: Push Docker image
  uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
  with:
    context: src
    tags: ${{ needs.metadata.outputs.tags }}
    labels: ${{ needs.metadata.outputs.labels }}
    cache-from: type=gha
    cache-to: type=gha,mode=max
    push: true
    provenance: false
```
