### ISSUE TITLE
Docker Multi-Stage Build Failing on COPY --from

### ISSUE THREAD

**Issue by OnerInce** [docker/build-push-action#909]
I am trying to build following multi-stage Dockerfile:

```dockerfile
FROM node:16.13-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node", "server.js"]

``` 

However, it fails on the last stage. Error message is:
`buildx failed with: ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref ixtqd2us9kaftl9v6qm0kc0rt::vteockhvetegcevutywlk57tn: "/app/public": not found`. 

Dockerfile building fine on local, that means something wrong with caching. I have tried different caching parameters but no luck. My Github Workflow definition as follows:

```
name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          version: latest
          buildkitd-flags: --debug

      - name: Build initial image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-next
          builder: ${{ steps.buildx.outputs.name }}
          file: frontend-next/Dockerfile.prod
          target: runner
          push: false
          tags: latest
          cache-from: type=gha,scope=my_cache
          cache-to: type=gha,mode=max,scope=my_cache

```
