### ISSUE TITLE
Cannot locate specified Dockerfile if the dockerfile is in a directory named Docker

### ISSUE THREAD

**Issue by chadsugithub** [docker/build-push-action#91]
The following yml

```
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        path: ./Client
        dockerfile: ./Client/Docker/Dockerfile.nanoserver-x64
```

It will fail with the following error.

`Error response from daemon: Cannot locate specified Dockerfile: Docker/Dockerfile.nanoserver-x64`

It works if the Docker directory is renamed to _Docker for example.
