### ISSUE TITLE
GitHub Action can use mamba to build regular projects but fails to build during Docker build

### ISSUE THREAD

**Issue by ZhangxiJesseFeng** [docker/build-push-action#914]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. Running GitHub action docker build:
```
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-docker-image:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build container
        run: docker build -f Dockerfile -t rietveld .
```
2. Job fails at Build container step
3. Log can be found at: https://github.com/lanl/MILK/actions/runs/5682611743/job/15401368032

#### Expected behaviour

4 weeks ago, there were no issues. The job just builds and publishes. You can see from the history of the actions that this is true.

#### Actual behaviour

We had made no changes in the code that should affect this, but as of last 2 weeks, the docker build on GitHub Actions continues to fail and the error and warning messages are difficult to decipher on what the issue actually is. It complains about mamba but mamba is perfectly fine when used in other action jobs not using Docker and they can build successfully.

### Configuration

* Repository URL (if public): https://github.com/lanl/MILK
* Build URL (if public): https://github.com/lanl/MILK/actions/runs/5682611743/job/15401368032

```yml
name: Build and Publish Rietveld Docker Image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-docker-image:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build container
        run: docker build -f Dockerfile -t rietveld .

  publish-container-image:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [build-docker-image]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push to local registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/lanl/milk:${{ github.ref_name }}-${{github.sha}}
```

### Logs

Log downloaded from the job, can also be found in the link provided above.
[logs_264.zip](https://github.com/docker/build-push-action/files/12185448/logs_264.zip)
