### ISSUE TITLE
Cache not read

### ISSUE THREAD

**Issue by ro0NL** [docker/build-push-action#917]
Hi,

Im using the following job step for building a multistage dockerfile:

```yaml
-
    uses: docker/build-push-action@v4
    with:
        context: .
        load: true
        target: app
        # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
        cache-from: type=gha,scope=app
        cache-to: type=gha,mode=max,scope=app
```

After the first run 53 caches are written

After the second run 105 caches are written, and no existing cache is used.

Am i missing something?

**Comment by crazy-max** [comment]
Maybe GitHub Actions cache is full so old objects are GCed? Would need to see your full workflow, Dockerfile and logs to make sure. Link to your repo would be easier though.

**Comment by ro0NL** [comment]
@crazy-max i think i was able to reproduce:

1st run without cache: https://github.com/ro0NL/test-docker-build/actions/runs/5724005099/job/15509630853
2nd run with 45 existing cache entries: https://github.com/ro0NL/test-docker-build/actions/runs/5724018658/job/15509671146

after the 2nd run there are 94 caches

initially i did saw CACHED docker steps

after using 

```yaml
'on':
    push:
        tags:
            - '*.*.*'
```

it seems to defacto ignore build cache
