### ISSUE TITLE
Push to Harbor failed with `401 Unauthorized` despite `docker/login-action@v2` suceeded

### ISSUE THREAD

**Issue by NexZhu** [docker/build-push-action#923]
#### Steps to reproduce this issue

I'm using Gitea Actions, my`build.yaml`:
```yml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: remote
          endpoint: tcp://buildkitd.buildkit.svc.cluster.local:1234

      - uses: docker/login-action@v2
        with:
          registry: harbor.internetapi.cn
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: docker/build-push-action@master
        with:
          context: .
          file: docker/Dockerfile.prebuilt
          push: true
          tags: harbor.redacted.com/fgfe/fes-starter:latest
```

`docker/login-action@v2` and build both succeeded, but pushing failed with `401 Unauthorized`

![image](https://github.com/docker/build-push-action/assets/4370605/29ee5364-0670-4ebd-b671-7d14ca184f6e)
![image](https://github.com/docker/build-push-action/assets/4370605/ee49843c-601d-4081-b640-f17898a394c3)

I'm sure the credential I'm using has the push right, because I've tested with the same credential on a server manually `docker login` and `docker push` to the same repository, it worked.

#### Expected behaviour

Should be able to push to Harbor.
