### ISSUE TITLE
Image gets built even if the build args have empty input

### ISSUE THREAD

**Issue by ashishjullia** [docker/build-push-action#926]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. Use the `yaml` provided below
2. Target any repo
3. Run the actions step

Also, here is the `Dockerfile`
```Dockerfile
# Specify the base image
FROM node:16-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG MYSQL_HOST 
ENV MYSQL_HOST=$MYSQL_HOST
RUN chmod +x entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
```

#### Expected behaviour

If there is the empty value for ${{ env.MYSQL_HOST }} then the build step should not proceed, means if should check the value being empty or not

#### Actual behaviour

The image is being built even if the value is empty for ${{ env.MYSQL_HOST }}

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: testrepo/${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "MYSQL_HOST=${{ env.MYSQL_HOST }}"
```

### Logs

I'm not sure whether such checks can be directly performed using this action or a separate step will be required just to check whether the values being passed are empty of not.
