### ISSUE TITLE
Hang after build and before "pushing layers"

### ISSUE THREAD

**Issue by Fish1** [docker/build-push-action#929]
#### Steps to reproduce this issue

1. checkout@v3
2. login-action@v2
3. metadata-action@v3
4. build-push-action@v4

#### Expected behaviour

> The image should be pushed to ghcr.io

#### Actual behaviour

> After the build and before "pushing layers" step.

> I have a nearly identical workflow here that builds another image. And it works fine and doesn't hang. https://github.com/yapms/yapms/actions/runs/5872278682

### Configuration

* Repository URL (if public): https://github.com/yapms/yapms
* Build URL (if public): https://github.com/yapms/yapms/actions/runs/5872278683/job/15926291141

```yml
name: Build YAPms Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-yapms

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.yapms
          build-args: |
            DOTENV_VAULT_KEY=${{ secrets.DOTENV_VAULT_KEY }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
```

### Logs

[logs_876.zip](https://github.com/docker/build-push-action/files/12354374/logs_876.zip)
