### ISSUE TITLE
What is the cache ttl for type=gha ?

### ISSUE THREAD

**Issue by mvynhb** [docker/build-push-action#942]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Hi I am using the below configuration in my github actions:

```
    - name: Build and cache
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: localhost:5000/my-app/app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=min
```

Its working as expected, the first run it builds my Dockerfile and the second run it uses the cache. However I have noticed that after 1 day or so the cache is not used anymore and needs to run the build again.

I read the ttl for cache entries on github action is 1 week https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy. Is there some setting I need to use to specify the ttl?

Thanks

### Expected behaviour

Cache is re-used.

### Actual behaviour

Cache is not re-used after about 1 day.

### YAML workflow

```yaml
- name: Build and cache
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: localhost:5000/my-app/app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=min
```
```


### Workflow logs

_No response_

### BuildKit logs

_No response_

### Additional info

_No response_
