### ISSUE TITLE
Node 16 no longer available via nodesource

### ISSUE THREAD

**Issue by mcsgroi** [docker/build-push-action#946]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Node 16 seems to no longer be provided via nodesource.

Node 16 url being used doesn't resolve a download: https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb

Node 18 url resolves: https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/nodejs_18.17.1-deb-1nodesource1_amd64.deb

### Expected behaviour

I expect the build and push plugin to be able to resolve dependencies and run.

### Actual behaviour

Runs fail with: 
```
#14 5.298 Err:1 https://deb.nodesource.com/node_16.x bullseye/main amd64 nodejs amd64 16.20.2-deb-1nodesource1
#14 5.298   404  Not Found [IP: 172.67.10.205 443]
#14 5.305 E: Failed to fetch https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb  404  Not Found [IP: 172.67.10.205 443]
#14 5.305 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
#14 ERROR: process "/bin/sh -c curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs" did not complete successfully: exit code: 100
```

### YAML workflow

```yaml
name: Publish Docker image

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: ["master", "main"]
  pull_request:
    branches:
      - 'master'
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=sha,format=long,prefix=sha-,suffix=
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ARG1=Value1
            ARG2=Value2
```
