### ISSUE TITLE
throws uppercase repository error when repository is in lowercase

### ISSUE THREAD

**Issue by schniti269** [docker/build-push-action#967]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Error: buildx failed with: ERROR: invalid tag "containersfallstudie.azurecr.io/***/frontendweb:14c4b972e95f9c491fa8557c104fd81f71ee2c05": repository name must be lowercase

if you are telling me i cant have uppercase secrets in this string why would that even make sense

### Expected behaviour

pass as IT IS ALLLLLLLL IN LOWERCASEEEEEEEEE

### Actual behaviour

FAIL 

### YAML workflow

```yaml
- name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containersfallstudie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_64da62845f5d4ca190df25f8e243d528 }}/frontendweb:${{ github.sha }}
        file: ./Dockerfile
```
