### ISSUE TITLE
What's the Context for COPY?

### ISSUE THREAD

**Issue by dschinkel** [docker/build-push-action#97]
What directory are we **in** (context) when we use the COPY command from our Docker file?  none of my copies work and the GITHUB WORKSPACE shows after my build that the files I want to copy are there yet none of these are working:

I'm using download artifact to bring back down the dist folder produced by the initial build job.  I assume that the Dockerfile should then be able to find my dist folder as it's definitely there in my job after I download that artifact
```
  push_to_registry:
    needs: build
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist-artifact
          path: dist
      - run: ls -la
      - run: ls dist
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          # OWNER/REPOSITORY/IMAGE_NAME
          repository: dschinkel/we-do-tdd/staging
          tag_with_sha: true
```

**But when it runs my Dockerfile it fails with the error below:**
```
FROM node:14.8.0-alpine
ENV PORT 80
COPY ./dist ./dist
```
**also tried:** `COPY dist dist`
**and** `COPY ./dist dist`
**and** `COPY dist ./dist`
**and** `COPY /dist /dist`
**and** `COPY dist /dist`

???

Seems like it's saying it can't create the dist directory on the container?
```
Step 4/4 : COPY dist /dist
COPY failed: stat /var/lib/docker/tmp/docker-builder055560440/dist: no such file or directory
```

I know dist is definitely there from my GitHub Actions webpack build:
![Screen Shot 2020-08-30 at 4 23 25 PM](https://user-images.githubusercontent.com/338798/91672182-7b4f4800-eaf2-11ea-87d9-b1d38852bbed.jpg)

**Comment by dschinkel** [comment]
Got it working.  Had to:

1) Use artifacts
2) Change my Dockerfile to:

```
FROM node:14.8.0-alpine
ENV PORT 80
WORKDIR dist
COPY . dist

```

**Comment by tuxerrante** [comment]
> * Use artifacts to persist my dist folder into my Docker Push Job

How?
The following, and many other variations of that, didn't work for me. 
```yml
jobs:
  build-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go get -d -v ./go/src/app/
      - name: Build
        run: go build -v -o app ./go/src/app/
      # - name: Test with the Go CLI
      #   run: go test

      - name: 'Tar files'
        run: tar -czvf app.tar.gz app

      - name: Archive go artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'app.tar.gz'
          path: 'app.tar.gz'

  build-and-push-image:
    needs: 'build-app'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download go bin artifact
        uses: actions/download-artifact@v3
        with:
          name: 'app.tar.gz'
      
      - name: 'UnTar files'
        run: tar -xvf app.tar.gz -C ./go/bin

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Will create and boot a builder that can be used in the build-push action.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # I can see the files here in the right folders
      - name: Check downloaded artifact
        run: |
          pwd
          ls -lah
          echo "./go/bin"
          ls -lah ./go/bin

      # Any file mutation in the steps that precede the build step will be ignored, 
      # since the context is based on the Git reference. Use the Path context to remove this restriction. 
      # https://github.com/marketplace/actions/build-and-push-docker-images#git-context
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true

```
The 'app' file is seeable from a 'run ls ./go/bin' just before the build-push-action, but not in the Dockerfile COPY action.
