### ISSUE TITLE
Support verbose option

### ISSUE THREAD

**Issue by dbabokin** [docker/build-push-action#98]
By default, image build doesn't leave any build traces in logs - neither for successful builds nor for failed ones. It would very useful to have output from build stage to understand what's gone wrong. Probably it make sense to add it as ``verbose`` option.

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

This new version should fix your issue using the `--debug` for [buildkitd-flags](https://github.com/docker/setup-buildx-action#customizing):

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .Dockerfile
          push: true
          tags: user/app:latest
```

Don't hesitate if you have any questions.
