### ISSUE TITLE
Multiplatform build slows drastically after the first platform

### ISSUE THREAD

**Issue by K20shores** [docker/build-push-action#982]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Creating a multiplatform build results in a build time that is very long or one that doesn't finish. I have two examples

In the micm project
1. [Building for one platform succeeds in 7 minutes](https://github.com/NCAR/micm/actions/runs/6433693183)
2. [Building for two platforms takes over an hour, so I canceled it](https://github.com/NCAR/micm/actions/runs/6433827511)
3. [Here's another I won't cancel. I expect it to time out](https://github.com/NCAR/micm/actions/runs/6434595983)

In another project when I tried this a few months ago, [the build timed out after six hours](https://github.com/NCAR/music-box/actions/runs/5591390708) for multiple platforms.

### Expected behaviour

The build doesn't time out for more than one platform.

### Actual behaviour

The build does time out for more than one platform.

### Repository URL

https://github.com/NCAR/micm

### Workflow run URL

https://github.com/NCAR/micm/actions/runs/6433827511

### YAML workflow

```yaml
name: Create and publish a Docker image

on:
  push:
    branches: ['release', '292-add-a-docker-image-publish']
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile.publish
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
