### ISSUE TITLE
output doesn't allow interpolation/accessing environment variables

### ISSUE THREAD

**Issue by BPodszun** [docker/build-push-action#986]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

The 'outputs' doesn't seem to accept any dynamic expression, neither normal environment variables ($foo) nor Github Action expressions (${{ env.foo}})

### Expected behaviour

I would expect that either `$foo` or `${{ env.foo }}` works in outputs and evaluates to the environment variable's value at runtime.

### Actual behaviour

The action creates a file that is literally called '$foo' or '${{ env.foo }}' in the filesystem.

### YAML workflow

```yaml
- name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: somethingHere
        outputs: type=docker,dest=/tmp/{{ env.BuildArtifact }}.tar
        build-args: |
          GitVersion=$(git describe --all --long)
          GitHash=$(git rev-parse HEAD)
          BuildTime="$(date -u -Ins)"
```
```


### Workflow logs

_No response_

### BuildKit logs

_No response_

### Additional info

_No response_
