### ISSUE TITLE
insufficient_scope: authorization failed

### ISSUE THREAD

**Issue by Yucked** [docker/build-push-action#987]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

Error when pushing to ghcr.io, workflow is as follow:

```yml
   publish:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Docker Login      
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
                
    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with: 
        pull: true
        context: .
        push: true
        tags: ghcr.io/yucked/grimoire:${{ github.run_number }}  

```

Already tried the suggestions in #160 

```
#3 [internal] load metadata for docker.io/library/build:latest
#3 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
------
 > [internal] load metadata for docker.io/library/build:latest:
------
Dockerfile:4
--------------------
   2 |     RUN apk add --no-cache curl unzip
   3 |     
   4 | >>> FROM build
   5 |     RUN curl -OJL https://github.com/Yucked/Grimoire/archive/refs/heads/main.zip && \
   6 |         unzip '*.zip' && \
--------------------
ERROR: failed to solve: build: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error: buildx failed with: ERROR: failed to solve: build: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

### Expected behaviour

Should be able to build the image

### Actual behaviour

Fails to build the image and push to github registry

```
Error: buildx failed with: ERROR: failed to solve: build: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

```

### Repository URL

https://github.com/Yucked/Grimoire

### Workflow run URL

https://github.com/Yucked/Grimoire/actions/runs/6486766699/job/17615641628

### YAML workflow

```yaml
name: Build & Publish
on: push

jobs:
   build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.x

   publish:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Docker Login      
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
                
    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with: 
        pull: true
        context: .
        push: true
        tags: ghcr.io/yucked/grimoire:${{ github.run_number }}
```
