### ISSUE TITLE
GHCR support

### ISSUE THREAD

**Issue by zored** [docker/build-push-action#99]
As GitHub docs say:
> The GitHub Packages Docker registry will be **superseded by GitHub Container Registry.**

There is [migration guide](https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images).

I tried to add `registry: ghcr.io` in Docker Hub config but got:
```
Error response from daemon: Get https://ghcr.io/v2/: denied
```

It would be great to find out what migration steps for `build-push-action` are too!

**Comment by crazy-max** [comment]
Hi @zored,

This will be available through [build-push-action v2](https://github.com/docker/build-push-action/tree/v2-build-push) (#92).
You can already try it through our [login-action](https://github.com/docker/login-action).

**Comment by bonifaido** [comment]
I made it work according to the GHCR migration guide https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images#updating-your-github-actions-workflow

The useful part is, that `GITHUB_TOKEN` doesn't work with ghcr.io, you have to use a Personal Access Token with registry scope:
> Add your new container registry authentication personal access token (PAT) as a GitHub Actions secret. GitHub Container Registry does not support using GITHUB_TOKEN for your PAT so you must use a different custom variable, such as CR_PAT. For more information, see "Creating and storing encrypted secrets."

**Comment by zored** [comment]
Thank you!

Here is my working sample of Github Actions `build-and-push.yaml` for GHCR that is **based on WIP branch** and works smoothly.
```
name: ci
on: push
jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - id: prep
        if: "startsWith(github.ref, 'refs/tags/v')"
        run: |
          echo ::set-output name=tags::ghcr.io/zored/velobeat:${GITHUB_REF#refs/tags/v}
      - uses: docker/setup-qemu-action@master
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          platforms: all
      - id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true
      - uses: docker/login-action@v1
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }} # - must be in GitHub Secrets!
      - uses: docker/build-push-action@v2-build-push
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./docker/image/app/Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64,linux/386
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
```

Looking forward for stable v2!
