### ISSUE TITLE
buildx failed with: ERROR

### ISSUE THREAD

**Issue by thisurawijesekera** [docker/build-push-action#993]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I am using this action to build docker images and push to the docker registry but giving following error
```
ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
Error: buildx failed with: ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
```
Here are the docker login, buildkit and build & push actions

```
      - name: Set Docker Buildx Environment
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_REPOSITORY }}:${{ env.version }}
          build-args: |
            JFROG_USERNAME=${{ env.JFROG_USERNAME }}
            JFROG_PASSWORD=${{ env.JFROG_PASSWORD }}  
```       

### Expected behaviour

action should build the image and push to docker regisry 

### Actual behaviour

Failed in docker build step

### YAML workflow

```yaml
- name: Set Docker Buildx Environment
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_REPOSITORY }}:${{ env.version }}
          build-args: |
            JFROG_USERNAME=${{ env.JFROG_USERNAME }}
            JFROG_PASSWORD=${{ env.JFROG_PASSWORD }}
```

### Workflow logs

ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
Error: buildx failed with: ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
