### ISSUE TITLE
action rebuilding default image unnecessarily 

### ISSUE THREAD

**Issue by PhilipDeegan** [docker/build-push-action#997]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

I'm building multiple images in a GHA matrix,
when building/pushing the non-default image, it for some reason builds the default image

I don't expect this really, it should just try to push the tag given

I understand I might not have things setup properly, but, maybe I do also

### Expected behaviour

Not build default images when pushing non-default images

### Actual behaviour

builds default images when pushing non-default images

### Repository URL

https://github.com/PHARCHIVE/phare_gha_dep_images

### Workflow run URL

https://github.com/PHARCHIVE/phare_gha_dep_images/actions/runs/6761300518/job/18376042161

### YAML workflow

```yaml
name: CMake Ubuntu

on:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        images: ['gcc:12.3.0', 'gcc:13.2.0']

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: chmod +x build.sh && ./build.sh ${{ matrix.images }}

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GCHR_USERNAME }}
        password: ${{ secrets.GCHR_TOKEN }}

    - uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/pharchive/phare_debian_dep/${{ matrix.images }}
```
